### ISSUE TITLE
dnsdist: addAction/rmRule consumes incrementally more memory

### ISSUE THREAD

**Issue by phonedph1** [PowerDNS/pdns#8530] opened 2019-11-13 19:12 UTC
- Program: dnsdist
 - Issue type: Bug report

### Short description
Adding/removing rules which reference a large network mask group causes increasing memory usage.

### Environment
 - Operating system: Debian
 - Software version: master
 - Software source: master compiled

### Steps to reproduce
Create a minimal dnsdist config:

```
-- security key for libsodium
setKey("xx")

-- listen for console connection
controlSocket("127.0.0.1")

addLocal("0.0.0.0:5353", {reusePort=true})
newServer({address="8.8.8.8"})

dropTest = newNMG()
for line in io.lines("ips") do
  dropTest:addMask(line)
end
```
where ips is of decent size `for x in $(seq 1 200); do for y in $(seq 1 200); do echo "2001::$y:$x/128"; done; done  > ips`

Now add/remove the rule a hundred times (this is just to simulate that we wish to periodically update these from a central source - in reality we would clear() the NMG, add entries, add a new rule, and move it to the top and delete the other one - but this seems simpler to reproduce)

```
rmRule(0)
addAction(NetmaskGroupRule(dropTest, true, true), DropAction())
```

### Expected behaviour
Memory usage to stay relatively consistent. 

### Actual behaviour
```
$ ps -eo rss,args | grep dnsdist
37248 ./dnsdist -C dnsdist.conf
$ for x in $(seq 1 100); do ./dnsdist -c -C dnsdist.conf < repro; done
Error: attempt to delete non-existing rule
$ ps -eo rss,args | grep dnsdist
836568 ./dnsdist -C dnsdist.conf
```

**Comment by rgacogne** [comment] 2019-11-15 10:18
I can reproduce this and am investigating. Interestingly enough, the leak seems to go away if I call `collectgarbage()` after every rule addition, like that:
```
rmRule(0)
addAction(NetmaskGroupRule(dropTest, true, true), DropAction())
collectgarbage()
```

**Comment by rgacogne** [comment] 2019-11-18 08:40
I checked that the objects are being destroyed correctly if we call `collectgarbarge()` once after removing/adding the rule a hundred times. Massif also confirms that the memory is properly released. Our metrics still report an important memory usage, likely because the pages stay mapped, but I don't think the memory is actually leaked.

**Comment by rgacogne** [comment] 2019-11-18 10:21
I'm closing this issue for now since it does not look like a leak anymore, please reopen it if needed :-)

**Closed by rgacogne** 2019-11-18 10:21 UTC
Labels: defect, dnsdist
