### ISSUE TITLE
dnsdist: Proxy support for DOH Downstream servers

### ISSUE THREAD

**Issue by dtouzeau** [PowerDNS/pdns#11412] opened 2022-03-13 23:05 UTC
- Program: dnsdist 
 - Issue type: Feature request

### Short description
HTTP Proxy support for DOH 

### Usecase
The use of DOH backends requires a direct connection to public HTTP servers.
If you want to use an HTTP proxy for logging and security reasons, the option is not available.
Also, a basic proxy login would be appreciated to identify requests from dnsdist

**Comment by rgacogne** [comment] 2022-03-14 08:36
It looks like a duplicate of https://github.com/PowerDNS/pdns/issues/10793

**Closed by rgacogne** 2022-03-14 08:36 UTC
Labels: feature request, dnsdist

**Comment by dtouzeau** [comment] 2022-03-14 08:46
#10793 is related to use nghttp as a workaround
It is only a workaround when you using a limited DOH downstream server and have performance issue on a stressed service.
Best is to integrate Proxy connection directly into the same process.

**Comment by rgacogne** [comment] 2022-03-14 08:53
To me #10793 is about adding proxy support to DoH downstream servers, and happens to suggest a work-around in the meantime :)
