### ISSUE TITLE
LUA records don't have source of randomness

### ISSUE THREAD

**Issue by mnordhoff** [PowerDNS/pdns#6853] opened 2018-08-15 08:38 UTC
- Program: Authoritative
 - Issue type: Feature request 

### Short description

`LUA` records -- and, I assume, other Lua-based features -- don't have access to a source of random data.

Lua's standard library has a PRNG, but it doesn't get seeded with anything.

There's no CSPRNG available without writing something complicated using `ffi` or file I/O.

### Usecase

Doing anything random. ;-) I don't have a specific personal use case, but someone will someday.

### Description

Lua's [`math` module](https://www.lua.org/manual/5.3/manual.html#6.7) has `math.random()` and `math.randomseed()` functions. However, every time a `LUA` record is queried, it's initialized with the same seed, so it always produces the same random data.

For example, this record always returns "`cb51`":

    @ LUA TXT "string.format('%x', math.random(0, 65535))"

The best you can do is use `math.randomseed()` to seed it from the query ID or timestamp or something.

A couple functions could be added to access PowerDNS's usual PRNG and/or CSPRNG.

**Comment by Habbie** [comment] 2018-08-15 08:41
Some notes from discussion on IRC:
* when not using LuaJIT, presumably `math.random()` would in fact give different numbers every time (but, due to using `rand(3)`, they would be of low quality)
* LuaJIT does not use `rand(3)`, instead it has its own PRNG engine that is seeded identically for every Lua state. This is where the problem described above comes from.
* It would be trivial to expose `random(3)` or `dns_random` (from #5274) to Lua scripts.
* If we do so, should we overwrite `math.random` or provide it separately?

**Comment by mnordhoff** [comment] 2019-04-05 23:20
Is this fixed by #7492, or should more be done (e.g. the ideas in the comment above)?

**Comment by Habbie** [comment] 2019-04-06 15:02
#7492 doesn't close this ticket because `math.random` still sucks, but I feel the problem is solved.

**Closed by Habbie** 2019-04-06 15:02 UTC
Labels: auth, enhancement
