### ISSUE TITLE
lua_auth4.o compiling issues....

### ISSUE THREAD

**Issue by DrARoberts** [PowerDNS/pdns#8769] opened 2020-01-31 01:49 UTC
Hi am am attempting to make a small help reference for an API I have written and the make install or make function is bombing out on lua-auth4.o
=
 - Program: PDNS
 - Issue type: Bug report

### Short description
The following bug is outputting when I execute the installation component of this help wiki I am writing: https://github.com/Chronolabs-Cooperative/Zones-API-PHP/wiki/How-to-install-PowerDNS-on-Ubuntu

### Environment

 - Operating system: Ubuntu 19.10 (Fresh Install)
 - Software version: latest on github.com
 - Software source: compiled yourself 

### Steps to reproduce
Follow the steps on: https://github.com/Chronolabs-Cooperative/Zones-API-PHP/wiki/How-to-install-PowerDNS-on-Ubuntu

### Expected behaviour
make compiler bombs out and hangs on:   CXX      lua-auth4.o

### Actual behaviour
    make  install-am
    make[2]: Entering directory '/var/pdns/pdns'
      CXX      arguments.o
      CXX      dynloader.o
      CXX      dynmessenger.o
      CXX      logger.o
      CXX      misc.o
      CXX      qtype.o
      CXX      statbag.o
      CXX      unix_utility.o
      CXX      dnsname.o
      CXX      dnslabeltext.o
      CXXLD    pdns_control
      CXX      auth-caches.o
      CXX      auth-packetcache.o
      CXX      auth-querycache.o
      CXX      backends/gsql/gsqlbackend.o
      CXX      base32.o
      CXX      base64.o
      LEX      bindlexer.c
      CC       bindlexer.o
      CXX      bindparser.o
      CXX      dbdnsseckeeper.o
      CXX      dnsbackend.o
      CXX      dns.o
      CXX      dnspacket.o
      CXX      dnsparser.o
      CXX      dns_random.o
      CXX      dnsrecords.o
      CXX      dnssecinfra.o
      CXX      dnssecsigner.o
      CXX      dnswriter.o
      CXX      dynlistener.o
      CXX      ednsoptions.o
      CXX      ednssubnet.o
      CXX      gss_context.o
      CXX      ipcipher.o
      CXX      iputils.o
      CXX      json.o
      CXX      lua-auth4.o
    packet_write_wait: Connection to 64.227.92.166 port 22: Broken pipe

### Other information
please contact me wishcraft@users.sourceforge.net - if it is just a case of an extension on ./configure to be specified..

**Comment by setharnold** [comment] 2020-01-31 01:55
A few questions from a by-stander:

- Are you sure you didn't just have network connectivity issues at this point?

- Can you paste the entire terminal session of your clone, configure, and build? The linked wiki page suggests to me that lua stuff probably shouldn't be built, but it also lists commands to install lua-related packages. Probably you'll need to give something explicit here that can be reproduced or inspected.

Thanks

**Comment by pieterlexis** [comment] 2020-01-31 08:07
Compiling `lua-auth4.o` takes at least 2gb of RAM. Doe syour machine have that (and/or enough swap)?

**Comment by omoerbeek** [comment] 2020-01-31 09:06
Also: we publish ubuntu packages, see https://repo.powerdns.com
And:

Our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Closed by omoerbeek** 2020-01-31 09:06 UTC
