### ISSUE TITLE
DNSSEC root

### ISSUE THREAD

**Issue by d0wnblog** [PowerDNS/pdns#4555] opened 2016-10-10 17:22 UTC
Hey,
when a client queries a pdns recursor DNSSEC isn't done for the root. 

http://pastebin.com/raw/x8zte4C3

another server where this does work: http://pastebin.com/raw/FYKexiDi

**Comment by pieterlexis** [comment] 2016-10-10 17:24
A note: after priming the cache with the root hints, the recursor does not go out to the internet to update this list and get RRSIGs. This might break downstream validators.

**Comment by d0wnblog** [comment] 2016-10-16 19:49
My config file shows up dnssec=validate

Here is a dig to powerdns.com with +dnssec http://pastebin.com/raw/dJvKW0uT
And here it is without +dnssec http://pastebin.com/raw/tSxwNi68

If I use my chromium I get a error when try to access powerdns.com

**Comment by pieterlexis** [comment] 2016-10-18 09:17
with [this config](https://gist.github.com/pieterlexis/e0b92724d6587591a889bebeec36ae2f), the problem was reproducible. However, this is only because the ns8.opennic.glue server does not send RRSIGs, that way, we can't validate the records (in process or validate mode) and SERVFAIL or (in process-no-validate mode, the default) answer without an RRSIG (that was indeed not cached).

With that config, using the IANA root servers, I cannot reproduce this issue. As discussed on IRC, closing this issue as it looks like a problem with opennic and not the recursor,

**Closed by pieterlexis** 2016-10-18 09:17 UTC
Labels: defect, rec
