### ISSUE TITLE
when dnssec is enabled, LUA does not work on the secondary server

### ISSUE THREAD

**Issue by kostiks91** [PowerDNS/pdns#14051] opened 2024-04-08 14:52 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description
when dnssec is enabled, LUA does not work on the secondary server

### Environment
 - Software version: pdns-auth-48:4.8.4
 - Software source: docker powerdns/pdns-auth-47:4.7.4 and powerdns/pdns-auth-48:4.8.4 and powerdns/pdns-auth-49:4.9.0

### Steps to reproduce
1. master: `pdnsutil create-zone example.com`
2. slave: `pdnsutil create-secondary-zone example.com <masterIP>`
3. master: `pdnsutil add-record example.com test LUA 'A "pickwrandom({{10, '127.0.0.1'}, {100, '127.0.1.1'}})"' `
4. `dig @<slaveIP> example.com`
```
; <<>> DiG 9.11.36-RedHat-9.11.36-8.el8_8.2 <<>> @<slaveIP> example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62533
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;example.com.                   IN      A

;; ANSWER SECTION:
example.com.            30      IN      A       127.0.1.1

```
5. master `pdnsutil secure-zone example.com`
6. `dig @<slaveIP> example.com`
```
; <<>> DiG 9.11.36-RedHat-9.11.36-8.el8_8.2 <<>> @<slaveIP> example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7110
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;example.com.                   IN      A

;; AUTHORITY SECTION:
example.com.            3600    IN      SOA     ns1.example.com. dns.example.com. 2024040411 10800 3600 604800 3600

```
8. master `pdnsutil disable-dnssec example.com`
9. `dig @<slaveIP> example.com`
```
; <<>> DiG 9.11.36-RedHat-9.11.36-8.el8_8.2 <<>> @<slaveIP> example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53125
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;example.com.                   IN      A

;; ANSWER SECTION:
example.com.            30      IN      A       127.0.1.1

```
10.

**Comment by Habbie** [comment] 2024-04-08 14:57
LUA is not expected to work in this context, because the secondary cannot sign the dynamic output. However, it's not expected to fail in the way you are seeing. Are you sure this is what is happening? And, when the zone is secured, do you see the LUA record in the database on the secondary?

**Comment by kostiks91** [comment] 2024-04-08 18:58
there is a recording on the secondary server
master 
```
[]# pdnsutil show-zone example.com
This is a Native zone
Metadata items: 
        ALSO-NOTIFY     <slaveIP>
Zone has NSEC semantics
keys: 
ID = 2 (CSK), flags = 257, tag = 63308, algo = 13, bits = 256     Active         Published  ( ECDSAP256SHA256 ) 
CSK DNSKEY = example.com. IN DNSKEY 257 3 13 Tzai1uUGDFJQiwAsnoIVMBYQOmim182D8OQUcfgxJ+s5LPbTqsRP58e66cL37Kxg0cqYJygexNvqaZup1hLtnQ== ; ( ECDSAP256SHA256 )
DS = example.com. IN DS 63308 13 2 d9454c08afb8b4920d33d6f9d32d945a81458ff53198a500e1f852d700f7a7ad ; ( SHA256 digest )
DS = example.com. IN DS 63308 13 4 642b89f07eaa206a8c64a9902b9589bc7e713678541aa1dd867244b0d8f0d1c73ca387f285a3a1b215033da8b6dde4cb ; ( SHA-384 digest )

[]# pdnsutil list-zone example.com
$ORIGIN .
example.com     30      IN      LUA     A "pickwrandom({{10, '127.0.0.1'}, {100, '127.0.1.1'}})"
example.com     3600    IN      NS      ns1.example.com.
example.com     3600    IN      NS      ns2.example.com.
example.com     3600    IN      SOA     ns1.example.com dns.example.com 2024040414 10800 3600 604800 3600
test.example.com        3600    IN      LUA     A "pickwrandom({{10, 127.0.0.1}, {100, 127.0.1.1}})"
```
slave 
```
[]# pdnsutil list-zone example.com
example.com     3600    IN      DNSKEY  257 3 13 Tzai1uUGDFJQiwAsnoIVMBYQOmim182D8OQUcfgxJ+s5LPbTqsRP58e66cL37Kxg0cqYJygexNvqaZup1hLtnQ==
example.com     30      IN      LUA     A "pickwrandom({{10, '127.0.0.1'}, {100, '127.0.1.1'}})"
example.com     3600    IN      NS      ns2.example.com.
example.com     3600    IN      NS      ns1.example.com.
example.com     3600    IN      RRSIG   NSEC 13 2 3600 20240418000000 20240328000000 63308 example.com 2tDRDktumFH4pgkJIAaE0+Rhy2Rk/kVIY/3PtvXFgDAsTRAq/R7U5xbtUVKDaHsKas0Xj7QIAPMmh4WJXwAJ2g==
example.com     30      IN      RRSIG   LUA 13 2 30 20240418000000 20240328000000 63308 example.com TIQH9NrLw84r3K8d1dSojjCW1tdQLFnHKv6fOY/+4N4DCYV3JIDbJ4uqBb9ZKUG5AAy7JGxpcdgrX1sUrRd1HA==
example.com     3600    IN      RRSIG   SOA 13 2 3600 20240418000000 20240328000000 63308 example.com N9AsJwwd+ors8fbwMVda+FQsgDfOUh8UdYYX5qy96l65DJqh+f50fZXlvP+QKJgmE9S1q6KIRS6fQsPUzTw3UA==
example.com     3600    IN      RRSIG   NS 13 2 3600 20240418000000 20240328000000 63308 example.com f0qfGdZPwD8LINAkomJJG8P8XHnbfUyTsWCGfYpdGW5+LOLxgZ1ium55pyDFbLSlPqEMdCJ2ZtGehEzfvy/5bQ==
example.com     3600    IN      RRSIG   DNSKEY 13 2 3600 20240418000000 20240328000000 63308 example.com GbEut6XBys7LYDU+akUy+OINE/B45pzc+aBqCztE/oXdSpa+bwpxfw4TD2FqMdTL3zd6vt67KNSEHXG1CDmWDA==
example.com     3600    IN      SOA     ns1.example.com dns.example.com 2024040415 10800 3600 604800 3600
test.example.com        3600    IN      LUA     A "pickwrandom({{10, 127.0.0.1}, {100, 127.0.1.1}})"
test.example.com        3600    IN      RRSIG   NSEC 13 3 3600 20240418000000 20240328000000 63308 example.com XN4PgI181MCm2wQkFLmSQYZa3ScvA8ji4zTRLNWIRqwIQWrAxIyGw5I/m8Cq1BJz2sAzB5uRRpc4tBWDxNionw==
test.example.com        3600    IN      RRSIG   LUA 13 3 3600 20240418000000 20240328000000 63308 example.com 35aBSv7gbwK0IrGLFyAHUWPTJwqwmRZvCs7iMBChrAgZyUZ8PDt+FNuVlWvD2y6dqP/LtmjHgkEoJjsBR8NoUg==
```

I forgot to note, I noticed this after updating from version 4.6.3, LUA worked on it regardless of dnssec
rolled back to 4.6.4: 
```
[]# dig @<slaveIP> example.com

; <<>> DiG 9.11.36-RedHat-9.11.36-8.el8_8.2 <<>> @<slaveIP> example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47403
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;example.com.                   IN      A

;; ANSWER SECTION:
example.com.            30      IN      A       127.0.1.1
```
листинг зоны на мой взгляд не отличается от версии 4.7.4
```
[]# pdnsutil --version
pdnsutil 4.6.4
[]# pdnsutil list-zone example.com
example.com     3600    IN      DNSKEY  257 3 13 Tzai1uUGDFJQiwAsnoIVMBYQOmim182D8OQUcfgxJ+s5LPbTqsRP58e66cL37Kxg0cqYJygexNvqaZup1hLtnQ==
example.com     30      IN      LUA     A "pickwrandom({{10, '127.0.0.1'}, {100, '127.0.1.1'}})"
example.com     3600    IN      NS      ns2.example.com.
example.com     3600    IN      NS      ns1.example.com.
example.com     3600    IN      RRSIG   NSEC 13 2 3600 20240418000000 20240328000000 63308 example.com 2tDRDktumFH4pgkJIAaE0+Rhy2Rk/kVIY/3PtvXFgDAsTRAq/R7U5xbtUVKDaHsKas0Xj7QIAPMmh4WJXwAJ2g==
example.com     30      IN      RRSIG   LUA 13 2 30 20240418000000 20240328000000 63308 example.com TIQH9NrLw84r3K8d1dSojjCW1tdQLFnHKv6fOY/+4N4DCYV3JIDbJ4uqBb9ZKUG5AAy7JGxpcdgrX1sUrRd1HA==
example.com     3600    IN      RRSIG   SOA 13 2 3600 20240418000000 20240328000000 63308 example.com N9AsJwwd+ors8fbwMVda+FQsgDfOUh8UdYYX5qy96l65DJqh+f50fZXlvP+QKJgmE9S1q6KIRS6fQsPUzTw3UA==
example.com     3600    IN      RRSIG   NS 13 2 3600 20240418000000 20240328000000 63308 example.com f0qfGdZPwD8LINAkomJJG8P8XHnbfUyTsWCGfYpdGW5+LOLxgZ1ium55pyDFbLSlPqEMdCJ2ZtGehEzfvy/5bQ==
example.com     3600    IN      RRSIG   DNSKEY 13 2 3600 20240418000000 20240328000000 63308 example.com GbEut6XBys7LYDU+akUy+OINE/B45pzc+aBqCztE/oXdSpa+bwpxfw4TD2FqMdTL3zd6vt67KNSEHXG1CDmWDA==
example.com     3600    IN      SOA     ns1.example.com dns.example.com 2024040415 10800 3600 604800 3600
test.example.com        3600    IN      LUA     A "pickwrandom({{10, 127.0.0.1}, {100, 127.0.1.1}})"
test.example.com        3600    IN      RRSIG   NSEC 13 3 3600 20240418000000 20240328000000 63308 example.com XN4PgI181MCm2wQkFLmSQYZa3ScvA8ji4zTRLNWIRqwIQWrAxIyGw5I/m8Cq1BJz2sAzB5uRRpc4tBWDxNionw==
test.example.com        3600    IN      RRSIG   LUA 13 3 3600 20240418000000 20240328000000 63308 example.com 35aBSv7gbwK0IrGLFyAHUWPTJwqwmRZvCs7iMBChrAgZyUZ8PDt+FNuVlWvD2y6dqP/LtmjHgkEoJjsBR8NoUg==
[root@pdns-dev-1 kssuhopl]#

```

**Comment by omoerbeek** [comment] 2024-04-08 19:08
Your version numbers confuse me, can you check them?

**Comment by mind04** [comment] 2024-04-08 19:24
The serial is not increased after zone modifications in the reproduction steps, so axfr is wonky at best.

**Comment by kostiks91** [comment] 2024-04-09 07:03
I don’t see a problem with axfr, records are always replicated and are present in the database
I tried changing versions starting, I only changed the container version
before 4.7.0-alpha1 works as I expect
```
[]# pdnsutil --version ; dig @0 example.com  ; pdnsutil list-zone example.com | grep LUA
pdnsutil 4.7.0-alpha1

; <<>> DiG 9.11.36-RedHat-9.11.36-8.el8_8.2 <<>> @0 example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7975
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;example.com.                   IN      A

;; ANSWER SECTION:
example.com.            30      IN      A       127.0.1.1

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(0.0.0.0)
;; WHEN: Tue Apr 09 09:49:20 MSK 2024
;; MSG SIZE  rcvd: 56

example.com     30      IN      LUA     A "pickwrandom({{10, '127.0.0.1'}, {100, '127.0.1.1'}})"
example.com     30      IN      RRSIG   LUA 13 2 30 20240418000000 20240328000000 63308 example.com TIQH9NrLw84r3K8d1dSojjCW1tdQLFnHKv6fOY/+4N4DCYV3JIDbJ4uqBb9ZKUG5AAy7JGxpcdgrX1sUrRd1HA==
```
starting from 4.7.0-beta2, when dnssec is enabled, lua does not work
```
[]# pdnsutil --version ; dig @0 example.com  ; pdnsutil list-zone example.com | grep LUA
pdnsutil 4.7.0-beta2

; <<>> DiG 9.11.36-RedHat-9.11.36-8.el8_8.2 <<>> @0 example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23448
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;example.com.                   IN      A

;; AUTHORITY SECTION:
example.com.            3600    IN      SOA     ns1.example.com. dns.example.com. 2024040416 10800 3600 604800 3600

;; Query time: 19 msec
;; SERVER: 127.0.0.1#53(0.0.0.0)
;; WHEN: Tue Apr 09 09:50:43 MSK 2024
;; MSG SIZE  rcvd: 84

example.com     30      IN      LUA     A "pickwrandom({{10, '127.0.0.1'}, {100, '127.0.1.1'}})"
example.com     30      IN      RRSIG   LUA 13 2 30 20240418000000 20240328000000 63308 example.com TIQH9NrLw84r3K8d1dSojjCW1tdQLFnHKv6fOY/+4N4DCYV3JIDbJ4uqBb9ZKUG5AAy7JGxpcdgrX1sUrRd1HA==
```

**Comment by Habbie** [comment] 2024-04-09 07:14
> Changed in #11350

Which was in 4.7.0-beta1.



> LUA is not expected to work in this context, because the secondary cannot sign the dynamic output. However, it's not expected to fail in the way you are seeing.

Which means it -is- expected to fail in the way you are seeing. Closing this as you are seeing the intended behaviour.

**Closed by Habbie** 2024-04-09 07:14 UTC
Labels: auth
