### ISSUE TITLE
PowerDNS Master (master=yes) fails to NOTIFY RFC Slaves

### ISSUE THREAD

**Issue by james-stevens** [PowerDNS/pdns#9019] opened 2020-04-09 10:00 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description
With the following METADATA setting, 

SOA-EDIT                        INCEPTION-EPOCH
SOA-EDIT-API                 EPOCH
SOA-EDIT-DNSUPDATE	EPOCH

PowerDNS will roll the SOA Serial to the current unixtime at midnight EVERY Thursday (whether the zone is signed or not, whether the zone has changed or not), but does *NOT* send a NOTIFY to RFC Slaves specified in the "pdns.conf" setting "also-notify"

This causes slaves to be "out-of-date" until they hit the REFRESH interval

If this is the time when PDNS chooses to change the RRSIG records, this also means the RRSIG records will be different on the PDNS Master and RFC Slaves, until the RFC slaves hit the REFRESH interval and update.

We use these metadata settings becuase we wish to use unixtime as the SOA Serial (becuase some zones can update more than 100 times in a day) and we have some signed zones.

### Environment
 - Operating system: Slackware 14.2
 - Software version: 4.2.0
 - Software source: Compiled from unmodified source

### Steps to reproduce
1. Create a zone with the metadata setting above & "master=yes"
2. Add a "bind" (or other RFC) slave and configure it to slave the zone from PDNS
3. Add your slave into "allow-axfr-ips" & "also-notify" in the pdns.conf of the master

All server timezones set to UTC

### Expected behaviour
If data in the zone changes, including the SOA Serial, the slave(s) should be NOTIFIED. Data changes (e.g. via API) to the zone are correctly NOTIFIED to the slave

When the SOA Serial is automatically rolled by the server that the NOTIFY does not work.

### Actual behaviour
When the SOA Serial is rolled (midnight Thursday UTC), the slaves are **not** NOTIFIED and will appear out-of-date to a monitoring system until the REFRESH interval is reached.

The same lack of NOTIFY is seen for both signed and unsigned zones. 

I tried setting "cache-ttl=0" & "slave-cycle-interval=5" to fix this, but it made no difference.

### Other information
One week is 604800 seconds. The only place I could find this mentioned in the manual (& src code) is for the deprecated setting "soa-expire-default". My zone's SOA does not include this value, so I am assuming it must be somehow hardcoded into PDNS.

There is no indication in the pdns log that the SOA Serial has been updated until the RFC slave notices and start zone transfers.

**Comment by Habbie** [comment] 2020-04-09 10:33
> One week is 604800 seconds. The only place I could find this mentioned in the manual (& src code) is for the deprecated setting "soa-expire-default". My zone's SOA does not include this value, so I am assuming it must be somehow hardcoded into PDNS.

Yes, it's hardcoded: https://doc.powerdns.com/authoritative/dnssec/modes-of-operation.html#signatures

**Comment by Habbie** [comment] 2020-04-09 10:36
> If data in the zone changes, including the SOA Serial, the slave(s) should be NOTIFIED. Data changes (e.g. via API) to the zone are correctly NOTIFIED to the slave

We've also had reports that even without notify, all serials changing at once on Thursday overwhelms some slaves. Adding NOTIFY would make that worse. Unless your SOA refresh is set to more than a week, I don't see the operational problem.

**Comment by Habbie** [comment] 2020-04-09 10:50
> When the SOA Serial is rolled (midnight Thursday UTC), the slaves are **not** NOTIFIED and will appear out-of-date to a monitoring system until the REFRESH interval is reached.

I suggest a `pdns_control notify \*` cronjob-or-systemd-equivalent just after midnight Thursday UTC.

**Comment by james-stevens** [comment] 2020-04-09 10:51
The problem is, as mentioned in the report, that any monitoring system that checks SOA Serial freshness between Master & Slave will report an error until the Slave updates, which can be a while, as short REFRESH intervals (causing frequent SOA polling) are unnecessary when using a reliable NOTIFY mechanism.

Normally we would expect to see updates to all slaves within a few seconds. We do this by running a "bind" slave on the same server as PDNS with "ixfr-from-differences yes;" set in bind. All external / remote slave then get updates from the on-box "bind" using NOTIFY & IXFR, which is virtually instant, even for very large zones.

I accept changing all zones at once with NOTIFY could also cause a problem for some people, so you could easily spread them out by adding in some pseudo-random jitter, or spreading it over multiple days. 

Because of our configuration, all-at-once would cause less of a problem for us.

For zones that are NOT signed, this SOA Serial rolling seems unnecessary anyway, so why do you do it?

Changing zone data without sending a NOTIFY, when you are configured to do this, is simply not correct behaviour.

**Comment by Habbie** [comment] 2020-04-09 10:52
> For zones that are NOT signed, this SOA Serial rolling seems unnecessary anyway, so why do you do it?

We only do it if configured to do so.

**Comment by james-stevens** [comment] 2020-04-09 10:53
How can I stop it rolling the SOA Serial on Thursday for unsigned zones, then?

**Comment by Habbie** [comment] 2020-04-09 10:53
> How can I stop it rolling the SOA Serial on Thursday for unsigned zones, then?

Don't set `SOA-EDIT` on them.

**Comment by james-stevens** [comment] 2020-04-09 10:56
So `SOA-EDIT` should only be set on signed zones?

**Comment by Habbie** [comment] 2020-04-09 10:57
> So `SOA-EDIT` should only be set on signed zones?

If you only want signed zones to get a new SOA on Thursday, then yes.

**Comment by Habbie** [comment] 2020-04-09 10:58
> If you only want signed zones to get a new SOA on Thursday, then yes.

Instead of setting it on each domain, you could also set `default-soa-edit-signed` in pdns.conf.

**Comment by james-stevens** [comment] 2020-04-09 11:02
That's a better config, but still left with the original problem, just only on signed zones now.

A cron-job will work, but its not really very satisfactory - if the data changes, the master should notify the slaves

**Comment by Habbie** [comment] 2020-04-09 11:03
Now that everything that can be clarified has been clarified, I'm closing this as a duplicate of #1872, which has more discussion on this.

**Closed by Habbie** 2020-04-09 11:03 UTC
Labels: auth, enhancement

**Comment by james-stevens** [comment] 2020-04-09 11:08
Seeing as that's been open since 2014, seems unlikely this issue is going to be resolved :(

**Comment by Habbie** [comment] 2020-04-09 11:11
Quite likely - it would be several days of work, adding a lot of complexity, for a problem for which a simple workaround exists for most users.
