### ISSUE TITLE
rec: Route 53 nameserver names sometimes bogus

### ISSUE THREAD

**Issue by mnordhoff** [PowerDNS/pdns#8642] opened 2019-12-18 00:56 UTC
- Program: Recursor
 - Issue type: Bug report

### Short description
Sometimes Recursor considers Route 53 server names -- e.g. "`dig ns-561.awsdns-06.net`" -- bogus. I am unsure why, but I'm skeptical it is correct. ;)

I think I've only seen it affect `A` records, and not `AAAA` records.

It may only happen to names that were previously resolved and cached without being validated, because they were used as nameservers to resolve other things. (Does that make sense?)

### Environment
 - Operating system: Ubuntu 16.04 x86-64
 - Software version: 4.3.0~beta1+master.19.gfa178d8fd-1pdns.xenial
 - Software source: PowerDNS repository

### Steps to reproduce
1. `sudo systemctl restart pdns-recursor`
2. `sudo rec_control trace-regex awsdns-`
1. `dig mattnordhoffdns.org ns; dig ns-379.awsdns-47.com; dig ns-379.awsdns-47.com aaaa; dig ns-561.awsdns-06.net; dig ns-561.awsdns-06.net aaaa; dig ns-1212.awsdns-23.org; dig ns-1212.awsdns-23.org aaaa; dig ns-1597.awsdns-07.co.uk; dig ns-1597.awsdns-07.co.uk aaaa`

### Expected behaviour
`NOERROR`.

### Actual behaviour
```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> ns-1597.awsdns-07.co.uk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 24716
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;ns-1597.awsdns-07.co.uk.	IN	A

;; Query time: 4 msec
;; SERVER: ::1#53(::1)
;; WHEN: Wed Dec 18 00:16:01 UTC 2019
;; MSG SIZE  rcvd: 52
```

### Other information
`tcpdump -lnptttt port 53` summary: https://mn0.us/ANjkczQhaTqo/tcpdump.txt (it may include some unrelated stuff)
`trace-regex awsdns-` logs: https://mn0.us/EBHahWWf2_uU/syslog.txt (try Ctrl+F 'Bogus')
`rec_control dump-cache`: https://mn0.us/DAC0vTtxzj5i/cache.txt

Recursor configuration is close to stock:

```
$ grep -ve ^# -e '^$' recursor.conf
allow-trust-anchor-query
carbon-ourname=clover_mattnordhoff_net
carbon-server=2a02:2770:8::2635:0:1
config-dir=/etc/powerdns
dnssec=validate
hint-file=/usr/share/dns/root.hints
include-dir=/etc/powerdns/recursor.d
local-address=127.0.0.1, ::1
lua-config-file=/etc/powerdns/recursor.lua
max-cache-ttl=172800
max-negative-ttl=10800
query-local-address6=::
quiet=yes
setgid=pdns
setuid=pdns
```

`/etc/powerdns/recursor.d/` is empty and the Lua stuff is just the stock root key thing. (Fun fact: My OS has both the old and new keys enabled.)

**Comment by mnordhoff** [comment] 2019-12-18 02:21
The zone cuts are apparently incorrect when failing to resolve the `A` record:

```
Dec 18 00:16:01 clover pdns_recursor[17694]: : list of cuts from ns-1597.awsdns-07.co.uk to .
Dec 18 00:16:01 clover pdns_recursor[17694]:  - .: Secure
Dec 18 00:16:01 clover pdns_recursor[17694]:  - uk: Secure
Dec 18 00:16:01 clover pdns_recursor[17694]:  - co.uk: Secure
Dec 18 00:16:01 clover pdns_recursor[17694]:  - awsdns-07.co.uk: Secure
Dec 18 00:16:01 clover pdns_recursor[17694]:  - ns-1597.awsdns-07.co.uk: Secure
```

But correct when successfully resolving the `AAAA` record (possibly in a different thread?):

```
Dec 18 00:16:01 clover pdns_recursor[17694]: : list of cuts from ns-1597.awsdns-07.co.uk to .
Dec 18 00:16:01 clover pdns_recursor[17694]:  - .: Secure
Dec 18 00:16:01 clover pdns_recursor[17694]:  - uk: Secure
Dec 18 00:16:01 clover pdns_recursor[17694]:  - co.uk: Secure
Dec 18 00:16:01 clover pdns_recursor[17694]:  - awsdns-07.co.uk: Insecure
```

**Comment by mnordhoff** [comment] 2019-12-18 08:47
Reproducible with NS1 instead of Route 53. At a glance, everything looks similar.

1. `sudo systemctl restart pdns-recursor`
2. `sudo rec_control trace-regex 'nsone\.net\.$'`
3. `dig herokuapp.com ns; dig dns1.p03.nsone.net; dig dns2.p03.nsone.net; dig dns3.p03.nsone.net; dig dns4.p03.nsone.net`

```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> dns1.p03.nsone.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 25419
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;dns1.p03.nsone.net.		IN	A

;; Query time: 8 msec
;; SERVER: ::1#53(::1)
;; WHEN: Wed Dec 18 08:25:57 UTC 2019
;; MSG SIZE  rcvd: 47
```

* https://mn0.us/8nP08R3ZVpf6/herokuapp.com-cache.txt
* https://mn0.us/tHMhPGo5AxDQ/herokuapp.com-syslog.txt
* https://mn0.us/fG81aPjkfijX/herokuapp.com-tcpdump.txt

N.b. `p03.nsone.net` really is a zone cut.

I failed to reproduce it with `imgur.com` instead of `herokuapp.com`.

**Comment by rgacogne** [comment] 2019-12-18 14:03
At a very quick glance it looks like a weird interaction between qname minimization and DNSSEC validation. It seems that we somehow end up doing zone cut detection (call to `computeZoneCuts()`) with `d_cacheOnly` set. When we try to get the DS records to determine whether there is a zone cut,  `doResolve()` returns `NODATA` because there is nothing in the cache but we mistake that for a real, secure, `NODATA` answer since we did not set the `d_cacheOnly` flag ourselves. This leads to an insecure zone being considered secure, and therefore to the answers for this zone being considered bogus since they are not properly signed.

**Comment by johnhtodd** [comment] 2019-12-18 17:58
This possibly was an issue with "workforcenow.adp.com" from yesterday; we see "Bogus" entries in logfiles, but the zone is not signed. They run their own nameservers (not AWS) with v6 destinations being sporadically unreachable but v4 being solid.

**Comment by omoerbeek** [comment] 2019-12-18 18:07
As  first step, the QName minimiation algoritm does a check of the cache by doing a call to `doResolveNoQNameMinimization` with the `d_cacheOnly` flags set. I can see how that trickles down to `computeZoneCuts()`. We might need to modify computeZoneCuts() to always set `d_cacheOnly` to false (and set it back to the old value on function exit) , but I would have to check if that would have undesired side effects in other cases.

**Comment by omoerbeek** [comment] 2019-12-20 09:45
I could not reproduce the case using the route53 test case, but I could using the ns1 one, which is reliably fixed by the PR AFAKS.

**Closed** 2019-12-20 12:46 UTC
Labels: defect, rec
