### ISSUE TITLE
Doc: authoritative and recursor web-server/api

### ISSUE THREAD

**Issue by LecrisUT** [PowerDNS/pdns#10091] opened 2021-02-17 05:34 UTC
From the documentation already provided it is unclear how the various web-server and apis can be combined, e.g.:
- If we run multiple authoritative pdns instances with different server-ids is it possible to use a single web-server endpoint (i.e. assigning the same web-server-address/port)? If not what is the purpose of `GET /servers`?
- Can the recursor, authoritative  and dnsdist web-server be combined in a similar manner as above?
- Is it possible to detect/control/forward from a recursor/dnsdist endpoint to authoritative dns endpoints (using the same or different api-keys). For example: if we register a new `forward-zone` on the recursor, it could check the same port on the forwarding ip, and add it's id to the recursor's `/servers` and reverse-proxy to the authoritative endpoint
- What is the purpose of `tcp-control` settings in authoritative pdns, and can it be configured for the above control scheme?
- What is the recommended approach for centrally managing a full pdns cluster with master/slave configurations.

**Comment by omoerbeek** [comment] 2021-02-17 07:40
I think the first paragraph of https://docs.powerdns.com/authoritative/http-api/server.html is clear:
```
The server endpoint is the ‘basis’ for all other API operations. In the PowerDNS Authoritative Server, the server_id is always localhost. However, the API is written in a way that a proxy could be in front of many servers, each with their own server_id.
```
The API was designed with to control multiple servers, but this is not implemented out of the box.

As for your fourth bullet, `pdns_control` can connect over TCP.

As for the last point:

Your GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Closed by omoerbeek** 2021-02-17 07:40 UTC

**Comment by LecrisUT** [comment] 2021-02-17 08:20
So in other words, we need a different api server to forward the requests to each of the built-in api server, and each api server would need its own ip/port pair to listen on. I guess the `GET /servers` is only for consistency with other standard APIs, but its presence makes this issue unclear when looking at the [recursor api endpoint documentation](https://docs.powerdns.com/recursor/common/api/endpoint-servers.html).

I understand that using the issue tracker for support is frowned upon, and I apologize for the rudeness. I still have a feature request, but that has been dependent on the former questions. Given the current status the feature request is:
- Can the built-in api accommodate for not only `GET /servers/localhost`, but also `GET /servers/{server_id}` with `server_id` taken from the configuration. The wording in the documentation indicates that that is not the case currently. This would simplify making simple reverse-proxy configurations and server discovery on local network, even though `GET /servers` will have to be manually implemented.
- Is a central `pdns` api server able to connect other api servers currently in development, or will it always be outsourced to third party front ends? I see that PowerDNS/pdnscontrol is obsolete, but are there any plans of bringing it back?

**Comment by Habbie** [comment] 2021-02-17 08:28
> Can the built-in api accommodate for not only `GET /servers/localhost`, but also `GET /servers/{server_id}` with `server_id` taken from the configuration. The wording in the documentation indicates that that is not the case currently. This would simplify making simple reverse-proxy configurations and server discovery on local network, even though `GET /servers` will have to be manually implemented.

That's an interesting one, and if you file that as a separate ticket for a featurer request, we can discuss it.



> Is a central `pdns` api server able to connect other api servers currently in development, or will it always be outsourced to third party front ends? I see that PowerDNS/pdnscontrol is obsolete, but are there any plans of bringing it back?

We have no plans. I assume you saw https://github.com/catalyst/powerdns-auth-proxy

(I am now closing comments on this ticket to avoid more responses on a closed ticket, because we will never look at those again.)
