### ISSUE TITLE
Recursor returns partial, incosistent repsonses for ANY type queries

### ISSUE THREAD

**Issue by nanidepave** [PowerDNS/pdns#4820] opened 2016-12-27 12:52 UTC
- Program:  Recursor
 - Issue type: Bug report 

### Short description
When querying Recursor for ANY type, after a previous specific type request (e.g. A) for the same domain was made, the results for the ANY type query are partial and inconsistent.

### Environment

 - Operating system: ubuntu
 - Software version: 16.04
 - Software source:  PowerDNS repository

### Steps to reproduce
```
dig github.com A
dig github.com ANY  (WRONG returns only A type)

(wait for caches to expire)

dig github.com ANY (OK returns all types as expected)

(wait for caches to expire)

dig github.com MX
dig github.com ANY (WRONG returns only MX type)
```

### Expected behaviour
Results for ANY type queries should be complete.

### Actual behaviour
Results for ANY type queries are partial and inconsistent.

**Comment by Habbie** [comment] 2016-12-27 12:58
Hello,

this is intended behaviour. If there is anything in the cache for a name, an ANY query will not cause an outgoing query to the authoritative (which is increasingly unlikely to yield any results anyway - for example CloudFlare does not honour ANY queries at all).

Closing ticket.

**Closed by Habbie** 2016-12-27 12:58 UTC
