### ISSUE TITLE
Setting recordcache.refresh_on_ttl_perc has little effect on forward domain names, with only one or two successful refreshes out of thousands of requests.

### ISSUE THREAD

**Issue by zhouyuyong** [PowerDNS/pdns#13902] opened 2024-03-12 13:12 UTC
- [ ] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [ ] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Recursor
 - Issue type: Bug report

### Short description
When using the forward_zones parameter in PowerDNS Recursor to specify forwarding a certain domain name to a specific internal DNS server, the refresh_on_ttl_perc parameter is set to 10. If the TTL value of a subdomain is 60, the TTL will not be updated when it reaches only 5 seconds remaining. A new query needs to be executed to refresh the TTL. However, sometimes the TTL can be refreshed earlier. By using rec_control trace-regex, you can trace the query process. It is suspected that there may be a bug in this part of the logic.

### Environment

 - Operating system: centos7.9 
 - Software version:  pdns-recursor-5.0.3-1pdns.el7.x86_64
 - Software source: 

### Steps to reproduce

1. /etc/pdns-recursor/recursor.yml
![image](https://github.com/PowerDNS/pdns/assets/7124402/442b80e5-a730-40e3-a7b3-cb4dc777d6ea)

2. /etc/pdns-recursor/recursor.d/zones.yml
![image](https://github.com/PowerDNS/pdns/assets/7124402/3861284d-9b60-4f70-9097-9e4fc4efa191)

3. Perform resolution tests using dig in a loop, and observe the trace results using the rec_control trace-regex command."
![image](https://github.com/PowerDNS/pdns/assets/7124402/bdb1831a-e62e-4177-8b89-67bc37f75ed6)

4. 
5. 

### Expected behaviour
Automatically refresh the record when the TTL time is less than 10%

### Actual behaviour
In most cases, when the TTL is already 0 and no cache is found in memory, the cache needs to be refreshed by querying the backend again

Rarely, in some cases, the cache may have been refreshed in advance when the TTL time is 0.

**Comment by zhouyuyong** [comment] 2024-03-13 12:24
If there are two layers of recursors upstream of the authoritative DNS server, then the top-level recursor, regardless of how the domain forwarding is configured, will trigger this issue. Only the recursor one level above the authoritative server can implement the functionality of recordcache.refresh_on_ttl_perc. It's very strange.   100% reproduction

**Comment by zhouyuyong** [comment] 2024-03-13 12:49
If any domain name from the internet is forwarded to a specific recursive server, the issue can be reliably reproduced, like this. Only occasionally does it hit the cache, like this.
![Uploading image.png…]()

**Comment by omoerbeek** [comment] 2024-03-13 13:03
> If there are two layers of recursors upstream of the authoritative DNS server, then the top-level recursor, regardless of how the domain forwarding is configured, will trigger this issue. Only the recursor one level above the authoritative server can implement the functionality of recordcache.refresh_on_ttl_perc. It's very strange. 100% reproduction

Yes, for chained recursors the refresh mechanism won't work very well, as the trigger for a refrehs is a query for the name in a certain time interval. If an earlier recursor has the name stil it it's cache, the query wont be sent to the next recursor an no trigger will happen. This is the reaosn why dnsdist has https://dnsdist.org/reference/actions.html?highlight=percentage#SetReducedTTLResponseAction

Will look into the general forwarding vs refresh mechanism soon.

**Comment by zhouyuyong** [comment] 2024-03-14 03:12
Let me understand. In my chained recursive architecture, it looks like this: recursor1 ---> dnsdist ---> recursor2 ----> authoritative. If the cache for a domain in recursor1 is still valid, the refresh won't be triggered at all. I tested and confirmed that it doesn't refresh every time. I conducted further tests by setting the recurse parameter to false in the forwarding configuration and changing the request path to client --> recursor --> authoritative. Through tracing, I found it's still an iterative query, and the issue persists. So, it seems that the problem is not triggered by chained recursion but rather by forwarding. To further verify this hypothesis, I removed the forward configuration and left the other settings default. The request path became client --> recursor --> internet DNS. Through tracing, I observed successful cache refreshes before TTL expiration. I hope these tests can help pinpoint the issue.

**Comment by omoerbeek** [comment] 2024-03-15 10:25
I have a test setup to reproduce what you are seeing. Here is a piece of log (loglevel=7 and quiet=no).
The `m6k.nl` domain is forwarded to a specific auth server.  Refresh percentage is is 20% and the test record has a TTL of 20.

First query comes in, no packet cache hit, no record cache hit, so rec has to resolve the query using outgoing queries (outqueries="5").
```
Mar 15 11:08:59 msg="Question" subsystem="syncres" level="0" prio="Info" tid="2" ts="1710497339.885" ecs="" mtid="1" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:51770"
Mar 15 11:08:59 msg="Answer" subsystem="syncres" level="0" prio="Info" tid="2" ts="1710497339.949" additional="1" answer-is-variable="0" answers="1" dotout="0" ecs="" into-packetcache="1" maxdepth="4" mtid="1" netms="59.685000" outqueries="5" proto="udp" qname="ttl20.m6k.nl" qtype="A" rcode="0" rd="1" remote="127.0.0.1:51770" tcpout="0" throttled="0" timeouts="0" totms="62.282000" validationState="Secure"
```
Next queries are answered from the packet cache:
```
Mar 15 11:09:01 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="2" ts="1710497341.628" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:60969" source="127.0.0.1:60969" tag="0"
Mar 15 11:09:10 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="2" ts="1710497350.075" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:64138" source="127.0.0.1:64138" tag="0"
Mar 15 11:09:16 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="2" ts="1710497356.955" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:49550" source="127.0.0.1:49550" tag="0"
Mar 15 11:09:18 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="2" ts="1710497358.187" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:53663" source="127.0.0.1:53663" tag="0"
```
And close to the deadline a refresh task is created and executed:
```
Mar 15 11:09:19 msg="resolving" subsystem="taskq" level="0" prio="Debug" tid="7" ts="1710497359.201" name="ttl20.m6k.nl" netmask="" qtype="A" refresh="1"
Mar 15 11:09:19 msg="done" subsystem="taskq" level="0" prio="Debug" tid="7" ts="1710497359.206" name="ttl20.m6k.nl" netmask="" qtype="A" rcode="0" records="2"
```
The next question is NOT a _packet_ cache hit, so the recursor has to resolve, but it has a refreshed entry in the _record_ cache, since it was refreshed by the refresh task: outqueries="0"
```
Mar 15 11:09:19 msg="Question" subsystem="syncres" level="0" prio="Info" tid="2" ts="1710497359.396" ecs="" mtid="2" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:61929"
Mar 15 11:09:19 msg="Answer" subsystem="syncres" level="0" prio="Info" tid="2" ts="1710497359.397" additional="1" answer-is-variable="0" answers="1" dotout="0" ecs="" into-packetcache="1" maxdepth="1" mtid="2" netms="0.000000" outqueries="0" proto="udp" qname="ttl20.m6k.nl" qtype="A" rcode="0" rd="1" remote="127.0.0.1:61929" tcpout="0" throttled="0" timeouts="0" totms="0.000000" validationState="Secure"
```
Next questions again answered by the packet cache:
```
Mar 15 11:09:25 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="2" ts="1710497365.354" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:56815" source="127.0.0.1:56815" tag="0"
Mar 15 11:09:30 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="2" ts="1710497370.554" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:56439" source="127.0.0.1:56439" tag="0"
```
Then wait a bit, for the next question both the _packet_ cache and _record_ cache entries are expired, so rec has to do outside queries: outqueries="1" 
```
Mar 15 11:09:47 msg="Question" subsystem="syncres" level="0" prio="Info" tid="2" ts="1710497387.693" ecs="" mtid="3" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:55084"
Mar 15 11:09:47 msg="Answer" subsystem="syncres" level="0" prio="Info" tid="2" ts="1710497387.698" additional="1" answer-is-variable="0" answers="1" dotout="0" ecs="" into-packetcache="1" maxdepth="1" mtid="3" netms="3.781000" outqueries="1" proto="udp" qname="ttl20.m6k.nl" qtype="A" rcode="0" rd="1" remote="127.0.0.1:55084" tcpout="0" throttled="0" timeouts="0" totms="4.399000" validationState="Secure"
```
Next question again answered by packet cache:
```
Mar 15 11:09:48 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="2" ts="1710497388.971" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:54360" source="127.0.0.1:54360" tag="0"
```

So this all works according to the design.

There is one important thing you need to know: if a refresh task is created by the packet cache, it is not executed immediately. The recursor will only look for tasks to be executed if packet cache misses occurs (plus a periodic thread). So if your recursor is only handling packet cache hits, it will not execute the refresh tasks in time most if the time. This happens a lot in test scenarios with a single client doing the same test query again and again. In a prodcutioin environment this is unlikely to occur. To work around this when testing, you can disable the packet for testing, or run a loop that creates packet cache misses: `while true; do dig $RANDOM.com; sleep 1; done`. 

If this does not explain what you are seeing, please run rec in your lab with the loglevel 7 and quiet=no, and compare what you are seeing with the log above.

**Comment by omoerbeek** [comment] 2024-03-15 10:32
Oh, I see you have `locked_ttl_perc` set as well and are using a recursive forward. Will retest with that as well.

**Comment by omoerbeek** [comment] 2024-03-15 10:43
> Oh, I see you have `locked_ttl_perc` set as well and are using a recursive forward. Will retest with that as well.

That also works OK in my tests (tested with packetcache disabled, for the reason mentioned above)

**Comment by zhouyuyong** [comment] 2024-03-18 12:38
> I have a test setup to reproduce what you are seeing. Here is a piece of log (loglevel=7 and quiet=no). The `m6k.nl` domain is forwarded to a specific auth server. Refresh percentage is is 20% and the test record has a TTL of 20.
> 
> First query comes in, no packet cache hit, no record cache hit, so rec has to resolve the query using outgoing queries (outqueries="5").
> 
> ```
> Mar 15 11:08:59 msg="Question" subsystem="syncres" level="0" prio="Info" tid="2" ts="1710497339.885" ecs="" mtid="1" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:51770"
> Mar 15 11:08:59 msg="Answer" subsystem="syncres" level="0" prio="Info" tid="2" ts="1710497339.949" additional="1" answer-is-variable="0" answers="1" dotout="0" ecs="" into-packetcache="1" maxdepth="4" mtid="1" netms="59.685000" outqueries="5" proto="udp" qname="ttl20.m6k.nl" qtype="A" rcode="0" rd="1" remote="127.0.0.1:51770" tcpout="0" throttled="0" timeouts="0" totms="62.282000" validationState="Secure"
> ```
> 
> Next queries are answered from the packet cache:
> 
> ```
> Mar 15 11:09:01 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="2" ts="1710497341.628" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:60969" source="127.0.0.1:60969" tag="0"
> Mar 15 11:09:10 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="2" ts="1710497350.075" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:64138" source="127.0.0.1:64138" tag="0"
> Mar 15 11:09:16 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="2" ts="1710497356.955" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:49550" source="127.0.0.1:49550" tag="0"
> Mar 15 11:09:18 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="2" ts="1710497358.187" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:53663" source="127.0.0.1:53663" tag="0"
> ```
> 
> And close to the deadline a refresh task is created and executed:
> 
> ```
> Mar 15 11:09:19 msg="resolving" subsystem="taskq" level="0" prio="Debug" tid="7" ts="1710497359.201" name="ttl20.m6k.nl" netmask="" qtype="A" refresh="1"
> Mar 15 11:09:19 msg="done" subsystem="taskq" level="0" prio="Debug" tid="7" ts="1710497359.206" name="ttl20.m6k.nl" netmask="" qtype="A" rcode="0" records="2"
> ```
> 
> The next question is NOT a _packet_ cache hit, so the recursor has to resolve, but it has a refreshed entry in the _record_ cache, since it was refreshed by the refresh task: outqueries="0"
> 
> ```
> Mar 15 11:09:19 msg="Question" subsystem="syncres" level="0" prio="Info" tid="2" ts="1710497359.396" ecs="" mtid="2" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:61929"
> Mar 15 11:09:19 msg="Answer" subsystem="syncres" level="0" prio="Info" tid="2" ts="1710497359.397" additional="1" answer-is-variable="0" answers="1" dotout="0" ecs="" into-packetcache="1" maxdepth="1" mtid="2" netms="0.000000" outqueries="0" proto="udp" qname="ttl20.m6k.nl" qtype="A" rcode="0" rd="1" remote="127.0.0.1:61929" tcpout="0" throttled="0" timeouts="0" totms="0.000000" validationState="Secure"
> ```
> 
> Next questions again answered by the packet cache:
> 
> ```
> Mar 15 11:09:25 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="2" ts="1710497365.354" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:56815" source="127.0.0.1:56815" tag="0"
> Mar 15 11:09:30 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="2" ts="1710497370.554" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:56439" source="127.0.0.1:56439" tag="0"
> ```
> 
> Then wait a bit, for the next question both the _packet_ cache and _record_ cache entries are expired, so rec has to do outside queries: outqueries="1"
> 
> ```
> Mar 15 11:09:47 msg="Question" subsystem="syncres" level="0" prio="Info" tid="2" ts="1710497387.693" ecs="" mtid="3" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:55084"
> Mar 15 11:09:47 msg="Answer" subsystem="syncres" level="0" prio="Info" tid="2" ts="1710497387.698" additional="1" answer-is-variable="0" answers="1" dotout="0" ecs="" into-packetcache="1" maxdepth="1" mtid="3" netms="3.781000" outqueries="1" proto="udp" qname="ttl20.m6k.nl" qtype="A" rcode="0" rd="1" remote="127.0.0.1:55084" tcpout="0" throttled="0" timeouts="0" totms="4.399000" validationState="Secure"
> ```
> 
> Next question again answered by packet cache:
> 
> ```
> Mar 15 11:09:48 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="2" ts="1710497388.971" proto="udp" qname="ttl20.m6k.nl" qtype="A" remote="127.0.0.1:54360" source="127.0.0.1:54360" tag="0"
> ```
> 
> So this all works according to the design.
> 
> There is one important thing you need to know: if a refresh task is created by the packet cache, it is not executed immediately. The recursor will only look for tasks to be executed if packet cache misses occurs (plus a periodic thread). So if your recursor is only handling packet cache hits, it will not execute the refresh tasks in time most if the time. This happens a lot in test scenarios with a single client doing the same test query again and again. In a prodcutioin environment this is unlikely to occur. To work around this when testing, you can disable the packet for testing, or run a loop that creates packet cache misses: `while true; do dig $RANDOM.com; sleep 1; done`.
> 
> If this does not explain what you are seeing, please run rec in your lab with the loglevel 7 and quiet=no, and compare what you are seeing with the log above.

I tested it according to your method, and the results I obtained were not the same. The first query yielded the same result，outqueries=1
`msg="Question" subsystem="syncres" level="0" prio="Info" tid="1" ts="1710762725.360" ecs="" mtid="22" proto="udp" qname="view-test.xxx.com" qtype="A" remote="xxxx:34220"
msg="Answer" subsystem="syncres" level="0" prio="Info" tid="1" ts="1710762725.367" additional="1" answer-is-variable="0" answers="1" dotout="0" ecs="" into-packetcache="1" maxdepth="0" mtid="22" netms="6.495000" outqueries="1" proto="udp" qname="view-test.xxx.com" qtype="A" rcode="0" rd="1" remote="xxxx:34220" tcpout="0" throttled="0" timeouts="0" totms="6.620000" validationState="Indeterminate"
`
The second query resulted in a packet cache hit
`
msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="1" ts="1710762728.387" proto="udp" qname="view-test.xxx.com" qtype="A" remote="xxxx:47167" source=":47167" tag="0"
`
However, when the TTL is close to expiration, the record cache is automatically refreshed only upon the first successful caching, and subsequent refreshes do not occur. Is this normal behavior?"

`
 msg="resolving" subsystem="taskq" level="0" prio="Debug" tid="3" ts="1710762199.148" name="view-test.xxx.com" netmask="" qtype="A" refresh="1"
 msg="done" subsystem="taskq" level="0" prio="Debug" tid="3" ts="1710762199.158" name="view-test.xxx.com" netmask="" qtype="A" rcode="0" records="1"
msg="Question" subsystem="syncres" level="0" prio="Info" tid="1" ts="1710762202.270" ecs="" mtid="8" proto="udp" qname="view-test.xxx.com" qtype="A" remote=":41156"
msg="Answer" subsystem="syncres" level="0" prio="Info" tid="1" ts="1710762202.270" additional="1" answer-is-variable="0" answers="1" dotout="0" ecs="" into-packetcache="1" maxdepth="0" mtid="8" netms="0.000000" outqueries="0" proto="udp" qname="view-test.xxx.com" qtype="A" rcode="0" rd="1" remote=":41156" tcpout="0" throttled="0" timeouts="0" totms="0.000000" validationState="Indeterminate"
`
Since then, there have been no occurrences of responses with outqueries=0，I repeated this test on another recursor, but there were no “resolving” log records. The test was conducted on two different nodes with only three requests made. When there was no cache in both the packet cache and record cache, a request was made once. When there was cache in the packet cache, a request was made once. After the packet cache expired, a request was made once."

If the packet cache is turned off and the domain name is requested in a loop with a sleep interval of 1 second, it can be observed from the logs that the records will be refreshed at the set refresh time.

If I use the 'zone to cache' feature to load the NS records of the internal view domain into the cache, and do not use forwarding, then the packet cache will always have cached data. There won't be an increase in latency due to external queries after expiration. However, there is one issue: there should be no requests coming in before ztc loading completes. Otherwise, the NS records corresponding to the domain on the Internet will be obtained through iterative queries. I'm out of ideas on how to handle this."

**Comment by omoerbeek** [comment] 2024-03-19 06:49
Note that the "resolving' log records require debug loglevel.

Your latest comment does not include useful information for me to try to reproduce.

**Comment by omoerbeek** [comment] 2024-07-22 09:14
I marked this "help needed", as I do not have enough information to reproduce.

**Comment by omoerbeek** [comment] 2024-12-09 12:39
Closing, lack of information to be able to reproduce.

**Closed by omoerbeek** 2024-12-09 12:39 UTC
Labels: rec
