### ISSUE TITLE
Suggestion on running multiple PDNS instance.

### ISSUE THREAD

**Issue by aashish791** [PowerDNS/pdns#9681] opened 2020-11-08 13:04 UTC
Hi Team,

Let me start with our current production setup, so we have 4 hypervisor servers on which we are running 2 PDNS instances each(total 8 instances) with PDNS version: 3.4 which we are planning to deprecate it and move to the latest PDNS version(Version: 4.4.). Each PDNS instances used 2 public IP's. 

We wanted to know what could be the best migration strategy along with its pros/cons and needed your suggestion on it.
I can think of the below ones but open to other suggestions as well.

Scenario 1: Run 4 instances with 2 public IP's on each hypervisor, so we can only 2 physical servers. 
Scenario 2: Run 2 instances each on 2 hypervisors with each instance will use 4 public IP's. 

P:S:  We have purchased 2 physical servers with good configuration(196GB RAM, 64 core CPU) and planning to deprecate the existing 4 physical servers.

Please suggest how can I proceed further? Hope I am able to explain my concerns.

Regards,
Aashish

**Comment by pieterlexis** [comment] 2020-11-08 13:26
I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2020-11-08 13:26 UTC
