### ISSUE TITLE
pdns_server refuses to reload after fixing a 'rejected' zone (bind backend)

### ISSUE THREAD

**Issue by mjholtkamp** [PowerDNS/pdns#1107] opened 2013-11-15 14:59 UTC
After making a mistake in my bind-style zone file, I noticed that pdns reported SERVFAIL for the domain. I fixed the mistake, did 'pdns_control reload' and I still got the SERVFAIL. 

Steps to reproduce:
 * Make a mistake in the zone file, mine was putting in: ```* IN SPF "v=spf1 ~all"``` after ```$ORIGIN "."```. (I know now that the wildcard was not a solution anyway, but that's a different matter).
 * Update the serial number
 * Run ```pdns_control reload``` (maybe add the domain, I did it without because the server only hosts a couple of small domains)
 * Query your DNS-server for your domain (observe SERVFAIL: this is expected)
 * Fix the mistake in the zone file (e.g. remove the offending line)
 * Update the serial number
 * Run ```pdns_control reload``` again.
 * Query your DNS-server again.

Expected behaviour:
 * Don't return SERVFAIL after fixing the mistake and reloading

Observations:
 * Again a SERVFAIL
 * In the logs (actual hostname and domain names censored): 

```
    Nov 15 15:21:19 hostname pdns[2142]: Reload was requested
    Nov 15 15:21:21 hostname pdns[2142]: Database module reported condition which prevented lookup (Zone for 'example.org' in '/zones/example.org' temporarily not available (file missing, or master dead)) sending out servfail
```

Notes:
 * version: ```Version: 3.1, compiled on Jun 28 2012, 21:22:51 with gcc version 4.7.0``` (debian jessie: 3.1-4)
 * using bind backend

**Comment by pieterlexis** [comment] 2016-05-04 13:53
This appears fixed in master. Can't reproduce, data is ignored.
```
example.net:     error at 2016-05-04 13:53:29 +0200 parsing 'example.net.' from file '/home/lieter/src/PowerDNS/pdns-conf/bind1/example.net.zone': Trying to insert non-zone     data, name='*.".".', qtype=SPF, zone='example.net.'
```

**Closed by pieterlexis** 2016-05-04 13:53 UTC
Labels: auth, defect
