### ISSUE TITLE
Dynamic DNS Update with MySql in backend, ServFail returned

### ISSUE THREAD

**Issue by anhackin** [PowerDNS/pdns#8919] opened 2020-03-10 16:30 UTC
### Issue
- Program: Authoritative
- Issue type: Bug report

### Short description
ServFail returned because the column 'change_date' in the 'records' table no longer exists.

### Environment
 - Operating system: Debian 10 Buster
 - Software version: 4.1.6
 - Software source: Debian repositories

### Steps to reproduce
1. Import or create a zone
2. Enable dynamic dns update in config
3. Set correct values for TSIG-ALLOW-DNSUPDATE and ALLOW-DNSUPDATE-FROM
3. Create keys for dymanic DNS update
4. Try random update with nsupdate

### Expected behaviour
NoError returned

### Actual behaviour
ServFail returned

### PowerDNS logs

> Mar 10 16:03:02 node1 pdns_server[15637]: UPDATE (15001) from 127.0.0.1 for example.com: Processing started.
Mar 10 16:03:02 node1 pdns_server[15637]: UPDATE (15001) from 127.0.0.1 for example.com: starting transaction.
Mar 10 16:03:02 node1 pdns_server[15637]: UPDATE (15001) from 127.0.0.1 for example.com: Adding record test.example.com|TXT
Mar 10 16:03:02 node1 pdns_server[15637]: UPDATE (15001) from 127.0.0.1 for example.com: Caught PDNSException: GSQLBackend unable to feed record: Could not prepare statement: insert into records (content,ttl,prio,type,domain_id,disabled,name,ordername,auth,change_date) values (?,?,?,?,?,?,?,?,?,NULL): Unknown column 'change_date' in 'field list'; Sending ServFail!

### Thank you
Amazing work by the way, really love PowerDNS ;-)

**Comment by mnordhoff** [comment] 2020-03-10 16:42
It sounds like your database is using the schema for version 4.2 or 4.3. You should... not do that. :P

You could upgrade to a newer version using the packages on https://repo.powerdns.com/.

If it's convenient, you could blow away your database and recreate it with the 4.1 schema. There is a link to it on https://doc.powerdns.com/authoritative/backends/generic-mysql.html.

There are .sql files to **upgrade** the database. See e.g. https://github.com/PowerDNS/pdns/tree/master/modules/gmysqlbackend. There aren't prepared files available, but you could do the _opposite_ to downgrade it.

Finally, this appears to be a support question, not a bug. If you need additional help, you should ask on the IRC channel or post on the mailing list. :-) https://www.powerdns.com/opensource.html

**Comment by Habbie** [comment] 2020-03-10 20:22
@mnordhoff thanks!

Indeed, this is a support question, so i'm closing it. If you need additional help, please come to IRC or the pdns-users list.

**Closed by Habbie** 2020-03-10 20:22 UTC
