### ISSUE TITLE
There is a lot of outgoing timeouts .

### ISSUE THREAD

**Issue by mengxifl** [PowerDNS/pdns#8151] opened 2019-08-01 03:00 UTC
### Short description

there is a lot of outgoing timeouts .

Aug 01 02:03:30 stats: 227073 questions, 17646 cache entries, 1302 negative entries, 7% cache hits
Aug 01 02:03:30 stats: throttle map: 2, ns speeds: 2
Aug 01 02:03:30 stats: outpacket/query ratio 49%, 0% throttled, 0 no-delegation drops
Aug 01 02:03:30 stats: 2 outgoing tcp connections, 0 queries running, 4467 outgoing timeouts
Aug 01 02:03:30 stats: 14641 packet cache entries, 48% packet cache hits
Aug 01 02:03:30 stats: 4 qps (average over 60 seconds)

timeouts  probability    4467 / 227073 * 100 = 1.9% 

it Normal ？

### Environment
 - Operating system: alpine 3.9
 - Software version: PowerDNS Recursor 4.1.9 
 - Software source: I use apk add install it

### Steps to reproduce
1. I have a k8s cluster 
2. I run apk add pdns-recursor in the  alpine 3.9  image  install pdns-recursor 4.1.9 
3. Use exec pdns_recursor it load default config file

### Expected behaviour

I think timeout times is too many

### Actual behaviour

```
bash-4.4# rm -rf /nsspeeds && rec_control dump-nsspeeds /nsspeeds && cat /nsspeeds
dumped 2 records
; nsspeed dump from thread follows
;
; nsspeed dump from thread follows
;
(empty) -> 219.141.136.10/2471.647461 219.141.140.10/1000000.000000 
; nsspeed dump from thread follows
;
(empty) -> 219.141.136.10/2813.262939 219.141.140.10/4304.000000
```

dig

bash-4.4# dig @219.141.140.10 bing.cn
```
; <<>> DiG 9.12.3-P4 <<>> @219.141.140.10 bing.cn
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50425
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;bing.cn.			IN	A

;; ANSWER SECTION:
bing.cn.		1	IN	CNAME	fw.dnsforwardingservice.com.
fw.dnsforwardingservice.com. 1	IN	A	128.14.144.128
fw.dnsforwardingservice.com. 1	IN	A	128.14.144.129

;; Query time: 40 msec
;; SERVER: 219.141.140.10#53(219.141.140.10)
;; WHEN: Thu Aug 01 02:49:37 UTC 2019
;; MSG SIZE  rcvd: 98
```

### Other information
I have 3 machines run 3 recursor 

config file
```
    local-address=0.0.0.0
    local-port=5300
    forward-zones-recurse=.=219.141.136.10;219.141.140.10
    max-cache-ttl=60
    max-negative-ttl=60
    packetcache-servfail-ttl=15
    packetcache-ttl=60
    network-timeout=5000
    statistics-interval=60
    loglevel=9
```

**Comment by rgacogne** [comment] 2019-08-01 07:42
The cause of timeouts is almost always an issue with the network or misbehaving authoritative servers.
I am closing this issue as so far it appears to be a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by rgacogne** 2019-08-01 07:42 UTC
