### ISSUE TITLE
aarch64/arm64 repository

### ISSUE THREAD

**Issue by g00g1** [PowerDNS/pdns#12960] opened 2023-06-28 13:19 UTC
- Program: Authoritative
 - Issue type: Feature request

### Short description
aarch64/arm64 support for official repository, currently it is unavailable:
```
Errors during downloading metadata for repository 'powerdns-auth-48':
  - Status code: 404 for http://repo.powerdns.com/el/aarch64/9/auth-48/repodata/repomd.xml (IP: 2a03:b0c0:2:d0::4a4:6001)
Error: Failed to download metadata for repo 'powerdns-auth-48': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

### Usecase
Support wider variety of environments where PowerDNS runs

### Description
I would ask to add aarch64/arm64 binaries to the repositories

**Comment by Habbie** [comment] 2023-06-28 13:19
duplicate of #8655

**Closed by Habbie** 2023-06-28 13:19 UTC
