### ISSUE TITLE
option to define source-address to carbonServer()

### ISSUE THREAD

**Issue by DNS-Leo** [PowerDNS/pdns#8199] opened 2019-08-14 16:08 UTC
When dnsdist is running on anycasted IP's it cannot reach the carbon server.
Defining an out-of-band IP using setLocal() wont help.
Also the order of setLocal() or addLocal doesn't help for me.

What did help is using a firewall to manipulate the source IP, but I rather have that done correctly by dnsdist itself.

Reading issue #1936 I see the problem is not just in dnsdist but also in pdns, and I guess it could also be an issue in pdns-recursor.

So this is kind of a Bug report but mainly a Feature request:

Can the function go from
carbonServer(serverIP[, ourname[, interval[, namespace[, instance]]]])
to
carbonServer(serverIP[, ourname[, interval[, namespace[, instance, src-addr]]]]])

### Description
add the option to define the source IP for carbon server statistic reports.

**Comment by Habbie** [comment] 2019-08-14 16:42
Hi Leo,

I've added the dnsdist label to #1936, which makes this ticket a duplicate of it, so I'll close this one.

**Closed by Habbie** 2019-08-14 16:42 UTC
Labels: dnsdist, feature request
