### ISSUE TITLE
dnsdist 1.2.0 - negative values in web gui stats

### ISSUE THREAD

**Issue by rygl** [PowerDNS/pdns#5652] opened 2017-08-25 06:51 UTC
Hi,

first of all - congrats to the new stable version! I have found a small issue so far: dnsdist 1.2.0 running for about 17 hours shows negative values of outgoing req. in web gui.

`#       Name    Address Status  Latency Queries Drops   QPS     Out     Weight  Order   Pools`
`0       beluga1 a.b.c.2:53      up      7       91783938        452810  2159    -78     100     1`
`1       beluga2 a.b.c.3:53      up      5       91783128        444472  2193    -67     100     1`
`2       beluga3 a.b.c.4:53      up      5       91793134        451395  2180    -96     100     1`
`3       beluga4 a.b.c.5:53      up      28      594399  1915    5       1       100     1       quarantine`
`4       murena4 a.b.c.37:53     up      27      593830  1800    6       0       100     1       quarantine`
`5       beluga1-ipv6    [x:x:x:x:1:2]:53        up      10      3362255 10574   66      1       100     1       ipv6_pool`
`6       beluga2-ipv6    [x:x:x:x:1:3]:53        up      7       3367511 10676   66      4       100     1       ipv6_pool`
`7       beluga3-ipv6    [x:x:x:x:1:4]:53        up      9       3368539 10726   89      2       100     1       ipv6_pool`
`8       beluga4-ipv6    [x:x:x:x:1:5]:53        up      0       0       0       0       0       100     1       ipv6_quarantine`
`9       murena4-ipv6    [x:x:x:y:1:5]:53        up      0       0       0       0       0       100     1       ipv6_quarantine`

Thanks

Aleš

**Comment by tbaschak** [comment] 2017-10-06 04:31
Pretty sure this is a duplicate of Issues #4344 and #3288

**Closed** 2017-12-15 09:39 UTC
Labels: defect, dnsdist
