### ISSUE TITLE
gmysql-zone-lastchange-query very slow

### ISSUE THREAD

**Issue by sirjbaxter** [PowerDNS/pdns#6700] opened 2018-05-31 18:24 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description

On upgrading powerdns authoritative with gmysql backed  to version 4.1.3 it started maxing out the mysql backend due to the  gmysql-zone-lastchange-query "select max(change_date) from records where domain_id=?".
Note that change_date is not indexed on the records table so this forces a table scan for the domain. In my case I am serving a local authoritative version of several top-level domains (.com included), so this results in > 300M rows being scanned on each query. 

### Environment

 - Operating system: Linux, OpenSUSE Tumbleweed
 - Software version: 4.1.3
 - Software source: Operating system repository

### Steps to reproduce

1. Run powerdns with gmysql backend and a huge domain.
2. Query powerdns.
3. Watch mysql server load -> infinity.

### Expected behaviour
mysql backend easily handles powerdns load

### Actual behaviour
mysql backend gets hung up executing "select max(change_date) from records where domain_id=?"

### Other information
Workaround: add gmysql-zone-lastchange-query="select 0" to pdns.conf file. However I don't know if this causes problems elsewhere. Note that I don't need the autoserial functionality.

**Comment by Habbie** [comment] 2018-06-07 08:53
> Workaround: add gmysql-zone-lastchange-query="select 0" to pdns.conf file. However I don't know if this causes problems elsewhere. Note that I don't need the autoserial functionality.

You say you don't need it but something is causing it to happen. Do you have a '0' serial on any domains? Can you log the `domain_id` for the lastchange query that is happening?

**Comment by sirjbaxter** [comment] 2018-06-07 12:34
The domain_id in the query can be 1,2,3. Not sure exactly what you are asking for in regards to '0' serial, but I have logged the DB structure and example contents of what appear to be the relevant tables:
```
MariaDB [pdns]> show tables;
+----------------+
| Tables_in_pdns |
+----------------+
| comments       |
| cryptokeys     |
| domainmetadata |
| domains        |
| records        |
| supermasters   |
| tsigkeys       |
+----------------+

MariaDB [pdns]> select * from domains;
+----+------+--------+------------+--------+-----------------+---------+
| id | name | master | last_check | type   | notified_serial | account |
+----+------+--------+------------+--------+-----------------+---------+
|  1 | com  | NULL   |       NULL | native |            NULL | NULL    |
|  2 | net  | NULL   |       NULL | native |            NULL | NULL    |
|  3 | org  | NULL   |       NULL | native |            NULL | NULL    |
+----+------+--------+------------+--------+-----------------+---------+

MariaDB [pdns]> select * from records limit 100,5;
+-----+-----------+-------------------------+------+-------------------------------+--------+------+-------------+----------+-----------+------+
| id  | domain_id | name                    | type | content                       | ttl    | prio | change_date | disabled | ordername | auth |
+-----+-----------+-------------------------+------+-------------------------------+--------+------+-------------+----------+-----------+------+
| 101 |         1 | bestsellerbootcamp.com  | NS   | NS2.PARKINGCREW.NET           | 172800 | NULL |        NULL |        0 | NULL      |    1 |
| 102 |         1 | brokergeneralagents.com | NS   | NS1.CA.EINSTEININDUSTRIES.COM | 172800 | NULL |        NULL |        0 | NULL      |    1 |
| 103 |         1 | brokergeneralagents.com | NS   | NS2.CA.EINSTEININDUSTRIES.COM | 172800 | NULL |        NULL |        0 | NULL      |    1 |
| 104 |         1 | newstrac.com            | NS   | NS07.DOMAINCONTROL.COM        | 172800 | NULL |        NULL |        0 | NULL      |    1 |
| 105 |         1 | newstrac.com            | NS   | NS08.DOMAINCONTROL.COM        | 172800 | NULL |        NULL |        0 | NULL      |    1 |
+-----+-----------+-------------------------+------+-------------------------------+--------+------+-------------+----------+-----------+------+

MariaDB [pdns]> select count(*) from records;
+-----------+
| count(*)  |
+-----------+
| 376794421 |
+-----------+

MariaDB [pdns]> describe domainmetadata;
+-----------+-------------+------+-----+---------+----------------+
| Field     | Type        | Null | Key | Default | Extra          |
+-----------+-------------+------+-----+---------+----------------+
| id        | int(11)     | NO   | PRI | NULL    | auto_increment |
| domain_id | int(11)     | NO   | MUL | NULL    |                |
| kind      | varchar(32) | YES  |     | NULL    |                |
| content   | text        | YES  |     | NULL    |                |
+-----------+-------------+------+-----+---------+----------------+

MariaDB [pdns]> select * from domainmetadata;
Empty set (0.00 sec)
 ```

**Comment by Habbie** [comment] 2018-06-07 12:35
Can you show the SOA records for the three zones?

**Comment by sirjbaxter** [comment] 2018-06-07 12:57
Like this?
```
MariaDB [pdns]> select * from records limit 1;
+----+-----------+------+------+----------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
| id | domain_id | name | type | content                                                                    | ttl  | prio | change_date | disabled | ordername | auth |
+----+-----------+------+------+----------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
|  1 |         1 | com  | SOA  | a.gtld-servers.net nstld.verisign-grs.com 1526486536 1800 900 604800 86400 |  900 | NULL |        NULL |        0 | NULL      |    1 |
+----+-----------+------+------+----------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
```

**Comment by Habbie** [comment] 2018-06-07 12:59
Do you think you can show a setup with just a few records entries that also shows lastchange-query happening? Because it should not happen in your setup.

**Comment by sirjbaxter** [comment] 2018-06-07 12:59
All 3 domains: 
```
MariaDB [pdns]> select * from records where name in ('com','net','org') and type='SOA';
+-----------+-----------+------+------+-------------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
| id        | domain_id | name | type | content                                                                       | ttl  | prio | change_date | disabled | ordername | auth |
+-----------+-----------+------+------+-------------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
|         1 |         1 | com  | SOA  | a.gtld-servers.net nstld.verisign-grs.com 1526486536 1800 900 604800 86400    |  900 | NULL |        NULL |        0 | NULL      |    1 |
| 316528181 |         2 | net  | SOA  | a.gtld-servers.net                                                            | 3600 | NULL |        NULL |        0 | NULL      |    1 |
| 351144340 |         3 | org  | SOA  | A0.ORG.AFILIAS-NST.INFO NOC.AFILIAS-NST.INFO 2012989015 1800 900 604800 86400 | 3600 | NULL |        NULL |        0 | NULL      |    1 |
+-----------+-----------+------+------+-------------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
```

**Comment by Habbie** [comment] 2018-06-07 13:00
your `net` SOA is incomplete, triggering the lastchange-query

Closing this as it's not a bug then.

**Closed by Habbie** 2018-06-07 13:00 UTC
Labels: auth, defect

**Comment by sirjbaxter** [comment] 2018-06-07 13:12
Ah - that makes sense. The net file moved from verisign to czdap which has a different format and our scripts were not correctly updated for the SOA record. Thanks.
