### ISSUE TITLE
gmysql table schema column change_date removed between 4.1 and 4.2

### ISSUE THREAD

**Issue by EelcoD** [PowerDNS/pdns#10117] opened 2021-02-23 20:27 UTC
- Program: Authoritative
 - Issue type: Bug report

### Environment

 - Operating system:  SUSE 15 SP 2
 - Software version:  pdns 4.3.1
 - Software source: SUSE 15 SP2 
 - 

### Steps to reproduce

1. cannot add powerdns records from phpipam because column not in table 
2. 
3. 

### Expected behaviour
insert record into table

### Actual behaviour

get error in phpipam

### Other information

pse return column back into default database schema

**Comment by pieterlexis** [comment] 2021-02-23 20:31
This is noted in the [upgrade docs](https://doc.powerdns.com/authoritative/upgrading.html#x-to-4-2-0)

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed** 2021-02-23 20:33 UTC
