### ISSUE TITLE
disabling cache not working for PowerDNS Recursor

### ISSUE THREAD

**Issue by deepika-maj** [PowerDNS/pdns#8373] opened 2019-10-02 17:42 UTC
I am trying to get records with original TTL and for that I tried to disable cache by adding following config to `/etc/powerdns/recursor.conf`:

```
disable-packetcache=yes
```
however it is still responding with cached TTL values for all records.

is this a bug?

I am using PowerDNS Recursor 4.2.0

**Comment by pieterlexis** [comment] 2019-10-02 17:48
The packet-cache caches whole DNS answers and is disabled in 4.2.0 with this setting:

```
$ ./pdns_recursor --local-port=5300 --socket-dir=. --trace --security-poll-suffix= --dnssec=validate --threads=1 --disable-packetcache 
....
Oct 02 19:45:11 1 [1/1] answer to question 'www.powerdns.com|A': 1 answers, 1 additional, took 8 packets, 391.59 netw ms, 408.616 tot ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=0, dnssec=Secure
Oct 02 19:45:12 1 [2/1] question for 'www.powerdns.com|A' from 127.0.0.1:44670
...
Oct 02 19:45:12 1 [2/1] answer to question 'www.powerdns.com|A': 1 answers, 1 additional, took 0 packets, 0 netw ms, 0 tot ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=0, dnssec=Secure
```

compared to:
```
$ ./pdns_recursor --local-port=5300 --socket-dir=. --trace --security-poll-suffix= --dnssec=validate --threads=1
...
Oct 02 19:46:30 1 [1/1] answer to question 'www.powerdns.com|A': 1 answers, 1 additional, took 8 packets, 278.16 netw ms, 293.385 tot ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=0, dnssec=Secure
Oct 02 19:46:31 1 question answered from packet cache tag=0 from 127.0.0.1:48153
```

The record cache could be effectively disabled by setting `max-cache-entries` to a very low number, but is NOT RECOMMENDED as the whole reason for having a resolver is the cache.

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2019-10-02 17:48 UTC

**Comment by deepika-maj** [comment] 2019-10-02 18:34
I tried with having both configs:

```
disable-packetcache=yes
max-cache-entries=0
```

but the queries are still hitting the cache

**Comment by Habbie** [comment] 2019-10-02 18:34
> I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on IRC.

I am now closing conversation on this issue, to make it clear that there is no support here. Please find us on IRC or our mailing list.
