### ISSUE TITLE
Failed at step NAMESPACE spawning /usr/sbin/pdns_server: Invalid argument with CentOS 7

### ISSUE THREAD

**Issue by aiso-net** [PowerDNS/pdns#9929] opened 2021-01-11 04:13 UTC
Fresh OS and PDNS install and get a startup error on CentOS 7:
[root@web ~]# service pdns start
Redirecting to /bin/systemctl start pdns.service
Job for pdns.service failed because the control process exited with error code. See "systemctl status pdns.service" and "journalctl -xe" for details.
[root@web ~]# journalctl -xe
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit pdns.service has begun starting up.
Jan 11 03:59:26 web systemd[22886]: Failed at step CAPABILITIES spawning /usr/sbin/pdns_server: Invalid argument
-- Subject: Process /usr/sbin/pdns_server could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- The process /usr/sbin/pdns_server could not be executed and failed.
--
-- The error number returned by this process is 22.
Jan 11 03:59:26 web1 systemd[1]: pdns.service: main process exited, code=exited, status=218/CAPABILITIES
Jan 11 03:59:26 web1 systemd[1]: Failed to start PowerDNS Authoritative Server.
-- Subject: Unit pdns.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit pdns.service has failed.
--
-- The result is failed.
Jan 11 03:59:26 web1 systemd[1]: Unit pdns.service entered failed state.
Jan 11 03:59:26 web1 systemd[1]: pdns.service failed.

 - Program: Authoritative
 - Issue type: Bug report

### Short description
It appears that AmbientCapabilities is not working (Fails) on CentOS 7 plus kernel. Tested on KVM (non-plus kernel) without issue.

### Environment

 - Operating system: CentOS 7 plus kernel
 - Software version: 3.10.0-229.20.1.el7.centos.plus.x86_64
 - Software source: PowerDNS CentOS 7 repository

### Steps to reproduce

1. yum install epel-release yum-plugin-priorities &&
curl -o /etc/yum.repos.d/powerdns-auth-44.repo https://repo.powerdns.com/repo-files/centos-auth-44.repo &&
yum install pdns
2. service pdns start

### Expected behaviour
The service to start

### Actual behaviour
The service failed

### Other information
rpm -qa | grep systemd
systemd-sysv-219-78.el7_9.2.x86_64
systemd-219-78.el7_9.2.x86_64
systemd-libs-219-78.el7_9.2.x86_64

sestatus
SELinux status:                 disabled

rpm -q centos-release
centos-release-7-9.2009.1.el7.centos.x86_64

systemd-detect-virt
kvm

systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

When I remark out AmbientCapabilities and then do systemctl daemon-reload ; service pdns start I get:
Jan 11 04:08:43 web pdns_server[24318]: Loading '/usr/lib64/pdns/libgmysqlbackend.so'
Jan 11 04:08:43 web pdns_server[24318]: This is a standalone pdns
Jan 11 04:08:43 web pdns_server[24318]: Listening on controlsocket in '/run/pdns/pdns.controlsocket'
Jan 11 04:08:43 web pdns_server[24318]: Unable to bind UDP socket to '0.0.0.0:53': Permission denied
Jan 11 04:08:43 web pdns_server[24318]: Fatal error: Unable to bind to UDP socket
Jan 11 04:08:43 web systemd[1]: pdns.service: main process exited, code=exited, status=1/FAILURE
Jan 11 04:08:43 web systemd[1]: Failed to start PowerDNS Authoritative Server.

When I keep it remarked out and add under service:
Capabilities=cap_net_bind_service+ep
SecureBits=keep-caps
then do systemctl daemon-reload ; service pdns start I get:
Jan 11 04:10:29 web pdns_server[24643]: Loading '/usr/lib64/pdns/libgmysqlbackend.so'
Jan 11 04:10:29 web pdns_server[24643]: This is a standalone pdns
Jan 11 04:10:29 web pdns_server[24643]: Listening on controlsocket in '/run/pdns/pdns.controlsocket'
Jan 11 04:10:29 web pdns_server[24643]: Unable to bind UDP socket to '0.0.0.0:53': Permission denied
Jan 11 04:10:29 web pdns_server[24643]: Fatal error: Unable to bind to UDP socket
Jan 11 04:10:29 web systemd[1]: pdns.service: main process exited, code=exited, status=1/FAILURE
Jan 11 04:10:29 web systemd[1]: Failed to start PowerDNS Authoritative Server.

**Comment by jsoref** [comment] 2021-01-11 06:50
@pieterlexis added AmbientCapabilities in #7956

The short of it is that this feature wasn't in the systemd that shipped w/ rhel7:
https://github.com/antoiner77/caddy-ansible/issues/31#issuecomment-296024862
https://unix.stackexchange.com/questions/550631/does-rhel-7-support-ambient-capabilities

**Comment by Habbie** [comment] 2021-01-11 07:39
> The short of it is that this feature wasn't in the systemd that shipped w/ rhel7:

Given that it works with the stock kernel, I'm pretty sure that's not the issue.

**Comment by pieterlexis** [comment] 2021-01-11 09:15
> Given that it works with the stock kernel, I'm pretty sure that's not the issue.

from the OP:

> Operating system: CentOS 7 plus kernel
> Software version: 3.10.0-229.20.1.el7.centos.plus.x86_64

Systemd on an ancient 3.10 kernel is asking for trouble, please install the normal CentOS kernel.

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2021-01-11 09:15 UTC
Labels: auth

**Comment by Habbie** [comment] 2021-01-11 09:38
> Systemd on an ancient 3.10 kernel is asking for trouble, please install the normal CentOS kernel.

Just for anyone who runs into this later: 3.10 is in fact the kernel version shipped in CentOS and CentOS plus. However, it's at 3.10.0-1160.* now, in both - so the reporter above is running an outdated kernel.

**Comment by aiso-net** [comment] 2021-01-11 16:48
Habbie, is correct make sure your running the latest kernel, and double check your grub config to make sure your booting into the latest kernel, centos plus should match the stock non plus kernel version. My grub was not booting into latest version installed so that was my issue.

**Comment by brianredbeard** [comment] 2021-04-25 00:58
FYI, with RHEL (and derivatives except for "stream" based versions) every major package gets version locked at the time of major release.  e.g. RHEL 7 shipped 3.10.0 in 2014.... and it will still be shipping a 3.10.0 kernel in the year 2023.  RHEL 8 ships a 4.18 kernel and will still have a 4.18 kernel in 2029: https://access.redhat.com/support/policy/updates/errata#Retired_Life_Cycle_Dates

That's the "value" of RHEL: patches get back-ported toguarantee administrators can be lazy and (theoretically) never have to worry about API, ABI, or configuration syntax changes.
