### ISSUE TITLE
DNSSEC is not supported via the API yet

### ISSUE THREAD

**Issue by ju5t** [PowerDNS/pdns#4262] opened 2016-07-31 08:12 UTC
On the API specification for [zone_collection](https://doc.powerdns.com/md/httpapi/api_spec/#zone95collection) you mention that DNSSEC is not yet implemented.

> TODO: dnssec, nsec3narrow, nsec3param, presigned are not yet implemented.

When would this be on the roadmap? We're in the process of migrating to 4.x and I really want to get rid of some old scripts while we are at it.

**Comment by Habbie** [comment] 2016-07-31 08:35
Duplicate of #1433; work in progress in #4106 where your testing and comments are welcome. Closing this one.

**Closed** 2016-08-01 09:16 UTC
