### ISSUE TITLE
nproxy health-check not recognized

### ISSUE THREAD

**Issue by Snowmanko** [PowerDNS/pdns#7525] opened 2019-02-27 10:40 UTC
Hi,

I am using nproxy to proxy notify events to backend slave pdns. When I try to use health-checks, id does not work and do not handle UDP packet as health-check packet.

From man : 
`nproxy also has a health-check option built in. A query for 'pdns.nproxy.' with QType 'TXT' will be responded to with an answer of "OK" (inside the TXT record. When the query is for an A-record, '1.2.3.4.' is returned.`

I am running nproxy on port 54.
1/ A query
Query - dig -p 54 -tA 'pdns.nproxy.' @[IP]
;; global options: +cmd
;; connection timed out; no servers could be reached

nproxy LOG - nproxy: Received non-notification packet for domain 'pdns.nproxy.' from external nameserver [IP]:[PORT]

2/ TXT query
Query - dig -p 54 -tTXT 'pdns.nproxy.' @[IP]
;; global options: +cmd
;; connection timed out; no servers could be reached

nproxy LOG - nproxy: Received non-notification packet for domain 'pdns.nproxy.' from external nameserver [IP]:[PORT]

Can someone test it or advice where can be the problem ?
BR!

**Comment by Snowmanko** [comment] 2019-02-27 10:41
My version is : 4.0.3-1+deb9u3 - Debian 9

**Comment by rgacogne** [comment] 2019-02-27 11:01
This is because `dig` is sending an `OPT` record `nproxy` doesn't expect, try with `+noedns`.

I am closing this issue as it appears to be a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [dnsdist mailinglist](https://mailman.powerdns.com/mailman/listinfo/dnsdist), or join us on IRC.

**Closed by rgacogne** 2019-02-27 11:01 UTC

**Comment by Snowmanko** [comment] 2019-02-27 11:05
Working! Thanks!
