### ISSUE TITLE
Crash on AXFR of one specific zone

### ISSUE THREAD

**Issue by Fil0sOFF** [PowerDNS/pdns#2843] opened 2015-11-02 14:22 UTC
PowerDNS crashes after each AXFR request to example.org domain. Here's MySQL dump https://gist.github.com/Fil0sOFF/fddbc6f1164b3fa35e11
Tested on the official pdns-static-3.4.6-1.x86_64 rpm package ( but it seems that all 3.4.x versions are affected). At the same time digging any specific record type (NS,MX,SOA) succeeds, but AXFR fails.
It works on 3.3.x though. 

After dropping ANY of those MX records, AXFR starts working.

The error log says the following about the crash:
```
Nov  2 13:59:41 nc-ph-0051-02 pdns[11688]: Got a signal 11, attempting to print trace: 
Nov  2 13:59:41 nc-ph-0051-02 pdns[11688]: /usr/sbin/pdns_server-instance() [0x63b350]
Nov  2 13:59:41 nc-ph-0051-02 pdns[11688]: /lib64/libc.so.6(+0x326a0) [0x7fa1b2ea36a0]
Nov  2 13:59:41 nc-ph-0051-02 pdns[11688]: /usr/sbin/pdns_server-instance() [0x6ec884]
Nov  2 13:59:41 nc-ph-0051-02 pdns[11688]: /usr/sbin/pdns_server-instance(_ZSt25__unguarded_linear_insertIN9__gnu_cxx17__normal_iteratorIP17DNSResourceRecordSt6vectorIS2_SaIS2_EE
EEPFbRKS2_S9_EEvT_T0_+0x129) [0x6e4a59]
Nov  2 13:59:41 nc-ph-0051-02 pdns[11688]: /usr/sbin/pdns_server-instance(_ZN18ChunkedSigningPipe10dedupRRSetEv+0x339) [0x6efa59]
Nov  2 13:59:41 nc-ph-0051-02 pdns[11688]: /usr/sbin/pdns_server-instance(_ZN18ChunkedSigningPipe6submitERK17DNSResourceRecord+0x60) [0x6efbc0]
Nov  2 13:59:41 nc-ph-0051-02 pdns[11688]: /usr/sbin/pdns_server-instance(_ZN13TCPNameserver6doAXFRERKSsN5boost10shared_ptrI9DNSPacketEEi+0x2e94) [0x5ec834]
Nov  2 13:59:41 nc-ph-0051-02 pdns[11688]: /usr/sbin/pdns_server-instance(_ZN13TCPNameserver12doConnectionEPv+0xabd) [0x5f0fcd]
Nov  2 13:59:41 nc-ph-0051-02 pdns[11688]: /lib64/libpthread.so.0(+0x7a51) [0x7fa1b320ca51]
Nov  2 13:59:41 nc-ph-0051-02 pdns[11688]: /lib64/libc.so.6(clone+0x6d) [0x7fa1b2f5993d]
Nov  2 13:59:42 nc-ph-0051-02 pdns[8513]: Our pdns instance (11688) exited after signal 6
Nov  2 13:59:42 nc-ph-0051-02 pdns[8513]: Respawning
```

**Comment by Habbie** [comment] 2015-11-02 14:24
1. Are you saying that removing -just one- MX record, no matter which one, makes the crash go away?
2. Can you try removing the trailing dot from all the MX records to see if that helps?

**Comment by Fil0sOFF** [comment] 2015-11-02 14:31
Yes, removing just one of those MX records makes the crash go away.
Removing the trailing dot doesn't help.

**Comment by Habbie** [comment] 2015-11-02 14:37
The backtrace suggests you are signing with DNSSEC; your database dump suggests you are not. Can you clarify?

**Comment by Fil0sOFF** [comment] 2015-11-02 14:54
DNSSEC is not enabled in my config file. Here is what I'm using https://gist.github.com/Fil0sOFF/32ae24a84f2cc17b5d1b

**Comment by pieterlexis** [comment] 2015-11-02 15:22
@Fil0sOFF Thanks, we can reproduce the crash and are looking into the reason for it.

**Comment by pieterlexis** [comment] 2015-11-02 17:23
The fix to this issue will be in the next release. But I was wondering... where do you these amounts (and names) of MX records for?

**Comment by Fil0sOFF** [comment] 2015-11-03 12:32
Thank you for such a quick fix.
We host a couple of DNS servers, it was a zone of one of the clients. Not sure what it's for.

**Closed** 2015-11-03 13:57 UTC
