### ISSUE TITLE
local-address: default to "127.0.0.1, ::1"

### ISSUE THREAD

**Issue by terrorobe** [PowerDNS/pdns#1497] opened 2014-07-01 10:17 UTC
alternatively: localhost magic keyword that binds to all available protocol families' loopback address? ;)

**Comment by Habbie** [comment] 2015-12-04 15:40
We can do this now that #2893 is merged. PR welcome!

**Comment by Habbie** [comment] 2015-12-04 16:20
duplicate of #1258

**Closed by Habbie** 2015-12-04 16:20 UTC
Labels: enhancement, rec
