### ISSUE TITLE
Multiple webserver-addresses

### ISSUE THREAD

**Issue by emilstahl** [PowerDNS/pdns#4282] opened 2016-08-04 09:04 UTC
webserver-address can't be set to multiple IP adresses. This is bad if you want it to listen on IPv4 and IPv6.

```
Exiting because: Unable to convert presentation address '94.231.110.90,2a02:2338:ff00::887:1'
Exiting because: Unable to convert presentation address '94.231.110.90,2a02:2338:ff00::887:1'
```

**Comment by Habbie** [comment] 2016-08-04 11:58
Duplicate of #960, closing. Thank you for your report!

**Closed by Habbie** 2016-08-04 11:58 UTC
