### ISSUE TITLE
CentOS6 don't have geoip backend in repo

### ISSUE THREAD

**Issue by dzxx36gyy** [PowerDNS/pdns#5761] opened 2017-10-02 19:02 UTC
### Short description
It seems there's no pdns-backend-geoip in CentOS6 Repo (both the epel or the official), how can i get it ?

### Environment
CentOS 6.9 x86_64

**Comment by pieterlexis** [comment] 2017-10-03 05:17
The libyaml-cpp in EL6 is too old to use with the geoip backend. There are 2 ways to get it:

1.  switch to EL 7
2. compile libyaml-cpp (and possibly libmaxminddb) yourself and compile PowerDNS against that

Closing as this is a support question and not a bug. Please use the [mailinglist](https://powerdns.com//mailing-lists.html) or [IRC](https://powerdns.com//opensource.html) for support.

**Closed by pieterlexis** 2017-10-03 05:17 UTC
