### ISSUE TITLE
AXFR garbage in zone with eccentric RRtypes

### ISSUE THREAD

**Issue by mdavids** [PowerDNS/pdns#7446] opened 2019-02-04 10:24 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description
SIDN Labs runs a so called DNS workbench.

[One of the zone files in that workbench contains a range of different RRtypes](https://workbench.sidnlabs.nl/zones/types.wb.sidnlabs.nl.txt). We managed to load it successfully in PowerDNS by slaving it with a sqlite3 back-end (and earlier attempt to do it with a bind backend resulted in https://github.com/PowerDNS/pdns/issues/7437)

The zone appears to work, but an AXFR fails:

dig AXFR types.wb.sidnlabs.nl @powerdns.sidnlabs.nl
;; Got bad packet: bad compression pointer

### Environment
 - Operating system:  Ubuntu 18.04
 - Software version:  pdns-server 4.1.1-1 package
 - Software source: Operating system repository

### Steps to reproduce

1.  dig AXFR types.wb.sidnlabs.nl @powerdns.sidnlabs.nl
2. dig AXFR types-signed.wb.sidnlabs.nl @powerdns.sidnlabs.nl

### Expected behaviour
Successful zone transfer

### Actual behaviour
; <<>> DiG 9.13.3 <<>> AXFR types.wb.sidnlabs.nl @powerdns.sidnlabs.nl
;; global options: +cmd
types.wb.sidnlabs.nl.	86400	IN	SOA	bind9.sidnlabs.nl. hostmaster.sidnlabs.nl. 1549195009 3600 600 1814400 3600
;; Got bad packet: bad compression pointer
3790 bytes

**Comment by omoerbeek** [comment] 2019-03-22 06:17
This seems to happen at least with MR and MG records. e.g.
```
dig MR mr.types.wb.sidnlabs.nl @powerdns.sidnlabs.nl
```
Is enough to trigger the issue.

How did you import the zone? Via a slave copy, db import using the sqlite tool, zone2sql or maybe another method?

**Comment by omoerbeek** [comment] 2019-03-22 09:53
I can reproduce using 4.1.x, but this is fixed in 4.2, which will be released soon.

Please confirm using https://downloads.powerdns.com/autobuilt_browser/#/auth/4.2.0-rc1

See https://github.com/PowerDNS/pdns/pull/6377 (although this PR does not seem to fix the MR case, it is fixed as well in my testing).

IMO this is not worth the trouble to backport since the record types are deprecated anyway.

**Comment by omoerbeek** [comment] 2019-04-02 11:58
@mdavids I'd appreciate some feedback. Thanks.

**Comment by mdavids** [comment] 2019-04-02 12:14
Unable to try this on the short term, sorry.

**Comment by mdavids** [comment] 2019-04-02 12:24
> How did you import the zone? Via a slave copy, db import using the sqlite tool, zone2sql or maybe another method?

We load it in PowerDNS by slaving it with a sqlite3 backend (an earlier attempt to do it with a bind backend resulted in #7437)

**Comment by omoerbeek** [comment] 2019-04-02 12:48
OK, I'm closing this and next will take a look at https://github.com/PowerDNS/pdns/issues/7437

**Closed by omoerbeek** 2019-04-02 12:48 UTC
