### ISSUE TITLE
pdnsutil check-zone yields inappropriate warning for pgsql backend

### ISSUE THREAD

**Issue by jsoref** [PowerDNS/pdns#5553] opened 2017-07-25 19:16 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description

check-zone complains about a missing period after the first dns server name in the SOA record.

### Environment

 - Operating system: Debian 9.0 Linux
 - Software version: 4.0.4
 - Software source: PowerDNS repository

### Steps to reproduce
1. install pdns4.0.4 / pdns-backend-pgsql 4.0.4-1pdns.jessie
2. create two zones:
```
 id  | domain_id |     name      | type |                               content                                |  ttl  | prio | change_date | ordername | auth | disabled
   1 |         1 | example.org   | SOA  | ns1.example.com root.example.com. 2017071905 1200 60 1209600 600     | 86400 |    0 |  1410536454 |           | t    | f
   2 |         2 | example.net   | SOA  | ns1.example.com. root.garnercorp.com. 2017072503 1200 60 1209600 600 | 86400 |    0 |             |           | t    | f
```

3. run `pdnsutil check-zone example.org` and `pdnsutil check-zone example.net`
4. Ask @Habbie for info about the warning

### Expected behaviour

Per @Habbie, the dot should not be included in the sql backend data.

### Actual behaviour

`[Warning] Parsed and original record content are not equal: example.org IN SOA 'ns1.example.com root.example.com. 2017072502 1200 60 1209600 600' (Content parsed as 'ns1.example.com. root.example.com. 2017072502 1200 60 1209600 600')`

**Comment by Habbie** [comment] 2020-01-24 10:35
I cannot reproduce this issue today. Closing.

**Closed by Habbie** 2020-01-24 10:35 UTC
Labels: auth, defect
