### ISSUE TITLE
recursor Failed to update

### ISSUE THREAD

**Issue by ebasse-prog** [PowerDNS/pdns#9637] opened 2020-10-22 10:29 UTC
- Program: Recursor
- Issue type: Bug report

**Short description**
Authorative (port 5300) + recursor (port 53) - not work.
In logs: 
`pdns_recursor[398295]: Failed to update . records, got an exception: Too much time waiting for .|NS, timeouts: 5, throttles: 0, queries: 6, 7510msec
pdns_recursor[398295]: Failed to update . records, RCODE=-1`

This same configuracion without recursor
Authorative (port 53) - work correctly.

### Environment

 - Operating system: Centos 8
 - Software version: PowerDNS Recursor 4.2.2 
 - Software source: the highest version in the official repo

### Steps to reproduce
 Add: forward-zones=example.com=127.0.0.1:5300

### Other information
pdns service and pdns-recursor service is on this same server. SELINUX is disabled. Firewall is not blocking.

**Comment by pieterlexis** [comment] 2020-10-22 10:31
This error in the trace is *always* the result of networking or firewall issues. Please investigate that. 

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2020-10-22 10:31 UTC
