### ISSUE TITLE
What does latency mean?

### ISSUE THREAD

**Issue by tangby** [PowerDNS/pdns#7803] opened 2019-05-10 05:59 UTC
How does it work out?

Numbers of requests or some span?

**Comment by chbruyand** [comment] 2019-05-10 07:21
I am closing this issue at it appears a support question and not a bug or issue. 
If you require further support, please ask for help via IRC or our mailing list - details are at https://www.powerdns.com/opensource.html

**Closed by chbruyand** 2019-05-10 07:21 UTC
