### ISSUE TITLE
Remotebackend call is not working

### ISSUE THREAD

**Issue by itstamil** [PowerDNS/pdns#8319] opened 2019-09-19 11:45 UTC
Hi, 
I was trying to post an data on every request to an backend JS code, but it won't work 

please help me sort this problem

> # MySQL Configuration file
> launch=gmysql,remote
> gmysql-host=localhost
> gmysql-dbname=powerdns
> gmysql-user=infyn
> gmysql-password=infyn@321
> 
> api=yes
> api-key=changeme
> remote-connection-string=http:url=http://localhost:8080
> cache-ttl=0
> negquery-cache-ttl=0
> query-cache-ttl=0

Regards,
Tamilvalavan

**Comment by rgacogne** [comment] 2019-09-19 11:47
I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on IRC.

**Closed by rgacogne** 2019-09-19 11:47 UTC

**Comment by itstamil** [comment] 2019-09-19 11:48
Ok
