### ISSUE TITLE
Bad json for binary log messages in statistics API response

### ISSUE THREAD

**Issue by KrisShannon** [PowerDNS/pdns#9349] opened 2020-07-22 03:14 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description
If there are binary log messages (e.g. from attempted hacking of the webserver) then the response from the statistics API endpoint can return invalid json.

### Environment

 - Operating system: Debian GNU/Linux 10 (buster)
 - Software version: 4.3.0-1pdns.buster
 - Software source: PowerDNS repository buster-auth-43

### Steps to reproduce
I'm not sure exactly how to generate a bad log message but here's an example of one as sent in the API response where the illegal UTF-8 bytes have been replaced by <0xHH>

```
{
      "value" : "1",
      "name" : "[webserver] 8ef848a1-570b-4b1f-aa25-eb7f59f4c63f 192.241.237.178:52962 \"\u0016\u0003\u0001\u0000<0x8b>\u0001\u0000\u0000<0x87>\u0003\u0003<0xe2>Q<0x8c><0x94>[<0xf9><0xa8>K?^<0xe8>\u0010Y<0xc7><0xbe>S\u0016RK<0xc5>D^\u0004_<0x9f>\u00056\u001b<0xb1><0xe7><0xa3><0x9f>\u0000\u0000\u001a<0xc0>/<0xc0>+<0xc0>\u0011<0xc0>\u0007<0xc0>\u0013<0xc0>  HTTP/0.9\" 400 143"
}
```

### Expected behaviour
The API response should be valid JSON (i.e. valid UTF-8)

This would probably involve some kind of escaping of binary blobs.

### Actual behaviour
The code calling the statistics API json (specifically [PowerDNS-Admin](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/94da9198c0aae382854a96d8537aec78fe94ee7b/powerdnsadmin/models/server.py#L51-L57)) dies while trying to decode the response.

**Comment by Habbie** [comment] 2020-07-22 21:09
> The code calling the statistics API json (specifically [PowerDNS-Admin](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/94da9198c0aae382854a96d8537aec78fe94ee7b/powerdnsadmin/models/server.py#L51-L57)) dies while trying to decode the response.

While I agree this looks like a bug on our side, if PowerDNS-Admin dies on it in a bad way, that should also be fixed in that project.

**Comment by KrisShannon** [comment] 2020-07-22 22:08
Absolutely.  We intend to report this in PowerDNS-Admin as well.

We are just playing around with possible fixes to suggest.

**Comment by omoerbeek** [comment] 2022-11-30 11:54
This issue happens with the code in auth that lists log lines in the REST statistics API. It is easy to reproduce.
I have attached an example file that `iconv -f UTF-8 /tmp/x.txt -o /dev/null` does not like:
```
iconv: illegal input sequence at position 8231
```
[x.txt](https://github.com/PowerDNS/pdns/files/10122839/x.txt)

(`jq` tends to be less picky).

The issue seems to originate in this `json11.cpp` code:
```
static void dump(const string &value, string &out) {
    out += '"';
    for (size_t i = 0; i < value.length(); i++) {
        const char ch = value[i];
        if (ch == '\\') {
            out += "\\\\";
        } else if (ch == '"') {
            out += "\\\"";
        } else if (ch == '\b') {
            out += "\\b";
        } else if (ch == '\f') {
            out += "\\f";
        } else if (ch == '\n') {
            out += "\\n";
        } else if (ch == '\r') {
            out += "\\r";
        } else if (ch == '\t') {
            out += "\\t";
        } else if (static_cast<uint8_t>(ch) <= 0x1f) {
            char buf[8];
            snprintf(buf, sizeof buf, "\\u%04x", ch);
            out += buf;
        } else if (static_cast<uint8_t>(ch) == 0xe2 && static_cast<uint8_t>(value[i+1]) == 0x80
                   && static_cast<uint8_t>(value[i+2]) == 0xa8) {
            out += "\\u2028";
            i += 2;
        } else if (static_cast<uint8_t>(ch) == 0xe2 && static_cast<uint8_t>(value[i+1]) == 0x80
                   && static_cast<uint8_t>(value[i+2]) == 0xa9) {
            out += "\\u2029";
            i += 2;
        } else {
            out += ch;
        }
    }
    out += '"';
}
```

I can see several problems here.

1. If the input string contains binary data that happen to be invalid UTF8 it is passed through in many cases, as those bytes will hit the last else branch. 
2. I'm not completely sure why the checks for e280a8 and e280a9 are done (it somehow assumes the input is already UTF8 encoded?) that generate UTF8 line separator/paragraph separator. But I know for sure these are potential out-of-bound accesses.

The upstream for this code is https://github.com/dropbox/json11/blob/master/json11.cpp. The repo is archived and no longer maintained.

We can either fix this locally or look for a better json encoding lib. A simple local fix would look like (untested, not even compiled!):
```
--- a/ext/json11/json11.cpp
+++ b/ext/json11/json11.cpp
@@ -93,18 +93,10 @@ static void dump(const string &value, string &out) {
             out += "\\r";
         } else if (ch == '\t') {
             out += "\\t";
-        } else if (static_cast<uint8_t>(ch) <= 0x1f) {
+        } else if (static_cast<uint8_t>(ch) <= 0x1f || static_cast<uint8_t>(ch) >= 0x7f ) {
             char buf[8];
             snprintf(buf, sizeof buf, "\\u%04x", ch);
             out += buf;
-        } else if (static_cast<uint8_t>(ch) == 0xe2 && static_cast<uint8_t>(value[i+1]) == 0x80
-                   && static_cast<uint8_t>(value[i+2]) == 0xa8) {
-            out += "\\u2028";
-            i += 2;
-        } else if (static_cast<uint8_t>(ch) == 0xe2 && static_cast<uint8_t>(value[i+1]) == 0x80
-                   && static_cast<uint8_t>(value[i+2]) == 0xa9) {
-            out += "\\u2029";
-            i += 2;
         } else {
             out += ch;
         }
```
@Habbie @rgacogne Opinions?

**Comment by rgacogne** [comment] 2022-11-30 13:41
I think it would make sense to add a local fix first, as we are likely going to have to support JSON11 for stable branches anyway, and then consider switching to a JSON library which is actually maintained.

**Closed** 2022-12-19 15:06 UTC
Labels: auth, defect
