### ISSUE TITLE
Different handling of wildcard in pdns-server 4.4 with pgsql backend on Ubuntu 20.04 and Rocky Linux 8

### ISSUE THREAD

**Issue by randrew943** [PowerDNS/pdns#11571] opened 2022-04-22 10:39 UTC
Dear Sirs,

2 different servers are running on Ubuntu 20.04 and Rocky Linux 8 with the latest updates.
PowerDNS authoritative server **4.4.3** on both systems was installed from repo.powerdns.com as described in http://repo.powerdns.com.
PowerDNS configs on both systems are the same.
Backends are pgsql.
DNSSEC is not used.

Both servers are running the same DB with the following records:
```
=> SELECT * FROM records WHERE type = 'A' AND name LIKE '%example.com%' LIMIT 10;
  id   | domain_id |           name           | type |    content     |  ttl  | prio | disabled | ordername  | auth | change_date
-------+-----------+--------------------------+------+----------------+-------+------+----------+------------+------+-------------
   906 |        21 | *.example.com          | A    | 192.168.1.111  | 21600 |    0 | f        | *          | t    |  1650610490
   911 |        21 | example.com            | A    | 192.168.1.111  | 21600 |    0 | f        |            | t    |  1650610490
  9230 |        21 | cn.example.com         | A    | 192.168.1.111  | 21600 |    0 | f        | cn         | t    |  1650610490
  5691 |        21 | redis.example.com | A    | 192.168.1.44   | 21600 |    0 | f        | poweradmin | t    |  1650610490
 11335 |        21 | *.cn.example.com       | A    | 192.168.1.111  | 21600 |    0 | f        |            | t    |  1650610490

```

**The expected behaviour** for both servers is to return 192.168.1.111 on every query for non-existent A-records from .example.com.
**In reality** it works as expected with PowerDNS on Rocky Linux 8, but with PowerDNS on Ubuntu 20.04 DNS query returns NXDOMAIN.

Rocky Linux 8
```
$ dig nonexistent.example.com @ns1.pdns.local

; <<>> DiG 9.16.1-Ubuntu <<>> nonexistent.example.com @ns1.pdns.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40459
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;nonexistent.example.com.	IN	A

;; ANSWER SECTION:
nonexistent.example.com. 21600 IN	A	192.168.1.111

;; Query time: 67 msec
;; SERVER: 10.10.10.10#53(10.10.10.10)
;; WHEN: пт кві 22 13:18:01 EEST 2022
;; MSG SIZE  rcvd: 70

```

Ubuntu 20.04
```
$ dig nonexistent.example.com @ns2.pdns.local

; <<>> DiG 9.16.1-Ubuntu <<>> nonexistent.example.com @ns2.pdns.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 31370
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;nonexistent.example.com.	IN	A

;; AUTHORITY SECTION:
example.com.		3600	IN	SOA	ns1.pdns.local. dnsmaster.pdns.local. 2022042203 28800 7200 1209600 3600

;; Query time: 43 msec
;; SERVER: 10.10.10.20#53(10.10.10.20)
;; WHEN: пт кві 22 13:18:06 EEST 2022
;; MSG SIZE  rcvd: 124


```

**Comment by Habbie** [comment] 2022-04-22 10:52
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question (a misconfiguration perhaps, but most likely not a bug). Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Closed by Habbie** 2022-04-22 10:52 UTC

**Comment by randrew943** [comment] 2022-04-22 13:48
You were absolutely right, the source of the problem was Postgres with a corrupted index for the "records" table. Sorry for disturbing.

**Comment by Habbie** [comment] 2022-04-22 14:23
I can see how you weren't expecting Postgres to behave that badly. Thank you for reporting back!
