### ISSUE TITLE
 SpoofCNAMEAction not work?

### ISSUE THREAD

**Issue by mengxifl** [PowerDNS/pdns#7780] opened 2019-05-05 10:22 UTC
I want to do this 

my Authoritative domain is example1.com.

www.example1.com -> www.example2.com

My dns  structure is:

     Recursor --->  dnsdist ---->  Authoritative Server 

myclient dns point to my Recursor dns.

I think add a CNAME record will succeed . but tures is not.

so i add a 

`addAction(makeRule("www.example1.com."), SpoofCNAMEAction(" www.example2.com"))`

but myclient can not access www.example1.com also. 

i test makeRule() it work so i think SpoofCNAMEAction not work . 

Actually I  prefer to do this on a Authoritative  server. so Is there any way to  implement ？

**Comment by pieterlexis** [comment] 2019-05-05 10:56
I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2019-05-05 10:56 UTC
