### ISSUE TITLE
Issue with older bind CAA records (TYPE257)

### ISSUE THREAD

**Issue by mzealey** [PowerDNS/pdns#8036] opened 2019-07-08 08:52 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description

Prior to CAA record support being properly added to bind in 9.9.6, it was possible to specify CAA records like:

```
example.com.        TYPE257 \# 18 00056973737565656E74727573742E6E6574
```

Unfortunately pdns parser only accepts the standard `0 issue "entrust.net"` format and bombs out ("expected digits at position 0 in '\# 18...") when you try doing the above rr specification. Is it possible to add in a general fallback-case to the parser where records have been specified in this raw format?

**Comment by Habbie** [comment] 2019-07-08 08:57
Duplicate of #804

**Closed by Habbie** 2019-07-08 08:57 UTC
