### ISSUE TITLE
Supermasters How to configure

### ISSUE THREAD

**Issue by m1911** [PowerDNS/pdns#6987] opened 2018-09-26 14:37 UTC
Master Server configuration information
```allow-axfr-ips=10.1.1.10
setgid=pdns
setuid=pdns
daemon=yes
master=yes
local-port=53
launch=gmysql
gmysql-host=127.0.0.1
gmysql-user=pdns
gmysql-password=pdns123
gmysql-dbname=pdns
default-soa-name=ns1.123.com
api=yes
api-key=pdnskey
gmysql-dnssec=yes
any-to-tcp=yes
expand-alias=yes
logging-facility=0
resolver=8.8.4.4:53
version-string=bind-9
max-queue-length=5000
max-cache-entries=1000000
max-tcp-connections=20
edns-subnet-processing=yes
udp-truncation-threshold=1680
supermaster=yes
```
Slave Server configuration information
```
setgid=pdns
setuid=pdns
daemon=yes
slave=yes
local-port=53
launch=gmysql
gmysql-host=127.0.0.1
gmysql-user=pdns
gmysql-password=pdns123
gmysql-dbname=pdns
gmysql-dnssec=yes
any-to-tcp=yes
expand-alias=yes
logging-facility=0
resolver=8.8.4.4:53
version-string=bind-9
max-queue-length=5000
max-cache-entries=1000000
max-tcp-connections=20
edns-subnet-processing=yes
udp-truncation-threshold=1680
```
Slave Server mysql info
```
MariaDB [pdns]> select * from supermasters;
+------------+-------------+----------+
| ip         | nameserver  | account  |
+------------+-------------+----------+
| 10.1.1.235 | ns2.123.com | internal |
+------------+-------------+----------+
```
Such configuration domain information cannot be transferred to the slave server.

**Comment by pieterlexis** [comment] 2018-09-26 14:41
I am closing this issue at it appears a support question and not a bug or issue.

Please the [Superslave documentation](https://doc.powerdns.com/authoritative/modes-of-operation.html#supermaster-automatic-provisioning-of-slaves) If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2018-09-26 14:41 UTC
