### ISSUE TITLE
Missing LUA backend.

### ISSUE THREAD

**Issue by quartzeye** [PowerDNS/pdns#9072] opened 2020-04-28 17:17 UTC
Just tried install a new powerdns server with authoritative and recusor server frontended with dnsdist on Ubintu 18.04.  I did this previous server a few weeks back and all was good.

However now when I install everything, the lua backend seems to be missing and none of the lua scripts or directories for powerdns seem to be installed.  Did someone miss something?  Did I miss something? I am using the following repo to install from:

 "deb [arch=amd64] http://repo.powerdns.com/ubuntu bionic-auth-41 main"

and the following directory was not installed
/usr/share/pdns-recursor/lua-config

nor was the 
/etc/powerdns/recursor.lua

DNSDist is chocking because of lua fatal errors probably related to the missing backend.

**Comment by pieterlexis** [comment] 2020-04-28 18:43
First of, the auth repo does not ship the recursor. Second, the Lua errors in dnsdist is more likely a configuration error.

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users).

**Closed by pieterlexis** 2020-04-28 18:43 UTC
