### ISSUE TITLE
MX Records won't resolve.

### ISSUE THREAD

**Issue by dwalsh9** [PowerDNS/pdns#5841] opened 2017-10-25 04:49 UTC
- Program: Authoritative

### Short description
Upon updating PDNS to version 4.1.0-0.1.rc1.1pdns.el6, MX records for a domain name SERVFAILS with the following error:

Exception building answer packet for domain.com/MX (Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content '0 ') sending out servfail. Check-zone shows no errors, and the same entries work perfect on the version 3 branch.

### Environment
 - Operating system: CentOS 6
 - Software version: 4.1.0-0.1.rc1.1pdns.el6
 - Software source: PDNS repo

### Steps to reproduce

1. Upgrade from version 3 -> 4. DNS stops resolving for that MX record only and throws the above error.

### Expected behaviour

It to resolve. 

### Actual behaviour
Throws error: 

Exception building answer packet for domain.com/MX (Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content '0 ')

### Other information

Here is the zone file in question:

[root@ns1 pdns]# pdnsutil list-zone domain.com
$ORIGIN .
em1.domain.com	14000	IN	CNAME	u2268330.wl081.sendgrid.net.
email.domain.com	14400	IN	CNAME	sendgrid.net.
lists.domain.com	14000	IN	MX	1 mx1.simplelists.com.
lists.domain.com	14000	IN	MX	5 mx2.simplelists.com.
lists.domain.com	14000	IN	TXT	v=spf1 include:simplelists.com -all
s1._domainkey.domain.com	14000	IN	CNAME	s1.domainkey.u2268330.wl081.sendgrid.net.
s2._domainkey.domain.com	14000	IN	CNAME	s2.domainkey.u2268330.wl081.sendgrid.net.
selector1._domainkey.lists.domain.com	14000	IN	TXT	k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDCdnStwjJpJVTuAILoc4EJTjp3MAeVyXs6GGr7SeET2h0RNfBBSrj9O8NS1y4iAGLs0e8FPa3XsWAtajbBHs7SGb++MelY5f9hiYLI2Rez9+U3eDxNIfncuKlMtmvu81sJ/UDB36cTI9EHAds1fMAp2y0/9N14th6YoPLfyUzIlwIDAQAB
smtpapi._domainkey.email.domain.com	14400	IN	CNAME	dkim.sendgrid.net.
smtpapi._domainkey.domain.com	14400	IN	CNAME	dkim.sendgrid.net.
www.domain.com	14400	IN	CNAME	youthaction.nationbuilder.com.
domain.com	14400	IN	A	174.129.25.170
domain.com	14400	IN	MX	1 ASPMX.L.GOOGLE.COM.
domain.com	14400	IN	MX	5 ALT1.ASPMX.L.GOOGLE.COM.
domain.com	14400	IN	MX	5 ALT2.ASPMX.L.GOOGLE.COM.
domain.com	14400	IN	MX	5 ALT3.ASPMX.L.GOOGLE.COM.
domain.com	14400	IN	MX	5 ALT4.ASPMX.L.GOOGLE.COM.
domain.com	86400	IN	NS	ns1.dns-service.net.au.
domain.com	86400	IN	NS	ns2.dns-service.net.au.
domain.com	86400	IN	SOA	ns1.dns-service.net.au servers.hosting-service.net.au 2016110503 7200 7200 1209600 86400
domain.com	14400	IN	TXT	v=spf1 +a +mx +ip4:202.40.166.219 +include:_spf.google.com +include:sendgrid.net ~all
domain.com	14400	IN	TXT	google-site-verification=XVT9Z4AZGAYVAzNohG_WBZZIbQgwvUMZBcPl_ayE0A8
domain.com	14400	IN	TXT	MS=ms21023894
domain.com	14400	IN	TXT	ms21023894.msv1.invalid.outlook.com
domain.com	14400	IN	TXT	MS=ms97293942

Any ideas as to what the cause is would be helpful, it works perfectly on an older branch. We use MySQL as the backend.

**Comment by ahupowerdns** [comment] 2017-10-25 06:14
Please do a mysql dump (or equivalent) of the domain in question & attach to ticket, Or try select * from records where content like '0 %', might show you something.

**Comment by dwalsh9** [comment] 2017-10-25 06:36
SQL query showed no results. 

Uploaded .SQL
[debug.sql.zip](https://github.com/PowerDNS/pdns/files/1413491/debug.sql.zip)

**Comment by ahupowerdns** [comment] 2017-10-25 07:06
Loaded it up here, it works fine. This combined with check-zone not reporting any errors leads me to think you may not be querying the database you think you are querying, or perhaps not the domain you think you are querying. We can't do anything else for you here, consider dropping by our IRC channel, but I'm closing this since it does not look like a bug. https://www.powerdns.com/opensource.html

**Closed by ahupowerdns** 2017-10-25 07:06 UTC

**Comment by dwalsh9** [comment] 2017-10-25 07:09
Thats why it works fine under 3.X and not 4.x..... 

It's definitely the right db, I only have one. Moment it's rolled back, no error.

**Comment by ahupowerdns** [comment] 2017-10-25 07:13
dwalsh9, I go through the trouble of reproducing your issue and I don't see it. Please do not tell me "hey it works in 3 so it must be a bug". If you want any further help, please upload a mysql dump that reproduces the problem for you in isolation. https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/
