### ISSUE TITLE
recursor: forward-zones-recurse parsing issue with 4.1

### ISSUE THREAD

**Issue by rmoriz** [PowerDNS/pdns#6893] opened 2018-08-28 19:01 UTC
Hi,

pdns-recursor with the following config

```
#################################
# forward-zones-recurse	Zones for which we forward queries with recursion bit, comma separated domain=ip pairs
#
forward-zones-recurse=.=127.0.2.1,127.0.2.1
``` 
worked in Ubuntu 16.04 (4.0.0-alpha2), broken in 18.04 (4.1.1) with the error message:

`Exception: Error parsing '127.0.2.1', missing =`

the idea behind this config (duplicate IP address) was to improve retry behaviour.

Example Repo:
https://github.com/rmoriz/pdns-recursor-issue

Steps:
```shell
docker build -f Dockerfile.1604 -t old  .  
docker run --rm -it old   # pdns recursor starts successfully

docker build -f Dockerfile.1804 -t new  .  
docker run --rm -it new   # pdns recursor crashes on start
```

**Comment by Habbie** [comment] 2018-08-28 19:30
Closing this as it's not a bug. Thank you for the research @zeha!

**Closed by Habbie** 2018-08-28 19:30 UTC
Labels: auth

**Comment by rmoriz** [comment] 2018-09-12 22:05
Seems like a couple of tutorials on the web are wrong about this as the manual does not specify this. Can you add a note/example to it? Thanks!

**Comment by zeha** [comment] 2018-09-12 22:10
https://docs.powerdns.com/recursor/settings.html#forward-zones has this documented. I guess the text could describe this better... please put changes that you'd like to see into a PR.
