### ISSUE TITLE
Where is the log? How to build a master-slave mode?

### ISSUE THREAD

**Issue by jiangby123** [PowerDNS/pdns#7512] opened 2019-02-22 07:57 UTC
I installed pdns-4.0 with yum. After running it, what is his running log? And how is his master-slave mode built?

**Comment by pieterlexis** [comment] 2019-02-22 07:58
`journalctl -u pdns.service` if you are on a system with systemd, otherwise anywhere where syslog logs (`/var/log/messages` probably)

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2019-02-22 07:58 UTC
