### ISSUE TITLE
pdns list-zone <zone> returns syntax that isn't compatible with pdns load-zone <zone>

### ISSUE THREAD

**Issue by KoffieNu** [PowerDNS/pdns#8550] opened 2019-11-18 16:11 UTC
- Program: Authoritative 
 - Issue type: Bug report

### Short description
When exporting a zone with pdnsutil list-zone, editing and importing it again with pdnsutil load-zone the fields get the zone added extra.

### Environment

 - Operating system: CentOS 7.7
 - Software version: pdns-4.1.11-1.el7.x86_64 (+ mysql backend)
 - Software source: EPEL

### Steps to reproduce

1. pdns list-zone 'zone' > zone-file
2. edit zone-file
3. pdns load-zone 'zone' zone-file

### Expected behaviour
The list-zone output should be correct to be used by load-zone.
The dns mapping loaded should be the same as the previous one, with the extra updates.

### Actual behaviour
The output of list-zones delivered all name fields without trailing dot, load-zone requires a trailing dot and will append 'zone' when it doesn't find any, rightfully so.

### Other information
Issue applies only to name field, not value. (that is exported by list-zone with trailing dot)

**Comment by Habbie** [comment] 2020-11-12 10:35
I cannot reproduce this issue in 4.3.0, so I'm closing this ticket.

**Closed by Habbie** 2020-11-12 10:35 UTC
Labels: auth, defect
