### ISSUE TITLE
rfc2136 update writing wrong data to wrong zone

### ISSUE THREAD

**Issue by zundg** [PowerDNS/pdns#1840] opened 2014-10-24 10:07 UTC
I'm running powerdns from pdns-static_3.4.0-1_amd64.deb, mysql backend on ubuntu 12.4.5 LTS

I used to host foo.de on ns1.foo.de and ns2.foo.de, so created a new domain/zone test.foo.de within powerdns and added two records to the foo.de zone: "test.foo.de IN NS ns1.foo.de" (for ns2 alike).

updates are generally forbidden, but via domainmetadata allowed for test.foo.de with TSIG only.

Testing with nsupdate i used "update add test.foo.de 300 A 1.2.3.4" which works fine. Running "update delete test.foo.de ..." does delete the A record defined before, but also _duplicates_ all "test.foo.de IN NS" records in the parent zone, which is just wrong in multiple ways. Why at all is it happending, and why is it happeing in a zone not allowed for updates using TSIG/rfc2136 stuff? I validated my config by trying to modify foo.de directly, but as expected updates were refused.

My fix, as not using DNSSEC, is to not have the "IN NS" records at all, which seems to work fine, 0*2 is still 0, so my tables are not getting spammed.

**Comment by cyclops1982** [comment] 2016-03-25 16:53
@zundg Can you provide clearer reproduction steps?
Would be great to see the zone foo.de and test.foo.de before you do the update and the exact nsupdate commands that you execute.

At the moment, i'm unable to reproduce this issue.

**Comment by zundg** [comment] 2016-08-25 21:18
So I have a domain foo.de and I point the NS record pdns.foo.de to the same server. I also have a pdns.foo.de domain on the server which I plan to update using rfc2136.

```
mysql> select * from domains where name like '%foo%';
+----+-----------------+--------+------------+--------+-----------------+---------+--------+
| id | name            | master | last_check | type   | notified_serial | account | dyndns |
+----+-----------------+--------+------------+--------+-----------------+---------+--------+
|  1 | foo.de          | NULL   |       NULL | MASTER |      2014137447 | NULL    |      1 |
| 48 | pdns.foo.de     | NULL   |       NULL | MASTER |      2016082504 | EXTERN  |      0 |
+----+-----------------+--------+------------+--------+-----------------+---------+--------+
7 rows in set (0.00 sec)
```

```
mysql> select * from records where name like '%pdns.foo%';
+--------+-----------+-------------+------+-------------------------------------------------------------------------+------+------+-------------+-----------+------+--------+-------+----------+
| id     | domain_id | name        | type | content                                                                 | ttl  | prio | change_date | ordername | auth | webkey | email | disabled |
+--------+-----------+-------------+------+-------------------------------------------------------------------------+------+------+-------------+-----------+------+--------+-------+----------+
| 201259 |        48 | pdns.foo.de | NS   | ns01.foo.de                                                             | 3600 |    0 |        NULL | NULL      |    1 | NULL   | NULL  |        0 |
| 201260 |        48 | pdns.foo.de | NS   | ns02.foo.de                                                             | 3600 |    0 |        NULL | NULL      |    1 | NULL   | NULL  |        0 |
| 201262 |        48 | pdns.foo.de | SOA  | ns1.pdns.foo.de. s-dns.bar.info. 2016082504 12000 1800 604800 86400 |   60 |    0 |        NULL | NULL      |    1 | NULL   | NULL  |        0 |
| 201263 |         1 | pdns.foo.de | NS   | ns01.foo.de                                                             | 3600 |    0 |  1472159391 | NULL      | NULL | NULL   | NULL  |        0 |
+--------+-----------+-------------+------+-------------------------------------------------------------------------+------+------+-------------+-----------+------+--------+-------+----------+
4 rows in set (0.00 sec)
```

I add something:
```
> update add pdns.foo.de 60 A 1.2.3.4
> send
```


```
mysql> select * from records where name like '%pdns.foo%';
+--------+-----------+-------------+------+-------------------------------------------------------------------------+------+------+-------------+-----------+------+--------+-------+----------+
| id     | domain_id | name        | type | content                                                                 | ttl  | prio | change_date | ordername | auth | webkey | email | disabled |
+--------+-----------+-------------+------+-------------------------------------------------------------------------+------+------+-------------+-----------+------+--------+-------+----------+
| 201259 |        48 | pdns.foo.de | NS   | ns01.foo.de                                                             | 3600 |    0 |        NULL | NULL      |    1 | NULL   | NULL  |        0 |
| 201260 |        48 | pdns.foo.de | NS   | ns02.foo.de                                                             | 3600 |    0 |        NULL | NULL      |    1 | NULL   | NULL  |        0 |
| 201263 |         1 | pdns.foo.de | NS   | ns01.foo.de                                                             | 3600 |    0 |  1472159391 | NULL      | NULL | NULL   | NULL  |        0 |
| 201264 |        48 | pdns.foo.de | A    | 1.2.3.4                                                                 |   60 |    0 |        NULL | NULL      |    1 | NULL   | NULL  |        0 |
| 201265 |        48 | pdns.foo.de | SOA  | ns1.pdns.foo.de. s-dns.bar.info. 2016082505 12000 1800 604800 86400 |   60 |    0 |        NULL | NULL      |    1 | NULL   | NULL  |        0 |
+--------+-----------+-------------+------+-------------------------------------------------------------------------+------+------+-------------+-----------+------+--------+-------+----------+
5 rows in set (0.01 sec)
```

and delte.. and add... and delete...
```
> update delete pdns.foo.de
> send
> update add pdns.foo.de 60 A 1.2.3.4
> send
> update delete pdns.foo.de
> send
> update add pdns.foo.de 60 A 1.2.3.4
> send
```

```
mysql> select * from records where name like '%pdns.foo%';
+--------+-----------+-------------+------+-------------------------------------------------------------------------+------+------+-------------+-----------+------+--------+-------+----------+
| id     | domain_id | name        | type | content                                                                 | ttl  | prio | change_date | ordername | auth | webkey | email | disabled |
+--------+-----------+-------------+------+-------------------------------------------------------------------------+------+------+-------------+-----------+------+--------+-------+----------+
| 201263 |         1 | pdns.foo.de | NS   | ns01.foo.de                                                             | 3600 |    0 |  1472159391 | NULL      | NULL | NULL   | NULL  |        0 |
| 201268 |         1 | pdns.foo.de | NS   | ns01.foo.de                                                             | 3600 |    0 |        NULL | NULL      |    1 | NULL   | NULL  |        0 |
| 201273 |         1 | pdns.foo.de | NS   | ns01.foo.de                                                             | 3600 |    0 |        NULL | NULL      |    1 | NULL   | NULL  |        0 |
| 201274 |        48 | pdns.foo.de | NS   | ns01.foo.de                                                             | 3600 |    0 |        NULL | NULL      |    1 | NULL   | NULL  |        0 |
| 201275 |        48 | pdns.foo.de | NS   | ns02.foo.de                                                             | 3600 |    0 |        NULL | NULL      |    1 | NULL   | NULL  |        0 |
| 201276 |         1 | pdns.foo.de | NS   | ns01.foo.de                                                             | 3600 |    0 |        NULL | NULL      |    1 | NULL   | NULL  |        0 |
| 201279 |        48 | pdns.foo.de | A    | 1.2.3.4                                                                 |   60 |    0 |        NULL | NULL      |    1 | NULL   | NULL  |        0 |
| 201280 |        48 | pdns.foo.de | SOA  | ns1.pdns.foo.de. s-dns.bar.info. 2016082509 12000 1800 604800 86400 |   60 |    0 |        NULL | NULL      |    1 | NULL   | NULL  |        0 |
+--------+-----------+-------------+------+-------------------------------------------------------------------------+------+------+-------------+-----------+------+--------+-------+----------+
8 rows in set (0.00 sec)

```
And end up with a bunch of NS records in domain_id 1. Luckily I don't actually need these records as the server I'm delegating to, is the same that also osts foo.de. So I delete all of the NS records in domain_id 1 and nothing gets duplicated....

**Comment by Habbie** [comment] 2018-11-29 12:52
Going to close this as we also have a test for it. Please comment if you disagree.

**Closed by Habbie** 2018-11-29 12:52 UTC
Labels: auth, defect, response needed, rfc2136
