### ISSUE TITLE
How to get certain record id?

### ISSUE THREAD

**Issue by faradoxuz** [PowerDNS/pdns#9291] opened 2020-07-01 16:28 UTC
- Program: Authoritative
 - Issue type: Feature request

### Description

How can I get certain record id of zone
for example NS record id

**Comment by pieterlexis** [comment] 2020-07-01 16:38
I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2020-07-01 16:38 UTC
