### ISSUE TITLE
Unable to delete a TSIG key

### ISSUE THREAD

**Issue by stevedsp1** [PowerDNS/pdns#12487] opened 2023-01-30 12:01 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description
Unable to delete a TSIG key with API or pdnsutil command.

### Environment

 - Operating system: Debian
 - Software version: 4.7.3
 - Software source: PowerDNS repository

### Steps to reproduce
1. Install a tsig key with the 'pdnsutil generate-tsig-key tsigkey1 hmac-sha256' command or with the API (POST /servers/localhost/tsigkeys)  
2. Try to delete it with the 'pdnsutil delete-tsig-key tsigkey1' command or with the API (DELETE /servers/{server_id}/tsigkeys/tsigkey1)

### Expected behaviour
The key must be deleted.

### Actual behaviour
- pdnsutil command returns 'Deleted TSIG key 'tsigkey1'' but key is not deleted. 
- API returns error : "TSIG key with name 'tsigkey1" not found".

### Other information
I have the issue with lmdb backend. 
This seems to be a regression following a recent update, I don't have a workaround.

**Comment by rgacogne** [comment] 2023-01-30 12:06
It looks like a duplicate of https://github.com/PowerDNS/pdns/issues/12394

**Closed as completed** 2023-01-30 12:10 UTC
Labels: auth, defect
