### ISSUE TITLE
Auth API emits mysterious notified_serial

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns#2174] opened 2015-02-03 16:30 UTC
I'm seeing a mysterious `notified_serial` emitted by the API on `PowerDNS Authoritative Server 3.4.1 (jenkins@autotest.powerdns.com built 20141030110054 root@autotest.powerdns.com)` when I enumerate zones:

```json
[
    {
        "dnssec": false,
        "id": "jp.aa.",
        "kind": "Native",
        "last_check": 0,
        "masters": [],
        "name": "jp.aa",
        "notified_serial": 17625472,
        "serial": 2015013011,
        "url": "/servers/localhost/zones/jp.aa."
    }
]
```

The `domains` table contains

```
+----+-------+--------+------------+--------+-----------------+---------+
| id | name  | master | last_check | type   | notified_serial | account |
+----+-------+--------+------------+--------+-----------------+---------+
|  1 | jp.aa | NULL   |       NULL | NATIVE |            NULL | NULL    |
+----+-------+--------+------------+--------+-----------------+---------+
```

If I explicitly `UPDATE notified_serial` to, say, `17`, that value is returned via the API, which is something I expect:

```json
[
    {
        "dnssec": false,
        "id": "jp.aa.",
        "kind": "Native",
        "last_check": 0,
        "masters": [],
        "name": "jp.aa",
        "notified_serial": 17,
        "serial": 2015013013,
        "url": "/servers/localhost/zones/jp.aa."
    }
]
```

Why is the `NULL` in the `domains` table translated to `17625472` (which doesn't correspond to a timestamp here -- `Thu, 23 Jul 1970 23:57:52 GMT`) ? 

If I then add a new zone:

```
insert into domains (name, type) values ('jp2.aa', 'NATIVE');
insert into records (domain_id, name, type, content, ttl) values (2, 'jp.aa', 'SOA', 'ns1.jp.aa', 3600);
insert into records (domain_id, name, type, content, ttl) values (2, 'jp.aa', 'NS', 'ns1.jp.aa', 3600);
```

and enumerate the zones via the API again, I get rubbish (i.e. the `17` I updated earlier for a different zone); this is *not* something I expect.

```json
[
    {
        "dnssec": false,
        "id": "jp.aa.",
        "kind": "Native",
        "last_check": 0,
        "masters": [],
        "name": "jp.aa",
        "notified_serial": 17,
        "serial": 2015013013,
        "url": "/servers/localhost/zones/jp.aa."
    },
    {
        "dnssec": false,
        "id": "jp2.aa.",
        "kind": "Native",
        "last_check": 0,
        "masters": [],
        "name": "jp2.aa",
        "notified_serial": 17,
        "serial": 0,
        "url": "/servers/localhost/zones/jp2.aa."
    }
]
```

```
 SELECT * FROM domains;
+----+--------+--------+------------+--------+-----------------+---------+
| id | name   | master | last_check | type   | notified_serial | account |
+----+--------+--------+------------+--------+-----------------+---------+
|  1 | jp.aa  | NULL   |       NULL | NATIVE |              17 | NULL    |
|  2 | jp2.aa | NULL   |       NULL | NATIVE |            NULL | NULL    |
+----+--------+--------+------------+--------+-----------------+---------+
```

**Comment by Habbie** [comment] 2015-02-03 21:24
I bet this is related to #1303

**Comment by Habbie** [comment] 2015-02-03 21:24
in fact I think this is a duplicate of #1303

**Comment by zeha** [comment] 2015-02-03 21:34
Indeed! Interesting that in #1303 it happened with gsqlite3. I bet I was using Linux for the test then.

**Closed** 2015-02-09 12:22 UTC
