### ISSUE TITLE
TCP Connection Thread died

### ISSUE THREAD

**Issue by tsumi** [PowerDNS/pdns#7995] opened 2019-06-27 08:26 UTC
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

On our autoritative cluster this error appear randomly on our logs:
`TCP Connection Thread died because of network error: Timeout reading data`
At the same time we detect some empty answers/timeout from our monitoring system (Pingdom).
What is the meaning of this error? We was not able to find any more info on Powerdns logs

### Environment

 - Operating system: Centos 7
 - Software version: 4.1.8 and 4.1.10
 - Software source: PowerDNS repository

### Steps to reproduce

1. Nothing, happen randomly by itself

**Comment by rgacogne** [comment] 2019-07-01 07:30
The exact message means that the authoritative server closed the connection because it did not receive  the data sent by the client on the network socket fast enough, be it the query size or the actual content of the query.

I am closing this issue at it appears a support question and not a bug or issue.
If you require further support, please ask for help via IRC or our mailing list - details are at https://www.powerdns.com/opensource.html

**Closed** 2019-07-01 07:33 UTC
Labels: auth

**Comment by fansari** [comment] 2023-04-04 14:25
I have the same issue with CentOS 9 and PowerDNS 4.7.3.

TCP Connection Thread died because of network error: Timeout reading data

These messages run in every some seconds.

How is this to fix?

**Comment by grinapo** [comment] 2023-12-15 15:19
For people coming from google search: This error is related to **TCP** traffic so first you should look around that, including possible TCP based transports like DNS-over-TLS, over-HTTP, EDNS and like.

For me this has been caused by DNS-over-TLS which had its certificate expired (not reloaded), so connecting clients have dropped the connections due to certificate error, and pdns-server have logged each and every one of them. 
(Debugging this was hell.)

**Comment by grinapo** [comment] 2023-12-15 16:34
Another cause: 

`dnsdist` forwards TCP based connections to pool (in my case pdns auth server), but keeps the TCP connection open by default. pdns-server instead really want it to be closed, and after a short while logs this error and closes the connection. In this case the error is annoying but harmless.
