### ISSUE TITLE
Make API error messages better when editing zone

### ISSUE THREAD

**Issue by BrightSkyz** [PowerDNS/pdns#6520] opened 2018-04-19 20:08 UTC
- Program: Authoritative 
 - Issue type: Feature request 

### Short description

Make the API error messages for editing a zone better. Currently you only get a JSON response of the first error like this:
```
{"error": "Record www.example.com./CNAME 'example.net': Not in expected format (parsed as 'example.net.')"}
```

### Usecase

There could be many uses for this, mine currently is getting the parsed value and re-sending the request so the records are changed/added.

### Description

When I do a request with a bunch of rrsets to be changed/added, I want to get a response that shows the error message that currently is sent, and the some data to go along with it. Also, adding a way to show all the records errors' instead of just showing first so we can fix all the stuff (by trying to parse the error message) and resend without resending multiple times to fix errors.

Optional extras that are nice: Adding an optional parameter in the PUT/POST/PATCH etc. methods called "retry" that will use the parsed and try again with the same request.

This is what the new request error response would look like:
<sub>(Note: I'm not sure of the other error messages that can occur with this message, so I am using the one I get commonly where I forget the period on the end of the CNAME record value.)</sub>
```
[
  {
    "message": "Record www.example.com./CNAME 'example.net': Not in expected format (parsed as 'example.net.')",
    "host": "www.example.com.",
    "type": "CNAME",
    "requested": "example.net",
    "parsed": "example.net."
  },
  {
    "message": "Record test.example.com./CNAME 'google.com': Not in expected format (parsed as 'google.com.')",
    "host": "test.example.com.",
    "type": "CNAME",
    "requested": "google.com",
    "parsed": "google.com."
  }
]
```

**Comment by Habbie** [comment] 2018-05-01 17:27
Duplicate of #6417

**Closed by Habbie** 2018-05-01 17:27 UTC
Labels: auth, enhancement, rest-api
