### ISSUE TITLE
MariaDB 10.2 errors with PowerDNS 4.1.0-rc1

### ISSUE THREAD

**Issue by mortenstevens** [PowerDNS/pdns#5819] opened 2017-10-12 14:42 UTC
I have a Fedora 26 VM with MariaDB 10.1 and a Fedora rawhide VM with MariaDB 10.2 for testing PowerDNS 4.1.0-rc1.
Note: The PowerDNS database, configuration and installation is identical on both hosts.

But I see some database errors in the log file only with MariaDB 10.2.

For example:

Oct 12 16:33:03 localhost.localdomain pdns[8227]: Remote 10.17.10.25 wants 'example.com|NS', do = 0, bufsize = 1680: packetcache MISS
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 0 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 0 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 1 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 2 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 3 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 4 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 5 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 6 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 7 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 8 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 9 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 0 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 1 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 0 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 1 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 0 column 7 has errno 120
Oct 12 16:33:03 localhost.localdomain pdns[8227]: Result field at row 1 column 7 has errno 120

Any ideas?

**Comment by Habbie** [comment] 2017-10-12 14:45
Duplicate of #5675. Also, why did you remove our issue template? It is there for a reason.

**Comment by mortenstevens** [comment] 2017-10-12 14:54
@Habbie 
This is just a quick report. Issue #5675 was reported one month ago, but I can't find a solution for it. Do you plan to fix it until the final 4.1.0 release?

**Comment by Habbie** [comment] 2017-10-12 14:55
@mortenstevens please post comments on the other ticket

**Comment by rgacogne** [comment] 2017-10-16 08:36
Closing this since it's a duplicate of #5675.

**Closed by rgacogne** 2017-10-16 08:36 UTC
