### ISSUE TITLE
tinydns: handle duplicate SOAs

### ISSUE THREAD

**Issue by MyIcecream** [PowerDNS/pdns#9173] opened 2020-05-29 03:02 UTC
When I migrate data from tinydns to gpgsql, I get this error:
 ```
# pdnsutil b2b-migrate tinydns gpgsql
May 29 02:53:03 [bindbackend] Done parsing domains, 0 rejected, 0 new, 0 removed
Moving zone(s) from tinydns to gpgsql
Processing 'klonopin-no-prescription.us'
Moved 10 record(s), 0 comment(s), 0 metadata(s) and 0 cryptokey(s)
Processing 'klonopin-no-prescription.us'
Error: Database error trying to insert new domain 'klonopin-no-prescription.us.': Fatal error during query: insert into domains (type,name,master,account,last_check, notified_serial) values($1,$2,$3,$4,null,null): ERROR:  duplicate key value violates unique constraint "name_index"
DETAIL:  Key (name)=(klonopin-no-prescription.us) already exists.
```
Operating system: Ubuntu 18.04.4 LTS
Software version: 4.1.13
Software source: PowerDNS repository

Does someone know how to deal with it, please?

**Comment by Woet** [comment] 2020-05-29 03:39
The error message mentions this:
`DETAIL:  Key (name)=(klonopin-no-prescription.us) already exists.`

Are you sure your PostgreSQL database doesn't contain this domain name already?

**Comment by MyIcecream** [comment] 2020-05-29 03:45
Although I recreate the new database, I still get this error
```
 id | domain_id |              name               | type |                                           content                                           | ttl  | prio | change_date | disabled | ordername | auth 
----+-----------+---------------------------------+------+---------------------------------------------------------------------------------------------+------+------+-------------+----------+-----------+------
  1 |         1 | klonopin-no-prescription.us     | SOA  | ns1.dynadot.com. hostmaster.klonopin-no-prescription.us. 1590544162 16384 2048 1048576 2560 | 2560 |    0 |             | f        |           | t
  2 |         1 | klonopin-no-prescription.us     | NS   | ns1.dynadot.com.                                                                            |  300 |    0 |             | f        |           | t
  3 |         1 | klonopin-no-prescription.us     | SOA  | ns2.dynadot.com. hostmaster.klonopin-no-prescription.us. 1590544162 16384 2048 1048576 2560 | 2560 |    0 |             | f        |           | t
  4 |         1 | klonopin-no-prescription.us     | NS   | ns2.dynadot.com.                                                                            |  300 |    0 |             | f        |           | t
  5 |         1 | klonopin-no-prescription.us     | A    | 52.4.209.250                                                                                |  300 |    0 |             | f        |           | t
  6 |         1 | www.klonopin-no-prescription.us | A    | 52.4.209.250                                                                                |  300 |    0 |             | f        |           | t
  7 |         1 | klonopin-no-prescription.us     | A    | 18.215.128.143                                                                              |  300 |    0 |             | f        |           | t
  8 |         1 | www.klonopin-no-prescription.us | A    | 18.215.128.143                                                                              |  300 |    0 |             | f        |           | t
  9 |         1 | klonopin-no-prescription.us     | A    | 18.213.250.117                                                                              |  300 |    0 |             | f        |           | t
 10 |         1 | www.klonopin-no-prescription.us | A    | 18.213.250.117                                                                              |  300 |    0 |             | f        |           | t

```

This is record table, why are there two SOA records?

**Comment by Habbie** [comment] 2020-05-29 05:08
> This is record table, why are there two SOA records?

Because there are two SOA records in your tinydns database, I'm pretty sure.

Our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by Habbie** [comment] 2020-05-29 11:18
I've retitled and reopened this issue, as it turns out we do have a bug!

**Comment by yds** [comment] 2020-05-29 11:32
@Habbie, re: tinydns SOA records.. tinydns constructs the SAO record always from the /first/ NS record while pdns-tinydns returns an SOA record with a /random/ NS from the zone..

e.g. if you have a.ns and b.ns -- tinydns will always use a.ns in the SOA if it was listed first in the input, while pdns will randomly return either a.ns or b.ns in the SOA record.

not a bug, per se, but also not consistent with how tinydns on-the-fly generates the SOA record.

**Comment by Habbie** [comment] 2020-05-29 12:16
> tinydns constructs the SAO record always from the /first/ NS record while pdns-tinydns returns an SOA record with a /random/ NS from the zone..

#9177 changes this from 'always last' to 'always first'

**Closed** 2020-11-09 18:52 UTC
Labels: auth
