### ISSUE TITLE
After fetching root zone '.' from Icann, nothing can be resolved

### ISSUE THREAD

**Issue by CRtEurope** [PowerDNS/pdns#4438] opened 2016-09-07 17:53 UTC
I have version 4.0.1 on a server.
The root zone from Icann is fetched and loaded but after this action no internet address can be resolved anymore.

I use the named.conf:
zone "." IN {
      type slave;
      masters { 192.0.32.132; 192.0.47.132; 2620:0:2d0:202::132; 2620:0:2830:202::132; };
      file "root.zone";
  };

When I deactivate this zone everything works flawlessly.

I also fetch all available arpa zones but don't know yet if tere are any problems with it.

We need this kind of root zone because we want to test powerdns and recursor as an open resolver.

If you need more information let me know.

**Comment by pieterlexis** [comment] 2016-09-07 18:01
Your full config please. And do you forward to your own root server or try to load the zone into the recursor

**Comment by CRtEurope** [comment] 2016-09-07 18:50
Here the config first. Additionally I must say that poerdns ist fast as hell in resolving. Congratulations. We are thinking about migrating completely to PowerDNS when everything has benn tested successfully.

pdns.conf:
`launch=bind,gmysql
# launch=hybrid,gmysql
# launch=gmysql

gmysql-host=127.0.0.1
gmysql-user=****
gmysql-password=*****
gmysql-dbname=powerdns
gmysql-dnssec=yes
setgid=pdns
setuid=pdns

# bind-dnssec-db=/etc/powerdns/zones/dnssec.db
bind-config=/etc/powerdns/named.conf
# bind-check-interval=600

8bit-dns=yes
allow-axfr-ips=0.0.0.0/0,::/0
allow-notify-from=0.0.0.0/0,::/0
allow-recursion=0.0.0.0/0,::/0
allow-unsigned-notify=yes
allow-unsigned-supermaster=yes
any-to-tcp=yes
# also-notify=192.0.2.1, 203.0.113.167
cache-ttl=20
config-dir=/etc/powerdns
daemon=yes
default-ttl=3600
disable-axfr=no
disable-tcp=no
distributor-threads=3
do-ipv6-additional-processing=yes
domain-metadata-cache-ttl=60
entropy-source=/dev/urandom
guardian=yes
local-address-nonexist-fail=no
local-address=127.0.0.1, 88.198.53.55
local-ipv6=::1, 2a01:4f8:131:1278::2
local-ipv6-nonexist-fail=no
local-port=53
log-dns-details=yes
log-dns-queries=yes
loglevel=9
master=yes
max-cache-entries=1000000
max-ent-entries=100000
max-nsec3-iterations=500
max-queue-length=5000
max-signature-cache-entries=2^64
max-tcp-connections=20
negquery-cache-ttl=60
overload-queue-length=0
query-local-address=88.198.53.55
query-local-address6=2a01:4f8:131:1278::2
query-logging=yes
out-of-zone-additional-processing=yes
do-ipv6-additional-processing=yes
log-dns-details=on
module-dir=/usr/lib/x86_64-linux-gnu/pdns
outgoing-axfr-expand-alias=no
out-of-zone-additional-processing=yes
prevent-self-notification=no
query-cache-ttl=20
queue-limit=1500
receiver-threads=1
recursor=127.0.0.1:3001
recursive-cache-ttl=10
retrieval-threads=2
security-poll-suffix=secpoll.powerdns.com
server-id=open-root.cesidian.info
signing-threads=3
slave=yes
slave-cycle-interval=60
slave-renotify=yes
socket-dir=/var/run
udp-truncation-threshold=4096
version-string=CRt DNS 3.0
write-pid=yes
xfr-max-received-mbytes=100
`

recursor.conf:
`setuid=pdns
setgid=pdns
allow-from=0.0.0.0/0,::/0
any-to-tcp=yes
config-dir=/etc/powerdns
disable-packetcache=no
disable-syslog=0
dnssec=validate
dnssec-log-bogus=yes
dont-query=10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, fc00::/7, fe80::/10, 0.0.0.0/8, 192.0.0.0/24, 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, 240.0.0.0/4, ::/96, ::ffff:0:0/96, 100::/64, 2001:db8::/32
edns-outgoing-bufsize=1680
edns-subnet-whitelist=0.0.0.0/0,::/0
entropy-source=/dev/urandom
etc-hosts-file=/etc/hosts
export-etc-hosts=yes
# forward-zones=cn.=8.8.4.4:53,th.=8.8.4.4:53
forward-zones-file=/etc/powerdns/forwarders.conf
# forward-zones-recurse=.=176.9.126.244,.=178.254.21.113,.=[2a01:4f8:151:90e9::2],.=[2001:470:520a::1],.=[2001:470:6d:80:a5f6:5a97:a53:71cb],.=[2001:470:6d:80:c4f1:32a:4521:c34
# forward-zones-recurse=.=176.9.126.244;178.254.21.113
hint-file=/etc/powerdns/named.cache // **tried with orignal root zone from Icann, but no avail**
local-address=127.0.0.1, 88.198.53.55, ::1, 2a01:4f8:131:1278::2
local-port=3001
log-common-errors=yes
loglevel=9
lowercase-outgoing=yes
lua-config-file=/etc/powerdns/trustanchors.conf
max-cache-entries=10000000
max-qperq=50
max-mthreads=2048
max-negative-ttl=600
max-packetcache-entries=500000
max-tcp-clients=128
max-tcp-per-client=0
max-total-msec=7000
minimum-ttl-override=0
network-timeout=1500
packetcache-ttl=3600
packetcache-servfail-ttl=60
root-nx-trust=yes
query-local-address=88.198.53.55
query-local-address6=2a01:4f8:131:1278::2
quiet=no
server-down-max-fails=64
server-down-throttle-time=60
server-id=open-root.cesidian.info
serve-rfc1918=no
socket-dir=/var/run
spoof-nearmiss-max=20
stack-size=200000
stats-ringbuffer-entries=10000
threads=8
trace=on
udp-truncation-threshold=4096
version-string=CRt DNS 3.0
webserver=yes
webserver-address=88.198.53.55
webserver-allow-from=0.0.0.0, ::/0
webserver-password=mcripkb7862
webserver-port=9000
write-pid=yes
`

**Comment by phonedph1** [comment] 2016-09-07 18:58
It looks like you are doing a number of things wrong here.

You have the auth pointing at a recursor, and the recursor also doing forward exceptions, and you tried to replace the root hint file with the actual root zone there at one point?

You should really try to make this work by having your auth load the root zone and then have your recursor be the primary entry point which forwards requests for . to your local auth server (the opposite of what you seem to have here).

**Comment by CRtEurope** [comment] 2016-09-07 19:00
Thanks but how can I mange this? Sorry

**Comment by pieterlexis** [comment] 2016-09-07 19:01
this breaks because you load the root-zone into the recursor **without** dnssec enabled for the bind-backend. You **need** the `bind-dnssec-db` to serve DNSSEC signed zones (even if they are slaved, as this contains the `PRESIGNED` domain metadata.

Your recursor is set to `dnssec=validate`, but the auth won't serve you the RRSIGs, so the validation result is bogus.

And indeed do as @phonedph1 says, have the recursor listen on port 53 and forward queries for the root to the auth with the `forward-zones=.=IP-OF-THE-AUTH`.

Closing this issue as it is not a bug but a support question, please use [the mailing list](https://www.powerdns.com/mailing-lists.html) for support questions.

**Closed by pieterlexis** 2016-09-07 19:01 UTC
