### ISSUE TITLE
while parsing IP address, expected digits at position 0 in '\# 4 0A000001'

### ISSUE THREAD

**Issue by daniel-widrick** [PowerDNS/pdns#10712] opened 2021-09-10 14:51 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description
trying to add an unknown record type (https://datatracker.ietf.org/doc/html/rfc3597.html) and (https://doc.powerdns.com/authoritative/appendices/types.html) Results in a parsing error.

### Environment

 - Operating system: Fedora 34
 - Software version: Sep 10 10:41:44 PowerDNS Authoritative Server 4.4.1 (C) 2001-2020 PowerDNS.COM BV
 - Software source: OS Repository

### Steps to reproduce

1. `pdnsutil add-record int.apt.widrick.net test TYPE1 "\# 4 0A000001"`

### Expected behaviour
The zone would be added to the backend and the server would answer queries for TYPE1 records
```
dig @127.0.0.1 TYPE1 int.apt.widrick.net
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36424
 int.apt.widrick.net.             800    IN      A       10.0.0.1
```

### Actual behavior
The record fails to parse and the server will not properly respond to requests for the record
```
dig @127.0.0.1 TYPE1 int.apt.widrick.net
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 27047
```

### Other information
We're actually attempting to get to the point where we can add TYPE55 (HIP)(https://datatracker.ietf.org/doc/html/rfc8005) records but we cannot even proceed wit the example case from the unknown records rfc/pdns documentation.

We're using a postgresql backend:
```create table records
(
    id        bigserial
        constraint records_pkey
            primary key,
    domain_id integer,
    name      varchar(255),
    type      varchar(10),
    content   varchar(1024),
    ttl       integer,
    prio      integer,
    disabled  boolean,
    ordername varchar(255),
    auth      boolean
);
create table domains
(
    id              serial
        constraint domains_pkey
            primary key,
    name            varchar(255),
    master          varchar(128),
    last_check      integer,
    type            varchar(6),
    notified_serial bigint,
    account         varchar(40)
);```

```launch=gpgsql
gpgsql-host=127.0.0.1
gpgsql-user=myUser
gpgsql-password=myPassword
gpgsql-dbname=dns

gpgsql-get-order-first-query=select ordername from records where domain_id = $1 and disabled = false and ordername is not null order by 1 asc limit 1
gpgsql-get-order-before-query=select ordername, name from records where ordername <= $1 and domain_id = $2 and disabled = false and ordername is not null order by 1 desc limit 1
gpgsql-get-order-after-query=select ordername from records where ordername > $1 and domain_id = $2 and disabled = false and ordername is not null order by 1 asc limit 1
gpgsql-get-order-last-query=select ordername, name from records where ordername != '' and domain_id = $1 and disabled = false and ordername is not null order by 1 desc limit 1```

**Comment by Habbie** [comment] 2021-09-10 14:53
Hi Daniel,

thank you for your extensive reports. However, this report is a duplicate of #804 - to summarise that, we know that this syntax does not work for types we support. So I'll have to close this, sorry.

**Closed by Habbie** 2021-09-10 14:53 UTC

**Comment by Habbie** [comment] 2021-09-10 14:59
Ah, @mind04 just pointed out to me that running with `upgrade-unknown-types=yes` should make your record work. Please try it!
