### ISSUE TITLE
dnsdist - marking server down breaks GUI

### ISSUE THREAD

**Issue by rygl** [PowerDNS/pdns#7519] opened 2019-02-26 14:51 UTC
- Program: dnsdist
 - Issue type: Bug 

### Short description
When I mark server in the pool as down manually using getServer():setDown() it breaks dnsdist GUI. No stats per server are displayed. Just list of dynblocked clients and the dnsdist summary.

### Environment

-    Operating system: Debian 9.6
-   Software version: 1.3.2-1pdns.stretch
-    Software source: https://repo.powerdns.com/debian/dists/

### Steps to reproduce

1. getServer():setDown()
2. Use GUI

### Expected behaviour
GUI is normally displayed

**Comment by rgacogne** [comment] 2019-02-26 14:52
Thanks for the bug report, I'm closing it since it's a duplicate of #7461.

**Closed by rgacogne** 2019-02-26 14:52 UTC
