### ISSUE TITLE
transfer zones

### ISSUE THREAD

**Issue by sami201** [PowerDNS/pdns#7627] opened 2019-03-26 14:33 UTC
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report/Feature request 

### Short description

I'm running two machines with PowerDNS, one being the master (SQL) and one being the slave (SQL). The problem is, that every domain added on master NS is not added on slave dns server 

### Environment

 - Operating system: CentOS7
 - Software version: powerdns4.2
 - Software source: 

### Steps to reproduce

Master's config  ns1//192.168.1.99:
allow-axfr-ips=192.168.1.98,192.168.1.0/24
master=yes
slave=no
also-notify=192.168.1.98
disable-axfr=no
soa-minimum-ttl=3600
soa-refresh-default=10800
soa-retry-default=3600
disable-axfr=no
daemon=yes
guardian=no
launch=gmysql
gmysql-host=localhost
gmysql-user=powerdns
gmysql-password=mypassword
gmysql-dbname=powerdns
gmysql-dnssec=yes
local-address=0.0.0.0
local-ipv6=
local-port=53
log-dns-details=yes
log-dns-queries=yes
log-timestamp=yes
loglevel=4
setgid=pdns
setuid=pdns
#also-notify=192.168.1.98
allow-notify-from=0.0.0.0/0

Slave's config:
daemon=yes
guardian=no
launch=gmysql
gmysql-host=localhost
gmysql-user=powerdns
gmysql-password=mypassword
gmysql-dbname=powerdns
gmysql-dnssec=yes
local-address=0.0.0.0
local-ipv6=
local-port=53
log-dns-details=yes
log-dns-queries=yes
log-timestamp=yes
loglevel=4
setgid=pdns
setuid=pdns
#allow-notify-from=192.168.1.99
slave=yes
disable-axfr=yes
disable-tcp=no
master=no
query-local-address=192.168.1.99,127.0.0.1
allow-notify-from=0.0.0.0/0

### Actual behaviour

master log: 
Mar 21 21:08:46 ns1 pdns_server: Unable to queue notification of domain 'exemple.com': nameservers do not resolve!
Mar 21 21:08:46 ns1 pdns_server: Queued also-notification of domain 'exemple.com' to 192.168.1.98:53
Mar 21 21:08:46 ns1 pdns_server: Error sending data to pdns_control: Broken pipe
Mar 21 21:08:48 ns1 pdns_server: Received unsuccessful notification report for 'exemple.com' from 192.168.1.98:53, error: Query Refused
Mar 21 21:08:48 ns1 pdns_server: Removed from notification list: 'exemple.com' to 192.168.1.98:53 Query Refused

### Usecase

ensure the transfer of zones between master and slave

**Comment by rgacogne** [comment] 2019-03-26 14:40
I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by rgacogne** 2019-03-26 14:40 UTC
