### ISSUE TITLE
PDNS Recursor consistently serving NXdomain

### ISSUE THREAD

**Issue by shriganesh** [PowerDNS/pdns#10700] opened 2021-09-08 06:08 UTC
- Program:  Recursor 
 - Issue type: Bug report

### Short description

For certain list of domains PDNS Recursor is consistently serving NXdomain while these domains get resolved just fine if I use different resolver (ex: 8.8.8.8/208.37.222.222). One commonality that I noticed is that all the failing domains have CNAME in the chain.

### Environment

 - Operating system: Ubuntu 20.04.3 LTS (focal)
 - Software version: 4.5.5
 - Software source: PowerDNS repository 

### Steps to reproduce

Configuration:
allow-from=0.0.0.0/0
api-key=******
config-dir=/etc/powerdns
daemon=yes
disable-syslog=no
dnssec=validate
etc-hosts-file=/etc/hosts
export-etc-hosts=on
forward-zones=.=208.67.222.222
forward-zones-recurse=.=208.67.222.222
hint-file=/usr/share/dns/root.hints
include-dir=/etc/powerdns/recursor.d
local-address=10.0.0.230:53
log-common-errors=yes
logging-facility=0
lua-config-file=/etc/powerdns/recursor.lua
max-negative-ttl=3600
packetcache-servfail-ttl=5
public-suffix-list-file=/usr/share/publicsuffix/public_suffix_list.dat
query-local-address=10.0.0.230
quiet=no
root-nx-trust=no
server-down-max-fails=100
setgid=pdns
setuid=pdns
trace=on
webserver=yes
webserver-address=10.0.0.230
webserver-allow-from=0.0.0.0/0
webserver-loglevel=normal
webserver-port=8082

### Expected behaviour

dig @8.8.8.8 resources.sonyliv.com

; <<>> DiG 9.11.5-P4 <<>> @8.8.8.8 resources.sonyliv.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55698
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;resources.sonyliv.com.         IN      A

;; ANSWER SECTION:
resources.sonyliv.com.  60      IN      CNAME   sony-liv.san.cloudinary.com.
sony-liv.san.cloudinary.com. 300 IN     CNAME   s4-san.cloudinary.com.edgekey.net.
s4-san.cloudinary.com.edgekey.net. 21600 IN CNAME e10700.dsca.akamaiedge.net.
e10700.dsca.akamaiedge.net. 20  IN      A       23.15.101.96

;; Query time: 51 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Sep 08 11:29:32 IST 2021
;; MSG SIZE  rcvd: 188

### Actual behaviour

dig @100.100.100.100 resources.sonyliv.com

; <<>> DiG 9.11.5-P4 <<>> @100.100.100.100 resources.sonyliv.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 39477
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;resources.sonyliv.com.         IN      A

;; AUTHORITY SECTION:
sonyliv.com.            3491    IN      SOA     localhost. root. 1 604800 86400 2419200 604800

;; Query time: 55 msec
;; SERVER: 100.100.100.100#53(152.67.182.178)
;; WHEN: Wed Sep 08 11:29:48 IST 2021
;; MSG SIZE  rcvd: 99

### Other information

1) Tried setting root-nx-trust to yes and no. Still same result.
2) Was running 4.2.1, saw few bugs #6112 #5107 #5246 #5252 but mine seems to be consistently happening (100% of the requests fail)
3) I enabled logging and trace. Below it the snip of log I got:
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: 2 [2/1] question for 'resources.sonyliv.com|A' from 99.99.99.99:62382
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] : no TA found for 'resources.sonyliv.com' among 1
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] : no TA found for 'sonyliv.com' among 1
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] : no TA found for 'com' among 1
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] : got TA for '.'
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] resources.sonyliv.com: Wants DNSSEC processing, auth data in query for A
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] resources.sonyliv.com: No cache hit for 'resources.sonyliv.com|A', trying to find an appropriate NS record
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] resources.sonyliv.com: Cache consultations done, have 1 NS to contact
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] resources.sonyliv.com: Domain is out-of-band
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] resources.sonyliv.com: auth storage has data, zone='sonyliv.com'
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] resources.sonyliv.com: accept answer 'sonyliv.com|SOA|localhost. root. 1 604800 86400 2419200 604800' from 'sonyliv.com' namese>
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] resources.sonyliv.com: determining status after receiving this packet
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] resources.sonyliv.com: got negative caching indication for name 'resources.sonyliv.com' (accept=1), newtarget='(empty)'
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] validation state was Indeterminate, state update is Indeterminate, validation state is now Indeterminate
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] resources.sonyliv.com: status=NXDOMAIN, we are done (have negative SOA)
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] validation state was Indeterminate, state update is Indeterminate, validation state is now Indeterminate
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] resources.sonyliv.com: failed (res=3)
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: 2 [2/1] answer to question 'resources.sonyliv.com|A': 0 answers, 1 additional, took 0 packets, 0 netw ms, 0 tot ms, 0 throttled, 0 >

**Note: The config file and output have been sanitized.**

**Comment by rgacogne** [comment] 2021-09-08 07:50
These (truncated, please don't do that) lines mean that the recursor believes it has local data for that zone:
```
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] resources.sonyliv.com: Domain is out-of-band
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] resources.sonyliv.com: auth storage has data, zone='sonyliv.com'
Sep 08 05:57:58 ubuntu-dns-vm-1 pdns_recursor[6929]: [2] resources.sonyliv.com: accept answer 'sonyliv.com|SOA|localhost. root. 1 604800 86400 2419200 604800' from 'sonyliv.com' namese>
```

So there is something in your configuration that does not show up in this ticket. What are the content of:
- /etc/hosts
- Any file in /etc/powerdns/recursor.d
- /etc/powerdns/recursor.lua

It's very hard for us to help you with incomplete and/or redacted information.

**Comment by pieterlexis** [comment] 2021-09-08 08:06
This won't fly:

```
forward-zones=.=208.67.222.222
forward-zones-recurse=.=208.67.222.222
```

pick one of them (the correct one for your usecase)

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2021-09-08 08:06 UTC
Labels: rec, response needed
