### ISSUE TITLE
Unit pdns.service entered failed state

### ISSUE THREAD

**Issue by foxconncaa** [PowerDNS/pdns#9065] opened 2020-04-27 10:01 UTC
4月 27 18:00:29 localhost.localdomain pdns_server[18173]: This is a standalone pdns
4月 27 18:00:29 localhost.localdomain pdns_server[18173]: Listening on controlsocket in '/var/run/pdns.controlsocket'
4月 27 18:00:29 localhost.localdomain pdns_server[18173]: Fatal error: Trying to set unknown parameter 'gmysqlhost'
4月 27 18:00:29 localhost.localdomain systemd[1]: pdns.service: main process exited, code=exited, status=1/FAILURE
4月 27 18:00:29 localhost.localdomain systemd[1]: Failed to start PowerDNS Authoritative Server.
-- Subject: Unit pdns.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit pdns.service has failed.
--
-- The result is failed.
4月 27 18:00:29 localhost.localdomain systemd[1]: Unit pdns.service entered failed state.
4月 27 18:00:29 localhost.localdomain systemd[1]: pdns.service failed.
4月 27 18:00:30 localhost.localdomain systemd[1]: pdns.service holdoff time over, scheduling restart.
4月 27 18:00:30 localhost.localdomain systemd[1]: Stopped PowerDNS Authoritative Server.
-- Subject: Unit pdns.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit pdns.service has finished shutting down.
4月 27 18:00:30 localhost.localdomain systemd[1]: Starting PowerDNS Authoritative Server...
-- Subject: Unit pdns.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit pdns.service has begun starting up.
4月 27 18:00:30 localhost.localdomain pdns_server[18183]: Reading random entropy from '/dev/urandom'
4月 27 18:00:30 localhost.localdomain pdns_server[18183]: Loading '/usr/lib64/pdns/libgmysqlbackend.so'
4月 27 18:00:30 localhost.localdomain pdns_server[18183]: This is a standalone pdns
4月 27 18:00:30 localhost.localdomain pdns_server[18183]: Listening on controlsocket in '/var/run/pdns.controlsocket'
4月 27 18:00:30 localhost.localdomain pdns_server[18183]: Fatal error: Trying to set unknown parameter 'gmysqlhost'
4月 27 18:00:30 localhost.localdomain systemd[1]: pdns.service: main process exited, code=exited, status=1/FAILURE
4月 27 18:00:30 localhost.localdomain systemd[1]: Failed to start PowerDNS Authoritative Server.
-- Subject: Unit pdns.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit pdns.service has failed.
--
-- The result is failed.
4月 27 18:00:30 localhost.localdomain systemd[1]: Unit pdns.service entered failed state.
4月 27 18:00:30 localhost.localdomain systemd[1]: pdns.service failed.

**Comment by pieterlexis** [comment] 2020-04-27 10:03
>  4月 27 18:00:29 localhost.localdomain pdns_server[18173]: Fatal error: Trying to set unknown parameter 'gmysqlhost'

That is indeed not a correct pdns.conf setting. I thing you mean `gmysql-host`(https://docs.powerdns.com/authoritative/backends/generic-mysql.html#gmysql-port)

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Comment by foxconncaa** [comment] 2020-04-27 10:03
ccentos7  &  VMware Workstation Pro

**Closed by pieterlexis** 2020-04-27 10:03 UTC
