### ISSUE TITLE
Odd NS selection after updates to an NS's IP address(es)

### ISSUE THREAD

**Issue by gpittarelli** [PowerDNS/pdns#1066] opened 2013-10-17 19:58 UTC
There is an issue in pdns's NS selection when the IP address(es) for a given NS change. pdns will send all recursive queries to the updated NS, regardless of whether or not a better NS is available. The issue seems to persist until pdns is restarted.

We ran across this issue while examining traffic captures for the d-root server during the changeover process which occurred earlier this year (Jan 3rd 2013). We then recreated it in an emulated environment (https://www.emulab.net/), emulating 13 root servers, a replacement d-root server, and a test server running pdns_recursor with a script to generate queries with invalid TLDs (guaranteed to be sent to a root server).

Though the experiment was specifically interested in testing root servers, I believe the same issue appears for non-root servers.

The timeline of events:
1. pdns working normally.
2. d-root IP address changes; all root servers begin returning a new IP address for d.root-servers.net
3. pdns still operates as in step 1, until the next priming query (every 2 hours).
4. Shortly after pdns re-primes the root server cache (and gets the new IP address), it begins sending all root server traffic to the new d-root IP address.

In the emulated network, the recursor had controlled latencies to each of the root servers. Of note, h-root (which should be prefered as the lowest latency server) had a latency of ~11ms, while both the new and the old d-root had around ~100ms. The issue causes pdns to prefer the 100ms server, leading to an overall decrease in performance for those queries.

Here is a graph of the recorded network traffic:

![reqs](https://f.cloud.github.com/assets/1004194/1355345/992b1dd4-3764-11e3-9b41-bf9f955d9df6.png)

Here is another graph zoomed in on the moment when pdns starts acting incorrectly:

![reqs_zoomed](https://f.cloud.github.com/assets/1004194/1355346/9ba33fce-3764-11e3-95fb-8a055eff2a41.png)

And here is a large (89M compressed, 1.2G uncompressed) debug log from the experimental run: http://www.cs.umd.edu/~gjp/pdns_ns_selection_log.tar.gz

I looked into the pdns source and I believe this is the sequence of events leading to this issue (these same events happen independently for each thread):
1. houseKeeping thread issues a priming query every 2 hours.
2. The priming query response returns the new d-root IP address, which replaces the cached IP address for the d.root-servers.net NS. The DEWMA collection for d.root-servers.net still contains the old IP address and its decayed latency.
3. pdns selects which NS to use for a query by sorting the NSs according to the lowest latency associated with the NS (in the NS's DEWMA collection).
4. The latency for the old d-root IP address continues to decay until it is the lowest latency, at which point pdns chooses to use d.root-servers.net for the current query.
5. pdns lookups the IP address for d.root-servers.net in the resolver cache, which returns the new d-root IP address (as updated in step 2).
6. Once the query completes, pdns submits the latency to the DEWMA collection for d.root-servers.net, using the new d-root IP address. The old d-root IP address and latency are still in the DEWMA collection, but the latency is not updated (and continues to decay).
7. Because the latency for the old d-root IP address continues to decay, pdns continues to select d.root-servers.net for root zone queries.

**Comment by ahupowerdns** [comment] 2017-02-23 10:17
4.x has new logic for nameserver selection, so this may well have resolved itself.

**Comment by Habbie** [comment] 2017-07-06 20:04
Changed milestone to 'rec-helpneeded' in the hope that somebody in the community will feel like redoing this experiment.

**Comment by giganteous** [comment] 2017-10-27 08:04
@gpittarelli I'm interested in helping out here, and to learn how to do this. 
Would you be so kind to share the mentioned files?

**Comment by gpittarelli** [comment] 2017-10-30 05:22
I recreated the experiment to verify this issue again using mininet. The necessary files are here: https://github.com/gpittarelli/pdns-network-sim

Here's the result:

![qpm](https://user-images.githubusercontent.com/1004194/32155730-6affe5ea-bcf6-11e7-952c-219ceaa41f56.png)

The switchover happened around 10 minutes in, and then at around 2 hrs in the recursor re-primed and we got stuck on the new d-root address. So it looks like the behavior still exists. This was tested with the version of pdns I got with `sudo apt-get install -y dns-recursor`.

```
$ /usr/sbin/pdns_recursor --version
Oct 30 01:38:15 PowerDNS Recursor 4.0.4 (C) 2001-2016 PowerDNS.COM BV
Oct 30 01:38:15 Using 64-bits mode. Built using gcc 6.3.0 20170516.
Oct 30 01:38:15 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Oct 30 01:38:15 Features: openssl lua 
Oct 30 01:38:15 Configured with: " '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--sysconfdir=/etc/powerdns' '--enable-reproducible' '--with-lua' '--with-protobuf=yes' '--enable-systemd' '--with-systemd=/lib/systemd/system' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/pdns-recursor-SmC8As/pdns-recursor-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro -Wl,-z,now -latomic' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/pdns-recursor-SmC8As/pdns-recursor-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -DPACKAGEVERSION='\''"4.0.4-1+deb9u1.Debian"'\'''"
```

**Comment by giganteous** [comment] 2017-10-30 08:00
I will rerun this experiment with the latest master today. Thanks for the pointers

**Comment by giganteous** [comment] 2017-10-31 08:34
It wasn't that easy. Mininet doesn't mould as easy as I wanted it to. It'll take a bit longer

**Comment by gpittarelli** [comment] 2017-10-31 23:02
What went wrong? I reran the experiment against master (e5d68d9fd when I built pdns) with a fresh VM and observed the issue again:

![qpm](https://user-images.githubusercontent.com/1004194/32252831-b84dbd22-be54-11e7-977a-0753dea005d7.png)

**Comment by rgacogne** [comment] 2017-11-01 15:34
> What went wrong? I reran the experiment against master (e5d68d9 when I built pdns) with a fresh VM and observed the issue again

Well, #5877 has not been merged yet so the issue is still present in master.

**Closed** 2017-11-01 18:39 UTC
Labels: enhancement, rec

**Comment by giganteous** [comment] 2017-11-02 10:35
@gpittarelli I had trouble getting getting the resolver to work due to a recursor.conf that contained settings that broke the whole testing. Fixed now.
