### ISSUE TITLE
rec_control --version doesn't show version

### ISSUE THREAD

**Issue by mzealey** [PowerDNS/pdns#4082] opened 2016-07-01 09:27 UTC
Installed 4.0.0~rc1-1pdns.trusty ubuntu package.

```
# rec_control --version
syntax: rec_control [options] command, options as below: 

  --chroot=...
        switch to chroot jail
  --config-dir=...
        Location of configuration directory (recursor.conf)
  --config-name=...
        Name of this virtual configuration - will rename the binary image
  --help
        Provide this helpful message
  --process=...
        When controlling multiple recursors, the target process number
  --socket-dir=...
        Where the controlsocket will live, /var/run when unset and not chrooted
  --timeout=...
        Number of seconds to wait for the recursor to respond
  --version
        Show the version of this program

In addition, 'rec_control help' can be used to retrieve a list
of available commands from PowerDNS
```

**Comment by pieterlexis** [comment] 2016-07-01 09:29
dupe of #4045

**Closed by pieterlexis** 2016-07-01 09:29 UTC
