### ISSUE TITLE
PDNS Recursor

### ISSUE THREAD

**Issue by Stat-Kaya** [PowerDNS/pdns#8600] opened 2019-12-02 14:30 UTC
Hi, I have the problem that the recursor doesn't send dnsupdates to the Auth server. But I get the right answer over dig and co.

**Comment by pieterlexis** [comment] 2019-12-02 14:36
I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2019-12-02 14:36 UTC
