### ISSUE TITLE
dig +trace fails (REFUSED)

### ISSUE THREAD

**Issue by ppanula** [PowerDNS/pdns#4353] opened 2016-08-23 10:32 UTC
pdns 4.0.1 with recursor (4.0.1) installed under CentOS 7.2, official RPMS used from powerdns repo.

Every dig query with +trace fails:

```
dig +trace +all @127.0.0.1 powerdns.com NS 

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> +trace +all @127.0.01 powerdns.com NS
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 28984
;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1680
;; QUESTION SECTION:
;.              IN  NS

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Aug 23 13:30:44 EEST 2016
;; MSG SIZE  rcvd: 28

```

syslog shows:
Remote 127.0.0.1 wants '.|NS', do = 1, bufsize = 1680: packetcache MISS

**Comment by ppanula** [comment] 2016-08-23 10:36
to be clear, normal dig queries without +trace works ok, recursion works, just not queries with +trace.

**Comment by phonedph1** [comment] 2016-08-23 18:14
The only thing dig requires is that we answer a query for ". NS" without the RD bit set. This works for me on 4.0.0 freshly started. I can re-produce it by rec_control wipe-cache . - obviously we aren't answering something without recursion if we need recursion to find it. 

I would expect most caches would have the root consistently primed, so this shouldn't be a common problem.

. should probably be a special case for this though.

**Comment by joshuaboniface** [comment] 2016-12-26 20:09
I'm experiencing this as well and not seeing an obvious solution anywhere. I had the same problem with PDNS3 but fixed it with `send-root-referral=yes`. But now that option is gone.

**Comment by ahupowerdns** [comment] 2017-02-20 09:34
So wrt some entries above - the root-referral is when people chain a recursor behing a powerdns authoritative server. The issue that 'dig +trace' doesn't work against the recursor should be exceptionally rare, and can be traced back to 'dig' not setting the RD bit. If the issue is not exceptionally rare, it might have another cause.

**Comment by joshuaboniface** [comment] 2017-02-23 22:17
>the root-referral is when people chain a recursor behing a powerdns authoritative server

I am doing exactly that.

**Comment by jph** [comment] 2017-11-27 03:35
Hello. I'm not sure if this is still the right place to ask, but I'm also seeing this behaviour with the pdns-recursor configured behind an authoritative instance of PowerDNS.

```
[root@ns1 ~]# dig +trace +all @127.0.0.1 NS google.com

; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7 <<>> +trace +all @127.0.0.1 NS google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 65356
;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1680
;; QUESTION SECTION:
;.				IN	NS

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Nov 27 14:34:24 AEDT 2017
;; MSG SIZE  rcvd: 28
```

**Comment by Habbie** [comment] 2017-11-27 09:49
@jph `recursor=` has been removed from Auth as of version 4.1 because it rarely does what people want. We recommend changing your setup. Our [migration docs](https://doc.powerdns.com/authoritative/guides/recursion.html) may be of help here.

**Comment by Habbie** [comment] 2017-11-27 09:50
Closing this ticket as there appears to be no actual problem with the recursor.

**Closed by Habbie** 2017-11-27 09:50 UTC
Labels: rec

**Comment by muzzol** [comment] 2019-04-02 08:21
sorry to resurrect this issue but I'm facing the same problem and I would like to know if this feature is removed forever or if this is a way to host pdns and recursor on same machine.

we are using this setup on our internal network with 2.9 version and works really well, so I don't really get why this is being removed.

**Comment by pieterlexis** [comment] 2019-04-02 08:31
> this is a way to host pdns and recursor on same machine.

This is the way to run the auth and recursor on the same machine, see [the docs](https://doc.powerdns.com/authoritative/guides/recursion.html). 

> we are using this setup on our internal network with 2.9 version and works really well, so I don't really get why this is being removed.

This was done to modernize the code base and to keep a good separation of concerns between the auth and recursor
