### ISSUE TITLE
Recursor ignores non-existing Luaconf file, reports no useful error

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#5075] opened 2017-02-23 09:39 UTC
- Program: Recursor 
 - Issue type: Bug report 

### Short description

When specifying a lua configuration file, and it does not exist, this does not lead to a useful error, complicating debugging.

### Environment

 - Operating system: 
 - Software version: 
 - Software source: 

### Steps to reproduce

1. 
2. 
3.

**Comment by Habbie** [comment] 2017-02-23 09:40
Duplicate of #4939 which I have now put in the rec-4.1.0 milestone.

**Closed by Habbie** 2017-02-23 09:40 UTC
