### ISSUE TITLE
auth 0/1 in remote backend

### ISSUE THREAD

**Issue by direktorn** [PowerDNS/pdns#5178] opened 2017-03-17 19:07 UTC
I'm using 3.4.11 
I've configured remote backend (RESTful) 

I want to return DNS answers with "ADDITIONAL SECTION" - primary returning root type records (MX) as far as I understand (some documentation i found in the pdns-user ml: 

**auth = 1 if your data is authoritative for the zone and 0 if not. usually you should set this to 1. setting it 0 will put the data into additional section.**

However doing that does not seems to work, using DIG all my records shows up in "ANSWER SECTION". 

It this expected behaviour?

**Comment by direktorn** [comment] 2017-03-20 16:03
I've upgraded to 4.x but no luck. Looks like the API has changed since 3.4 - But i'm not able to see  any changelogs for the API, nor any documentation for the remote backend that is version specific.  I'm I missing something?

**Comment by Habbie** [comment] 2017-03-20 16:10
Hello, this appears to be a support question, not a bug report. Please find our mailing lists or IRC channel via https://www.powerdns.com/opensource.html and ask your question there.

Closing this ticket. Good luck!

**Closed by Habbie** 2017-03-20 16:10 UTC
Labels: auth
