### ISSUE TITLE
BIND backend fails to ignore bind logging configuration

### ISSUE THREAD

**Issue by xkr47** [PowerDNS/pdns#2761] opened 2015-09-27 17:01 UTC
* using pdns-3.4.6-1.fc22.x86_64 as provided by standard Fedora 22
* using BIND backend

When trying to start with bind configuration file from bind version 9.9.3, I get the following error:

    Sep 27 17:41:01 test2 pdns[8645]: Error parsing bind configuration: Error in bind configuration '/var/named/named.conf' on line 43: syntax error
    Sep 27 17:41:01 test2 pdns[8645]: Caught an exception instantiating a backend: Error in bind configuration '/var/named/named.conf' on line 43: syntax error

Here's a snippet of the offending configuration file, with line 43 annotated.

    logging {
        channel query-log {
            file "data/named-query.log" versions 1000 size 100m; # line 43
            print-time yes;
        };
        category queries { query-log; };
        channel default_debug {
            file "data/named.run";
            severity dynamic;
            print-time yes;
        };
    }; 

I'm suspecting that line 48, also starting with `file` might also cause issues if one would simply remove line 43.. didn't try that though. I just removed the whole "logging" snippet presented above after which pdns started fine.

**Comment by cmouse** [comment] 2015-09-27 17:09
This seems to be a mistake in pdns/bindparser.yy:147. I'll take a look.

**Comment by Habbie** [comment] 2015-10-02 10:48
duplicate of #2290

**Closed by Habbie** 2015-10-02 10:48 UTC
Labels: auth, defect
