### ISSUE TITLE
Fatal error connecting to dnsdist console

### ISSUE THREAD

**Issue by sbeccato** [PowerDNS/pdns#8984] opened 2020-03-30 16:32 UTC
Hi,

running dnsdist **1.5.0-0.alpha1.1** on **CentOS 8.1.1911** I'm not able to connect to console.

dnsdist configuration:

```setLocal('10.211.93.11:53')

controlSocket('10.211.93.40:5199')
setKey("secret")
addACL('0.0.0.0/0')


webserver("10.211.93.40:8083", "supersecretpassword", "supersecretAPIkey")


newServer({address="8.8.8.8", name="Server01"})
newServer({address="8.8.4.4", name="Server02"})
newServer({address="1.1.1.1", name="Server03"})
setServerPolicy(leastOutstanding)

pc = newPacketCache(10000)
getPool(""):setCache(pc)
```

ulimit status:
```su - dnsdist -c 'ulimit -aHS' -s '/bin/bash'
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7583
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 16384
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7583
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Trying to connect to console from localhost:
```dnsdist -c
Fatal error: failed in readn2: Connection reset by peer
```

Please note that:
- 10.211.93.40 is a real IP on that VM
- 10.211.93.11 is a VRRP IP managed by Keepalived
- Selinux is disabled
- Firewalld is stopped

**Comment by pieterlexis** [comment] 2020-03-30 16:37
You did not set an ACL on the console, see the [docs](https://dnsdist.org/reference/config.html?highlight=acl#addConsoleACL)

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2020-03-30 16:37 UTC
