### ISSUE TITLE
Sign supermaster/superslave zone transfers with TSIG

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#656] opened 2013-04-26 11:36 UTC
Add support for signing superslave transfers. Currently, TSIG key is assigned to zone. Because superslave creates zones when notified, it doesn't have any key to check signatures. 

IP-based security is not strong enough, especially when using DNSSEC (superslave then becomes the weak link - attacker could do MITM and put his own zones in authoritative server).

**Comment by reissmann** [comment] 2015-06-14 17:20
This would be a great feature! At the moment, I do not use supermaster/superslave operation as I do not trust IP-based security. 

My setup uses a hidden master holding DNSSEC key material, which transfers the singed zones to the slave servers. At the moment, whenever I want to add a zone, I have to put hands on the slave servers to add the new zone and the TSIG information.

I would love to see this feature in an upcoming release!

**Comment by cmouse** [comment] 2015-06-15 10:03
@reissmann if you can test #2591 would be nice.

**Comment by cmouse** [comment] 2015-06-16 07:46
@reissmann can you try again? it  should work now.

**Comment by reissmann** [comment] 2015-06-16 16:43
I have tested this with a master using the bind backend and a slave using the gmysql backend.

When adding a new zone, it only gets transferred to the slave, if it uses a tsig key the slave knows of. If I get this right, it can be any key configured on the slave. The name of the key then gets added to the domainmetadata table, which means that future zone transfers will only work with this specific key.

**Comment by cmouse** [comment] 2015-06-16 16:52
Yep. Just as intended. Good to hear it worked.

**Comment by reissmann** [comment] 2015-06-16 17:37
Thank you for implementing this :)

**Closed** 2016-01-22 14:54 UTC
Labels: enhancement
