### ISSUE TITLE
PowerDNS recursion fails with specific behaviour

### ISSUE THREAD

**Issue by Jarpse** [PowerDNS/pdns#1708] opened 2014-09-11 10:11 UTC
Couldn't quickly find another issue on this subject (undoubtedly there is though, from what I've seen from  #powerdns @ oftc)

Running pDNS auth 3.4 with bind for recursion. IP's allowed for recursion are configured.

Now, when I try recursion:
`dig @dnsbox aspmx.l.google.com`, It'll resolve the entries for me.

When an non-authorized IP tries to recursion at this box, it doesn't get a reply (WARNING: recursion requested but not available). But, after this happens, the box won't resolve the entry for allowed IP's as well. After restarting pDNS or issuing pdns_control purge, it'll resolve the entry again, until a non-allowed client tries to resolve at this box. Then it gives out blanks again.

We've sort-of temp fixed it by lowering the cache-ttl so that it'll quickly restore itself after such an non-allowed recursion has happened, but this is not an optimal situation.

Took us a while to figure this out. Any chance 3.3.1 *not* having this behaviour?

**Comment by Habbie** [comment] 2015-12-15 10:59
Duplicate of at least two other tickets. Closing.

**Closed by Habbie** 2015-12-15 10:59 UTC
Labels: auth, defect
