### ISSUE TITLE
Duplicate zone-entrys in 3.4.5 (json experimental api)

### ISSUE THREAD

**Issue by EugenMayer** [PowerDNS/pdns#2366] opened 2015-03-20 12:27 UTC
Every zone is listed twice in the json rest api: 

postgresql database:
http://pastie.org/10041828

zones:
http://pastie.org/10041833
http://pastie.org/private/sund50s0qzhqnnuo4x5upw

iam using the current debian build, 3.4.5

I could not find anything about this in the closed nor opened issues - thats why iam opening this

**Comment by zeha** [comment] 2015-03-25 07:49
Please include your database contents.

**Comment by EugenMayer** [comment] 2015-03-25 07:51
The whole db? I cant - this is internal, i cannot just publish those. Is there any specific thing you are looking for?

**Comment by zeha** [comment] 2015-03-25 07:55
It's hard to know what to look for without seeing it in this case -- a pure guess would include interesting SOA, NS records and duplicates or other weird entries in the domains table. 
If you can't publish the DB, please try to reduce it's contents until the issue no longer manifests itself.

**Comment by EugenMayer** [comment] 2015-06-22 07:24
hello @zeha ... upgraded to 3.4.5 today, no help. So here are my observations:
 - using the exp api, all zones are there 2 times, with the same fields (same id and serial)
 - all entrys in records habe prio:0,change_date=(today unix), disabled=false,ordername,true,auth:true and are all type A except the SOA entries
 - i am using postgreqsl
 - all DBs except records, domains are EMPTY - is that an issue, e.g. supermaster?
 - if i use nsedit to create a zone, its listed twice also

Some DB extracts

RECORDS: all soa
     id  | domain_id |          name           | type |                        content                        |  ttl  | prio | change_date | disabled | ordername | auth
     115 |        15 | o.kw.lan                | SOA  | ns1.kw.lan kw.lan 2015022700 28800 7200 604800 86400  | 86400 |    0 |  1434956344 | f        | true      | t
     107 |        14 | dev.kw.lan              | SOA  | ns1.kw.lan kw.lan 2015022800 28800 7200 604800 86400  | 86400 |    0 |  1434956344 | f        | true      | t
     126 |        17 | bacula.kw.lan           | SOA  | ns1.kw.lan kw.lan 2015022800 28800 7200 604800 86400  | 86400 |    0 |  1434956344 | f        | true      | t
       8 |         8 | kw.lan                  | SOA  | ns1.kw.lan kw.lan 2015030500 28800  7200 604800 86400  | 86400 |    0 |  1434956344 | f        | true      | t
      38 |        11 | maintain.kw.de | SOA  | ns1.kw.lan kw.lan 2015031000 28800 7200 604800 86400  | 86400 |    0 |  1434956344 | f        | true      | t
      154 |        18 | dev.kw.de      | SOA  | ns1.kw.lan kw.lan 2012040701 28800 7200 604800 86400  | 86400 |    0 |  1434956344 | f        | true      | t

RECORDS: A (Some)

 id | domain_id |               name               | type |   content   |  ttl  | prio | change_date | disabled | ordername | auth
----+-----------+----------------------------------+------+-------------+-------+------+-------------+----------+-----------+------
 33 |        11 | eugenmbp.maintain.kw.de | A    | 10.66.0.102 | 86400 |    0 |  1434956344 | f        | true      | t
 43 |        11 | evlks.maintain.kw.de    | A    | 10.66.0.104 | 86400 |    0 |  1434956344 | f        | true      | t
 59 |        15 | sw.o.kw.lan                      | A    | 10.88.0.102 | 86400 |    0 |  1434956344 | f        | true      | t

domains:

 id |          name           | master | last_check |  type  | notified_serial | account
----+-------------------------+--------+------------+--------+-----------------+---------
  8 | kw.lan                  |        |            | NATIVE |                 |
 11 | maintain.kw.de |        |            | NATIVE |                 |
 14 | dev.kw.lan              |        |            | NATIVE |                 |
 15 | o.kw.lan                |        |            | NATIVE |                 |
 17 | bacula.kw.lan           |        |            | NATIVE |                 |
 18 | dev.kw.de      |        |            | NATIVE |                 |

**Comment by EugenMayer** [comment] 2015-06-22 07:26
also, those is an example of the exp api for one zone listed twice:

  [{
    "id": "o.kw.lan.",
    "url": "/servers/localhost/zones/o.kw.lan.",
    "name": "o.kw.lan",
    "kind": "Native",
    "dnssec": false,
    "account": "",
    "masters": [],
    "serial": 2015022700,
    "notified_serial": 0,
    "last_check": 0
  },

  {
    "id": "o.kw.lan.",
    "url": "/servers/localhost/zones/o.kw.lan.",
    "name": "o.kw.lan",
    "kind": "Native",
    "dnssec": false,
    "account": "",
    "masters": [],
    "serial": 2015022700,
    "notified_serial": 0,
    "last_check": 0
  }]

**Comment by EugenMayer** [comment] 2015-06-30 06:43
anything needed here to work on this issue?

**Comment by EugenMayer** [comment] 2015-07-12 18:56
I could really need help on this, iam pretty clueless right now

**Comment by zeha** [comment] 2015-07-13 20:42
After manually typing all the data you've provided into a psql shell, I get the following response for a `GET http://127.0.0.1:8082/servers/localhost/zones` 

```json
[
  {
    "id": "kw.lan.",
    "url": "/servers/localhost/zones/kw.lan.",
    "name": "kw.lan",
    "kind": "Native",
    "dnssec": false,
    "account": "",
    "masters": [],
    "serial": 0,
    "notified_serial": 0,
    "last_check": 0
  },
  {
    "id": "maintain.kw.de.",
    "url": "/servers/localhost/zones/maintain.kw.de.",
    "name": "maintain.kw.de",
    "kind": "Native",
    "dnssec": false,
    "account": "",
    "masters": [],
    "serial": 2015022700,
    "notified_serial": 0,
    "last_check": 0
  },
  {
    "id": "dev.kw.lan.",
    "url": "/servers/localhost/zones/dev.kw.lan.",
    "name": "dev.kw.lan",
    "kind": "Native",
    "dnssec": false,
    "account": "",
    "masters": [],
    "serial": 2015022700,
    "notified_serial": 0,
    "last_check": 0
  },
  {
    "id": "o.kw.lan.",
    "url": "/servers/localhost/zones/o.kw.lan.",
    "name": "o.kw.lan",
    "kind": "Native",
    "dnssec": false,
    "account": "",
    "masters": [],
    "serial": 2015022700,
    "notified_serial": 0,
    "last_check": 0
  },
  {
    "id": "bacula.kw.lan.",
    "url": "/servers/localhost/zones/bacula.kw.lan.",
    "name": "bacula.kw.lan",
    "kind": "Native",
    "dnssec": false,
    "account": "",
    "masters": [],
    "serial": 2015022700,
    "notified_serial": 0,
    "last_check": 0
  },
  {
    "id": "dev.kw.de.",
    "url": "/servers/localhost/zones/dev.kw.de.",
    "name": "dev.kw.de",
    "kind": "Native",
    "dnssec": false,
    "account": "",
    "masters": [],
    "serial": 2015022700,
    "notified_serial": 0,
    "last_check": 0
  }
]
```

* PowerDNS/pdns@1b46799
* postgresql 9.4.4 from brew
* OS X 10.10

pdns_server command line was: `./pdns/pdns_server -- --daemon=no --local-port=5301 --socket-dir=./ --module-dir=../regression-tests/modules --no-shuffle --launch=gpgsql --gpgsql-dnssec --send-root-referral --experimental-dnsupdate=yes --cache-ttl=0 --no-config --gpgsql-dbname=pdns --experimental-json-interface=yes --webserver=yes --webserver-port=8082 --webserver-address=127.0.0.1 --experimental-api-key=changeme`

Used Data:

```
\i modules/gpgsqlbackend/schema.pgsql.sql 
insert into domains (id, name, type) values (8, 'kw.lan', 'NATIVE');
insert into domains (id, name, type) values (11, 'maintain.kw.de', 'NATIVE');
insert into domains (id, name, type) values (14, 'dev.kw.lan', 'NATIVE');
insert into domains (id, name, type) values (15, 'o.kw.lan', 'NATIVE');
insert into domains (id, name, type) values (17, 'bacula.kw.lan', 'NATIVE');
insert into domains (id, name, type) values (18, 'dev.kw.de', 'NATIVE');
insert into records (id, domain_id, name, type, content, ttl, prio, change_date, disabled, ordername, auth) values (115, 15, 'o.kw.lan', 'SOA', 'ns1.kw.lan kw.lan 2015022700 28800 7200 604800 86400', 86400, 0, 1434956344, f, true, t);
insert into records (id, domain_id, name, type, content, ttl, prio, change_date, disabled, ordername, auth) values (115, 15, 'o.kw.lan', 'SOA', 'ns1.kw.lan kw.lan 2015022700 28800 7200 604800 86400', 86400, 0, 1434956344, false, true, true);
insert into records (id, domain_id, name, type, content, ttl, prio, change_date, disabled, ordername, auth) values (107, 14, 'dev.kw.lan', 'SOA', 'ns1.kw.lan kw.lan 2015022700 28800 7200 604800 86400', 86400, 0, 1434956344, false, true, true);
insert into records (id, domain_id, name, type, content, ttl, prio, change_date, disabled, ordername, auth) values (126, 17, 'bacula.kw.lan', 'SOA', 'ns1.kw.lan kw.lan 2015022700 28800 7200 604800 86400', 86400, 0, 1434956344, false, true, true);
insert into records (id, domain_id, name, type, content, ttl, prio, change_date, disabled, ordername, auth) values (8, 8, 'bacula.kw.lan', 'SOA', 'ns1.kw.lan kw.lan 2015022700 28800 7200 604800 86400', 86400, 0, 1434956344, false, true, true);
insert into records (id, domain_id, name, type, content, ttl, prio, change_date, disabled, ordername, auth) values (38, 11, 'maintain.kw.de', 'SOA', 'ns1.kw.lan kw.lan 2015022700 28800 7200 604800 86400', 86400, 0, 1434956344, false, true, true);
insert into records (id, domain_id, name, type, content, ttl, prio, change_date, disabled, ordername, auth) values (154, 18, 'dev.kw.de', 'SOA', 'ns1.kw.lan kw.lan 2015022700 28800 7200 604800 86400', 86400, 0, 1434956344, false, true, true);
insert into records (id, domain_id, name, type, content, ttl, prio, change_date, disabled, ordername, auth) values (33, 11, 'eugenmbp.maintain.kw.de', 'A', '10.66.0.102', 86400, 0, 1434956344, false, true, true);
insert into records (id, domain_id, name, type, content, ttl, prio, change_date, disabled, ordername, auth) values (43, 11, 'evlks.maintain.kw.de', 'A', '10.66.0.104', 86400, 0, 1434956344, false, true, true);
insert into records (id, domain_id, name, type, content, ttl, prio, change_date, disabled, ordername, auth) values (59, 15, 'sw.o.kw.lan', 'A', '10.88.0.102', 86400, 0, 1434956344, false, true, true);
```

**Comment by zeha** [comment] 2015-07-13 20:51
Basically, I can't reproduce this. More information may help (see my post for some of the things that may be relevant). Also, does `pdnssec check-zone` report anything?

If you can't provide a reproducible test case, you could join the PowerDNS IRC Channel, see https://www.powerdns.com/opensource.html

**Comment by EugenMayer** [comment] 2015-07-22 09:27
Hello zeha, sorry for my late response, i oversaw the github notification.

As an example, i check kw.lan:

pdnssec check-zone kw.lan
[Error] Following record had a problem: kw.lan IN SOA ns1.kw.lan kw.lan 2015030500 28800 7200 604800 86400
[Error] Error was: All data was not consumed
[Error] No NS record at zone apex in zone 'kw.lan'
Checked 57 records of 'kw.lan', 2 errors, 0 warnings.

I asked in the channel already, but had now answers.

Can you identify the issue here? If you need anything else, let me know.

**Comment by zeha** [comment] 2016-03-08 00:23
No; for now I think this is a support issue more than anything else. Please come to IRC or post to the lists, closing this here in the bug tracker.

**Closed by zeha** 2016-03-08 00:23 UTC
Labels: auth, web
