### ISSUE TITLE
Tracing of recursor actions should include RPZ lookups

### ISSUE THREAD

**Issue by tih** [PowerDNS/pdns#8742] opened 2020-01-25 14:12 UTC
- Program: Recursor
 - Issue type: Feature request

### Short description

When the recursor logs a detailed trace of its actions in handling a question, because it's been given e.g. a 'rec_control trace-regex' command, if the request matches an entry in a loaded RPZ zone, it will respond as specified in the RPZ zone, but without any trace logging of this. Since tracing is used when one is trying to figure out a problem, this can be confusing. It would be helpful if the use of the RPZ zone were properly logged in the trace output.

### Usecase

In my particular case, I was trying to figure out why a certain query kept coming up with a NXDOMAIN response. Turning on trace logging gave my nothing useful - this is the complete trace for a (failing) query, for which NXDOMAIN was returned:

Jan 25 09:12:50 barsoom pdns_recursor[22994]: 1 [1/1] TCP question for 'postgresqlco.nf|A' from 127.0.0.1:58794
Jan 25 09:12:50 barsoom pdns_recursor[22994]: Starting validation of answer to postgresqlco.nf|A for 127.0.0.1:58794

By and by, I discovered that the reason was an erroneous "*.nf CNAME ." in my RPZ zone.

### Description

Resolving the above problem would have been quicker and easier if the recursor had told me, in the trace log, that it found a match in the RPZ zone, and how it used that data. Therefore, I would like to see trace logging extended to include this.

**Comment by phonedph1** [comment] 2020-01-25 15:02
Related: #6277

**Comment by Habbie** [comment] 2020-01-25 15:04
Duplicate of, I'd even say..

**Comment by omoerbeek** [comment] 2020-08-31 12:50
#9376 should fix this

**Closed by omoerbeek** 2020-08-31 12:50 UTC
Labels: feature request, rec
