### ISSUE TITLE
Where is the log? How to build a master-slave mode?

### ISSUE THREAD

**Issue by jiangby123** [PowerDNS/pdns#7513] opened 2019-02-22 08:05 UTC
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report/Feature request 

### Environment

 - Operating system: 
 - Software version: 
 - Software source: 

### Steps to reproduce

1. 
2. 
3. 

### Description

I installed pdns-4.0 with yum. After running it, what is his running log? And how is his master-slave mode built?

**Comment by pieterlexis** [comment] 2019-02-22 08:08
We spent a lot of time on our [documentation](https://doc.powerdns.com/authoritative/modes-of-operation.html#master-operation).

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2019-02-22 08:08 UTC
