### ISSUE TITLE
Duplcate log pdns_recursor

### ISSUE THREAD

**Issue by xbgmsharp** [PowerDNS/pdns#3296] opened 2016-01-24 17:08 UTC
On a fresh install of on Debian 8 Jessie with pdns_recursor . I have the following message double message in my syslog. The issue does not only apply to stats but to any message
1 is in a standard log entry format, the other one not.

```
Jan 24 18:00:25 gate pdns_recursor[655]: stats: 701 questions, 2123 cache entries, 308 negative entries, 4% cache hits
Jan 24 18:00:25 gate pdns_recursor[655]: Jan 24 18:00:25 stats: 701 questions, 2123 cache entries, 308 negative entries, 4% cache hits
Jan 24 18:00:25 gate pdns_recursor[655]: stats: throttle map: 0, ns speeds: 1244
Jan 24 18:00:25 gate pdns_recursor[655]: stats: outpacket/query ratio 201%, 0% throttled, 0 no-delegation drops
Jan 24 18:00:25 gate pdns_recursor[655]: stats: 15 outgoing tcp connections, 1 queries running, 23 outgoing timeouts
Jan 24 18:00:25 gate pdns_recursor[655]: stats: 555 packet cache entries, 8% packet cache hits
Jan 24 18:00:25 gate pdns_recursor[655]: stats: 0 qps (average over 1913 seconds)
Jan 24 18:00:25 gate pdns_recursor[655]: Jan 24 18:00:25 stats: throttle map: 0, ns speeds: 1244
Jan 24 18:00:25 gate pdns_recursor[655]: Jan 24 18:00:25 stats: outpacket/query ratio 201%, 0% throttled, 0 no-delegation drops
Jan 24 18:00:25 gate pdns_recursor[655]: Jan 24 18:00:25 stats: 15 outgoing tcp connections, 1 queries running, 23 outgoing timeouts
Jan 24 18:00:25 gate pdns_recursor[655]: Jan 24 18:00:25 stats: 555 packet cache entries, 8% packet cache hits
Jan 24 18:00:25 gate pdns_recursor[655]: Jan 24 18:00:25 stats: 0 qps (average over 1913 seconds)
```

or

```
Jan 24 16:26:12 gate pdns_recursor[521]: Jan 24 16:26:12 Refreshed . records
Jan 24 16:26:12 gate pdns_recursor[521]: Refreshed . records
```

**Comment by Habbie** [comment] 2016-01-25 10:03
Duplicate of #1607 which also has a workaround [in a comment](https://github.com/PowerDNS/pdns/issues/1607#issuecomment-170005646). Closing!

**Closed by Habbie** 2016-01-25 10:03 UTC
