### ISSUE TITLE
supermaster with multiple ip addresses (IPv4 + IPv6) leads to duplicate SOA entries

### ISSUE THREAD

**Issue by stbuehler** [PowerDNS/pdns#2413] opened 2015-04-05 22:06 UTC
Version: packages from debian jessie 3.4.1-4

I added IPv4 and IPv6 addresses in the supermaster tables as separate entries; then I click "Notify slaves" in pdnscontrol on the master for a zone that is not present yet on the slave.

With a high probability pdnscontrol on the slave will show the zone twice, and show each record (especially SOA) in the zone twice. There is only one entry in the domains table, but the records table has duplicate entries (for the same domain id).

Having both addresses in the supermaster table is needed to have both addresses set as "master" addresses for the slave zones (this part works).

Update: an explicit `pdns_control retrieve $zone` on the slave fixes the issue.

**Comment by mind04** [comment] 2015-04-14 12:15
Duplicate of #1502 (or very closely related)

**Comment by Habbie** [comment] 2017-03-07 11:55
Probably fixed as #1502 was fixed. Please let us know if you disagree.

**Closed by Habbie** 2017-03-07 11:55 UTC
Labels: auth, defect

**Comment by stbuehler** [comment] 2017-03-14 07:52
I deleted a zone 3 times, and each following notify from the supermaster worked as it should - looking good (version 4.0.3).

**Comment by Habbie** [comment] 2017-03-14 08:14
Thanks for checking!
