### ISSUE TITLE
DNS stops after time?

### ISSUE THREAD

**Issue by kvanleeuwen** [PowerDNS/pdns#8055] opened 2019-07-10 14:54 UTC
Hello,

After one hour the powerdns crashes:
Backend reported condition which prevented lookup (GSQLBackend lookup query: Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?) sending out servfail

Backend reported condition which prevented lookup (GSQLBackend lookup query: Could not execute mysql statement: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?: Lost connection to MySQL server during query) sending out servfail

Does anyone have a clue?

Regards,
Kevin

**Comment by pieterlexis** [comment] 2019-07-10 14:54
I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information, version numbers, and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2019-07-10 14:54 UTC
