### ISSUE TITLE
dnsdist: UUIDs not working as intended

### ISSUE THREAD

**Issue by erypolovina** [PowerDNS/pdns#11474] opened 2022-03-28 23:49 UTC
- Program: dnsdist 
 - Issue type: Bug report

### Short description

I would like to use the UUID feature to get and remove the servers but the feature is not working as expected as it does not consistently find the server.
Additionally, it would be very helpful if the uuid is also shown in the webserver API as it is only available through the console.

### Environment

 - Operating system: CentOS 7
 - Software version: v1.6.0 and v1.7.0
 - Software source: Operating system repository

### Steps to reproduce

1. Open the dnsdist console `$ dnsdist -c`
2. Show the servers using `> showServers({showUUIDs=true})`
3. Copy one of the UUIDs from the output and run `> getServer("$UUID")` ($UUID is the uuid that was copied)
    a. Notice that some servers are fetched correctly and others are not 
4. Repeat step 3 for all the servers and notice getting/removing the server by uuid is not always consistent

### Expected behaviour

The result should be the same as when getting/removing the server  by a regular number id 
ex. If the result is 
```
#   UUID
1   4c8060b0-6490-4bbb-98c3-1ea94964558
```
Then `getServer(1)` and `getServer("4c8060b0-6490-4bbb-98c3-1ea94964558")` should return the same thing

### Actual behaviour

`getServer()` (and `rmServer()`) command does not alway work when getting the server by UUID

**Comment by hhoffstaette** [comment] 2022-05-03 13:35
This made me curious, but just like Remi I can access all servers via UUID consistently and without issue. Running 1.7.1.

**Comment by erypolovina** [comment] 2022-05-25 18:34
Hi @rgacogne 
> I created a large number of backends, each of them getting a random UUID, and called getServer(<uuid>):setUp() in a loop.

Can you let me know how you called the getServer command in a loop? Was this in the dnsdist console? Also, what environment are you running/how is dnsdist installed for you? It is still not working in my end so maybe it could be the binary from centos? 

We are adding the servers as I sent in the last comment. Are you also adding them in a similar way?

**Comment by rgacogne** [comment] 2023-01-09 14:30
Closing since we could not reproduce the issue, please let me know if this is still an issue!

**Closed by rgacogne** 2023-01-09 14:30 UTC
Labels: defect, dnsdist
