### ISSUE TITLE
API endpoint /servers/{server_id}/zones/{zone_id}/check should exist but when calling there is an error and the endpoint cannot be found in the source code.

### ISSUE THREAD

**Issue by ArnoSen** [PowerDNS/pdns#8475] opened 2019-10-28 12:55 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description

GET /servers/{server_id}/zones/{zone_id}/check is a documented endpoint in https://doc.powerdns.com/authoritative/http-api/zone.html. However, I reviewed the sourcecode at I cannot find that this is implemented in code. 

In all the versions of wc-auth.cc that I verified, this path is not registered.

### Environment
N/A

### Steps to reproduce
Call the 'check' endpoint as described in https://doc.powerdns.com/authoritative/http-api/zone.html.

### Expected behaviour
That the endpoint works. 
I am running 4.1.5 and got an error when calling the `check` endpoint. I checked if a newer version had that endpoint and i checked a lost of branches and tags, but the endpoint was not there.

### Actual behaviour
Calling the check endpoint resulted in: 
'{"error": "Could not find domain '<testdomain>./check.'"}'

**Comment by mnordhoff** [comment] 2019-10-28 19:49
This seems to be a duplicate of #6865.

**Closed** 2022-11-28 14:47 UTC
Labels: auth, docs, defect
