### ISSUE TITLE
Slave doesn't initiate zone transfer with slave-cycle-interval

### ISSUE THREAD

**Issue by berkutta** [PowerDNS/pdns#4976] opened 2017-02-06 09:01 UTC
- Program: GSQLBackend 
 

### Short description

I'm trying to do Zone Transfers from a PDNS Master to a PDNS Slave. But it fails with an MySQL Issue. The PDNS Master & Slave have an Database which got setup with the standard schema. notified_serial is an int.

### Environment

 - Operating system: Ubuntu Xenial
 - Software version: 4.0.0-alpha2
 - Software source: PDNS Repository

Set the pdns as slave=yes and slave-cycle-interval=60

### Expected behaviour
Slave should start to transfer the zone from the master to the slave

### Actual behaviour

It doesn't to anything. It say's no unfresh slave domains (seems ok after startup) but it doesn't try to initiate a zone transfer after 60s.
```
Feb 06 09:45:31 public-2 pdns[38970]: PowerDNS Authoritative Server 4.0.0-alpha2 (C) 2001-2016 PowerDNS.COM BV
Feb 06 09:45:31 public-2 pdns[38970]: Using 64-bits mode. Built using gcc 5.3.1 20160330.
Feb 06 09:45:31 public-2 pdns[38970]: PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according ...version 2.
Feb 06 09:45:31 public-2 pdns[38970]: Creating backend connection for TCP
Feb 06 09:45:31 public-2 pdns[38970]: Master/slave communicator launching
Feb 06 09:45:31 public-2 pdns[38970]: [bindbackend] Parsing 0 domain(s), will report when done
Feb 06 09:45:31 public-2 pdns[38970]: [bindbackend] Done parsing domains, 0 rejected, 0 new, 0 removed
Feb 06 09:45:31 public-2 pdns[38970]: About to create 3 backend threads for UDP
Feb 06 09:45:31 public-2 pdns[38970]: No new unfresh slave domains, 0 queued for AXFR already
Feb 06 09:45:31 public-2 pdns[38970]: Done launching threads, ready to distribute questions
```

**Comment by pieterlexis** [comment] 2017-02-06 09:31
> Feb 06 09:45:31 public-2 pdns[38970]: [bindbackend] Done parsing domains, 0 rejected, 0 new, 0 removed

It looks like you are not starting the mysql backend, but only the BIND backend without configuration. Please verify that `launch=gmysql` is set in your pdns.conf. (or in one of the files in /etc/powerdns/pdns.d). If you intend to use the BIND backend on the slave, you'll need to add slave zones in the file pointed to by `bind-config`.

When using the gmysql backend, ensure that the domains you want to slave are in the `domains` table with type `SLAVE` (see the [docs on SQL slave operation](https://doc.powerdns.com/md/authoritative/backend-generic-sql/#slave-operation).

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information to the [pdns-users](https://mailman.powerdns.com/mailman/listinfo/pdns-users) mailinglist, or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2017-02-06 09:31 UTC
