### ISSUE TITLE
PowerDNS Auth server fails to start if config has a "notify" directive with custom port

### ISSUE THREAD

**Issue by ehudkaldor** [PowerDNS/pdns#6965] opened 2018-09-12 19:51 UTC
- Program: Authoritative, Recursor
 - Issue type: Bug report

### Short description
cannot change notify ports between master and slave(s)

### Environment

 - Operating system: Centos 7.4
 - Software version: 4.10
 - Software source: PowerDNS repository

### Steps to reproduce
1. add a custom port to any "notify" directive in /etc/pdns/pdns.conf, either from master (also-notify=192.168.1.3:5300, only-notify=192.168.1.3:5300, allow-notify-from=192.168.1.3:5300)
2. start service and watch it fail

### Expected behaviour
server should start and notify over custom port

### Actual behaviour
PowerDNS service fails to start

**Comment by pieterlexis** [comment] 2018-09-12 20:17
From the docs:

> only-notify
>    IP Ranges, separated by commas or whitespace
> also-notify
>    IP addresses, separated by commas
> allow-notify-from
>    IP ranges, separated by commas

only also-notify can have optional ports, the rest are netmasks (like 192.0.2.1/32)

**Comment by ehudkaldor** [comment] 2018-09-12 20:38
> From the docs:
> 
> > only-notify
> > IP Ranges, separated by commas or whitespace
> > also-notify
> > IP addresses, separated by commas
> > allow-notify-from
> > IP ranges, separated by commas
> 
> only also-notify can have optional ports, the rest are netmasks (like 192.0.2.1/32)

I am running both the auth and recursor on the same machine, and as suggested by PowerDNS, the recursor is listening on port 53, and the auth on port 5300. how do you manage notification under this scenario?

**Comment by aj-gh** [comment] 2018-09-12 23:09
Why would you need the port in "only-notify" or "allow-notify-from" - you have it in "also-notify"?

**Comment by pieterlexis** [comment] 2018-09-13 07:14
> I am running both the auth and recursor on the same machine, and as suggested by PowerDNS, the recursor is listening on port 53, and the auth on port 5300. how do you manage notification under this scenario?

In [the docs on recursion with the auth](https://doc.powerdns.com/authoritative/guides/recursion.html), we recommend using [dnsdist](http://dnsdist.org), it can steer these messages [to the right process](https://dnsdist.org/advanced/axfr.html).

Closing as this is not a bug but a support request. Please take this to the [pdns-users mailinglist](https://mailman.powerdns.com).

**Closed by pieterlexis** 2018-09-13 07:14 UTC
