### ISSUE TITLE
CNAME loops return SERVFAIL

### ISSUE THREAD

**Issue by kjette** [PowerDNS/pdns#4307] opened 2016-08-11 14:48 UTC
Thanks to: ietf-dane@dukhovni for the report.

I think that the authoritative server needs to just return 
the CNAME data it has (without chasing the CNAME) when the target 
of the CNAME does not exist or loops. This is what the secondaries 
to, and the primary should act the same.

Hashes:

```
q6d7nlmm7hj224qvb6lpmg6cpln6dso0. doesnotexist.dbdo.se 
ioibg7vnme250daecms1319sphul4jmu. *.dbdo.se 
vg23qt8s9k87afurdic9pfp2cudf886m. dbdo.se
```

Answers:

```
@ns6.binero.se.[156.154.67.59] 
; <<>> DiG 9.10.3-P4 <<>> +dnssec +noall +cmd +comment +qu +ans +auth +nocl +nottl +nosplit +norecur -t a doesnotexist.dbdo.se @156.154.67.59 
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25267 
;; flags: qr aa; QUERY: 1, ANSWER: 2, AUTHORITY: 4, ADDITIONAL: 1 
;doesnotexist.dbdo.se. IN A 
doesnotexist.dbdo.se. CNAME doesnotexist.dbdo.se. 
doesnotexist.dbdo.se. RRSIG CNAME 8 2 7200 20160825000000 20160804000000 34296 dbdo.se. 
ioibg7vnme250daecms1319sphul4jmu.dbdo.se. NSEC3 1 0 1 AB VG23QT8S9K87AFURDIC9PFP2CUDF886M CNAME RRSIG 
vg23qt8s9k87afurdic9pfp2cudf886m.dbdo.se. NSEC3 1 0 1 AB 3F8EGOT7HUPFFDVJ3S9EV18VCK5C9KNJ A NS SOA RRSIG DNSKEY NSEC3PARAM 
ioibg7vnme250daecms1319sphul4jmu.dbdo.se. RRSIG NSEC3 8 3 3600 20160825000000 20160804000000 34296 dbdo.se. 
vg23qt8s9k87afurdic9pfp2cudf886m.dbdo.se. RRSIG NSEC3 8 3 3600 20160825000000 20160804000000 34296 dbdo.se.
```

```
@ns7.binero.se.[195.74.39.30] 
; <<>> DiG 9.10.3-P4 <<>> +dnssec +noall +cmd +comment +qu +ans +auth +nocl +nottl +nosplit +norecur -t a doesnotexist.dbdo.se @195.74.39.30 
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 6939 
;; flags: qr aa; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1 
;doesnotexist.dbdo.se. IN A
```

**Comment by Habbie** [comment] 2016-08-11 14:58
If anybody has authoritative references, or information on what different implementations do (besides your secondary which I understand is UltraDNS), that would be helpful here.

**Comment by kjette** [comment] 2016-08-12 06:39
There's an interesting closely related thread at:

https://www.ietf.org/mail-archive/web/namedroppers/current/thrd8.html#06284

though it is not exactly the same... On my BIND authoritative server, not 
surprisingly in agreement with Paul Vixie's position, an in-zone CNAME that 
points to a non-existent target yields NXDOMAIN along with the CNAME:

; <<>> DiG 9.10.3-P4 <<>> -t a +norecur +dnssec +noall +comment +cmd +ans +nottl +nocl +nosplit bogus.msmuxy.org @mournblade.imrryr.org 
;; global options: +cmd 
;; Got answer: 
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 8952 
;; flags: qr aa; QUERY: 1, ANSWER: 2, AUTHORITY: 6, ADDITIONAL: 1

;; OPT PSEUDOSECTION: 
; EDNS: version: 0, flags: do; udp: 4096 
;; ANSWER SECTION: 
bogus.msmuxy.org. CNAME morebogus.msmuxy.org. 
bogus.msmuxy.org. RRSIG CNAME 8 3 3600 20160826021344 20160812011344 37851 msmuxy.org. J7lGFWABj6mojr2iVy9cLoURV9ojlQ8nGdK0x5cWCDUTRoMgPKW8EJbplnX5DgW8bo+gm/UZQb6d+pPxmSkDo+zG78YOXRf+w3Eul6OYMHZqSUZ5nSZd6lWEa49KmJAxf5FDmHRgOjIbHDESNihx07QEUqHbihZZPWq1ULE/1qM=

While a self-referential loop returns NOERROR:

; <<>> DiG 9.10.3-P4 <<>> -t a +norecur +dnssec +noall +comment +cmd +ans +nottl +nocl +nosplit loop.msmuxy.org @mournblade.imrryr.org 
;; global options: +cmd 
;; Got answer: 
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9274 
;; flags: qr aa; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION: 
; EDNS: version: 0, flags: do; udp: 4096 
;; ANSWER SECTION: 
loop.msmuxy.org. CNAME loop.msmuxy.org. 
loop.msmuxy.org. RRSIG CNAME 8 3 3600 20160826022020 20160812012020 37851 msmuxy.org. n88sseoXrsCO30NTb1SRf0jG3nUZf5ByoxO25wIvaOWmcKOuJRBVwTSduE07O7Emg3YBkHTnCTxnFrIU3kL5SHCkZYbod6lFdfKAEyaNfj3R65hwsNmMyXorkCOZAYJuybojoxwOKjcLGmEE8DI17jgCsMHQ3xmruV1BrQperHA=

As does a wildcard loop (after I add the wildcard last):

; <<>> DiG 9.10.3-P4 <<>> -t a +norecur +dnssec +noall +comment +cmd +ans +nottl +nocl +nosplit madeupname.msmuxy.org @mournblade.imrryr.org 
;; global options: +cmd 
;; Got answer: 
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24923 
;; flags: qr aa; QUERY: 1, ANSWER: 4, AUTHORITY: 4, ADDITIONAL: 1

;; OPT PSEUDOSECTION: 
; EDNS: version: 0, flags: do; udp: 4096 
;; ANSWER SECTION: 
madeupname.msmuxy.org. CNAME wildloop.msmuxy.org. 
madeupname.msmuxy.org. RRSIG CNAME 8 2 3600 20160826022020 20160812012020 37851 msmuxy.org. MJ9NVamBcCvI+5aoGFa3Sp9tTzVj8cEzcQQhLLBnydP6ef409cpHgA9Jvtj43v2h0DjfHOlff0ZQIgYciSLKa1HlJ0kh6sqdgoPoVJmWUpfGFtKBznF3qA++juiImA/BN7JbKZmxkuM8FfR+5u3+ZFrpWelZdCANsHl67rbOFPc= 
wildloop.msmuxy.org. CNAME wildloop.msmuxy.org. 
wildloop.msmuxy.org. RRSIG CNAME 8 2 3600 20160826022020 20160812012020 37851 msmuxy.org. MJ9NVamBcCvI+5aoGFa3Sp9tTzVj8cEzcQQhLLBnydP6ef409cpHgA9Jvtj43v2h0DjfHOlff0ZQIgYciSLKa1HlJ0kh6sqdgoPoVJmWUpfGFtKBznF3qA++juiImA/BN7JbKZmxkuM8FfR+5u3+ZFrpWelZdCANsHl67rbOFPc=

At the end of that discussion a new draft emerged, which led to this RFC:

https://tools.ietf.org/html/rfc6604#section-3

this says that when a CNAME chain encounters an error, the ultimate RCODE 
must be NXDOMAIN if the target does not exist, or NOERROR if ultimately 
no matching data is found.

With CNAME loops it seems that NOERROR is right, because one never encounters 
a non-existent node.

**Comment by Habbie** [comment] 2016-08-15 17:56
1034 3.6.2 does state 'CNAME chains should be followed and CNAME loops signalled as an error.' 6604 section 3 conveniently ignores the loop situation. I see how 6604 3 can be read to argue for the NOERROR situation, but it's a very weak position.

Now, what might help is if you have some real life situation that is broken -only because of this behaviour of PowerDNS-. Can you show that?

**Comment by Habbie** [comment] 2016-08-15 18:05
Just for completeness I read the whole thread you referenced; it centers on the question of whether 'A CNAME B' in the same zone, where B does not exist, should return NOERROR or NXDOMAIN. Any relation to the issue in this ticket is basically coincidental, I'm afraid to say.

**Comment by kjette** [comment] 2016-08-16 16:06
Well, when TLSA lookups SERVFAIL, then email can't be delivered to the domain, 
even when the MX host's A/AAAA records exist and don't SERVFAIL. That is, 
given:

example.com. IN MX ? ; ANCOUNT=0 NOERROR 
example.com. IN A 192.0.2.1 
*.example.com. IN CNAME bogus.example.com.

Non-DANE MTAs can deliver email to example.com. DANE MTA can only 
deliver email to example.com if the _25._tcp.example.com. TLSA lookup 
does not SERVFAIL, but with PowerDNS it does! For other DNS servers, 
the response is "ANCOUNT=0 NOERROR" (just as for the missing MX RRs), 
and email delivery works.

I don't have a current example, because the domains I've found to have 
the problem don't receive email, but the issue is there and will break 
other domains I've not found, or that might show up in the future.

**Comment by hlindqvist** [comment] 2016-08-16 16:58
@kjette Regarding practical applicability, will changing this in pdns-auth not just move the SERVFAIL response from the authoritative side to the recursor?
If it truly is wrong, I agree that it should be changed but it seems like it likely will not solve your immediate problem.

BIND appears to behave as you describe both when authoritative and when acting as a recursor but some other recursor implementations do SERVFAIL on this (as RFC1034 said they should).

Some examples that SERVFAIL on bogus.msmuxy.org:
Unbound (1.5.8)
Google Public DNS as well as Verisign Public DNS (whatever their implementations are, tested mostly for fun)

**Comment by Habbie** [comment] 2016-08-16 17:20
Verisign is unbound-based

On August 16, 2016 6:58:10 PM GMT+02:00, "Håkan Lindqvist" <notifications@github.com> wrote:
>@kjette Regarding practical applicability, will changing this in
>pdns-auth not just move the SERVFAIL response from the authoritative
>side to the recursor?
>If it truly is wrong, I agree that it should be changed but it seems
>like it likely will not solve your immediate problem.
>
>BIND appears to behave as you describe both when authoritative and when
>acting as a recursor but some other recursor implementations do
>SERVFAIL on this (as RFC1034 said they should).
>
>Some examples that SERVFAIL on bogus.msmuxy.org:
>Unbound (1.5.8)
>Google Public DNS as well as Verisign Public DNS (whatever their
>implementations are, tested mostly for fun)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/4307#issuecomment-240166475

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by Habbie** [comment] 2016-08-16 17:34
OpenDNS also fails to resolve it (and times out in fact).

**Comment by hlindqvist** [comment] 2016-08-16 17:37
Fwiw, pdns-recursor 4.0.1 (and 3.6.2 as packaged in Debian 8) also SERVFAIL.

**Comment by kjette** [comment] 2016-08-22 09:45
> Regarding practical applicability, will changing this in pdns-auth not 
> just move the SERVFAIL response from the authoritative side to the recursor?

Well, the recursor should return either NXDOMAIN or NODATA, at 
least if the CNAME does not loop, but merely points at a non-existent 
target. With loops, it is perhaps implementation dependent.

> If it truly is wrong, I agree that it should be changed but it seems like 
> it likely will not solve your immediate problem.

Indeed, for loops, the unbound iterator returns SERVFAIL, BIND may 
not. Have not tested that yet.

**Comment by hlindqvist** [comment] 2016-08-22 19:18
@kjette But does pdns auth actually respond with SERVFAIL where "the CNAME does not loop, but merely points at a non-existent target"?

To my understanding this bug report was specifically about the loop scenario (that's what the examples showed) and this other scenario does not appear to be trivially reproducible.

**Comment by Habbie** [comment] 2016-08-23 15:32
Indeed it is starting to look like this ticket holds two conversations - one about the CNAME target not existing, one about the CNAME looping. I have so far assumed the ticket was just about looping. If you also have an issue with how we treat the 'final target does not exist' case, please open yet another ticket for that.

**Comment by Habbie** [comment] 2016-08-23 15:33
I have updated the ticket title to make the topic for this one clearer :)

**Comment by Habbie** [comment] 2017-04-10 10:58
Re-reading this whole thread, I don't see any reason to change this behaviour. Closing this.

**Closed by Habbie** 2017-04-10 10:58 UTC
Labels: auth
