### ISSUE TITLE
PDNS-Recursor: DNS64 SERVFAIL for two-level CNAME chain

### ISSUE THREAD

**Issue by ruffy91** [PowerDNS/pdns#12841] opened 2023-05-18 19:53 UTC
- Program: Recursor
 - Issue type: Bug report

### Short description
DNS64 does not return fake AAAA record for CNAME chain

### Environment

 - Operating system: Ubuntu 22.04.2
 - Software version: 4.8.4
 - Software source: PowerDNS repository

### Steps to reproduce
1. Enable DNS64 using dns64-prefix
2. Try to resolve www.powershellgallery.com using `dig www.powershellgallery.com AAAA`

### Expected behaviour
I expected to receive the fake AAAA record for the A record received after following the CNAME chain, including the CNAME records that lead to this A record

### Actual behaviour
I get SERVFAIL
```
:~# dig www.powershellgallery.com AAAA

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> www.powershellgallery.com AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 30059
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.powershellgallery.com.     IN      AAAA

;; Query time: 0 msec
;; SERVER: ::1#53(::1) (UDP)
;; WHEN: Thu May 18 19:42:38 UTC 2023
;; MSG SIZE  rcvd: 54
```

### Other information
I did not observe this behavior for CNAME records where the chain is only 1 level deep, only for 2 levels or more.
I get the correct response when asking for the A record:
```
dig www.powershellgallery.com A   

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> www.powershellgallery.com A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50502
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.powershellgallery.com.     IN      A

;; ANSWER SECTION:
www.powershellgallery.com. 3592 IN      CNAME   powershellgallerytrafficmanager.trafficmanager.net.
powershellgallerytrafficmanager.trafficmanager.net. 30 IN CNAME psg-prod-eastus.cloudapp.net.
psg-prod-eastus.cloudapp.net. 10 IN     A       172.174.17.44

;; Query time: 171 msec
;; SERVER: ::1#53(::1) (UDP)
;; WHEN: Thu May 18 19:42:35 UTC 2023
;; MSG SIZE  rcvd: 173
```

**Comment by chbruyand** [comment] 2023-09-18 09:49
It looks like the 2 levels chain is covered by our tests https://github.com/PowerDNS/pdns/blob/2a22ce5d1e83d0d7c66d642a395f29e8f3b755e0/regression-tests.recursor-dnssec/test_DNS64.py#L94
I tested with more and it works as expected. Would you maybe have more informations to help us reproduce the issue ?

**Comment by chbruyand** [comment] 2023-09-20 07:41
I also tested with multiple CNAME across 2 different zones and it works as expected. So far I haven't been able to reproduce the issue.

**Comment by omoerbeek** [comment] 2023-11-06 12:22
Closing, please re-open if encountered again.

**Closed by omoerbeek** 2023-11-06 12:22 UTC
Labels: rec, response needed
