### ISSUE TITLE
[Warning] DNSKEY at '1.1.1.in-addr.arpa' in non-presigned zone will mostly be ignored and can cause problems

### ISSUE THREAD

**Issue by fahimipour** [PowerDNS/pdns#8998] opened 2020-04-05 12:41 UTC
I have just finished setting up DNSSEC for my PTR records, after adding the DNSKEY as a record and validating the dnssec records (all verified) I get this warning when I use "pdnsutil check-all-zones"

[Warning] DNSKEY at '1.1.1.in-addr.arpa' in non-presigned zone will mostly be ignored and can cause problems

Is that something I need to be concerned about or is it just a bug in printing the wrong warning?

**Comment by Habbie** [comment] 2020-04-06 07:47
Hello,

1. we have an issue template; you destroyed it; next time, please use the template
2. you do not own 1.1.1.in-addr.arpa, APNIC does
3. this is not a bug report or a feature request

Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Closed by Habbie** 2020-04-06 07:47 UTC
