### ISSUE TITLE
PowerDNS using the wrong TSIG key with two slaves

### ISSUE THREAD

**Issue by knorr3** [PowerDNS/pdns#10637] opened 2021-08-09 11:02 UTC
**PowerDNS version you are using**
PowerDNS Authoritative Server 4.4.1

**What backends you use (gMySQL, BIND etc)**
gMySQL

**If you are using DNSSEC**
No

**Operating system it is running on**
FreeBSD 13

**Where you got the binary from**
https://www.freshports.org/dns/powerdns/

**What is going wrong**
I have a PowerDNS authoritative server as master and two bind instances as slave. Each slave has its own TSIG key.  
The PowerDNS server manages a zone which should be transferred to both slaves. 
The problem is, when I modify the zone and PowerDNS tries to notify both slaves, it only uses the first entry for that domain. 
Let's say I have host A with key A and host B with key B. 

In the domainmetadata table:
```
+----+-----------+-----------------+--------------------+
| id | domain_id | kind            | content            |
+----+-----------+-----------------+--------------------+
| 38 |         4 | TSIG-ALLOW-AXFR | A                  |
| 39 |         4 | TSIG-ALLOW-AXFR | B                  |
+----+-----------+-----------------+--------------------+
```

But when the zone is about to be transferred I get the following:

Master (pdns):
```
Aug  9 11:55:57 pdns[2030]: IXFR-out zone 'example.com', client 'A:17903', transfer initiated with serial 2021080921
Aug  9 11:55:57 pdns[2030]: AXFR-out zone 'example.com', client 'A:17903', transfer initiated
Aug  9 11:55:58 pdns[2030]: Received unsuccessful notification report for 'example.com' from B:53, error: Server Not Authoritative for zone / Not Authorized
Aug  9 11:55:58 pdns[2030]: Received unsuccessful notification report for 'example.com' from B:53, error: Server Not Authoritative for zone / Not Authorized
```

Slave B (bind):
```
09-Aug-2021 11:49:46.932 security: error: client @0x809177f60 pdns#18121: request has invalid signature: TSIG A tsig verify failure (BADKEY)
```

When I first activate key B and then key A, I get the same result but with slave A.
I assume that PDNS just uses the first entry in the database for the domain. 

**What you expect to happen (many problems are in fact wrong expectations, and not bugs)**

It transfers the zone to host A with key A and to host B with key B.

**Comment by Habbie** [comment] 2021-08-09 11:13
it looks like we have no way to specify what you are looking for, so I've marked this as a feature request. I put it in the 'auth-helpneeded' milestone, which means we agree this would be nice to have, but we have not put it on the roadmap for any version.

**Comment by Habbie** [comment] 2021-08-09 11:37
@mind04 pointed out that this is a duplicate of #1550, so I'm closing this one.

**Closed by Habbie** 2021-08-09 11:37 UTC
Labels: auth, feature request

**Comment by klaus-nicat** [comment] 2021-08-09 11:41
Meanwhile you can use the workaround that was introduced for this problem: 
https://doc.powerdns.com/authoritative/settings.html#send-signed-notify  -> set to "no"
