### ISSUE TITLE
rec: Consider ways to handle DS queries for names from export-etc-hosts or forward-zones

### ISSUE THREAD

**Issue by phonedph1** [PowerDNS/pdns#10189] opened 2021-03-18 15:41 UTC
- Program: Recursor
 - Issue type: Bug report

### Short description
`DS` queries can cause issues with names served from `export-etc-hosts` or `forward-zones`. Various combinations of DNSSEC and other options could potentially make this worse (untested).

This demonstrates it for `export-etc-hosts` but the same conditions can occur when using `forward-zones`

### Environment
 - Operating system: Debian 
 - Software version: 4.5.0~alpha3+master.101.g5d9b7eaf6-1pdns.buster
 - Software source: PowerDNS repository

### Steps to reproduce

Setup a minimal environment using `export-etc-hosts`

```
root@slurpee2:/etc/powerdns# systemctl restart pdns-recursor
root@slurpee2:/etc/powerdns# cat recursor.conf 
config-dir=/etc/powerdns
hint-file=/usr/share/dns/root.hints
include-dir=/etc/powerdns/recursor.d
local-address=127.0.0.1
lua-config-file=/etc/powerdns/recursor.lua
quiet=yes
setgid=pdns
setuid=pdns

dnssec=off
root-nx-trust=no
qname-minimization=no
nothing-below-nxdomain=no

export-etc-hosts=yes
root@slurpee2:/etc/powerdns# grep powerdns /etc/hosts
127.0.53.53 powerdns.corp
root@slurpee2:/etc/powerdns# dig ds powerdns.corp @127.0.0.1

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> ds powerdns.corp @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 8133
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;powerdns.corp.			IN	DS

;; AUTHORITY SECTION:
.			3600	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2021031800 1800 900 604800 86400

;; Query time: 85 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Mar 18 09:34:36 MDT 2021
;; MSG SIZE  rcvd: 117

root@slurpee2:/etc/powerdns# dig powerdns.corp @127.0.0.1

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> powerdns.corp @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 28933
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;powerdns.corp.			IN	A

;; AUTHORITY SECTION:
.			3597	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2021031800 1800 900 604800 86400

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Mar 18 09:34:39 MDT 2021
;; MSG SIZE  rcvd: 117

root@slurpee2:/etc/powerdns# 
```

### Expected behaviour
Expect the A record to always be served, and not trashed by the preceding DS query.

### Actual behaviour
See above.

### Other information
We solve this issue by using a `preresolve` hook, however this seems to have hit a few folks so documented here incase there are some thoughts on it.

**Comment by omoerbeek** [comment] 2021-03-30 08:48
An A query:

```
Mar 30 10:46:14 [1] powerdns.corp: Wants NO DNSSEC processing, auth data in query for A
Mar 30 10:46:14 [1] powerdns.corp: No cache hit for 'powerdns.corp|A', trying to find an appropriate NS record
Mar 30 10:46:14 [1] powerdns.corp: Cache consultations done, have 1 NS to contact
Mar 30 10:46:14 [1] powerdns.corp: Domain is out-of-band
Mar 30 10:46:14 [1] powerdns.corp: auth storage has data, zone='powerdns.corp'
Mar 30 10:46:14 [1] powerdns.corp: accept answer 'powerdns.corp|A|127.0.53.53' from 'powerdns.corp' nameservers? ttl=86400, place=1 YES! - This answer was retrieved from the local auth store.
```

A DS query:
```
Mar 30 10:47:27 [1] powerdns.corp: Wants NO DNSSEC processing, auth data in query for DS
Mar 30 10:47:27 [1] powerdns.corp: No cache hit for 'powerdns.corp|DS', trying to find an appropriate NS record
Mar 30 10:47:27 [1] corp: Checking if we have NS in cache for 'corp'
Mar 30 10:47:27 [1] corp: no valid/useful NS in cache for 'corp'
Mar 30 10:47:27 [1] corp: Checking if we have NS in cache for '.'
etc
```

**Comment by rgacogne** [comment] 2021-03-30 09:17
Right, the DS query needs to be sent to the parent zone so the forward doesn't apply. But with both `root-nx-trust=no` and ` nothing-below-nxdomain=no` the result of the DS query should not influence the result of the `A` one, or am I missing something? `dnssec=off` means that we should not be doing `aggressive NSEC caching` either.

**Comment by omoerbeek** [comment] 2021-03-30 09:20
The issue seems to be that the `corp.` NS give an NXDOMAIN leading to the conclusion that the whole domain does not exist. After the DS query:
```
; negcache dump follows
;
powerdns.corp. 3585 IN TYPE0 VIA . ; (Indeterminate)
. 3585 IN SOA a.root-servers.net. nstld.verisign-grs.com. 2021033000 1800 900 604800 86400 ; (Indeterminate)
```

**Comment by omoerbeek** [comment] 2021-03-30 09:29
https://gist.github.com/omoerbeek/275fc10406edc0b05b34b28495b2dbdd

Seems to work, but I'm not sure the condition is correct, though unittests pass.

**Comment by rgacogne** [comment] 2021-03-30 09:32
Ah, right, `nothing-below-nxdomain=no` applies to names below the NXD, but this is the exact same name, I'm not sure we can solve this.

**Comment by rgacogne** [comment] 2021-03-30 09:35
> Seems to work, but I'm not sure the condition is correct, though unittests pass.

So we would be sending the DS query to the forward server? That could work in some cases for forward-recurse, but that does not seem right for the "normal" forward case.

**Comment by omoerbeek** [comment] 2021-03-30 09:41
> > Seems to work, but I'm not sure the condition is correct, though unittests pass.
> 
> So we would be sending the DS query to the forward server? That could work in some cases for forward-recurse, but that does not seem right for the "normal" forward case.

The code in master always chops for any DS query. The diff does: don't chop for auth zones or recursive forwarders. So "regular" forwarders still get chopped. But like I said, double plus tricky stuff.

**Comment by omoerbeek** [comment] 2021-03-30 09:48
BTW, I could not reproduce this with DNSSEC enabled and a local unsigned auth zone (with NTA) as a child of a signed zone.

**Comment by omoerbeek** [comment] 2021-04-06 09:06
I also could not reproduce this with DNSSEC disabled and a forward zone or an auth zone. Investigating what makes the `export-etc-hosts` case different

**Comment by omoerbeek** [comment] 2021-04-06 14:01
Found out the issue happens if the names in the auth or forwarded zones equal the name. 
At first I was forwarding to zone `b.c`, while querying the name `a.b.c`. 

`export-etc-hosts` creates the equivalent of
`authzones=powerdns.corp=zone` with the contents of zone being:
```
powerdns.corp. SOA ...
powerdns.corp. NS localhost.
powerdns.corp A 127.0.53.53
```
And if I create a similar auth or forward zone I'm seeing the issue. This also means that the condition in the gist is not right, as suspected. Though I'm not sure how to solve the issue, a naive attempt (using 
```
if (!isForwardOrAuth(subdomain)) {
  subdomain.chopOff();
}
```

breaks `test_forward_zone_recurse_nord_dnssec`

**Comment by brlumen** [comment] 2021-04-07 13:56
This is exactly what I reported in https://github.com/PowerDNS/pdns/issues/10166

**Comment by brlumen** [comment] 2021-04-07 14:43
Look, I have not looked at the source code, but in the process of researching my problem, I discovered that the recurser does some magic in the process of processing DS requests.
In fact, the recurser should have 2 possible options for processing a DS request:
 1. An internal query generated by the recurser itself, which is required for dnssec validation. And here everything is working fine now;
2. An incoming request from a third-party recurser.
In the second option, the recurser must forward the request to the server to which the request's DS domain is delegated.
After all, the problem arises because of what? The recurser tries to validate the zone, although it is not required to do so in the case of an external request.
After all, a DS request can only be performed by a validating client, which at the moment can only be a client with a recursive function and full dnssec support. We must not interfere with his work.

**Comment by rgacogne** [comment] 2021-04-07 14:59
> After all, the problem arises because of what? The recurser tries to validate the zone, although it is not required to do so in the case of an external request.

Are you sure about that? It seems to me that the recursor is not trying to validate here, since DNSSEC validation has been disabled, but simply to fetch the DS it has been asked for?

> the recurser must forward the request to the server to which the request's DS domain is delegated.

The thing is, DS records are special ones and live in the parent zone, not the child zone so we should not forward the query for the apex of the zone in case of a `forward-zones`. We might be fine with doing that for a `forward-zones-recurse`.

As for internal zones, I am not sure, it's hard to know what everyone would expect to see. 
If the zone does exist in the global DNS tree and is not secure, going to the parent zone for the DS query is fine, answering from the internal one might not if the parent zone is secure.
If the zone does exist and is secure, going to the parent zone should be fine as long as the internal zone is signed. Answering from the internal zone does not seem right.
If the zone does not exist, secure or not we can't go to the parent zone because we would get a NXD and cache it.

So perhaps we should make that configurable, somehow?

**Comment by omoerbeek** [comment] 2021-04-07 17:49
> Are you sure about that? It seems to me that the recursor is not trying to validate here, since DNSSEC validation has been disabled, but simply to fetch the DS it has been asked for?

Right, this PR is about a DS query form a client causing the whole zone go NXDOMAIN.

**Comment by omoerbeek** [comment] 2021-04-09 05:52
I'm going to investigate if `addNTA` and `addTA` will work or can be made to work for this case.

**Comment by omoerbeek** [comment] 2021-04-09 08:02
On master, even with `dnssec=validate` and an NTA for both `powerdns.corp` and `corp`  see the NXDOMAIN for `powerdns.corp` after a `powerdns.corp` `DS` query. This is a surprise to me, I would have expectd the NTA's to handle that.

This also happens with `dnssec=off`.

**Comment by rgacogne** [comment] 2021-04-09 08:05
> This is a surprise to me, I would have expected the NTA's to handle that.

The NTA tells the recursor to stop validating from that point on, until a TA is found. It doesn't tell the recursor to lie about the real DS, though?

**Comment by rgacogne** [comment] 2021-04-09 08:26
Just pasting a few thoughts:
- If the client does DNSSEC validation, either it has a TA/NTA and would not do a DS query anyway, or the zone exists and is unsigned, or validation will break no matter what
- I think we are mixing two things here: 1/ DNSSEC validation of forward/internal zones, which might be solved with NTA/TA 2/ external DS queries for forward/internal zones resulting in a NXD override the forward/internal zone. Perhaps 2/ is a special case and we should not insert such a result in the negcache for forward/internal zones?
- I’m not sure TA or NTA should influence what we return to clients except for the AD bit

**Comment by brlumen** [comment] 2021-04-12 05:01
I tried to filter the DS request of the fake domain on dnsdist. Generated an empty answer, to which clients with oracle linux 8 with the default systemd-resolved reacted as a failed one, which led to a resolving error and a servfail response. Systemd-resolving was installed with default settings.
It seems that the option with "do not cache the nxdomain response to the DS request" seems to be the only option, the rest of the questions lie in a completely different plane and have nothing to do with this issue.

**Comment by rgacogne** [comment] 2021-04-12 07:12
> I tried to filter the DS request of the fake domain on dnsdist. Generated an empty answer, to which clients with oracle linux 8 with the default systemd-resolved reacted as a failed one, which led to a resolving error and a servfail response. Systemd-resolving was installed with default settings.

It likely does DNSSEC validation and thus will fail no matter what we return since we can return a valid proof :-/

**Comment by mnordhoff** [comment] 2021-04-12 07:17
Would it make sense to have logic so that, if the query name matches an entry in `export-etc-hosts` or `forward-zones`, magically pretend `NXDOMAIN` is `NODATA` and disable aggressive NSEC(3)?

**Comment by rgacogne** [comment] 2021-04-12 07:35
That sounds like a good idea, yes!

**Comment by brlumen** [comment] 2021-04-12 08:16
In my case, before the answer was forged, this client had no problems resolving fake zones. The problem is that the chain of trust was broken because of the forged answer, so even if the answer is not empty but with nxdomain, it must be signed with the root zone key that the client trusts.

**Comment by brlumen** [comment] 2021-04-12 08:27
That is, to inform the client that the subdomain is not signed can only be the one he trusts, in our case - the dnskey root zone fingerprint.

**Comment by rgacogne** [comment] 2021-04-12 08:33
I'm afraid I don't understand, how could the chain of trust not be broken since the zone doesn't exist? In that case there won't be anything else than a `NXDomain` answer validating the chain of trust, right?

**Comment by brlumen** [comment] 2021-04-12 08:43
Yes, and root servers do it with success.
Note that authoritative servers usually respond with rcode = refused to requests for zones that they do not maintain, while root servers issue rcode = nxdomain.

**Comment by omoerbeek** [comment] 2021-04-12 08:44
> Would it make sense to have logic so that, if the query name matches an entry in `export-etc-hosts` or `forward-zones`, magically pretend `NXDOMAIN` is `NODATA` and disable aggressive NSEC(3)?

Interesting, though we should keep in mind that `export-etc-hosts` is just a special case of `auth-zones`. So the test likely should be on those.

**Comment by rgacogne** [comment] 2021-04-12 08:49
> Yes, and root servers do it with success.

I'm now 100% lost. Root servers have the private key to sign their answers, the recursor does not.

> Note that authoritative servers usually respond with rcode = refused to requests for zones that they do not maintain, while root servers issue rcode = nxdomain.

An authoritative server, including a root server, will reply with nxdomain for a non-existent name inside one of the zone they are authoritative for (unless there is a delegation to a different zone between the zone they are authoritative for and the requested name). It will reply with refused if it is neither authoritative for the zone nor any parent zone. The root servers are, by definition, always authoritative for a parent zone.

**Comment by brlumen** [comment] 2021-04-12 09:30
My own brain explodes :)
> I'm now 100% lost. Root servers have the private key to sign their answers, the recursor does not.

The recursor has a fingerprint of the public key of the root zone in the form of DS in TA.

> An authoritative server, including a root server, will reply with nxdomain for a non-existent name inside one of the zone they are authoritative for (unless there is a delegation to a different zone between the zone they are authoritative for and the requested name). It will reply with refused if it is neither authoritative for the zone nor any parent zone. The root servers are, by definition, always authoritative for a parent zone.

I meant to say that since root servers are the entry point, they have no other answer than nxdomain, and this is used in dnssec, including to disable nsec (3) for all kinds of fake domains.
BUT! Without a signed response from nxdomain, from the root servers, the validating recurser will not be able to disable dnssec checking via nxdomain for the fake domain.

**Comment by omoerbeek** [comment] 2021-04-12 09:36
Before we go into DNSSEC issues, I like to stress that the issues alraedy exists with DNSSEC disabled, since the DS query gets an NXDOMAIN answer which then NXDOMAINs (as a verb) the whole domain.

**Comment by brlumen** [comment] 2021-04-12 10:10
> Before we go into DNSSEC issues, I like to stress that the issues alraedy exists with DNSSEC disabled, since the DS query gets an NXDOMAIN answer which then NXDOMAINs (as a verb) the whole domain.

I agree.

**Closed** 2021-04-20 13:02 UTC
Labels: defect, rec
