### ISSUE TITLE
geoip backend zone.yaml file dynamic reconfiguration

### ISSUE THREAD

**Issue by starjoe** [PowerDNS/pdns#6600] opened 2018-05-11 08:45 UTC
- Program: Authoritative
 - Issue type: Feature request 

### Short description
1. The zone file in the geoip backend can support dynamic loading.
2. Can a single zone file in the geoip backend be split into multiple zones?

### Usecase

1.We do not need to reload/force-reload after modifying the zones file.
2.The fact that a single zone's file is showing off more data in the file will lead to reload for a long time. Therefore, it is recommended that you can use a domain name or a zone file. Alternatively, you can split a zone file into multiple zone files. Modifying a file does not require reloading all files.

In bind, a domain name is a zone file. In pdns, all the domain names are in a zones file. Can it be divided into multiple zone files like bind?

**Comment by Habbie** [comment] 2018-05-11 08:47
For your convenience, I have restored the parts of the feature request template that you removed. Please fill them all in.

**Comment by starjoe** [comment] 2018-05-17 02:07
@Habbie  Has been modified, do not understand what I said white?

**Comment by Habbie** [comment] 2019-05-14 13:25
Duplicate of #5944

**Closed by Habbie** 2019-05-14 13:25 UTC
Labels: auth, response needed
