### ISSUE TITLE
TCP Connection Thread died because of network error

### ISSUE THREAD

**Issue by troykelly** [PowerDNS/pdns#12803] opened 2023-05-11 13:29 UTC
- Program: Authoritative, Recursor
 - Issue type: Bug report

### Short description
Recursor --> Authoritative results in 100% failure
```text
pdns_auth            | May 11 12:50:44 TCP Connection Thread died because of network error: Error reading DNS data from TCP client ::1: Timeout reading data
```

### Environment

 - Operating system: Docker
 - Software version: PowerDNS Recursor 4.8.4, PowerDNS Authoritative Server 4.7.4
 - Software source: pschiffe/pdns-mysql & pschiffe/pdns-recursor

### Steps to reproduce

1. Docker stack with both authoritative & recursor using host mode netwokring
2. auth 127.0.0.1:853,[::1]:853, recursor 127.0.0.1:953,[::1]:953
3. forward-zones-recurse=61.10.in-addr.arpa=[::1]:853 (or 127.0.0.1 - both fail)
4. request the PTR for `3.16.61.10.in-addr.arpa`

### Expected behaviour

The PTR record returned

### Actual behaviour

Timeouts resulting in servfail

### Other information

This is not a networking / connectivity issue - I can install `bind-utils` in the recursor container and perform successful lookups.

The recursor container can obviously perform lookups over TCP and UCP to the authoritative server, I'm not sure why the powerdns recursor is unable to perform the same lookup.

Perhaps related to https://github.com/PowerDNS/pdns/issues/7995 but this was closed without investigation, so I'm not sure.

#### Log from containers

```text
pdns_recursor        | May 11 13:11:34 msg="Question" subsystem="syncres" level="0" prio="Info" tid="3" ts="1683810694.909" ecs="" mtid="2" proto="udp" qname="3.16.61.10.in-addr.arpa" qtype="PTR" remote="127.0.0.1:50504"
pdns_recursor        | May 11 13:11:34 [2] : no TA found for '3.16.61.10.in-addr.arpa' among 1
pdns_recursor        | May 11 13:11:34 [2] : no TA found for '16.61.10.in-addr.arpa' among 1
pdns_recursor        | May 11 13:11:34 [2] : no TA found for '61.10.in-addr.arpa' among 1
pdns_recursor        | May 11 13:11:34 [2] : no TA found for '10.in-addr.arpa' among 1
pdns_recursor        | May 11 13:11:34 [2] : no TA found for 'in-addr.arpa' among 1
pdns_recursor        | May 11 13:11:34 [2] : no TA found for 'arpa' among 1
pdns_recursor        | May 11 13:11:34 [2] : got TA for '.'
pdns_recursor        | May 11 13:11:34 [2] 3.16.61.10.in-addr.arpa: Wants DNSSEC processing, auth data in query for PTR
pdns_recursor        | May 11 13:11:34 [2] 3.16.61.10.in-addr.arpa: No cache hit for '3.16.61.10.in-addr.arpa|PTR', trying to find an appropriate NS record
pdns_recursor        | May 11 13:11:34 [2] 3.16.61.10.in-addr.arpa: Cache consultations done, have 1 NS to contact
pdns_recursor        | May 11 13:11:34 [2] 3.16.61.10.in-addr.arpa: Domain has hardcoded nameserver
pdns_recursor        | May 11 13:11:34 [2] 3.16.61.10.in-addr.arpa.: Nameservers: +[::1]:853(0.00ms)
pdns_recursor        | May 11 13:11:34 [2] 3.16.61.10.in-addr.arpa: Resolved '61.10.in-addr.arpa' NS (empty) to: ::1
pdns_recursor        | May 11 13:11:34 [2] 3.16.61.10.in-addr.arpa: Trying IP [::1]:853, asking '3.16.61.10.in-addr.arpa|PTR'
pdns_recursor        | May 11 13:11:34 [2] 3.16.61.10.in-addr.arpa: using DoT with [::1]:853
pdns_recursor        | May 11 13:11:39 msg="Question" subsystem="syncres" level="0" prio="Info" tid="3" ts="1683810699.913" ecs="" mtid="3" proto="udp" qname="3.16.61.10.in-addr.arpa" qtype="PTR" remote="127.0.0.1:48821"
pdns_recursor        | May 11 13:11:39 [3] : no TA found for '3.16.61.10.in-addr.arpa' among 1
pdns_recursor        | May 11 13:11:39 [3] : no TA found for '16.61.10.in-addr.arpa' among 1
pdns_recursor        | May 11 13:11:39 [3] : no TA found for '61.10.in-addr.arpa' among 1
pdns_recursor        | May 11 13:11:39 [3] : no TA found for '10.in-addr.arpa' among 1
pdns_recursor        | May 11 13:11:39 [3] : no TA found for 'in-addr.arpa' among 1
pdns_recursor        | May 11 13:11:39 [3] : no TA found for 'arpa' among 1
pdns_recursor        | May 11 13:11:39 [3] : got TA for '.'
pdns_recursor        | May 11 13:11:39 [3] 3.16.61.10.in-addr.arpa: Wants DNSSEC processing, auth data in query for PTR
pdns_recursor        | May 11 13:11:39 [3] 3.16.61.10.in-addr.arpa: No cache hit for '3.16.61.10.in-addr.arpa|PTR', trying to find an appropriate NS record
pdns_recursor        | May 11 13:11:39 [3] 3.16.61.10.in-addr.arpa: Cache consultations done, have 1 NS to contact
pdns_auth            | May 11 13:11:39 TCP Connection Thread died because of network error: Error reading DNS data from TCP client ::1: Timeout reading data
pdns_recursor        | May 11 13:11:39 [3] 3.16.61.10.in-addr.arpa: Domain has hardcoded nameserver
pdns_recursor        | May 11 13:11:39 [3] 3.16.61.10.in-addr.arpa.: Nameservers: +[::1]:853(0.00ms)
pdns_recursor        | May 11 13:11:39 [3] 3.16.61.10.in-addr.arpa: Resolved '61.10.in-addr.arpa' NS (empty) to: ::1
pdns_recursor        | May 11 13:11:39 [3] 3.16.61.10.in-addr.arpa: Trying IP [::1]:853, asking '3.16.61.10.in-addr.arpa|PTR'
pdns_recursor        | May 11 13:11:39 [3] 3.16.61.10.in-addr.arpa: using DoT with [::1]:853
pdns_recursor        | May 11 13:11:39 [2] 3.16.61.10.in-addr.arpa: error resolving from ::1 over TCP, possible error: Transport endpoint is not connected
pdns_recursor        | May 11 13:11:39 [2] 3.16.61.10.in-addr.arpa: Failed to resolve via any of the 1 offered NS at level '61.10.in-addr.arpa'
pdns_recursor        | May 11 13:11:39 [2] 3.16.61.10.in-addr.arpa: failed (res=-1)
pdns_recursor        | May 11 13:11:39 msg="Answer" subsystem="syncres" level="0" prio="Info" tid="3" ts="1683810699.917" additional="1" answers="0" dotout="1" ecs="" mtid="2" netms="5006.493000" outqueries="1" proto="udp" qname="3.16.61.10.in-addr.arpa" qtype="PTR" rcode="2" rd="1" remote="127.0.0.1:50504" tcpout="0" throttled="0" timeouts="0" totms="5008.080000" validationState="Indeterminate"
pdns_recursor        | May 11 13:11:44 msg="Question answered from packet cache" subsystem="in" level="0" prio="Notice" tid="3" ts="1683810704.918" proto="udp" qname="3.16.61.10.in-addr.arpa" qtype="PTR" remote="127.0.0.1:40292" source="127.0.0.1:40292" tag="0"
pdns_auth            | May 11 13:11:44 TCP Connection Thread died because of network error: Error reading DNS data from TCP client ::1: Timeout reading data
pdns_recursor        | May 11 13:11:44 [3] 3.16.61.10.in-addr.arpa: error resolving from ::1 over TCP, possible error: Transport endpoint is not connected
pdns_recursor        | May 11 13:11:44 [3] 3.16.61.10.in-addr.arpa: Failed to resolve via any of the 1 offered NS at level '61.10.in-addr.arpa'
pdns_recursor        | May 11 13:11:44 [3] 3.16.61.10.in-addr.arpa: failed (res=-1)
pdns_recursor        | May 11 13:11:44 msg="Answer" subsystem="syncres" level="0" prio="Info" tid="3" ts="1683810704.920" additional="1" answers="0" dotout="1" ecs="" mtid="3" netms="5004.808000" outqueries="1" proto="udp" qname="3.16.61.10.in-addr.arpa" qtype="PTR" rcode="2" rd="1" remote="127.0.0.1:48821" tcpout="0" throttled="0" timeouts="0" totms="5006.752000" validationState="Indeterminate"
pdns_auth            | May 11 13:11:48 Remote 127.0.0.1 wants '3.16.61.10.in-addr.arpa|PTR', do = 0, bufsize = 1232: packetcache MISS
```

#### From recursor container

`lookup to auth`

```text
[root@test-dns-001 /]# dig PTR 3.16.61.10.in-addr.arpa @localhost -p 853

; <<>> DiG 9.18.14 <<>> PTR 3.16.61.10.in-addr.arpa @localhost -p 853
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57310
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;3.16.61.10.in-addr.arpa.       IN      PTR

;; ANSWER SECTION:
3.16.61.10.in-addr.arpa. 1800   IN      PTR     ups001.internal.sy3.aperim.net.

;; Query time: 12 msec
;; SERVER: 127.0.0.1#853(localhost) (UDP)
;; WHEN: Thu May 11 13:16:44 UTC 2023
;; MSG SIZE  rcvd: 96
```

```text
pdns_auth            | May 11 13:16:44 Remote 127.0.0.1 wants '3.16.61.10.in-addr.arpa|PTR', do = 0, bufsize = 1232: packetcache MISS
```

```text
[root@test-dns-001 /]# dig +tcp PTR 3.16.61.10.in-addr.arpa @localhost -p 853

; <<>> DiG 9.18.14 <<>> +tcp PTR 3.16.61.10.in-addr.arpa @localhost -p 853
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28085
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;3.16.61.10.in-addr.arpa.       IN      PTR

;; ANSWER SECTION:
3.16.61.10.in-addr.arpa. 1800   IN      PTR     ups001.internal.sy3.aperim.net.

;; Query time: 4 msec
;; SERVER: 127.0.0.1#853(localhost) (TCP)
;; WHEN: Thu May 11 13:18:01 UTC 2023
;; MSG SIZE  rcvd: 96
```

```text
pdns_auth            | May 11 13:18:01 TCP Remote 127.0.0.1 wants '3.16.61.10.in-addr.arpa|PTR', do = 0, bufsize = 1232: packetcache MISS
```

```text
[root@test-dns-001 /]# dig PTR 3.16.61.10.in-addr.arpa @::1 -p 853

; <<>> DiG 9.18.14 <<>> PTR 3.16.61.10.in-addr.arpa @::1 -p 853
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63978
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;3.16.61.10.in-addr.arpa.       IN      PTR

;; ANSWER SECTION:
3.16.61.10.in-addr.arpa. 1800   IN      PTR     ups001.internal.sy3.aperim.net.

;; Query time: 4 msec
;; SERVER: ::1#853(::1) (UDP)
;; WHEN: Thu May 11 13:18:38 UTC 2023
;; MSG SIZE  rcvd: 96
```

```text
pdns_auth            | May 11 13:18:38 Remote ::1 wants '3.16.61.10.in-addr.arpa|PTR', do = 0, bufsize = 1232: packetcache MISS
```

```text
[root@test-dns-001 /]# dig +tcp PTR 3.16.61.10.in-addr.arpa @::1 -p 853

; <<>> DiG 9.18.14 <<>> +tcp PTR 3.16.61.10.in-addr.arpa @::1 -p 853
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22815
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;3.16.61.10.in-addr.arpa.       IN      PTR

;; ANSWER SECTION:
3.16.61.10.in-addr.arpa. 1800   IN      PTR     ups001.internal.sy3.aperim.net.

;; Query time: 12 msec
;; SERVER: ::1#853(::1) (TCP)
;; WHEN: Thu May 11 13:19:36 UTC 2023
;; MSG SIZE  rcvd: 96
```

```text
pdns_auth            | May 11 13:19:36 TCP Remote ::1 wants '3.16.61.10.in-addr.arpa|PTR', do = 0, bufsize = 1232: packetcache MISS
```

#### Recursor known okay

```text
➜  test-dns-001 dig +tcp A google.com @localhost -p 953

; <<>> DiG 9.18.12-1ubuntu1-Ubuntu <<>> +tcp A google.com @localhost -p 953
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51413
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             292     IN      A       172.217.24.46

;; Query time: 0 msec
;; SERVER: 127.0.0.1#953(localhost) (TCP)
;; WHEN: Thu May 11 13:26:25 UTC 2023
;; MSG SIZE  rcvd: 55
```

```text
➜  test-dns-001 dig +tcp 46.24.217.172.in-addr.arpa @localhost -p 953

; <<>> DiG 9.18.12-1ubuntu1-Ubuntu <<>> +tcp 46.24.217.172.in-addr.arpa @localhost -p 953
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58940
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;46.24.217.172.in-addr.arpa.    IN      A

;; AUTHORITY SECTION:
24.217.172.in-addr.arpa. 45     IN      SOA     ns1.google.com. dns-admin.google.com. 530863604 900 900 1800 60

;; Query time: 0 msec
;; SERVER: 127.0.0.1#953(localhost) (TCP)
;; WHEN: Thu May 11 13:27:09 UTC 2023
;; MSG SIZE  rcvd: 115
```

**Comment by Habbie** [comment] 2023-05-11 13:33
> pdns_recursor        | May 11 13:11:39 [3] 3.16.61.10.in-addr.arpa: using DoT with [::1]:853

your recursor is configured to use DNS over TLS with that port, but that's not how you are running your auth. You might want to set `dot-to-port-853=no` in `recursor.conf`

As this is a support question and not a bug report, I'm closing this.

**Closed by Habbie** 2023-05-11 13:33 UTC

**Comment by Habbie** [comment] 2023-05-11 13:35
(thank you, by the way, for the extensive report. Made it easy for me to find the issue!)
