### ISSUE TITLE
GSQLBackend errors due to malformed SOA record

### ISSUE THREAD

**Issue by dkoster** [PowerDNS/pdns#6248] opened 2018-02-08 07:12 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description
Powerdns reports SQL error in logs for a domain with an malformed SOA record.
```
Feb  8 08:03:40 cachet pdns_server: Backend reported permanent error which prevented lookup (GSQLBackend lookup query:Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and name=? and domain_id=?), aborting
```

`pdnsutil check-zone` reports no errors, `pdnsutil edit-zone` reports an issue.

### Environment
 - Operating system: CentOS 7 (fully patched) 
 - Software version: 4.1.0
 - Software source: PowerDNS repository

### Steps to reproduce
1. The SOA record is as followed in the database:
```
name = aktatrading.nl
type = SOA
content = "ns1.peweb.net"
```

2. tail your logs and just send out an request for the domain:

```
$ host aktatrading.nl 62.148.190.237
Using domain server:
Name: 62.148.190.237
Address: 62.148.190.237#53
Aliases:

Host aktatrading.nl not found: 2(SERVFAIL)
```

logs:
```
Feb  8 08:06:36 cachet pdns_server: Backend reported permanent error which prevented lookup (GSQLBackend lookup query:Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and name=? and domain_id=?), aborting
Feb  8 08:06:36 cachet pdns_server: Backend error (retry once): GSQLBackend lookup query:Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and name=? and domain_id=?
Feb  8 08:06:36 cachet pdns_server: gmysql Connection successful. Connected to database 'pdns' on '127.0.0.1'.
Feb  8 08:06:36 cachet pdns_server: Exception building answer packet for aktatrading.nl/A (Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content 'ns1.peweb.net  0 10800 3600 604800 3600') sending out servfail
```

3. Running pdnsutils check-zone reports:
```
# pdnsutil check-zone aktatrading.nl
Feb 08 08:07:19 Reading random entropy from '/dev/urandom'
Feb 08 08:07:19 gmysql Connection successful. Connected to database 'pdns' on '127.0.0.1'.
Feb 08 08:07:19 gmysql Connection successful. Connected to database 'pdns' on '127.0.0.1'.
Checked 10 records of 'aktatrading.nl', 0 errors, 0 warnings.
```

### Expected behaviour
You would expected check-zone to report an issue with the SOA record. So you can fix this.
Also you would expect an useful error in the logs instead of an SQL error, which would point out that the database scheme is off, however its not. And no custom SQL queries used.

### Actual behaviour
See reproduce steps.

```
$ host aktatrading.nl 62.148.190.237
Using domain server:
Name: 62.148.190.237
Address: 62.148.190.237#53
Aliases:

Host aktatrading.nl not found: 2(SERVFAIL)
```

Logs:

```
Feb  8 08:06:36 cachet pdns_server: Backend reported permanent error which prevented lookup (GSQLBackend lookup query:Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and name=? and domain_id=?), aborting
Feb  8 08:06:36 cachet pdns_server: Backend error (retry once): GSQLBackend lookup query:Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and name=? and domain_id=?
Feb  8 08:06:36 cachet pdns_server: gmysql Connection successful. Connected to database 'pdns' on '127.0.0.1'.
Feb  8 08:06:36 cachet pdns_server: Exception building answer packet for aktatrading.nl/A (Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content 'ns1.peweb.net  0 10800 3600 604800 3600') sending out servfail
```

Check-zone:
```
# pdnsutil check-zone aktatrading.nl
Feb 08 08:07:19 Reading random entropy from '/dev/urandom'
Feb 08 08:07:19 gmysql Connection successful. Connected to database 'pdns' on '127.0.0.1'.
Feb 08 08:07:19 gmysql Connection successful. Connected to database 'pdns' on '127.0.0.1'.
Checked 10 records of 'aktatrading.nl', 0 errors, 0 warnings.
```

Edit-zone:
```
# pdnsutil edit-zone aktatrading.nl
Feb 08 08:10:14 Reading random entropy from '/dev/urandom'
Feb 08 08:10:14 gmysql Connection successful. Connected to database 'pdns' on '127.0.0.1'.
Feb 08 08:10:14 gmysql Connection successful. Connected to database 'pdns' on '127.0.0.1'.
Error: Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content 'ns1.peweb.net'
```

### Other information
Fixing the SOA record, fixes the issue completely. So the reason for failing is known, but the software seems to ignore the issue.

**Comment by tjikkun** [comment] 2018-02-13 11:05
I had a similar issue. It turned out the SOA record ended with a space character. Removing it solved the issue for me.

**Comment by Habbie** [comment] 2018-05-01 18:02
I cannot reproduce the SERVFAIL and the related gsql error. If you are still able to reproduce this problem, can you share more information, like your pdns.conf?

**Comment by dkoster** [comment] 2018-05-07 12:25
## General
I've created an newly fresh installed virtual.
With this virtual an can reproduce the issue

## Version numbers
CentOS 7 (CentOS Linux release 7.4.1708 (Core), fully patched)
PowerDNS 4.1.1 from the powerdns repo (pdns-4.1.1-1pdns.el7.x86_64)
MariaDB (CentOS standard version, mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1, mariadb-5.5.56-2.el7.x86_64)

The virtual machine is fully standard, no other changes.

## Database dump and config files powerdns / mysql
[pdns.zip](https://github.com/PowerDNS/pdns/files/1979764/pdns.zip)

## Behaviour
In the dump I've added the "broken" domain and a test domain.

### querying the test.nl domain:
> $ host test.nl. 62.148.190.238
> Using domain server:
> Name: 62.148.190.238
> Address: 62.148.190.238#53
> Aliases:
>
> test.nl has address 62.148.190.238
> test.nl mail is handled by 20 mail.test.nl.

No errors, all is fine

### querying the broken domain
> $ host aktatrading.nl. 62.148.190.238
> Using domain server:
> Name: 62.148.190.238
> Address: 62.148.190.238#53
> Aliases:
>
> Host aktatrading.nl not found: 2(SERVFAIL)

On the first query the logs show:
>May  7 14:19:57 dnstest pdns_server: Exception building answer packet for aktatrading.nl/A (Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content 'ns1.peweb.net  0 10800 3600 604800 3600') sending out servfail
>May  7 14:19:57 dnstest pdns_server: Exception building answer packet for aktatrading.nl/A (Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content 'ns1.peweb.net  0 10800 3600 604800 3600') sending out servfail

On the next queries the logs show:
> May  7 14:20:49 dnstest pdns_server: Exception building answer packet for aktatrading.nl/A (Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content 'ns1.peweb.net  0 10800 3600 604800 3600') sending out servfail
> May  7 14:20:49 dnstest pdns_server: Backend reported permanent error which prevented lookup (GSQLBackend lookup query:Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and name=? and domain_id=?), aborting
> May  7 14:20:49 dnstest pdns_server: Backend error (retry once): GSQLBackend lookup query:Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and name=? and domain_id=?
> May  7 14:20:49 dnstest pdns_server: gmysql Connection successful. Connected to database 'pdns' on '/var/lib/mysql/mysql.sock'.
> May  7 14:20:49 dnstest pdns_server: Exception building answer packet for aktatrading.nl/A (Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content 'ns1.peweb.net  0 10800 3600 604800 3600') sending out servfail

pdnsutil check-zone shows:
> # pdnsutil check-zone aktatrading.nl
> May 07 14:21:33 Reading random entropy from '/dev/urandom'
> May 07 14:21:33 gmysql Connection successful. Connected to database 'pdns' on '/var/lib/mysql/mysql.sock'.
> May 07 14:21:33 gmysql Connection successful. Connected to database 'pdns' on '/var/lib/mysql/mysql.sock'.
> Checked 10 records of 'aktatrading.nl', 0 errors, 0 warnings.

Hope this is enough to reproduce the issue.

**Comment by petteyg** [comment] 2018-12-09 18:50
Did you figure out what the root cause of this is? I had to revert to 4.0.6 to make everything work again; whatever triggered this bug caused other previously working zones to exhibit the same SERVFAIL. FWIW, direct requests for SOA still responded fine even on the otherwise broken zones.

**Comment by dkoster** [comment] 2018-12-10 08:52
> Did you figure out what the root cause of this is? I had to revert to 4.0.6 to make everything work again; whatever triggered this bug caused other previously working zones to exhibit the same SERVFAIL. FWIW, direct requests for SOA still responded fine even on the otherwise broken zones.

@petteyg My fix was fixing the SOA content record. In my case it was just "ns1.domain.ext" and fixing it to "ns1.domain.ext hostmast.domain.ext 2018082300 14400 3600 604800 10800" solved the problem. The SQL error should tell you which domain is "broken".

**Comment by sspans** [comment] 2018-12-10 11:56
I guess the main complaint here is that check-zone doesn't report/handle this misconfiguration.

**Comment by dkoster** [comment] 2018-12-10 12:13
> I guess the main complaint here is that check-zone doesn't report/handle this misconfiguration.

@sspans Basicly that is correct. check-zone misses "broken" records. When working with the API, more of this type of mismatches appear. There are more tickets about this. However in this case it  should not return such a horrible SQL error, but that did help finding the issue and solve it ;)

**Comment by petteyg** [comment] 2018-12-10 14:57
> 
> 
> > Did you figure out what the root cause of this is? I had to revert to 4.0.6 to make everything work again; whatever triggered this bug caused other previously working zones to exhibit the same SERVFAIL. FWIW, direct requests for SOA still responded fine even on the otherwise broken zones.
> 
> @petteyg My fix was fixing the SOA content record. In my case it was just "ns1.domain.ext" and fixing it to "ns1.domain.ext hostmast.domain.ext 2018082300 14400 3600 604800 10800" solved the problem. The SQL error should tell you which domain is "broken".

I've always had just the first NS as the SOA, and it's always worked up until now. When querying SOA records, it appends the rest of that automatically. Those numbers are all (except the timestamp) defaults, and given it has never had problems appending them in the past, and only started failing in 4.1.5, I suspect that is treating the symptom, not the cause.

**Comment by grischard** [comment] 2019-08-07 13:25
It happened to me too with a trailing space in the SOA, and `check-zone` was able to detect it:

`[Error] Following record had a problem: "foo.lu IN SOA ns1.bar.lu hostmaster.bar.lu 2019052404 28800 7200 604800 86400 "`

**Comment by petteyg** [comment] 2019-10-10 22:52
FWIW I am no longer seeing this bug in recent 4.1.x releases. No related mention I can find in the changelogs, but something was broken and something appears to have been fixed. All domains with SOA "ns1.mydomain.com" are functioning fine at the moment.

**Comment by Habbie** [comment] 2019-10-11 07:44
We've had multiple reports of recent versions no longer showing this problem, so I'm closing this.

**Closed by Habbie** 2019-10-11 07:44 UTC
Labels: auth, defect
