### ISSUE TITLE
Can Lua be used for authoritative server ? 

### ISSUE THREAD

**Issue by thechile** [PowerDNS/pdns#5081] opened 2017-02-23 13:27 UTC
Hi, apologies if this is obvious somewhere in the documentation but I can only find reference to Lua in context of recursor/scripting and as an authoritative backend. 

Can Lua be used for the authoritative server ? 

My objective is to audit existing DNS zones and associated records that are configured in our authoritative server and stored in a MySQL backend. My plan was to use Lua on `preresolve` to track `dq.qname` and bump a counter in redis or direct in mysql. 

Thank you
Scott

**Comment by Habbie** [comment] 2017-02-23 13:29
Hello Scott,

there is an undocumented Lua hook in the auth that could probably do this, but I would not recommend relying on it, it is strictly for test suite usage. I would probably recommend putting dnsdist in front and exporting protobuf logging from it.

Closing this ticket as this is not a bug or a feature request. Please use IRC or the mailing list for further discussion!

**Closed by Habbie** 2017-02-23 13:29 UTC
