### ISSUE TITLE
Wildcard handling in recusor auth-zones doesn't match nsd/bind

### ISSUE THREAD

**Issue by sspans** [PowerDNS/pdns#2819] opened 2015-10-22 13:22 UTC
The following zone produces different results when loaded in pdns-recursor versus nsd/bind.
NB: The is a zone loaded in pdns-recursor, not normal powerdns.

Version used: pdns-recursor-3.7.2-1.el6.x86_64

QUERY | pdns-recursor | NSD
------------ | -------------| -------------
s3.storage.foobar.baz | NOERROR - CNAME | NOERROR - CNAME
*.s3.storage.foobar.baz | NOERROR - CNAME | NOERROR - CNAME
foo.s3.storage.foobar.baz | NOERROR - EMPTY | NOERROR - CNAME

Querying '*.s3' works:

```
<sspans@mccmmon1:~>  dig @127.0.0.1 *.s3.storage.foobar.baz
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44446
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;*.s3.storage.foobar.baz. IN	A

;; ANSWER SECTION:
*.s3.storage.foobar.baz. 86355 IN CNAME s3-internal.otherdomain.tld.
```

Versus 'foo.s3':

```
<sspans@mccmmon1:~>  dig @127.0.0.1 foo.s3.storage.foobar.baz
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51594
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;foo.s3.storage.foobar.baz. IN A
```

This is the zone-file used:

```bind
; zone 'storage.foobar.baz'

$TTL    300
$ORIGIN storage.foobar.baz.

$INCLUDE include/soa.conf

@                       NS      dns-auth1.mydomain.tld.
@                       NS      dns-auth2.mydomain.tld.

s3                      CNAME   s3-internal.otherdomain.tld.
*.s3                    CNAME   s3-internal.otherdomain.tld.
```

**Comment by pieterlexis** [comment] 2015-10-22 13:23
dupe of #2818

**Closed by pieterlexis** 2015-10-22 13:23 UTC
