### ISSUE TITLE
pdns-auth: Empty responses and "Should not get here" error related to additional records processing and query-cache

### ISSUE THREAD

**Issue by sulate** [PowerDNS/pdns#5153] opened 2017-03-15 09:45 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description
Authoritative server returns no answers with NOERROR status for qtype A (and AAAA) queries and logs "Should not get here ... please run pdnsutil rectify-zone" error when querying a cross-domain address which was previously included in additional section for another query. (But only when second query is done within query-cache-ttl time window.)

### Environment
 - Operating system: Ubuntu 16.04.1 LTS (Xenial)
 - Software version: 4.0.3-1 (packages from Ubuntu Zesty)
 - Software source: Operating system repository
 - Backend: ldapbackend

### Steps to reproduce
1. Related configuration:
```
cache-ttl=0        # disable packet-cache to always trigger backend queries
query-cache-ttl=5  # enable query cache for error to trigger
do-ipv6-additional-processing=yes  # (default=yes) for error to trigger
```
First domain has cross-domain MX-reference (and we are authoritative for both of them):
```
my-domain.com.    IN    MX    10 mx-host-of-my-domain.example.com.
```
2. First query to fill query-cache: `dig +norecurse my-domain.com. mx @localhost`
3. Second query to trigger error: `dig +norecurse mx-host-of-my-domain.example.com. a @localhost`
(run within `query-cache-ttl` time window. Can also be repeated and response stays invalid for the cache time window.)

### Expected behaviour
Second query should return normal qtype A answer.
```
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37438
;; flags: qr aa; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; ANSWER SECTION:
mx-host-of-my-domain.example.com.       43200   IN      A       10.0.0.1
```

### Actual behaviour
Second query returns no answers and no errors and "Should not get here" error is logged.
```
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32489
;; flags: qr aa; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
```

### Other information
(Have not debugged or compiled anything but only looked at the source code.)
In `packethandler.cc` function `*PacketHandler::questionOrRecurse`:

To end up into "Should not get here" we are basically getting a `rr.auth==false` answer from `while(B.get(rr))` for type ANY backend-lookup, and when error happens this rr is coming from query-cache.

The broken cache-entry is added in `PacketHandler::doAdditionalProcessingAndDropAA` when making the type ANY backend-lookup for the additional record.

So I'm thinking maybe this code:
```
if(rr.auth && !rr.dr.d_name.isPartOf(soadata.qname)) // don't sign out of zone data using the main key 
  rr.auth=false;
```
is altering also the rr which just got stored in to the cache?

Also when setting `do-ipv6-additional-processing=no` the error does not happen, since the additional lookup is then type A. (rr.auth probably still false but cached result is not used at least in this test scenario).

**Comment by Habbie** [comment] 2017-03-21 15:41
I cannot reproduce this.

My setup: auth-4.0.3 from git, built on my mac. LDAP filled by `start-test-stop 5300 ldap-tree`. Command line: `/Users/peter/projects/powerdns/pdns/regression-tests/../pdns/pdns_server --daemon=no --local-port=5300 --config-dir=. --config-name=ldap --socket-dir=./ --no-shuffle --query-logging --cache-ttl=0 --dname-processing --lua-prequery-script=./check_stest_source --do-ipv6-additional-processing=yes --query-cache-ttl=20`.

Test output:
```
 dig mx wtest.com @127.0.0.1 -p 5300 ; dig a smtp-servers.example.com. @127.0.0.1 -p 5300

; <<>> DiG 9.11.0a2 <<>> mx wtest.com @127.0.0.1 -p 5300
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8557
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 4
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;wtest.com.			IN	MX

;; ANSWER SECTION:
wtest.com.		3600	IN	MX	10 smtp-servers.example.com.
wtest.com.		3600	IN	MX	15 smtp-servers.wtest.com.

;; ADDITIONAL SECTION:
smtp-servers.example.com. 120	IN	A	192.168.0.2
smtp-servers.example.com. 120	IN	A	192.168.0.3
smtp-servers.example.com. 120	IN	A	192.168.0.4

;; Query time: 4 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Tue Mar 21 16:39:28 CET 2017
;; MSG SIZE  rcvd: 152


; <<>> DiG 9.11.0a2 <<>> a smtp-servers.example.com. @127.0.0.1 -p 5300
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49397
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;smtp-servers.example.com.	IN	A

;; ANSWER SECTION:
smtp-servers.example.com. 120	IN	A	192.168.0.2

;; Query time: 1 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Tue Mar 21 16:39:28 CET 2017
;; MSG SIZE  rcvd: 69
```

What am I missing?

**Comment by sulate** [comment] 2017-03-28 12:47
Have been testing this all day. Seems it doesn't happen anymore with github master version. It does with latest download version though: https://downloads.powerdns.com/releases/pdns-4.0.3.tar.bz2

I also found out that you have to have multiple cross domain MX references for error to present itself. Then ONE of the A queries for MX hosts works ok and all others give the "empty NOERROR" response.

So you can reproduce this by adding another example.com MX host for wtest.com like this:
```
wtest.com.              3600    IN      MX      10 smtp-servers.example.com.
wtest.com.              3600    IN      MX      15 smtp-servers.wtest.com.
wtest.com.              3600    IN      MX      20 outpost.example.com.
```
Here's an ldif for it:
```
dn: dc=wtest,dc=com,ou=dns,o=power
changetype: modify
add: mXRecord
mXRecord: 20 outpost.example.com
-
```
And then results will be like this:
```
$ dig @127.0.0.1 -p 5300 +norecurse +noall +question +ans wtest.com. mx outpost.example.com. a smtp-servers.example.com. a

;wtest.com.                     IN      MX
wtest.com.              3600    IN      MX      10 smtp-servers.example.com.
wtest.com.              3600    IN      MX      15 smtp-servers.wtest.com.
wtest.com.              3600    IN      MX      20 outpost.example.com.
;outpost.example.com.           IN      A
;smtp-servers.example.com.      IN      A
smtp-servers.example.com. 120   IN      A       192.168.0.2
```

**Comment by sulate** [comment] 2017-08-09 08:44
This issue is still present in the latest release version: `4.0.4-1pdns.xenial`

**Comment by evacomm** [comment] 2017-08-18 09:34
I'm also having this issue

**Comment by Habbie** [comment] 2018-02-08 11:37
Has anyone who sees the issue tried 4.1.0?

**Comment by jsoref** [comment] 2018-03-13 05:11
fwiw, my problem w/ pdns-rec turned out to be caused by something which appears to be this, my `ns3` was running:
 pdns-backend-pgsql                4.0.5-1pdns.xenial  
 pdns-server                       4.0.5-1pdns.xenial  

And it was returning the empty bits. Running rectify did fix it. I'm sorry I didn't keep the database. I do have the original dump which I used to populate ns3, I suppose I could try playing with that...

**Comment by Habbie** [comment] 2019-05-14 12:42
Closing this as nobody has said they experienced this issue on 4.1.0 or newer.

**Closed by Habbie** 2019-05-14 12:42 UTC
Labels: auth, defect
