### ISSUE TITLE
pdns-recursor fails to resolve records for domain if qname-minimization is enabled

### ISSUE THREAD

**Issue by sesa-me** [PowerDNS/pdns#10263] opened 2021-04-05 20:26 UTC
- Program: Recursor
 - Issue type: Bug report

### Short description
pdns-recursor versions 4.4.0 onwards fail to resolve records from a specific domain, queries return SERVFAIL. 
The same queries work fine in 4.3.7. 

### Environment
 - Operating system: Alpine Linux 3.13
 - Software version: 4.3.7 (successful) / 4.4.0+ (fails)
 - Software source: Source tarballs, self compiled
 - Configure options: ./configure --enable-static --enable-static-boost --with-protobuf
 
### Steps to reproduce

The problem domain consists of 3, IPv6 only, NS records, 

```text
welterde.dn42.  3502    IN      SOA     ns1.any.welterde.dn42. hostmaster.welterde.dn42. 2021040520 28800 3600 2419200 3600
welterde.dn42.  3600    IN      NS      ns1.any.welterde.dn42.
welterde.dn42.  3600    IN      NS      ns2.any.welterde.dn42.
welterde.dn42.  3600    IN      NS      ns3.any.welterde.dn42.
ns1.any.welterde.dn42.  3600    IN      AAAA    fdef:5d0d:ee12:0:100:53:42:1
ns2.any.welterde.dn42.  3600    IN      AAAA    fdef:5d0d:ee12:0:100:53:42:2
ns3.any.welterde.dn42.  3600    IN      AAAA    fdef:5d0d:ee12:0:100:53:42:3
```

The .dn42 TLD is forwarded by the recursor to an authoritative server (pdns) using a forward-zones files:

```text
dn42 = [fd42:4242:2601:ac53::1]:53
```

A single delegation and glue for ns1.any.welterde.dn42 exists in the .dn42 zone:

```text
welterde.dn42   900     IN      NS      ns1.any.welterde.dn42.
ns1.any.welterde.dn42   900     IN      AAAA    fdef:5d0d:ee12:0:100:53:42:1
```

Querying the records using pdns-recursor 4.3.7 is successful:

```shell
# pdns_recursor --version
Apr 05 19:16:44 Unable to open /usr/local/etc/recursor.conf
Apr 05 19:16:44 Unable to parse configuration file '/usr/local/etc/recursor.conf'
Apr 05 19:16:44 Asked to run with pdns-distributes-queries set but no distributor threads
, raising to 1
Apr 05 19:16:44 PowerDNS Recursor 4.3.7 (C) 2001-2020 PowerDNS.COM BV
Apr 05 19:16:44 Using 64-bits mode. Built using gcc 10.2.1 20201203 on Apr  5 2021 18:33:
27 by simon@abuild.
Apr 05 19:16:44 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and yo
u are welcome to redistribute it according to the terms of the GPL version 2.
Apr 05 19:16:44 Features: fcontext libcrypto-ecdsa libcrypto-ed25519 libcrypto-ed448 libc
rypto-eddsa lua nod protobuf sodium 
Apr 05 19:16:44 Configured with: " '--enable-static' '--enable-static-boost' '--with-prot
obuf'"

# drill -p 5353 AAAA ns2.any.welterde.dn42 @fd42:4242:2601:3502:216:3eff:fe11:fdbd
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 44383
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; ns2.any.welterde.dn42.       IN      AAAA

;; ANSWER SECTION:
ns2.any.welterde.dn42.  3600    IN      AAAA    fdef:5d0d:ee12:0:100:53:42:2

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 69 msec
;; SERVER: fd42:4242:2601:3502:216:3eff:fe11:fdbd
;; WHEN: Mon Apr  5 19:16:50 2021
;; MSG SIZE  rcvd: 67
```

Performing the same query on pdns-recursor version 4.4.0 and later results in a SERVFAIL
The trace for this query appears to show the recursor looping on the same queries until it eventually fails.

```sh
# pdns_recursor --version
Apr 05 19:09:49 PowerDNS Recursor 4.4.0 (C) 2001-2020 PowerDNS.COM BV
Apr 05 19:09:49 Using 64-bits mode. Built using gcc 10.2.1 20201203 on Apr  5 2021 18:40:
45 by simon@abuild.
Apr 05 19:09:49 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and yo
u are welcome to redistribute it according to the terms of the GPL version 2.
Apr 05 19:09:49 Features: fcontext libcrypto-ecdsa libcrypto-ed25519 libcrypto-ed448 libc
rypto-eddsa lua nod protobuf sodium 
Apr 05 19:09:49 Configured with: " '--enable-static' '--enable-static-boost' '--with-prot
obuf'"

# drill -p 5353 AAAA ns2.any.welterde.dn42 @fd42:4242:2601:3502:216:3eff:fe11:fdbd
;; ->>HEADER<<- opcode: QUERY, rcode: SERVFAIL, id: 49367
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; ns2.any.welterde.dn42.       IN      AAAA

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 76 msec
;; SERVER: fd42:4242:2601:3502:216:3eff:fe11:fdbd
;; WHEN: Mon Apr  5 19:09:59 2021
;; MSG SIZE  rcvd: 39
```

Attached are the server config and logs with trace enabled for both 4.3.7 (successful) and 4.4.0 (failure). The traces show a complete log from clean restart to end of the query. 
The server would normally run with DNSSEC enabled, however this has been disabled for the purposes of the test, The server is also configured to run on port 5353 for testing. 

[recursor-dns53.conf.txt](https://github.com/PowerDNS/pdns/files/6260398/recursor-dns53.conf.txt)
[trace-4.4.0.txt](https://github.com/PowerDNS/pdns/files/6260399/trace-4.4.0.txt)
[trace-4.3.7.txt](https://github.com/PowerDNS/pdns/files/6260402/trace-4.3.7.txt)

### Expected behaviour
The domain records should resolve successfully in 4.4.0 and later.

### Actual behaviour
Records fail to resolve.

### Other information
none

**Comment by Habbie** [comment] 2021-04-06 06:22
Just to test, can you try with `qname-minimization=no`?

**Comment by sesa-me** [comment] 2021-04-06 07:07
Aha, yes that works fine. 
Successful trace from 4.4.3 with qname-minimization disabled, attached for reference. 

[trace-4.4.3.txt](https://github.com/PowerDNS/pdns/files/6262753/trace-4.4.3.txt)

**Comment by omoerbeek** [comment] 2021-04-06 07:08
> Just to test, can you try with `qname-minimization=no`?

Yes, the relevant 4.3 trace lines do not have QM, while the 4.4 one have. Might be a delegation missing or similar issue.

**Comment by Habbie** [comment] 2021-04-06 07:09
@omoerbeek I think the NS names being two labels below the delegated names might be a clue.

**Comment by sesa-me** [comment] 2021-04-06 07:45
Another data point, we have a similar zone for another user which does work ok. 
The only difference I can see with the second zone is that it also has an A record for the nameservers.

Tested on 4.4.0 and 4.4.3 with qname-minimization on.

Delegation and glues from .dn42

```text
erinn.dn42	900	IN	NS	iria.ns.erinn.dn42.
erinn.dn42	900	IN	NS	uladh.ns.erinn.dn42.
iria.ns.erinn.dn42	900	IN	A	172.21.89.131
iria.ns.erinn.dn42	900	IN	AAAA	fdfd:468b:bab6:4952::2
uladh.ns.erinn.dn42	900	IN	A	172.21.89.129
uladh.ns.erinn.dn42	900	IN	AAAA	fdfd:468b:bab6:554c::1
```

```sh
# drill -p 5353 NS erinn.dn42 @fd42:4242:2601:3502:216:3eff:fe11:fdbd
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 26787
;; flags: qr rd ra ; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; erinn.dn42.	IN	NS

;; ANSWER SECTION:
erinn.dn42.	3600	IN	NS	iria.ns.erinn.dn42.
erinn.dn42.	3600	IN	NS	uladh.ns.erinn.dn42.

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 2624 msec
;; SERVER: fd42:4242:2601:3502:216:3eff:fe11:fdbd
;; WHEN: Tue Apr  6 07:42:11 2021
;; MSG SIZE  rcvd: 70

# drill -p 5353 A iria.ns.erinn.dn42 @fd42:4242:2601:3502:216:3eff:fe11:fdbd
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 51693
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; iria.ns.erinn.dn42.	IN	A

;; ANSWER SECTION:
iria.ns.erinn.dn42.	60	IN	A	172.21.89.131

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 1190 msec
;; SERVER: fd42:4242:2601:3502:216:3eff:fe11:fdbd
;; WHEN: Tue Apr  6 07:42:42 2021
;; MSG SIZE  rcvd: 52
# drill -p 5353 AAAA iria.ns.erinn.dn42 @fd42:4242:2601:3502:216:3eff:fe11:fdbd
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 34342
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; iria.ns.erinn.dn42.	IN	AAAA

;; ANSWER SECTION:
iria.ns.erinn.dn42.	60	IN	AAAA	fdfd:468b:bab6:4952::1

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 2596 msec
;; SERVER: fd42:4242:2601:3502:216:3eff:fe11:fdbd
;; WHEN: Tue Apr  6 07:42:56 2021
;; MSG SIZE  rcvd: 64
```

**Comment by pieterlexis** [comment] 2021-04-06 07:58
Could it be the fact that the 'tld' is forwarded? Is there some special sauce somewhere?

**Comment by rgacogne** [comment] 2021-04-06 08:03
So `dn42` is forwarded to a server that replies with a delegation whose DNS is in-bailiwick, with a single `AAAA` glue (no `A`). I guess we don't handle that very well..

**Comment by omoerbeek** [comment] 2021-04-06 14:16
To be clear, the issue is not 4.3 vs 4.4, but whether qname minimization is enabled or not.

**Comment by omoerbeek** [comment] 2021-04-07 10:47
OK, so what is happening is roughly:

1. We look for a nameserver for `welterde.dn42` and get `ns1.any.welterde.dn42` with only AAAA glue whcih gets cached.
2. The QM process then tries to resolve `any.welterde.dn42|A` and finds NS `ns1.any.welterde.dn42`
3. So it need to resolve that NS name to an address. It starts with resolving for A which is not in the cache, so it needs to to go out. Nearest ancestor is  `welterde.dn42` and so a loop.

If it would have looked into the cache for both A and AAAA records for `ns1.any.welterde.dn42`, and be satisfied with anything it finds, it would not need to go out and use the AAAA record for  `ns1.any.welterde.dn42`.

I have experimental code to first look in the cache for both A and AAAA here and that seems to solve the issue.

But before changing this is needs way more contemplation and testing. So for the moment I would advise to add an A record for the NS name. The recursor then sees that in the cache, not go out for more A's and use the cached AAAA record(s) as well for the following step: contacting the NS.

This issue is releated to #7542.

**Comment by sesa-me** [comment] 2021-04-07 11:45
Thanks for the update and explanation. 

I'm happy to support testing of any potential fixes. It's relatively easy for me to battle test builds with real users and in DN42 we have a variety of IPv4/IPv6 only or dual stacked networks to check specific cases.

**Comment by omoerbeek** [comment] 2021-04-07 11:52
Below the logs from a setup where the NS has no A record and one with an A record:

[logNoA.txt](https://github.com/PowerDNS/pdns/files/6271326/logNoA.txt)
[logA.txt](https://github.com/PowerDNS/pdns/files/6271327/logA.txt)

**Comment by omoerbeek** [comment] 2021-04-09 07:35
@sesa-me: 've created a PR (#10276). It would be nice if you could give it a spin.

**Comment by sesa-me** [comment] 2021-04-09 09:55
Great, thanks. 
More than happy to test, I should be able to get it deployed today and give it a good run over the weekend.

**Comment by omoerbeek** [comment] 2021-04-13 06:17
@sesa-me The weekend is over, did you have a chance to test?

**Comment by sesa-me** [comment] 2021-04-13 07:18
@omoerbeek, yes I was able to build the patch and I can confirm it does resolve the original issue.  

The build was deployed across 5 instances. I checked the stats this morning and they have been online for ~300k seconds (3.5 days) during which time each instance has processed ~257k questions. 

As far as I can tell its working fine, I've not seen any issues and had no complaints.

**Closed** 2021-04-13 10:33 UTC
Labels: rec
