### ISSUE TITLE
DKIM TXT double quote issue

### ISSUE THREAD

**Issue by ScOut3R** [PowerDNS/pdns#2881] opened 2015-11-10 09:32 UTC
Hi,

long DKIM keys with double quoted strings in it cannot be parsed by PowerDNS.

```
default._domainkey.bukkautohaz.hu. 600 IN TXT	"v=DKIM1\; k=rsa\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk030mAksNOhZ/b+8yAMGu1RNfW/4LFF9502YtjT9tTfJADXv51mvn0+apCd1Thd/STHjdh9H5JZ5u9X0wv6r9zm03Vl9aSP8yMI/XBlJdh91NhlCzraH5dGj3af/R+sbbel7u7p1AZQuPn9OHCpVjZDDruYGaUVlxZa+h3kASPlj7uQqFGP4haeYBa1P3OVRI" "rqbZ/fbH8mn8f4yV+b5FXXy2K043yviqaWCr+JGhjuiJgBFmjCU5ZHzdj97E/v53cmy6d1T/6dyB9DspNQsfxBfooL/ymGuDG0V+h0sG1YwaEal08CSRh4vE2vQIWnVRnlo1qZQjBtmRljWZw1l0wIDAQAB\;"
```

```
Exception building answer packet (Parsing record content: Data field in DNS should end on a quote (") in '"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk030mAksNOhZ/b+8yAMGu1RNfW/4LFF9502YtjT9tTfJADXv51mvn0+apCd1Thd/STHjdh9H5JZ5u9X0wv6r9zm03Vl9aSP8yMI/XBlJdh91NhlCzraH5dGj3af/R+sbbel7u7p1AZQuPn9OHCpVjZDDruYGaUVlxZa+h3kASPlj7uQqFGP4haeYBa1P3OVR') sending out servfail
```

I am running pdns 3.3 on Ubuntu 14.04 as a slave. The master is a cPanel 11.52 instance. According to cPanel the TXT record is valid and passes authentication when it is asked from cPanel's bind server. May I ask some reflection on this from the pdns team?

Kind regards,
Mate

**Comment by Habbie** [comment] 2015-11-10 09:36
Hello Mate,

this is not about double quotes. the `content` column in your `records` table is too small. Please make it bigger!

Closing ticket.

**Closed by Habbie** 2015-11-10 09:36 UTC

**Comment by bluehorseshoe1** [comment] 2017-01-04 18:50
Just thought I would leave a comment as I ran into the same issue recently trying to use DKIM with Google for Work. 

After adding the TXT record to PowerDNS I noticed that my DNS replication broke. I ran over the logs and noticed the following error message. (Host running Ubuntu 16.04)

**Error Message**
`TCP Connection Thread died because of STL error: Parsing record content: Data field in DNS should end on a quote (")`

After digging for awhile I stumbled across this post and thought I would give it a try. Below is what seemed to work for me. 

I had no clue how to get the content column in the records table larger. Eventually I stumbled through all the bounce back errors and figured out how to make the column bigger. As soon as I ran the commands below and re-tired saving the new TXT record, PowerDNS updated the DNS slave and excepted the record finally without errors.  I tested, and everything was successful. 

Here is what fixed this for me.

Login in to MariaDB
`mysql -u root -p`

Select the DB to work with:
` USE `powerdns`;`

Run ALTER TABLE command:
`LTER TABLE records MODIFY content VARCHAR(60000);`

Exit 

Restart Service
`service mysql restart`

**Comment by jorgefuertes** [comment] 2018-11-24 17:59
> Hello Mate,
> 
> this is not about double quotes. the `content` column in your `records` table is too small. Please make it bigger!
> 
> Closing ticket.

That's its not the problem, I have the same one and the column is MEDIUMTEXT.
Powerdns need quotes there (I don't realize why) and that crash aganist the DKIM ones. I did tried to scape the internal ones but it stores the backslashes too.

**Comment by phonedph1** [comment] 2018-11-24 20:57
This ticket is like 3 years old, if you have a reproducible problem you should open a new issue with updated version information and table description.
