### ISSUE TITLE
dnsdist NOTIFY distribution

### ISSUE THREAD

**Issue by Snowmanko** [PowerDNS/pdns#7518] opened 2019-02-26 14:49 UTC
Hi,

I just want to ensure myself how NOTIFY distribution in DNSDIST exactly works.
My setup looks like this - MASTER -> DNSDIST -> SLAVE PDNSs (pool of 4 nodes)

My Question is if MASTER will send NOTIFY to DNSDIST, will DNSDIST redistribute these NOTIFY to all SLAVES in DNSDIST backend? How to I achieve situation that all slaves in dnsdist backend will be notified of zone change on MASTER?

Thanks for clarification in advance.
BR!

**Comment by rgacogne** [comment] 2019-02-26 14:54
I am closing this issue as it appears to be a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [dnsdist mailinglist](https://mailman.powerdns.com/mailman/listinfo/dnsdist), or join us on IRC.

**Closed by rgacogne** 2019-02-26 14:54 UTC

**Comment by YazJon2209** [comment] 2019-02-28 18:16
Text
