### ISSUE TITLE
Use the api interface to add  records, the "change_date" field in the pdns.domian table is NULL.

### ISSUE THREAD

**Issue by DengLZ** [PowerDNS/pdns#11048] opened 2021-11-30 06:49 UTC
# curl -X PATCH --data '{"rrsets": [ {"name": "aaa.test.dom.", "type": "A", "ttl": 600, "changetype": "REPLACE", "records": [ {"content": "192.0.5.4", "disabled": false } ] } ] }' -H 'X-API-Key: xxxxxxxxx' http://127.0.0.1:8081/api/v1/servers/localhost/zones/test.dom. | jq .

![image](https://user-images.githubusercontent.com/9841643/143998950-39eed95d-364c-4e1f-8b17-eb77830d68e0.png)

**Comment by Habbie** [comment] 2021-12-03 15:27
This is intended behaviour; also, `change_date` has been removed in recent versions.

Closing this ticket.

**Closed by Habbie** 2021-12-03 15:27 UTC
