### ISSUE TITLE
[dnsdist 1.5] reusePort=true doesn't take effect when running with systemd

### ISSUE THREAD

**Issue by fancy-rabbit** [PowerDNS/pdns#9973] opened 2021-01-14 09:23 UTC
dnsdist 1.5.1 official deb package for debian stretch, 
after started with systemd, when running a new instance by dnsdist -v, it printed
```Fatal error: binding socket to 0.0.0.0:53: Address already in use```

it seems that #7820 caused this because CAP_NET_BIND_SERVICE is not enough for unprivileged user to setsockopt() with SO_REUSEPORT.

**Comment by pieterlexis** [comment] 2021-01-14 09:30
this is probably systemd-resolved that is running on 127.0.0.53:53 that has *not* enabled `SO_REUSEPORT`. Please check what is listening with `ss` or `netstat` and either shut that service down, or listen on specific addresses with dnsdist (highly recommended).

A quick check reveals that using `SO_REUSEPORT` works as expected on a systemd machine.

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2021-01-14 09:30 UTC
Labels: dnsdist

**Comment by fancy-rabbit** [comment] 2021-01-14 09:53
thanks, there aren't any other processes like systemd-resolved listening on port 53 and I'm now moving to the mailinglist.
sorry for any incovenience.
