### ISSUE TITLE
Resolution failure on large response

### ISSUE THREAD

**Issue by neonknight** [PowerDNS/pdns#10402] opened 2021-05-13 07:11 UTC
- Program: Recursor
 - Issue type: Bug report

### Short description
resolution can fail if response packet is larger than 1232 bytes, e.g. dig txt hpe.com @my.pdns.rec 

### Environment

 - Operating system: Centos 7.9.2009
 - Software version: 4.3.6
 - Software source: PowerDNS repository

### Steps to reproduce
```
cat /etc/pdns-recursor/recursor.conf | grep -v '^$' | grep -v '^#'
setuid=pdns-recursor
setgid=pdns-recursor
root-nx-trust=yes
allow-from=127.0.0.0/8, 10.0.0.0/8, 192.168.0.0/16
api-key=xxxxxxxx
disable-packetcache=yes
dnssec=log-fail
dnssec-log-bogus=yes
local-address=127.0.0.1
threads=4
webserver=yes
webserver-address=0.0.0.0
webserver-allow-from=127.0.0.0/8, 10.0.0.0/8, 192.168.0.0/16
webserver-password=xxxxxxxxxx
```

1. dig txt hpe.com @my.pdns.rec
2. dig txt hpe.com @ns1.hpe.com
3. compare output

### Expected behaviour

`dig txt hpe.com @my.pdns.rec` should not result in SERVFAIL, instead it should be the same result as `dig txt hpe.com @ns1.hpe.com`

### Actual behaviour
```
pdns_recursor[16071]: hpe.com: status=did not resolve, got 8 NS, looping to them
pdns_recursor[16071]: hpe.com: Trying to resolve NS 'ns2.hpe.com' (1/8)
pdns_recursor[16071]: Nameserver ns2.hpe.com IPs: 15.219.160.22(0.00ms)
pdns_recursor[16071]: hpe.com: Resolved 'hpe.com' NS ns2.hpe.com to: 15.219.160.22
pdns_recursor[16071]: hpe.com: Trying IP 15.219.160.22:53, asking 'hpe.com|TXT'
pdns_recursor[16071]: hpe.com: ns2.hpe.com (15.219.160.22) returned a packet we could not parse over UDP, trying sibling IP or NS
[..]
pdns_recursor[16071]: hpe.com: Failed to resolve via any of the 8 offered NS at level 'hpe.com'
pdns_recursor[16071]: hpe.com: failed (res=-1)
pdns_recursor[16071]: QM hpe.com.|TXT child=hpe.com: Step3 Final resolve: Server Failure/0
```

### Other information

Resolution works when setting the following config values:
```
edns-outgoing-bufsize=1680
udp-truncation-threshold=1680
```
Problem may be caused by hpe.com's authoritative servers not setting TC bit even though response is larger than packet size announced by recursor. Even if cause may be a broken implementation on authoritative side, pdns recorsor may want to find a graceful workaround to still show the expected response data.

**Comment by pieterlexis** [comment] 2021-05-13 07:18
> pdns_recursor[16071]: hpe.com: ns2.hpe.com (15.219.160.22) returned a packet we could not parse over UDP, trying sibling IP or NS

In 4.4, we log:

> May 13 09:14:04 [1] hpe.com: Got 0 answers from ns4.hpe.com (15.203.224.22), rcode=1 (Form Error), aa=0, in 134ms

This is because the server on the other end _ignores_ the EDNS buffer size and does not send TC=1:

```
$ dig @15.203.224.22 hpe.com txt +norec +bufsize=1232 +dnssec

; <<>> DiG 9.16.15 <<>> @15.203.224.22 hpe.com txt +norec +bufsize=1232 +dnssec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6154
;; flags: qr aa; QUERY: 1, ANSWER: 14, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;hpe.com.			IN	TXT

;; ANSWER SECTION:
hpe.com.		3600	IN	TXT	"apple-domain-verification=4Cdj0ldqUY073mFE"
hpe.com.		3600	IN	TXT	"v=spf1 mx a:b235-36.smtp-out.ap-southeast-2.amazonses.com a:b235-37.smtp-out.ap-southeast-2.amazonses.com  include:_spf.hpe.com include:spf-002e3701.pphosted.com include:spf-002e3702.pphosted.com include:_spf.salesforce.com include:spfa.mailendo.com ~all"
hpe.com.		3600	IN	TXT	"atlassian-domain-verification=WhCSeLlkFTp8ngTypIkgAZWjm4qlUIszeT3YtnhAGKZ/yroe6iDCr/rXptRbTIXj"
hpe.com.		3600	IN	TXT	"drift-domain-verification=878e45b2812bdb609a112d9f1b3ff60a216b847c1d27debab5c9fafe2f97575a"
hpe.com.		3600	IN	TXT	"drift-domain-verification=045a8f12bb6b3e17edc02333fa73a5349d7dac0f8dd99a304b7e0af6158ed902"
hpe.com.		3600	IN	TXT	"n08Ufe68rkAALICCaGJlGcasnxPl/kYd217q9zDfdaM+WIjPCRCWY5yoq10l0+Y4gvt/9VcfOveyW8L+apcA1w=="
hpe.com.		3600	IN	TXT	"MS=ms45337283"
hpe.com.		3600	IN	TXT	"4c08c81b4e9a40a2844bedc517078569"
hpe.com.		3600	IN	TXT	"adobe-sign-verification=21a6b63bbd3ec6aa8f683a32f6ead2c"
hpe.com.		3600	IN	TXT	"google-site-verification=3BgafjSnVzA8lvjVAG5r7HUZPaCW6CDaB0TBOU4xPMc"
hpe.com.		3600	IN	TXT	"amazonses:zpmrHOEbOQ9bNvV/kfgesIThb10dsFsDAHUYdB8qHv0="
hpe.com.		3600	IN	TXT	"facebook-domain-verification=yygq2qho49o9c4cd433i1ncpf0gnq2"
hpe.com.		3600	IN	TXT	"apple-domain-verification=0U9Ua48rBIsiS2cQ"
hpe.com.		3600	IN	TXT	"atlassian-domain-verification=O0io8Mu1F0bM4yl1Jopj8XwIYFnKlI5A6bebwmOQW5Nn6kO57j4zPfwyholaa2Uo"

;; Query time: 133 msec
;; SERVER: 15.203.224.22#53(15.203.224.22)
;; WHEN: Thu May 13 09:17:13 CEST 2021
;; MSG SIZE  rcvd: 1293
```

The received is bigger than the bufsize. So the auth is non-compliant and sending broken answers. The zone operator needs to fix their auths.

**Comment by pieterlexis** [comment] 2021-05-13 07:21
I'll keep this ticket open so we can improve logging in this area. Unfortunately for your operations, this is not a bug in PowerDNS but an RFC violation at the hpe.com zone operator.

**Comment by Habbie** [comment] 2021-05-13 10:40
> I'll keep this ticket open so we can improve logging in this area.

One nice trick I read about is to read 1233, so you can detect the oversized response.

**Comment by omoerbeek** [comment] 2021-05-13 10:53
Form a quick glance this is a duplicate of  #9632

**Comment by Habbie** [comment] 2021-05-13 10:53
It is!

**Closed** 2021-05-13 10:53 UTC
