### ISSUE TITLE
Bug report - Securing zone - GSQLBackend error

### ISSUE THREAD

**Issue by dellarte** [PowerDNS/pdns#7486] opened 2019-02-15 15:03 UTC
- Program: Authoritative
- Issue type: Bug report

### Short description
When trying to Secure an existing zone with `pdnsutil secure-zone myzone.tld`.
I get a GSQLBackend error : 
`Error: GSQLBackend list query: Provided parameter count does not match statement: SELECT content,ttl,prio,type,domain_id,suspended,name,auth FROM records where domain_id=? AND NOT suspended`

### Environment

 - Operating system: Debian 9
 - Software version: 
pdns-backend-mysql       4.1.6-1pdns.stret    amd64
pdns-server                      4.1.6-1pdns.stret    amd64

### Steps to reproduce
1. Run the command `pdnsutil rectify-zone myzone.tld`

### Expected behaviour
Success message with a secured zone i guess

### Actual behaviour
`root@lab:~# pdnsutil rectify-zone myzone.tld
Feb 15 15:45:27 Reading random entropy from '/dev/urandom'
Feb 15 15:45:27 [bindbackend] Parsing 0 domain(s), will report when done
Feb 15 15:45:27 [bindbackend] Done parsing domains, 0 rejected, 0 new, 0 removed
Error: GSQLBackend list query: Provided parameter count does not match statement: SELECT content,ttl,prio,type,domain_id,suspended,name,auth FROM records where domain_id=? AND NOT suspended`

### Usecase
Setting up DNSSEC on my PowerDNS Authoritative Version

**Comment by pieterlexis** [comment] 2019-02-15 15:05
'suspended' is not a default field in the normal SQL schema, please check your schema and all gmysql-*-query settings in your config.

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2019-02-15 15:05 UTC
