### ISSUE TITLE
Improper handling of DNSSEC with multiple MySQL backends

### ISSUE THREAD

**Issue by pcevela** [PowerDNS/pdns#9045] opened 2020-04-20 18:26 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description
Zones which have DNSSEC enabled, are not properly handled when using multiple backends. Mechanism is relying on table "cryptokeys" where "domain_id" is matching with "domain_id" from table "domains".
This is not properly handled when domains in each backends are unique.
This is affecting not only management, but also resolving.

### Environment

 - Operating system: CentOS 8
 - Software version: pdns-4.3.0-1pdns.el8.x86_64, pdns-backend-mysql-4.3.0-1pdns.el8.x86_64
 - Software source: Official powerdns-auth-43 repo

### Steps to reproduce

1. Install M1
2. Install M2
3. Install DB1
4. Install DB2
5. To M1, configure DB1 access
6. On M1 Create zone (i.e. customer-domain.com)
7. To M2, configure access to DB2 and DB1
8. On M2 Create zone (i.e. internal-domain.com)
9. Enable DNSSEC on zone created in step 6
10. Enable DNSSEC on zone created in step 8
10. Try to resolve zone signed in step 9 from M1 @localhost --> RRSIG is visible
11. Try to resolve zone signed in step 9 from M2 @localhost --> is NOT visible
12. Try to resolve zone signed in step 10 from M2 @localhost --> RRSIG is visible

**notice**: This problem also applies on API

### Expected behaviour
In step 11 of procedure, RRSIG should be visible.
In API, dnssec flag should be also be "true".

### Actual behaviour
Step 10:
```
dig @10.8.110.252 customer-comain.com +dnssec

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el8 <<>> @10.8.110.252 customer-comain.com +dnssec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45726
;; flags: qr aa rd; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
;; QUESTION SECTION:
;customer-comain.com.           IN      A

;; ANSWER SECTION:
customer-comain.com.    3600    IN      RRSIG   A 13 2 3600 20200430000000 20200409000000 25544 customer-comain.com. Z2cznTLMxW8x9offy8oVgD43cQoCWqo6nwRFK+KTvaLPnXQ8Uz+HlGg9 /LKOfKZZ2Uz4GvuJNt0UxJf/16+JBg==
customer-comain.com.    3600    IN      A       127.0.0.2
customer-comain.com.    3600    IN      A       127.0.0.3

;; Query time: 2 msec
;; SERVER: 10.8.110.252#53(10.8.110.252)
;; WHEN: Mon Apr 20 20:11:56 CEST 2020
;; MSG SIZE  rcvd: 195
```
Step 11:
```
dig @10.8.110.250 customer-comain.com +dnssec

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el8 <<>> @10.8.110.250 customer-comain.com +dnssec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22245
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
;; QUESTION SECTION:
;customer-comain.com.           IN      A

;; ANSWER SECTION:
customer-comain.com.    3600    IN      A       127.0.0.3
customer-comain.com.    3600    IN      A       127.0.0.2

;; Query time: 2 msec
;; SERVER: 10.8.110.250#53(10.8.110.250)
;; WHEN: Mon Apr 20 20:12:03 CEST 2020
;; MSG SIZE  rcvd: 80
```
Step 12:
```
dig @10.8.110.250 internal-domain.com +dnssec

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el8 <<>> @10.8.110.250 internal-domain.com +dnssec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17126
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
;; QUESTION SECTION:
;internal-domain.com.           IN      A

;; ANSWER SECTION:
internal-domain.com.    3600    IN      A       127.0.0.1
internal-domain.com.    3600    IN      RRSIG   A 13 2 3600 20200430000000 20200409000000 11034 internal-domain.com. y5CMp8EVVlNKUk9Mj3s3Tzpka6rmaod7BMhjbl07riEtMJKkI7qz1xSr 1nloWW42TqNRlSVsWm5XSOH8Oi2x8A==

;; Query time: 2 msec
;; SERVER: 10.8.110.250#53(10.8.110.250)
;; WHEN: Mon Apr 20 20:22:16 CEST 2020
;; MSG SIZE  rcvd: 179
```

**API**
Requesting M1
```
    {
        "account": "",
        "dnssec": true,
        "edited_serial": 2020042004,
        "id": "customer-comain.com.",
        "kind": "Master",
        "last_check": 0,
        "masters": [],
        "name": "customer-comain.com.",
        "notified_serial": 2020042004,
        "serial": 2020042004,
        "url": "/api/v1/servers/localhost/zones/customer-comain.com."
    }
```
Requesting M2
```
    {
        "account": "",
        "dnssec": true,
        "edited_serial": 2020042002,
        "id": "internal-domain.com.",
        "kind": "Master",
        "last_check": 0,
        "masters": [],
        "name": "internal-domain.com.",
        "notified_serial": 2020042002,
        "serial": 2020042002,
        "url": "/api/v1/servers/localhost/zones/internal-domain.com."
    },
    {
        "account": "",
        "dnssec": false,
        "edited_serial": 2020042004,
        "id": "customer-comain.com.",
        "kind": "Master",
        "last_check": 0,
        "masters": [],
        "name": "customer-comain.com.",
        "notified_serial": 2020042004,
        "serial": 2020042004,
        "url": "/api/v1/servers/localhost/zones/customer-comain.com."
    }
```

### Other information
I think it is related to [this bug](https://github.com/PowerDNS/pdns/issues/6626)

**Comment by Habbie** [comment] 2020-04-20 18:28
Hello, thank you for a very extensive report, this is much appreciated. Indeed this is because of #6626, and we've been discussing closing that one as wontfix.

So, I'm very sorry, but I'm closing this ticket.

**Closed by Habbie** 2020-04-20 18:28 UTC

**Comment by pcevela** [comment] 2020-04-20 18:51
Hi Peter, thank you for quick reply.
I really don't understand why fixing this behavior a problem.
Of course, I don't fully know architecture, but from outside look, this is just a matter of pointing to right database for signing key. Ident of secondary db is already there (from config file) and handling of "secondary" relations between "domains" a and "records" tables are also working great.
I would like also to point to the fact, that documentation is not mentioning this fact nowhere :)
That also means multiple backends are really not taken as equal.

**Comment by Habbie** [comment] 2020-04-20 18:52
The problem is that we usually make a separate database connection for the DNSSEC stuff, and that second connection does not know where the first connection found things. I will have a look at improving the documentation on this.



>  That also means multiple backends are really not taken as equal.

Sadly this is correct, but the effort to make them equal would be huge :(
