### ISSUE TITLE
Use let's encrypt certificates for DoT

### ISSUE THREAD

**Issue by Warok21** [PowerDNS/pdns#7301] opened 2018-12-28 08:42 UTC
### Program: dnsdist

- Issue type: Failure
- Short description
### Environment
- Operating system: Ubuntu 16.04
- Software version: dnsdist 1.3.3 (Lua 5.1.4)

### Steps to reproduce
`certbot -d mydomain.com --manual --preferred-challenges dnscertonly #used to create the certificate 
`
`cat /etc/dnsdist/dnsdist.conf 
`

> addLocal("160.98.31.165")
> addTLSLocal('160.98.31.165:853', '/etc/letsencrypt/xxx/fullchain.pem', '/etc/letsencrypt/xxx/privkey.pem')
> newServer({address='1.1.1.1'})
> getServer(0):setUp()
> addACL('160.98.0.0/16')
> setACL('160.98.0.0/16')

Client :
Windows 10
Content of stubby.yml:

resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128
edns_client_subnet_private : 1
round_robin_upstreams: 1
idle_timeout: 10000
listen_addresses:
  - 127.0.0.1
  - 0::1
upstream_recursive_servers:
  - address_data: 160.98.31.165
    tls_auth_name: "cn that I used in the command"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: computed hash
Expected behaviour
Client making the connection with the server

Actual behaviour

> Got TCP connection from 160.98.30.134:59888
> Closing TCP client connection with 160.98.30.134:59888

### Question:
Which files should I use, because if I read the README, 
> `privkey.pem`  : the private key for your certificate.
> `fullchain.pem`: the certificate file used in most server software.
> `chain.pem`    : used for OCSP stapling in Nginx >=1.3.7.
> `cert.pem`     : will break many server configurations, and should not be used
>                  without reading further documentation (see link below).

I should use the private key and the fullchain like I do.
Here is [the trace](https://imgur.com/a/1wOtkJg) for more details if you want

**Comment by Habbie** [comment] 2018-12-28 20:44
Hi, unless I'm mistaken, this looks like a support question, not a bug report. Please see https://www.powerdns.com/opensource.html to find out about our mailing lists and IRC channel, where you can get free and open support for dnsdist and other PowerDNS projects.

Closing this.

**Closed by Habbie** 2018-12-28 20:44 UTC

**Comment by Warok21** [comment] 2018-12-29 08:01
A little would have be great... Thanks
