### ISSUE TITLE
PowerDNS Multi-Tenancy Feature / WorkAround

### ISSUE THREAD

**Issue by MarcelMertens** [PowerDNS/pdns#10816] opened 2021-10-06 14:05 UTC
Hello,
we are an ManagedServiceProvider and looking for a multi tenant dns solution with a small footprint.
Requirements are simple:
- Public DNS Zone for all Tenants (_customerrecord_.public.domain.tld)
- Private DNS Zone for each Tenant (_customerrecord_.private.domain.tld)
- The private DNS Zone Domain Name must be the same for all Tenant.
- There could be identical records in different Private DNS Zones.
- The Tenant can be identified by the DNS-Request Source Address
- Create / Manage a new Tenant and individual tenant records should be possible via ReST API

Customer1 -> All DNS Requests comming from IP xx.xx.xx.yy
server1.private.domain.tld -> 192.168.0.11
server2.private.domain.tld -> 192.168.0.12
server3.private.domain.tld -> 192.168.0.13

Customer2 -> All DNS Requests comming from IP xx.xx.xx.zz
server1.private.domain.tld -> 192.168.1.11
server2.private.domain.tld -> 192.168.2.34
server3.private.domain.tld -> 192.168.0.13

I already managed this with Bind9 and Views, but Bind does not provide any API for this.

Any chance to archive with PowerDNS?

Kind Regards

**Comment by pieterlexis** [comment] 2021-10-06 14:42
I am closing this issue at it appears a support question and not a bug or issue. You also did not use the provided template that explains how to get support.

For you specific question, please provide the end goal and usecases. From a quick look at the requirements, PowerDNS, together with dnsdist can provide most of these requirements.

If you require support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

If you would like to engage with us in private to discuss your requirements and usecase, you can contact our [sales department](https://www.open-xchange.com/about-ox/contact-us/dns-solutions/).

**Closed by pieterlexis** 2021-10-06 14:42 UTC
