### ISSUE TITLE
Allow domain types to be PRIMARY/SECONDARY

### ISSUE THREAD

**Issue by promasu** [PowerDNS/pdns#12967] opened 2023-06-29 12:02 UTC
- Program: Authoritative
 - Issue type: Feature request

### Short description
Move domain types from MASTER/SLAVE to PRIMARY/SECONDARY

### Usecase
The naming inside the configuration has been moved from MASTER/SLAVE to PRIMARY/SECONDARY a couple of versions ago, but we still use MASTER/SLAVE in the database field domains.type and even for the column name domains.master.
We should align the naming everywhere in the software so in the database as well.

### Description
At least allow the field domains.type to be set to PRIMARY/SECONDARY in the database and maybe move on further by deprecating MASTER/SLAVE entirely.
Update of the database fields is easily possible by the administrators and therefore does not need to be handled by pdns.

**Comment by Habbie** [comment] 2023-06-29 12:14
duplicate of #9322

**Closed by Habbie** 2023-06-29 12:14 UTC
