### ISSUE TITLE
pdns_server crashes repeatedly on OpenBSD/sparc64

### ISSUE THREAD

**Issue by othyro** [PowerDNS/pdns#6742] opened 2018-06-17 15:36 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description

pdns_server crashes repeatedly on OpenBSD/sparc64.

### Environment

 - Operating system: OpenBSD 6.3 GENERIC.MP#486 sparc64
 - Software version: powerdns-4.1.1
 - Software source: Operating system repository ie. OpenBSD ports

[pdns.conf.txt](https://github.com/PowerDNS/pdns/files/2109114/pdns.conf.txt)

### Steps to reproduce

1. /etc/rc.d/pdns_server start; (watch logs); /etc/rc.d/pdns_server stop
2. To get the attached trace: ktrace -di /usr/local/sbin/pdns_server --daemon=yes & (wait a few seconds); /etc/rc.d/pdns_server stop; kdump -f ktrace.out > pdns_trace.txt

### Expected behaviour

Would be nice if the server started and ran as normal like it used to.

### Actual behaviour

[messages.txt](https://github.com/PowerDNS/pdns/files/2109121/messages.txt)

### Other information

[pdns_trace.txt](https://github.com/PowerDNS/pdns/files/2109122/pdns_trace.txt)

Note that valgrind isn't available on OpenBSD/sparc64.

**Comment by cmouse** [comment] 2018-06-17 15:42
are you able to get a core dump that you could use to get a backtrace with?

**Comment by cmouse** [comment] 2018-06-17 15:43
judging from the behavior you could start it with `gdb --args /usr/local/sbin/pdns_server --daemon=no` and then `run`, and once it crashes, issue 'bt full` and paste here?

**Comment by rgacogne** [comment] 2018-06-17 16:13
The trace shows that the server exited because of an unhandled exception:
> "terminate called after throwing an instance of 'PDNSException'"
"terminate called recursively"

It also looks like a core was dumped before exiting in a file named "pdns_server.core". You should be able to load it into gdb with `gdb /usr/local/sbin/pdns_server pdns_server.core` then issue a `bt full`.

**Comment by othyro** [comment] 2018-06-17 17:31
# gdb /usr/local/sbin/pdns_server  pdns_server.core                       
GNU gdb 6.3
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "sparc64-unknown-openbsd6.3"...
(no debugging symbols found)

Core was generated by `pdns_server'.
Program terminated with signal 6, Aborted.
(no debugging symbols found)
Loaded symbols for /usr/local/sbin/pdns_server
Reading symbols from /usr/lib/libcrypto.so.43.1...done.
Loaded symbols for /usr/lib/libcrypto.so.43.1
Reading symbols from /usr/local/lib/libsodium.so.9.1...done.
Loaded symbols for /usr/local/lib/libsodium.so.9.1
Reading symbols from /usr/local/lib/libsqlite3.so.37.2...done.
Loaded symbols for /usr/local/lib/libsqlite3.so.37.2
Reading symbols from /usr/lib/libz.so.5.0...done.
Loaded symbols for /usr/lib/libz.so.5.0
Reading symbols from /usr/lib/libpthread.so.25.1...done.
Loaded symbols for /usr/lib/libpthread.so.25.1
Reading symbols from /usr/local/lib/libestdc++.so.17.1...done.
Loaded symbols for /usr/local/lib/libestdc++.so.17.1
Reading symbols from /usr/lib/libm.so.10.1...done.
Loaded symbols for /usr/lib/libm.so.10.1
Reading symbols from /usr/lib/libc.so.92.3...done.
Loaded symbols for /usr/lib/libc.so.92.3
Reading symbols from /usr/libexec/ld.so...done.
Loaded symbols for /usr/libexec/ld.so
Reading symbols from /usr/local/lib/pdns/libgsqlite3backend.so...done.
Loaded symbols for /usr/local/lib/pdns/libgsqlite3backend.so
#0  *_libc_abort () at /usr/src/lib/libc/stdlib/abort.c:57
57               * it again, only harder.
(gdb) bt full
#0  *_libc_abort () at /usr/src/lib/libc/stdlib/abort.c:57
        mask = 4294967263
        sa = {__sigaction_u = {__sa_handler = 0x1d, __sa_sigaction = 0x1d}, 
  sa_mask = 4294967295, sa_flags = -251544}
#1  0x000000a68b302cb0 in __gnu_cxx::__verbose_terminate_handler ()
    at /usr/obj/ports/gcc-4.9.4/gcc-4.9.4/libstdc++-v3/libsupc++/vterminate.cc:50
        name = 0xfffffffffffc1860 ""
        terminating = true
        t = Variable "t" is not available.

**Comment by ahupowerdns** [comment] 2018-06-17 17:45
hi - does it really stop there? This trace looks weird, there is no frame 1 or 2? and "57 * it again, only harder", was that printed by gdb?

**Comment by othyro** [comment] 2018-06-18 01:10
That was copied and pasted straight from the terminal. I can run the process manually with gdb and post that output as well.

**Comment by othyro** [comment] 2018-09-28 15:36
> you could start it with `gdb --args /usr/local/sbin/pdns_server --daemon=no` and then `run`, and once it crashes, issue `bt full` and paste here?

Apologies for the late response. This just loops as if I started it via the RC script.

**Comment by omoerbeek** [comment] 2019-01-29 09:45
I have a sparc64 OpenBSD box, I'll update it and try to reproduce this week.

**Comment by omoerbeek** [comment] 2019-01-30 11:04
Can reproduce on OpenBSD 6.4 sparc64. Stack unwinding on exceptions goes wrong in some cases. Will update to current and see how that one fares.

**Comment by omoerbeek** [comment] 2019-01-30 12:15
On current this crashes as well. As this concerns the way C++ exceptions are handled, I'm asking advise on the OpenBSD ports mailing list.

**Comment by omoerbeek** [comment] 2019-02-01 08:18
Well, I've made some progress, currently building a patched gcc on my sparc64. That takes long.....

**Comment by omoerbeek** [comment] 2019-02-06 11:01
A compiler fix has been committed to OpenBSD/ports (fixing the exception handling). Together with the above unaligned access fix (to be backported on the OpenBSD port) auth now works on OpenBSD/sparc64.

**Closed by omoerbeek** 2019-02-06 11:01 UTC
Labels: auth, defect, response needed
