### ISSUE TITLE
cannot notify: Unable to convert presentation address

### ISSUE THREAD

**Issue by julian70400** [PowerDNS/pdns#8016] opened 2019-07-02 10:10 UTC
### Short description
When I try to notify my slave of existence of a second new domain, got this error from the master in logs :

Jul  2 11:42:45 vps692141 pdns_server[8561]: Jul 02 11:42:45 Weird, trying to send a message that needs truncation, 39 > 0
Jul  2 11:42:45 vps692141 pdns_server[8561]: Jul 02 11:42:45 Weird, trying to send a message that needs truncation, 39 > 0
Jul  2 11:42:45 vps692141 pdns_server[8561]: Jul 02 11:42:45 Weird, trying to send a message that needs truncation, 39 > 0
Jul  2 11:42:50 vps692141 pdns_server[8561]: Jul 02 11:42:50 1 domain for which we are master needs notifications
Jul  2 11:42:50 vps692141 pdns_server[8561]: Jul 02 11:42:50 Error looking up name servers for mydomain.ovh, cannot notify: Unable to convert presentation address '#01146.105.56.95'

### Environment
 - Operating system: SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
 - Software version: 4.0.3
 - Software source: .deb

### Steps to reproduce

1. adding new domain
2.  pdns_control notify mydomain.ovh
3. look the logs

### Expected behaviour
show my new domain on my slave

### Other information
**My master conf :**
```
allow-axfr-ips=127.0.0.1 51.68.120.47
allow-recursion=127.0.0.1
config-dir=/etc/powerdns
daemon=yes
disable-axfr=no
guardian=yes
local-address=0.0.0.0
local-port=53
master=yes
slave=no
launch=
module-dir=/usr/lib/x86_64-linux-gnu/pdns
setgid=pdns
setuid=pdns
socket-dir=/var/run
version-string=anonymous
include-dir=/etc/powerdns/pdns.d
logging-facility=0
#log-dns-details=yes
#log-dns-queries=yes
loglevel=3
local-ipv6=
gmysql-dnssec=no
```

**My Slave conf :**
```
allow-axfr-ips=127.0.0.1
allow-notify-from=51.83.73.20
allow-recursion=127.0.0.1
config-dir=/etc/powerdns
daemon=yes
disable-axfr=no
guardian=yes
launch=
local-address=0.0.0.0
local-port=53
master=no
slave=yes
module-dir=/usr/lib/x86_64-linux-gnu/pdns
setgid=pdns
setuid=pdns
socket-dir=/var/run
version-string=powerdns
include-dir=/etc/powerdns/pdns.d
slave-cycle-interval=60
gmysql-dnssec=no

```

Important : I notifyed a first domain, and this works, but a second one do not.

**Comment by Habbie** [comment] 2019-07-02 10:12
Please run `pdnsutil check-zone` on your domain.

**Comment by pieterlexis** [comment] 2019-07-02 10:14
```
 Jul 2 11:42:50 vps692141 pdns_server[8561]: Jul 02 11:42:50 Error looking up name servers for mydomain.ovh, cannot notify: Unable to convert presentation address '#1146.105.56.95'
```

This means you have `#1146.105.56.95` in your `masters` field in the `domains` table for `mydomain.ovh`, which is indeed a garbage IP address

**Comment by pieterlexis** [comment] 2019-07-02 10:14
I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2019-07-02 10:14 UTC
