### ISSUE TITLE
TXT return 422 

### ISSUE THREAD

**Issue by FryShadow** [PowerDNS/pdns#7840] opened 2019-05-22 07:34 UTC
- Program: Authoritative

Issue :
With PHP curl api, tried to add TXT records with the same content but on different domain

1. himydomain.com TXT "v=spf1 include:mailgun.org ~all"
2. apps.himydomain.com TXT "v=spf1 include:mailgun.org ~all"

 - Operating system : CentOS 7
 - Software version: PHP 7 , PDNS 4.1.8 

1. Add (1) from php curl api return http_code 204
2. Add (2) from php curl api return http_code 422 (error) and records not added

Is it a bug for a duplicate entry ?

**Comment by Habbie** [comment] 2019-05-22 11:21
Can you please show your full curl/HTTP call, and full response?

**Comment by FryShadow** [comment] 2019-05-22 14:37
Current and new TXT records will pass thru as per below :

` [rrsets] => Array
        (
            [0] => Array
                (
                    [name] => apps.hidomain.com.
                    [type] => TXT
                    [ttl] => 3600
                    [changetype] => REPLACE
                    [records] => Array
                        (
                            [0] => Array
                                (
                                    [content] => "v=spf1 include:mailgun.org ~all"
                                    [disabled] => 
                                )

                            [1] => Array
                                (
                                    [content] => "v=spf1 include:mailgun.org ~all"
                                    [disabled] => 
                                )

                            [2] => Array
                                (
                                    [content] => "k=rsa; p=content-strip"
                                    [disabled] => 
                                )

                            [3] => Array
                                (
                                    [content] => "k=rsa; p=content-strip"
                                    [disabled] => 
                                )

                        )

                )

        )`

```
$headers = [
                    'Accept: application/json',
                    'Content-Type: application/json; charset=utf-8',
                    'X-API-Key: '.$this->pdnskey,];

                $ch = curl_init();
                      curl_setopt($ch, CURLOPT_URL, $this->pdnsurl.'/'.$zone->domain);
                      curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
                      curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PATCH');
                      curl_setopt($ch, CURLOPT_TIMEOUT, 100);
                      curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                      curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($rrsets));
                      
                $response = json_decode(curl_exec($ch));

$http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
```

With http_code normal reply will get 204 and as per question earlier will get 422. 
If the new TXT records is not the same like I change to "v=spf1 include:gmail.com ~all" will return a success with http_code 204.

**Comment by Habbie** [comment] 2019-05-22 19:49
```
[0] => Array
                                (
                                    [content] => "v=spf1 include:mailgun.org ~all"
                                    [disabled] => 
                                )

                            [1] => Array
                                (
                                    [content] => "v=spf1 include:mailgun.org ~all"
                                    [disabled] => 
                                )
```

These two records are identical. Please remove one.

**Comment by Habbie** [comment] 2019-05-22 19:56
I'm closing this as it is a support request, not a bug report. If you need more help, please find us on IRC or our mailing lists. All information is at https://www.powerdns.com/opensource.html

**Closed** 2019-05-23 07:26 UTC
