### ISSUE TITLE
pdnsutil domain_id always 0

### ISSUE THREAD

**Issue by coeurtech** [PowerDNS/pdns#10173] opened 2021-03-13 10:06 UTC
### Short description
pdnsutil seems to always reference domain_id 0 when executing tasks

### Environment
Solaris 11.4, MySQL 8.0.23, pdns 4.4.1
Compiled using gcc 5.5

### Steps to reproduce
After getting everything compiled,  setting up the schema in mysql, and getting everything configured, pdns starts fine.  I then proceeded to run a "pdnsutil test-schema example.com"

### Expected behaviour
Test would complete without issue

### Actual behaviour
SIGABRT on pdnsutil, core dumped, due to SQL failures

pdnsutil INSERTS example.com into domains table without issue, domain_id = 1:

2021-03-13T08:59:10.509974Z        93 Prepare   insert into domains (type,name,master,account,last_check,notified_serial) values(?,?,?,?,NULL,NULL)
2021-03-13T08:59:10.510243Z        93 Execute   insert into domains (type,name,master,account,last_check,notified_serial) values('SLAVE','example.com','127.0.0.1','_testschema',NULL,NULL)
2021-03-13T08:59:10.526498Z        93 Reset stmt

pdnsutil then performs SELECT statements to obtain domain information and existing records, the select statements were verified in MySQL CLI:

2021-03-13T08:59:10.527063Z        93 Prepare   select id,name,master,last_check,notified_serial,type,account from domains where name=?
2021-03-13T08:59:10.527234Z        93 Execute   select id,name,master,last_check,notified_serial,type,account from domains where name='example.com'
2021-03-13T08:59:10.527917Z        93 Reset stmt
2021-03-13T08:59:10.528753Z        93 Prepare   SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?
2021-03-13T08:59:10.528925Z        93 Execute   SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type='SOA' and name='example.com'
2021-03-13T08:59:10.529620Z        93 Reset stmt

Then pdnsutil performs cleanup and tries to insert a SOA, but notice the value for domain_id, it is 0:

2021-03-13T08:59:10.529917Z        93 Query     begin
2021-03-13T08:59:10.530267Z        93 Prepare   delete from records where domain_id=?
2021-03-13T08:59:10.530411Z        93 Execute   delete from records where **domain_id=0**
2021-03-13T08:59:10.530800Z        93 Reset stmt
2021-03-13T08:59:10.531211Z        93 Prepare   insert into records (content,ttl,prio,type,domain_id,disabled,name,ordername,auth) values (?,?,?,?,?,?,?,?,?)
2021-03-13T08:59:10.531497Z        93 Prepare   insert into records (content,ttl,prio,type,domain_id,disabled,name,ordername,auth) values (?,?,?,?,?,?,?,?,?)
2021-03-13T08:59:10.531572Z        93 Execute   insert into records (content,ttl,prio,type,domain_id,disabled,name,ordername,auth) values ('ns1.example.com. ahu.example.com. 2012081039 7200 3600 1209600 3600',**0**,0,'SOA',0,0,'example.com',NULL,1)
2021-03-13T08:59:10.532699Z        93 Close stmt

**Comment by Habbie** [comment] 2021-03-15 11:10
Hello! I cannot reproduce this failure on Debian Buster, MySQL 8.0.23, pdns 4.4.1, gcc 8.3.0. Can you please give us:

* the full output from `pdnsutil test-schema`
* your full configure+make log
* any patches you applied to make pdns compile
* a dump of your database after the crash

Thanks!

**Comment by coeurtech** [comment] 2021-03-16 20:25
Hi there!  I didn't patch anything but I did need to compile LUA as a shared library... unfortunately the default Makefile doesn't have that coded (I used http://lua-users.org/lists/lua-l/2006-10/msg00091.html as a reference to adjust the Makefiles in the LUA tarball).  Attached the database dump and console configure output.  I don't have the make output but I can go back and re-compile.

FULL OUTPUT:
```
pdns@BTSVLKATn01:~$ bin/pdnsutil test-schema example.com
Note: test-schema will try to create the zone, but it will not remove it.
Please clean up after this.

If this test reports an error and aborts, please check your database schema.
Constructing UeberBackend
Picking first backend - if this is not what you want, edit launch line!
Creating slave domain example.com
Slave domain created
Starting transaction to feed records
Feeding SOA
Abort(coredump)
```
[powerdnsdbdump.txt](https://github.com/PowerDNS/pdns/files/6151172/powerdnsdbdump.txt)

[powerdns_configure.txt](https://github.com/PowerDNS/pdns/files/6151776/powerdns_configure.txt)

[config.log](https://github.com/PowerDNS/pdns/files/6151777/config.log)

Thanks!

**Comment by Habbie** [comment] 2021-03-16 20:46
Do you think you can get a gdb backtrace out of this? With symbols perhaps?

**Comment by coeurtech** [comment] 2021-03-16 20:56
I can do mdb... Solaris... gotta be different :)

root@BTSVLKATn01: mdb sbin/pdns_server ./core
Loading modules: [ libc.so.1 ld.so.1 ]
> $c
libc.so.1`__lwp_sigqueue+8(6, ffffffff7fff8b20, 5, 5, 0, 0)
libc.so.1`abort+0x10c(1, 1000, 6, 0, 1bc894, 1000)
libgcc_s.so.1`uw_init_context_1+0xa0(ffffffff7fff9460, ffffffff7fffa320, ffffffff575db60c, ffffffff575db60c, ffffffff7fff8cd0, ffffffff5fb0f510)
libgcc_s.so.1`_Unwind_RaiseException+0x14(100749570, 1004b1638, 1, ffffffff7fff9460, 0, 0)
libstdc++.so.6.0.21`__cxa_throw+0x70(100749590, 100530a60, 100399bc8, ffffffff7e502a80, 1, 100749570)
_ZN15SMySQLStatement7executeEv+0x1288(10073d1b0, ffffffff7fffa998, 1, 10039e268, ffffffff58d02840, 100749590)
_ZN11GSQLBackend10feedRecordERK17DNSResourceRecordRK7DNSNameb+0x4a8(100733220, ffffffff58d02840, ffffffff7fffec28, 10039d384, ffffffff7fffa998, 10073d1b0)
main+0x2908(100113260, 100113200, 1001132a8, ffffffff7fffec29, ffffffff58d02840, 100733220)
_start+0x7c(0, 0, 0, 0, 0, 0)

I know why it's aborting, when executing "insert into records (content,ttl,prio,type,domain_id,disabled,name,ordername,auth) values ('ns1.example.com. ahu.example.com. 2012081039 7200 3600 1209600 3600',0,0,'SOA',0,0,'example.com',NULL,1)" it fails because domain_id is 0 instead of 1 (I have run the foreign key SQL provided with the source code so that is enforcing the relationship).

What I'm boggled with is why "select id,name,master,last_check,notified_serial,type,account from domains where name='example.com'" in the code results with id = 0.  Running that same statement using the mysql CLI clearly shows id = 1.
```

mysql>use powerdns;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql>select id,name,master,last_check,notified_serial,type,account from domains where name='example.com'
    -> ;
+----+-------------+-----------+------------+-----------------+-------+-------------+
| id | name        | master    | last_check | notified_serial | type  | account     |
+----+-------------+-----------+------------+-----------------+-------+-------------+
|  1 | example.com | 127.0.0.1 |       NULL |            NULL | SLAVE | _testschema |
+----+-------------+-----------+------------+-----------------+-------+-------------+
1 row in set (0.00 sec)

```

**Comment by zeha** [comment] 2021-03-21 21:46
I think we also want to see your full pdns configuration files...

**Comment by coeurtech** [comment] 2021-03-24 14:55
launch=gmysql
gmysql-socket=/opt/app/powerdns/var/run/mysql.sock
gmysql-password=<DELETED FROM OUTPUT>
local-address=0.0.0.0, ::
local-port=53
log-dns-details=yes
log-dns-queries=yes
log-timestamp=yes
query-logging=yes
setgid=pdns
setuid=pdns
write-pid=yes

**Comment by Habbie** [comment] 2022-11-28 14:29
Sorry, I'm closing this, as we have been unable to reproduce it. Please let us know if you have any additional information, or reproduction on a newer version.

**Closed by Habbie** 2022-11-28 14:29 UTC
Labels: auth
