### ISSUE TITLE
Recursor API needs --forward-zones in recursor.conf not on command line

### ISSUE THREAD

**Issue by johnyb** [PowerDNS/pdns#5421] opened 2017-06-16 16:51 UTC
- Program: Recursor
 - Issue type: Bug report

### Short description

Providing forward-zones parameter via CLI and using the HTTP API afterwards leads to problems when using HTTP API.

### Environment
 - Operating system: centos
 - Software version: master
 - Software source: PowerDNS repository

### Steps to reproduce
1. make sure,  `forward-zones` is not part of recursor.conf
2. start a pdns_recursor instance with `--forward-zones=`, `--api-config-dir=/tmp/pdns`, and `--include-dir=/tmp/pdns` parameter set via cli arguments
3. create a new forwarded zone via API

### Expected behaviour

no error when creating Forwarded zone; forwarded zone can be resolved via recursor

### Actual behaviour

error is returned (“Could not find domain …”); resolving the domain not possible

### Other information

It seems, the `--forward-zones=` parameter overrides everything in config files. If you leave this parameter, recursor won't start:
`
pdns_rec_1    | Jun 16 15:28:18 Exception: Incremental parameter 'forward-zones' without a parent
`
If you add the parameter, everything configured in config files will be overridden by the parameter.

Everything works fine if you add `forward-zones=` to the recursor.conf file and not provide it via cli argument.

------

Ping johnyb in IRC for any questions about this, that do not fit into this ticket

**Comment by johnyb** [comment] 2017-06-16 16:52
This might even be intended behaviour, but it took me quite a while to figure out, why this was not working.

**Comment by johnyb** [comment] 2017-06-16 17:05
May be, this is not just only a bug report, but a feature request. My use-case was the following:

1. create a minimal recursor setup without forward-zones in recursor.conf
2. forwarded zones should be managed via API

my minimal config files looks like this:
```
api-key = mimimi
api-config-dir = /tmp
daemon = no
local-address = [::]:53
webserver = yes
webserver-address = ::
```

This will allow the API to create new zone configurations in `/tmp` directory. This will not work without `include-dir=/tmp` being set. If you do set this parameter, it will still not work because of the error: `pdns_rec_1 | Jun 16 15:28:18 Exception: Incremental parameter 'forward-zones' without a parent`. So setting it initially is mandatory. This can currently only be done via config file, *not* via CLI.

**Comment by zeha** [comment] 2017-06-17 00:58
This is a limitation of the current option parser IIRC.

This page could say that the options need to go into the .conf file though:
https://doc.powerdns.com/md/httpapi/README/#try-it-recursor-edition

**Comment by zeha** [comment] 2017-06-18 21:17
BTW, you should also add `forward-zones-recurse=` to the conf file, in case you create such zones.

**Comment by Habbie** [comment] 2017-06-19 15:49
Duplicate of #5376

**Closed by Habbie** 2017-06-19 15:49 UTC
Labels: docs, rec, web
