### ISSUE TITLE
Memory leak when using API (list of all zones) on authoritative server (4.2.1)

### ISSUE THREAD

**Issue by aldem** [PowerDNS/pdns#8643] opened 2019-12-18 15:29 UTC
- Program: Authoritative, 4.2.1
 - Issue type: Bug report

### Short description
I periodically run house-keeping tasks to make sure that all slaves are in sync with master (mostly to sync deleted zones on slaves), and use API request "GET /api/v1/servers/localhost/zones" to get list of all zones and their serial.

Over time, I have noticed huge memory usage on slaves (> 5G), despite low-capacity caches (200K entries) and relatively low query-rate (< 200 qps).

Further investigation, i.e. running above mentioned request multiple times in a row has revealed the problem:
![image](https://user-images.githubusercontent.com/754722/71097300-16480200-21b0-11ea-9cb8-4a7c5fb5b5e7.png)

Beginning of the graph is a state before any API request, the rest is when I started to query list of zones in a loop - as you could see, with every request memory usage is increasing, and in less than 10 minutes it is 10x more than initially. Each request took ca. 15-20 seconds to execute.

There are ca. 150K zones in the sqlite3 backend (ca. 200 of them are DNSSEC protected, though I am not sure if this is relevant as this is slave only), all updates from master are done using AXFRs, though it seems that only API calls (at least list of zones) are causing this behavior.

The problem was present in v4.2.0 too, though I could not link it to memory leak at first.

### Environment
 - Operating system: CentOS 7.7.1908, 64bit
 - Software version: PowerDNS Authoritative Server 4.2.1 + sqlite3 backend
 - Software source: official PowerDNS repo, 4.2.1-1pdns.el7

### Steps to reproduce
1. Create bunch of zones in sqlite3 backend (> 100K), mark them as slave
2. Enable webserver & API access
2. Run `curl -H "X-API-Key: api-key" http://localhost:8081/api/v1/servers/localhost/zones` in a loop and watch memory usage

My configuration:
```
allow-axfr-ips=...
allow-dnsupdate-from=...
allow-notify-from=...
api=yes
api-key=api-key
axfr-lower-serial=yes
cache-ttl=60
carbon-interval=60
default-api-rectify=yes
default-soa-mail=dns-master.example.com
default-soa-name=ns1.example.com
disable-syslog=yes
distributor-threads=1
dname-processing=yes
dnssec-key-cache-ttl=300
dnsupdate=yes
expand-alias=yes
launch=gsqlite3
gsqlite3-database=/var/lib/pdns/pdns.sqlite
gsqlite3-pragma-synchronous=1
gsqlite3-pragma-foreign-keys=1
gsqlite3-dnssec=1
# allow any supermaster regardless of name
gsqlite3-supermaster-query=select account from supermasters where ip=:ip
local-port=53
log-timestamp=no
master=no
max-packet-cache-entries=200000
max-cache-entries=200000
resolver=127.0.0.1:53
retrieval-threads=16
reuseport=yes
server-id=dns
setuid=pdns
slave=yes
# v4.2.0+
superslave=yes
trusted-notification-proxy=127.0.0.1
udp-truncation-threshold=1232
webserver=yes
webserver-address=0.0.0.0
webserver-allow-from=127.0.0.1,::1
webserver-port=8081
```

### Expected behaviour
Memory usage is not increased over time after each API request.

### Actual behaviour
Every API call to get list of zones significantly increases memory usage, and it is never released.

**Comment by rgacogne** [comment] 2019-12-23 15:31
I am unable to reproduce this issue using our 4.2.1 package on CentOS 7.7.1908:
- installing pdns, pdns-backend-sqlite 4.2.1 1pdns.el7 ;
- creating 100k empty zones via `pdnsutil create-zone`; set their kind as `slave` and master to `192.0.2.1` directly in the database ;
- starting `pdns` with the configuration provided above ;
- sending `curl -H "X-API-Key: api-key" http://localhost:8081/api/v1/servers/localhost/zones` queries in a loop.

This unfortunately does not result in a growing memory usage for me, observed with carbon/metronome and via top. It might be that the content of the zones actually matters, would you by any chance be able to share a minimal content that does reproduce the issue?

**Comment by aldem** [comment] 2019-12-23 16:37
Unfortunately, I could not share actual content, but what I did not mention yet (I didn't expect that content might matter) - some of those zones (ca. 270) are secured, thus slaves got additionally RRSIG records in AXFR, and populating domainmetadata with 'PRESIGNED' and 'NSEC3PARAM' records.

Most of the zones are pretty small, having usually couple of A and MX records, plus 3 NS records each, some have a bit rare RRs like NAPTR and SRV, and plenty (ca 1/3) have few CNAME and TXT records.

Actually, DNSSEC related content might be the one which is actually making issues, as this is the only thing that makes slave zones look different on slaves, but I will make a few tests with master (just to be sure).

**Comment by rgacogne** [comment] 2019-12-24 13:11
Thank you for the additional details! I tried adding a few secured zones but that doesn't trigger a leak either for me (I tested on Arch this time, but I don't expect any difference on CentOS 7).
Any chance you could run one of the slave under valgrind (with `--leak-check=full`) for a short while? If you do, please clear the caches (`pdns_control purge`) before stopping the server (`pdns_control quit`) to get a clean report. If you can't run it under valgrind, I would still be interested in knowing if `pdns_control purge` has any effect on the memory consumption.

**Comment by aldem** [comment] 2019-12-24 15:07
It seems that this is not memory leak but memory hog, probably related to memory fragmentation while processing huge amounts of data (list of zones in JSON is really big).

First time I didn't let it run long enough to avoid OOM, but now I have got the courage:

![image](https://user-images.githubusercontent.com/754722/71417111-e68f7300-2663-11ea-877f-e9d919f96193.png)

As you could see, stable usage (few days in normal mode, no API calls, just queries) is really stable and is about 1G (quite acceptable). But once I started to request list of zones, it quickly grows, and then, after ca. 50 requests, it becomes stable again, though consuming 6x more RAM.  `pdns_control purge` did help but just a bit.

Additional research reveals that maximum (stable) memory usage is indeed depends on content (amount and probably actual content of records), interesting fact is that master consumes ca. 2x less RAM (requesting zone list) than slave on same content (tested with 100K zones with 1000 secured).

And while this is not memory leak (probably issue title should be changed), I believe that it still make sense to investigate and somehow reduce memory consumption as it is way too high...

**Comment by rgacogne** [comment] 2019-12-24 15:35
Thanks for following up! So the memory you get back after calling `pdns_control purge` is used by the metadata and keys caches that are being filled up by the API calls. They might have got filled by regular queries eventually but this is much more faster.
The part that you don't get back, though, is very weird. It looks like the memory allocator is not reusing the previously allocated memory pages correctly, otherwise we should not grow much more after the first call..

**Comment by zeha** [comment] 2019-12-24 15:47
How many visible CPU cores does this machine have?

**Comment by aldem** [comment] 2019-12-24 17:20
Only 2 cores.

I did another test (another slave node, same OS, dataset and configuration, only 4 cores) - requested all RRs (which are in the database) twice from the slave (~ 320K queries/run, with caches set to 200K entries), this resulted in stable memory usage ~ 250M, requesting list of zones increased this to ~ 1G and stays like this.

The only difference to original node producing high RAM usage is that it is serving queries (on average 110 qps), the second one is doing nothing, but running queries in parallel to requesting list of zones didn't change anything.

**Comment by rgacogne** [comment] 2019-12-26 09:16
> I did another test (another slave node, same OS, dataset and configuration, only 4 cores) - requested all RRs (which are in the database) twice from the slave (~ 320K queries/run, with caches set to 200K entries), this resulted in stable memory usage ~ 250M, requesting list of zones increased this to ~ 1G and stays like this.

I'm guessing this does not populate the metadata and key caches the way requesting the zone information via the API does? This can be checked using `pdns_control show 'key-cache-size'` and `pdns_control show 'meta-cache-size'`.

**Comment by rgacogne** [comment] 2019-12-26 09:19
Oh, I missed the second part of the sentence, sorry! So it would be interesting to have a look at the traffic the first slave is receiving, any chance you would be able to do a PCAP capture and replay it to the second slave via `dnsreplay`?

**Comment by rgacogne** [comment] 2020-02-11 11:28
Very likely related to: https://github.com/PowerDNS/pdns/issues/8449#issuecomment-584080508

**Comment by aldem** [comment] 2020-02-11 16:09
@rgacogne seems so - I did a quick test and memory usage is now stable (more or less) at ca. 500M on same dataset (with MALLOC_ARENA_MAX=1).

I will make more tests on more systems and see what happens.

**Comment by zeha** [comment] 2020-11-08 18:15
Is this still a problem, esp. with the MALLOC settings changed?

**Comment by Habbie** [comment] 2020-11-08 20:14
Let's close this in a week if there's no news.

**Comment by aldem** [comment] 2020-11-09 16:32
Sorry guys... forgot about this issue.

No, there are no problems anymore - memory usage is stable and low enough, could be even operated on 1G RAM system.

Perhaps this trick with MALLOC_ARENA_MAX could be added to the documentation or even enabled by default as I see no downsides.

**Comment by Habbie** [comment] 2020-11-09 16:33
Thanks! We put it in the docs a while ago, at https://doc.powerdns.com/authoritative/performance.html?highlight=malloc_arena_max#caches-memory-allocations-glibc

Closing ticket!

**Closed by Habbie** 2020-11-09 16:33 UTC
Labels: auth, defect
