### ISSUE TITLE
rec: forward-zones with ProxyProtocol servfailed

### ISSUE THREAD

**Issue by Bodenhaltung** [PowerDNS/pdns#14355] opened 2024-06-18 16:06 UTC
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Recursor
 - Issue type: Bug report

### Short description
If ProxyProtocol enabled, forward-zones failed with a timeout / servfail.

### Environment
 - Operating system: Debian
 - Software version: PowerDNS Recursor 5.0.6
 - Software source: PowerDNS repository, compiled yourself

### Steps to reproduce
1. Configure DNSdist with a Recursor and Auth with ProxyProtocol (`useProxyProtocol=true`)
2. Configure ProxyProtocol in PowerDNS Recursor and Auth with `proxy-protocol-from`)
3. Configure a forward-zone in Recursor to the Authoritative Server

### Expected behaviour
Forward the Zone to Auth and showing the Answer(s). :)

### Actual behaviour

```
 dig @stage01 resolve.bar

; <<>> DiG 9.16.48-Debian <<>> @stage01 resolve.bar
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 6799
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
; EDE: 22 (No Reachable Authority): (delegation resolve.bar)
;; QUESTION SECTION:
;resolve.bar.                   IN      A

;; Query time: 1792 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Tue Jun 18 17:58:32 CEST 2024
;; MSG SIZE  rcvd: 68
```
Recursor trace-regex:
```
 us === START OF TRACE 2024-06-18T17:58:30.386 ===
179 QM resolve.bar: doResolve
188 resolve.bar: Wants DNSSEC processing, auth data required by query for A
196 QM resolve.bar: Step0 Not cached
197 QM resolve.bar: Step0 qname is in a forwarded domain resolve.bar
198 QM resolve.bar: Step2 New child resolve.bar
205 QM resolve.bar: Step3 Going to do final resolve
206 resolve.bar: Wants DNSSEC processing, auth data required by query for A
208 resolve.bar: No cache hit for 'resolve.bar|A', trying to find an appropriate NS record
209 resolve.bar: Checking if we have NS in cache for 'resolve.bar'
211 resolve.bar: No valid/useful NS in cache for 'resolve.bar'
211 resolve.bar: Checking if we have NS in cache for 'bar'
219 resolve.bar: No valid/useful NS in cache for 'bar'
219 resolve.bar: Checking if we have NS in cache for '.'
225 resolve.bar: NS (with ip, or non-glue) in cache for '.' -> 'l.root-servers.net', within bailiwick: 1, in cache, ttl=3599979
234 resolve.bar: NS (with ip, or non-glue) in cache for '.' -> 'j.root-servers.net', within bailiwick: 1, in cache, ttl=3599979
240 resolve.bar: NS (with ip, or non-glue) in cache for '.' -> 'f.root-servers.net', within bailiwick: 1, in cache, ttl=3599979
242 resolve.bar: NS (with ip, or non-glue) in cache for '.' -> 'h.root-servers.net', within bailiwick: 1, in cache, ttl=3599979
245 resolve.bar: NS (with ip, or non-glue) in cache for '.' -> 'd.root-servers.net', within bailiwick: 1, in cache, ttl=3599979
247 resolve.bar: NS (with ip, or non-glue) in cache for '.' -> 'b.root-servers.net', within bailiwick: 1, in cache, ttl=3599979
249 resolve.bar: NS (with ip, or non-glue) in cache for '.' -> 'k.root-servers.net', within bailiwick: 1, in cache, ttl=3599979
251 resolve.bar: NS (with ip, or non-glue) in cache for '.' -> 'i.root-servers.net', within bailiwick: 1, in cache, ttl=3599979
253 resolve.bar: NS (with ip, or non-glue) in cache for '.' -> 'm.root-servers.net', within bailiwick: 1, in cache, ttl=3599979
255 resolve.bar: NS (with ip, or non-glue) in cache for '.' -> 'e.root-servers.net', within bailiwick: 1, in cache, ttl=3599979
261 resolve.bar: NS (with ip, or non-glue) in cache for '.' -> 'g.root-servers.net', within bailiwick: 1, in cache, ttl=3599979
263 resolve.bar: NS (with ip, or non-glue) in cache for '.' -> 'c.root-servers.net', within bailiwick: 1, in cache, ttl=3599979
265 resolve.bar: NS (with ip, or non-glue) in cache for '.' -> 'a.root-servers.net', within bailiwick: 1, in cache, ttl=3599979
271 resolve.bar: We have NS in cache for '.' (flawedNSSet=0)
272 resolve.bar authOrForwDomain: resolve.bar nsFromCacheDomain: . isPartof: 1
273 resolve.bar: Using forwarder as NS
276 resolve.bar: Cache consultations done, have 1 NS to contact
281 resolve.bar: Domain has hardcoded nameserver
286 resolve.bar: Nameservers: -127.0.0.1:5353(0.00ms)
291 resolve.bar: Resolved 'resolve.bar' NS (empty) to: 127.0.0.1
293 resolve.bar: Trying IP 127.0.0.1:5353, asking 'resolve.bar|A'
1792641 resolve.bar: Timeout resolving after 1792.31 ms
1792686 resolve.bar: Failed to resolve via any of the 1 offered NS at level 'resolve.bar'
1792690 resolve.bar: Failed (res=-1)
1792693 QM resolve.bar: Step3 Final resolve: Server Failure/0
=== END OF TRACE 2024-06-18T17:58:32.179 ===
```

127.0.0.1:5353:
```
sdig 127.1 5353 resolve.bar A proxy 0 1.2.3.4:99 5.6.7.8:100
Reply to question for qname='resolve.bar.', qtype=A
Rcode: 0 (No Error), RD: 0, QR: 1, TC: 0, AA: 1, opcode: 0
0       resolve.bar.    600     IN      A       45.86.125.66
0       resolve.bar.    600     IN      A       45.86.125.67
```

**Comment by omoerbeek** [comment] 2024-06-18 16:13
Thanks for the report.
When you initially told me about this I understood enabling proxy protocol in rec (on the incoming side) would break forwarding. But from this report the auth you're forwarding to expects the proxy protocol headers
But at the moment rec cannot not add those, so it cannot talk to the auth it is using as a forwarding target, hence it ServFails, as expected. This looks like a duplicate of #11931

**Closed** 2024-06-18 16:23 UTC
Labels: rec
