### ISSUE TITLE
Can`t install dnsdist on raspberry pi 4

### ISSUE THREAD

**Issue by mydevice** [PowerDNS/pdns#9230] opened 2020-06-15 12:39 UTC
Hello,

I try to install dnsdist on raspberry pi 4 

From the repo.powerdns.com and i get this error:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dnsdist : Depends: libprotobuf10 but it is not installable
           Depends: libre2-3 (>= 20131024+dfsg) but it is not installable
           Depends: libsodium18 (>= 1.0.3) but it is not installable
E: Unable to correct problems, you have held broken packages.

can you provide some guide to install the dependencies ?

Thank you.

**Comment by pieterlexis** [comment] 2020-06-15 12:59
Can you tell us what OS you're running on your pi? What and repo you've added?

**Comment by spirillen** [comment] 2020-06-15 13:03
Just to post the "dummy" :question: have you tried

```
apt install -f
```

to install unmet  dependencies

**Comment by mydevice** [comment] 2020-06-15 13:36
@pieterlexis the os is Raspbian GNU/Linux 10 \n \l

@spirillen  0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by pieterlexis** [comment] 2020-06-15 13:45
`libre2` is shipped in the repository. From the [Packages](http://archive.raspbian.org/raspbian/dists/buster/main/binary-armhf/Packages):

```
Package: libre2-5
Source: re2
Version: 20190101+dfsg-2
Architecture: armhf
[...]
Priority: optional
Section: libs
Filename: pool/main/r/re2/libre2-5_20190101+dfsg-2_armhf.deb
[...]
```

However, you package depends on `libre2-3` (not `libre2-5`). You probably have added the Debian 9  (stretch) repo instead of the 10 (buster) repo for dnsdist to your apt sources. Please check and correct this.

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2020-06-15 13:45 UTC
