### ISSUE TITLE
Serial 0 in SOA record

### ISSUE THREAD

**Issue by sadequenoor** [PowerDNS/pdns#9091] opened 2020-05-06 22:57 UTC
I have installed Authoritative Server 4.3.0-1pdns.e17 on 3 identical Centos 7 machines. 
I have 1 master and 2 slaves.

When I add a SOA record with serial 0 into the records table, the notified_serial in the domains table is changed to 0 on the master. On the slaves the notified_serial is set to NULL in the domains table. Everything else looks like it is the same, the entries all replicate with the exception of this one cell value.

**Comment by Habbie** [comment] 2020-05-07 11:59
If I understood correctly (from IRC discussion), the problem is that the 0 serial correctly replicates to the slave via AXFR, but the slave then keeps saying it does not have the zone, because we treat the zero serial wrong.

**Comment by zeha** [comment] 2020-11-09 22:00
Didn't @mind04 fix this recently?

**Comment by mind04** [comment] 2020-11-09 22:07
Yes, fixed in #9649

**Comment by zeha** [comment] 2020-11-09 22:09
> Yes, fixed in #9649

I was thinking about another PR, but can't remember which one :(

**Comment by Habbie** [comment] 2020-11-18 21:17
As far as I know, this should work in 4.4. Closing this. Please report back if you find otherwise!

**Closed by Habbie** 2020-11-18 21:17 UTC
Labels: auth, defect
