### ISSUE TITLE
could not reset statistics on pdns-recursor, dnsdist, pdns-authoritative

### ISSUE THREAD

**Issue by maxadamo** [PowerDNS/pdns#11366] opened 2022-02-25 14:19 UTC
- Program: Authoritative, Recursor, dnsdist
 - Issue type: could not reset statistics

### Short description

Let's make it easy. [Unbound](https://nlnetlabs.nl/documentation/unbound/howto-statistics/) has a configuration setting as follows:
```
statistics-cumulative: no
```
If I set it to `no` every time I query the endpoint, the metric counters are being reset. 

### Usecase

I need an easy way to extract the usage rate instead of the grand total. 

### Description

I think a kill SIGNAL would suffice, but for instance, I tried a SIGHUP against the recursor the daemon died.

**Comment by Habbie** [comment] 2022-02-25 14:22
duplicate of #9030

**Closed by Habbie** 2022-02-25 14:22 UTC
