### ISSUE TITLE
Can not add MX record via API

### ISSUE THREAD

**Issue by BadikovVV** [PowerDNS/pdns#12671] opened 2023-03-22 09:51 UTC
- Program: Authoritative 
 - Issue type: Bug report

### Environment

 - Operating system: Ubuntu 20.04.5 LTS
 - Software version: PowerDNS Authoritative Server 4.6.4 
 - Software source: 

### Steps to reproduce

1. When manipulating with DNS MX record via API ,
set   "content": "1  mx.aa.dd.cc." ( two or more blanks after '1')
 and you will get error 
 '{"error": "Record mk8s.myvvb.local./MX \'1  mx.myvvb.local.\': Not in expected format (parsed as \'1 mx.myvvb.local.\')"}'
2. with only one blank after '1' -all is OK!
### Expected behaviour
Like in BIND or knot - no reason how many 0x20 symbols after '1'

### Actual behaviour
JSON.data for PATCH request
{"rrsets": [{"changetype": "REPLACE", "type": "MX", "name": "mk8s.myvvb.local.", "ttl": "3600", 
"records": [{"content": "1  mx.myvvb.local.", "disabled": false}], "comments": [{"content": "Test MX", "account": "", "modified_at": 1679396440}]}]}

'{"error": "Record mk8s.myvvb.local./MX \'1  mx.myvvb.local.\': Not in expected format (parsed as \'1 mx.myvvb.local.\')"}'

**Comment by omoerbeek** [comment] 2023-03-22 10:45
The API works like this: it parses record content and then generates the "canonical representation" from the parsed content. If the original and the generated one differ, it says so and refuses the update.
I think this is mostly a documentation issue. The API should be strict.

**Comment by Habbie** [comment] 2023-03-23 10:22
Duplicate of #9870

**Closed by Habbie** 2023-03-23 10:22 UTC
Labels: auth

**Comment by 0x00af** [comment] 2023-03-24 14:26
> The API should be strict.

The API should be RFC compliant.
