### ISSUE TITLE
TXT record and Cname record api call

### ISSUE THREAD

**Issue by mandevx** [PowerDNS/pdns#5713] opened 2017-09-20 09:07 UTC
I am unable to find the api call to add new txt record and new cname record I tried to create an api 

```
curl -X PATCH --data '{"rrsets": [ {"name": "test.somedomains.com.", "type": "TXT", "ttl": 301, "changetype": "REPLACE", "records": [ {"content": "sjMckCpSLmPdB4ddQplURxF6QSSJ4qoIU4LqBhh3dLM", "disabled": false } ] } ] }' -H 'X-API-Key: ThepassAPI' http://record.hipkart.com:8081/api/v1/servers/localhost/zones/somedomains.com. | jq .
```

but I get following error :--

```
"error": "Record txttest.somedomain.com./TXT 'sjMckCpSLmPdB4ddQplURxF6QSSJ4qoIU4LqBhh3dLM': Not in expected format (parsed as '\"sjMckCpSLmPdB4ddQplURxF6QSSJ4qoIU4LqBhh3dLM\"')"
```

Is there a doc or places I can find complete details of all API call types if not what is wrong in the above api call that I should replace and understand .

**Comment by arogozin** [comment] 2017-09-29 13:18
Try this:

```
curl -X PATCH \
  http://DNS_SERVER_API:8081/api/v1/servers/localhost/zones/somedomain.com. \
  -H 'content-type: application/json' \
  -H 'x-api-key: YOUR_API_KEY_GOES_HERE' \
  -d '{
  "rrsets": [
    {
      "name": "test.somedomain.com.",
      "type": "TXT",
      "ttl": 300,
      "changetype": "REPLACE",
      "records": [
        {
          "content": "\"HELLO WORLD\"",
          "disabled": false
        }
      ]
    }
  ]
}'
```

**Comment by Habbie** [comment] 2017-09-29 13:19
@arogozin thank you for responding!

However, as this is not a bug report or a feature request, I am closing this.

@mandevx please find us on our mailing lists or IRC channel, via https://www.powerdns.com/opensource.html

**Closed by Habbie** 2017-09-29 13:19 UTC

**Comment by TLMcNulty** [comment] 2018-12-14 17:13
> I am unable to find the api call to add new txt record and new cname record I tried to create an api
> 
> ```
> curl -X PATCH --data '{"rrsets": [ {"name": "test.somedomains.com.", "type": "TXT", "ttl": 301, "changetype": "REPLACE", "records": [ {"content": "sjMckCpSLmPdB4ddQplURxF6QSSJ4qoIU4LqBhh3dLM", "disabled": false } ] } ] }' -H 'X-API-Key: ThepassAPI' http://record.hipkart.com:8081/api/v1/servers/localhost/zones/somedomains.com. | jq .
> ```
> but I get following error :--
> 
> ```
> "error": "Record txttest.somedomain.com./TXT 'sjMckCpSLmPdB4ddQplURxF6QSSJ4qoIU4LqBhh3dLM': Not in expected format (parsed as '\"sjMckCpSLmPdB4ddQplURxF6QSSJ4qoIU4LqBhh3dLM\"')"
> ```
> Is there a doc or places I can find complete details of all API call types if not what is wrong in the above api call that I should replace and understand .

Hey @mandevx any chance you got this working, I have the same error on a TXT record call.

**Comment by Habbie** [comment] 2018-12-14 17:15
Hello,

@arogozin responded with a curl command that works. Also, as I said, this is nog a bug report or feature request, so it has been closed. If you are looking for help, please use our mailing lists or IRC channel, see https://www.powerdns.com/opensource.html for details.
