### ISSUE TITLE
API zone create  - nameservers array / NS RrSet

### ISSUE THREAD

**Issue by adrpp** [PowerDNS/pdns#4132] opened 2016-07-07 12:00 UTC
Hello,

I've noticed 'strange' behavior while creating new zone containing NS records via API.
pdns version / dist package: 4.0.0~alpha2-3build1 @ ubuntu 16.04 lts

assume having two NS fqdns (ns1.example.org. and ns2.example.org.)

scenario A)
- zone's nameservers array filled with valid NS fqdn's
- NS rrset present (containing two records, each record.content equals to certain NS fqdn)
- result is newly created zone, but NS RrSet contains 4 records (each NS fqdn duplicated)

scenario B)
- zones nameservers array empty
- NS rrset present (containing two records, each record.content equals to certain NS fqdn)
- result is newly created zone with 2 Records inside of the NS RrSet - which is correct

Is this by design or may it be considered as a bug ?
Afaik there needs to be checked whether the incoming zone object contains RrSet of type NS or not.
If so, there shouldn't take palce any 'appending' of RR's

Thank you,
Regards,
Adrian

**Comment by Habbie** [comment] 2016-07-07 12:06
duplicates are forbidden so this definitely is not by design!

**Comment by zeha** [comment] 2016-07-07 12:10
this is a bug, but also the data you send is wrong :-)

**Comment by adrpp** [comment] 2016-07-07 12:24
@zeha 
why ? because of including custom NS RrSet into the body ?

**Comment by zeha** [comment] 2016-07-07 12:31
yes; IMO you should decide on one or the other. I /think/ the fix for this will enforce 'either nameservers array OR NS in rrsets'

**Comment by adrpp** [comment] 2016-07-07 12:39
@zeha 
yes, I did, just wanted to let you know about this :)
so while leaving nameservers empty and using custom NS RrSet it works well :)

**Closed** 2016-12-13 12:37 UTC
Labels: auth, defect, web
