### ISSUE TITLE
pdnsutil check zone segfault on SRV entry

### ISSUE THREAD

**Issue by github-k8n** [PowerDNS/pdns#5781] opened 2017-10-06 19:48 UTC
When importing a bind file to pdns (backend PostgreSQL) with a specific SRV record, the import succeeds but the pdnsutil will segfault when checking the zone.

the offending entry is:
`_imap._tcp                      SRV     0 0 0 .`

(done to "disable" the unencrypted imap service)

pdns just segfaults with
pdnsutil[22905]: segfault at 60 ip 0000559af43dd792 sp 00007ffd74d06cf0 error 4 in pdnsutil[559af4249000+23d000]

I would expect pdnsutil to either work with that entry or not allowing the import in the first place.
The current behavior (accepting it on import, segfaulting on zone checking) is not consistent.

BIND doesn't seem to have any issues with this entry...

System is Gentoo with pdns 4.1.0_rc1

**Comment by pieterlexis** [comment] 2017-10-07 09:08
What version of PowerDNS does this occur on? What OS and where did the binaries come from?

**Comment by github-k8n** [comment] 2017-10-07 09:14
As written above, Gentoo Linux with powerdns 4.1.0_rc1.
Being Gentoo it was compiled on the server itself. 
Can you reproduce it with the binaries? (Should be easy to do, just add the record and do a check-all-zones)

**Comment by rgacogne** [comment] 2017-10-07 10:32
I can't reproduce on master, it might have been fixed by #5684. Any chance you could try to see if you still have the issue on master?

**Comment by rgacogne** [comment] 2017-10-07 10:51
I can indeed reproduce the issue on 4.1.0-rc1 but it has been fixed on master.

**Comment by github-k8n** [comment] 2018-02-02 08:01
Looking at my notifications in github I see that i never answered here :-)
Yes, the issue seems indeed to be fixed in 4.1.0, thanks!

**Closed** 2018-02-03 13:21 UTC
Labels: auth, defect
