### ISSUE TITLE
Mixed opt-out flag between NSEC3PARAM and NSEC3 results in invalid PowerDNS response in AXFR mode

### ISSUE THREAD

**Issue by olafz** [PowerDNS/pdns#10604] opened 2021-07-20 21:15 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description
PowerDNS fails to reply with a valid DNSSEC response when it is used as secondary and if the upstream name server mixes non-opt-out and opt-out on the NSEC3PARAM and NSEC3 records.

### Environment
 - Operating system: Debian
 - Software version: 4.4
 
### Steps to reproduce
The setup to reproduce this is as follows.

First, you need to have a primary nameserver that supports DNSSEC, AXFR and NSEC3 and uses mixed opt-out between `NSEC3PARAM` and `NSEC3` (this is valid behavior). PowerDNS is a secondary nameserver and gets its information via AXFR from the primary. PowerDNS gets the pre-signed zones.

This is an example response that an AXFR looks like (shortened to the relevant part for readability):

```
➜ ~ dig axfr domain.com @ns0.primary.eu

domain.com. 0 IN NSEC3PARAM 1 0 10 8F7F4E40D01A69A5

481N287V97IND4KQKNEVI4QC71GIC0L9.domain.com. 3600 IN NSEC3 1 1 10 8F7F4E40D01A69A5 IQ413TL6K0L978FQ6Q16QKL0C6C84CQB
481N287V97IND4KQKNEVI4QC71GIC0L9.domain.com. 3600 IN RRSIG NSEC3 13 3 3600 20210811123041 20210712123041 29011 domain.com. CkIfMKZOhvJaDbZ+nIsUrfgSgvQGNY0dnajdKcXU3QXHNDoPvMp9VNKQ JmlLqpQdlH9rIRCJ0LtOMrfN5qL44g==
```

Now, to check the behavior of the primary, I do a DNS query for a non-existent record. In this case, the answer is identical to what you would expect from looking at the AXFR response (again, shortened for readability):

```
➜ ~ dig foobar.domain.com @ns0.primary.eu +dnssec

481N287V97IND4KQKNEVI4QC71GIC0L9.domain.com. 3600 IN NSEC3 1 1 10 8F7F4E40D01A69A5 IQ413TL6K0L978FQ6Q16QKL0C6C84CQB
481N287V97IND4KQKNEVI4QC71GIC0L9.domain.com. 3600 IN RRSIG NSEC3 13 3 3600 20210811123041 20210712123041 29011 domain.com. CkIfMKZOhvJaDbZ+nIsUrfgSgvQGNY0dnajdKcXU3QXHNDoPvMp9VNKQ JmlLqpQdlH9rIRCJ0LtOMrfN5qL44g==
```

Now, when I query the PowerDNS secondary, the response is different (and invalid). Note the difference in the opt-out flag, `NSEC3 1 0 10` versus `NSEC3 1 1 10`:

```
➜ ~ dig foobar.domain.com @ns1.secondary.eu +dnssec

481n287v97ind4kqknevi4qc71gic0l9.domain.com. 3600 IN NSEC3 1 0 10 8F7F4E40D01A69A5 IQ413TL6K0L978FQ6Q16QKL0C6C84CQB
481n287v97ind4kqknevi4qc71gic0l9.domain.com. 3600 IN RRSIG NSEC3 13 3 3600 20210811123041 20210712123041 29011 domain.com. CkIfMKZOhvJaDbZ+nIsUrfgSgvQGNY0dnajdKcXU3QXHNDoPvMp9VNKQ JmlLqpQdlH9rIRCJ0LtOMrfN5qL44g==
```

Instead of using the information PowerDNS got via AXFR for the `NSEC3` record, it looks like PowerDNS dynamically generates the `NSEC3` records for pre-signed zones itself (based on the `NSEC3PARAM`). When you're in luck they match, but they don't in this mixed setup example.

### Expected behaviour
I expect the DNSSEC response to be valid. All information to be able to respond with a valid DNSSEC reply is given to PowerDNS via AXFR.

### Actual behaviour
The DNSSEC response is invalid. It looks like PowerDNS deletes the NSEC3 records on the incoming zone transfer and dynamically generates the `NSEC3` records for pre-signed zones itself (based on the `NSEC3PARAM`). This is a bug.

**Comment by mnordhoff** [comment] 2021-07-20 21:40
I don't know if implementations follow this (since it's unhelpful), but the NSEC3PARAM opt-out flag MUST be 0.

https://datatracker.ietf.org/doc/html/rfc5155#section-4.1.2

**Comment by olafz** [comment] 2021-07-21 12:05
> I don't know if implementations follow this (since it's unhelpful), but the NSEC3PARAM opt-out flag MUST be 0.

The NSEC3PARAM opt-out flag _is_ 0 in this bug-report. See my first command with output:

> ```
> ➜ ~ dig axfr domain.com @ns0.primary.eu
> 
> domain.com. 0 IN NSEC3PARAM 1 0 10 8F7F4E40D01A69A5
> ```

This bug occurs with the `NSEC3` records (specifically in case they have the opt-out flag set to 1).

**Comment by RobinGeuze** [comment] 2021-07-21 12:07
PowerDNS does not support opt-out NSEC3 at the moment I think. It doesn't have any possibility for the backend to specify opt-out should be used.

**Comment by olafz** [comment] 2021-07-21 13:25
> Assuming you somehow managed to set the opt-out flag on NSEC3PARAM on an incoming AXFR (yes I know its disallowed) it might work assuming you don't do mixed opt-out and non-opt-out in one zone.

I have now "solved" this by clearing the opt-out flag on the `NSEC3`-records on the primary. However, this is only an option if your setup can meet the consequences this has for [delegation](https://datatracker.ietf.org/doc/html/rfc5155#section-3.1.2.1).

In my opinion, the current PowerDNS approach (dynamically generating `NSEC3`-records for pre-signed zones) is broken and leads to errors and confusion.

**Comment by Habbie** [comment] 2021-07-21 13:40
> `➜ ~ dig axfr domain.com @ns0.primary.eu`

Are these the real names? If not, can you please provide them? Can you also provide the full AXFR output from whatever primary is serving the XFR to PowerDNS?

**Comment by Habbie** [comment] 2021-07-21 13:45
Also, can you please show what PowerDNS, as a secondary/slave, puts in domainmetadata during/after the transfer?

**Comment by Habbie** [comment] 2021-07-21 13:53
> PowerDNS does not support opt-out NSEC3 at the moment I think. It doesn't have any possibility for the backend to specify opt-out should be used.

It does, and it should pick up the optout bit from the NSEC3s in the transfer.

**Comment by Habbie** [comment] 2021-07-30 09:32
Ping! We cannot reproduce this, and we also cover this in our test suite. We will need more information to solve your problem. Please provide it if you can.

**Comment by olafz** [comment] 2021-08-01 13:24
> We will need more information to solve your problem. Please provide it if you can.

I'll work on a setup that can be used to test this. In our setup we have "solved" this issue by clearing the opt-out flag on the `NSEC3`-records on the primary, and I can't change that as it will break the setup again 😄 I'll work on a setup that replicates this behavior and let you know.

**Comment by Habbie** [comment] 2021-08-09 10:59
Any news?

**Comment by Habbie** [comment] 2023-03-23 17:31
Closing this as we cannot reproduce it. Let us know if you have any more info!

**Closed by Habbie** 2023-03-23 17:31 UTC
Labels: auth, defect
