### ISSUE TITLE
TSIG per IP

### ISSUE THREAD

**Issue by joachimtingvold** [PowerDNS/pdns#4688] opened 2016-11-15 20:07 UTC
Maybe slightly relevant to #3945 and #4378.

Would be nice to specify a specific TSIG key to be used for specific IP's (both IPv4 and IPv6) -- similar to what BIND has. This way you can specify different TSIG keys to be used for different slaves -- **even when they are slaves of the same domain**. The latter is the key for this request, as the current limit is "one TSIG per domain".

On a supermaster setup, where supermaster+ns1+ns2 share the same TSIG, and supermaster+ns3 share the same TSIG, I tried to set two "TSIG-ALLOW-AXFR" entries in domainmetadata for a domain. However, it would only use the first TSIG key it found when doing the notify (i.e. ns1+ns2 did the AXFR, but not ns3).

**Comment by bjmgeek** [comment] 2022-03-01 17:36
This seems like a duplicate of #1550.

**Comment by Habbie** [comment] 2024-02-07 10:32
> This seems like a duplicate of #1550

Indeed, thanks. Closing this one.

**Closed by Habbie** 2024-02-07 10:32 UTC
Labels: auth, feature request
