### ISSUE TITLE
dnsdist - useClientSubnet not working as expected

### ISSUE THREAD

**Issue by magical14** [PowerDNS/pdns#12665] opened 2023-03-18 08:07 UTC
Program: authoritative, dnsdist
 Issue type: Bug report

### Short description
The softwares are dnsdist and auth, setup on the same virtual machine. 
dnsdist accepts queries on public IP at port 53 and forwards to auth on localhost at port 5300. 
The remote server IP (client/resolver) is not shown but instead that of configured dnsdist.
 
### Environment
Operating system: Rocky Linux release 9.1 (Blue Onyx)
Software version:  pdns-4.7.3-1pdns.el9.x86_64 and dnsdist-1.7.3-1.el9.x86_64
Software source: PowerDNS repository

### Steps to reproduce
dnsdist.conf
```
setACL({'0.0.0.0/0'})
addLocal("<public_ip>:53")
newServer({address="127.0.0.1:5300", useClientSubnet=true})
setRingBuffersSize(1000000, 100)
setMaxTCPClientThreads(20)
addAction(OrRule({OpcodeRule(DNSOpcode.Notify), OpcodeRule(DNSOpcode.Update), QTypeRule(DNSQType.AXFR), QTypeRule(DNSQType.IXFR)}), RCodeAction(DNSRCode.REFUSED))

local dbr = dynBlockRulesGroup()
dbr:setQueryRate(30, 10, "Exceeded query rate", 60)
dbr:setRCodeRate(DNSRCode.NXDOMAIN, 20, 10, "Exceeded NXD rate", 60)
dbr:setRCodeRate(DNSRCode.SERVFAIL, 20, 10, "Exceeded ServFail rate", 60)
dbr:setQTypeRate(DNSQType.ANY, 5, 10, "Exceeded ANY rate", 60)
dbr:setResponseByteRate(10000, 10, "Exceeded resp BW rate", 60)
function maintenance()
  dbr:apply()
end

webserver("<public_ip>:8083")
setWebserverConfig({apiKey="<snip>", password="<snip>", acl="0.0.0.0/0"})
```

### Expected behaviour
The auth should receive the true client IP address but instead shows the localhost.

### Actual behaviour
The auth should receive the true client IP address since this information is used for GeoIP processing.

**Comment by Bodenhaltung** [comment] 2023-03-18 08:19
Hi, where exactly you are looking for the Client IP in Auth?

**Comment by magical14** [comment] 2023-03-18 09:03
In the webserver of the auth under "Remote server IP"

![image](https://user-images.githubusercontent.com/92709731/226095980-0e6194fb-6218-4e5c-b042-b0cea0f903e6.png)

**Comment by omoerbeek** [comment] 2023-03-18 09:12
Shows your auth config, in particular the value of `edns-subnet-processing` is relevant.

**Comment by magical14** [comment] 2023-03-18 10:09
Yes, that configuration exists on the auth

```
bind-config=/etc/pdns/named.conf
cache-ttl=0
consistent-backends=yes
daemon=no
edns-subnet-processing=yes
enable-lua-records=yes
lua-health-checks-expire-delay=120
lua-health-checks-interval=10
lua-records-exec-limit=0
geoip-database-files=/etc/pdns/GeoIP2-Country.mmdb,/etc/pdns/GeoIP2-City.mmdb,/etc/pdns/GeoIP2-ISP.mmdb
launch=bind,geoip
query-cache-ttl=0
query-logging=yes
setgid=pdns
setuid=pdns
webserver=yes
webserver-address=<snip>
webserver-port=8081
webserver-password=<snip>
webserver-allow-from=0.0.0.0/0
version-string=<snip>
api=yes
api-key=<snip>
logging-facility=0
svc-autohints=yes
local-address=127.0.0.1:5300
server-id=<snip>
```

**Comment by rgacogne** [comment] 2023-03-18 11:22
> In the webserver of the auth under "Remote server IP"
> 
> ![image](https://user-images.githubusercontent.com/92709731/226095980-0e6194fb-6218-4e5c-b042-b0cea0f903e6.png)

Unless I'm mistaken, the authoritative server is not logging the IP it received via EDNS Client Subnet in that field. But it should provide it to the GeoIP backend. Have you actually tested what the GeoIP backend is getting?

If you want more parts of the authoritative server to see the actual client IP, you could consider using the proxy protocol instead: https://dnsdist.org/advanced/passing-source-address.html#proxy-protocol and https://docs.powerdns.com/authoritative/settings.html#proxy-protocol-from

**Comment by magical14** [comment] 2023-03-18 12:16
Indeed I cross checked this one now. The GeoIP backend configured on the auth is working correctly. 

I configure packetbeat to capture DNS on the VM. So it is configured to listen packets from port 53 and 5300. The port 53 capture as client ip to be the true client ip and port 5300 capture has client ip as localhost which is also displayed on the auth webserver.

So function works fine, but is there a reason for auth to not display the true-ip of the client?

**Comment by rgacogne** [comment] 2023-03-18 15:06
The main reason is that EDNS Client Subnet was designed to allow the authoritative server to give the most accurate answer to a query based on where the real client is, like you are doing with GeoIP, not for a trusted reverse-proxy to provide the initial client IP, so the content of EDNS Client Subnet is usually not trustworthy, as the client can lie. So, at least by default, one does not want to base the access control checks on that, and the logs are more useful with the remote IP to act on DoS or other issues.
This is one of the reasons why we have been looking at other ways of passing the information from a reverse-proxy like dnsdist to its backend, like XPF and nowadays the proxy-protocol: since we trust the proxy we know the only IP that matters is the forwarded one. Plus we can convey more information (think source and destination ports, plus meta-data if needed), of course.

**Comment by magical14** [comment] 2023-03-19 02:30
Thanks for your reply. I will read again the Proxy Protocol documentation. 

But using this method will affect the dnsdist caching? My auth response configured with GeoIP is source dependant as lookup is done for country/asnum etc and then answer provided.

Also the query rate filtering will apply default to the forwarded IP or there is a separate function for it?

**Comment by Habbie** [comment] 2023-03-20 07:59
As your problem appears resolved (and was not a bug) I'm closing this ticket. For your questions, please see the prepared message I pasted right below:

Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Closed by Habbie** 2023-03-20 07:59 UTC
