### ISSUE TITLE
Recursor logging until disk full

### ISSUE THREAD

**Issue by jangrewe** [PowerDNS/pdns#8533] opened 2019-11-14 08:15 UTC
- Program: Recursor
 - Issue type: Bug report

### Short description
pdns-recursor spams log causing disk to fill up

### Environment
 - Operating system: Debian stretch
 - Software version: 4.1.14-1pdns.stretch
 - Software source: PowerDNS repository

### Steps to reproduce
I'm not exactly sure what triggers this condition in general, but when pdns-recursor runs out of open file handlers, it starts spamming my system logs with millions of duplicate lines.

### Expected behaviour
Maybe some kind of rate-limiting for duplicate log messages

### Actual behaviour
```
Nov 14 05:06:56 hades pdns_recursor[45931]: Network error in web thread: Accepting a connection: Too many open files
````

**Comment by pieterlexis** [comment] 2019-11-14 09:40
Cleaning and rate-limiting of logs should be done by your logging system, both rsyslog, syslog-ng and systemd-journald have settings for this.

As for the actual error message, you need to increase the LimitNOFile in the systemd unit file so the recursor can use more file descriptors.

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2019-11-14 09:40 UTC
