### ISSUE TITLE
Failure to rsolve MX record in pdn_recursor 3.7.1

### ISSUE THREAD

**Issue by jm-hi-heg** [PowerDNS/pdns#2473] opened 2015-04-29 10:40 UTC
Hi, 

we're failing to look up the MX record for apps.jobserve.com. Is this a known issue, is it just us, is there more information you need?

tcpdump of the request from the client:
```
   dns_client.38871 > pdns_recursor: [udp sum ok] 24985+ MX? apps.jobserve.com. (35)
   pdns_recursor > dns_client.38871: [bad udp cksum e30!] 24985 ServFail q: MX? apps.jobserve.com. 0/0/0 (35) 
```

tcpdump of the request from the powerdns recursor:
```
11:33:29.250918 IP (tos 0x0, ttl 64, id 14209, offset 0, flags [DF], proto UDP (17), length 63)
    pdns_recursor.29864 > 194.193.170.70.domain: [bad udp cksum b49e!] 57815 MX? apps.jobserve.com. (35)
        0x0000:  4500 003f 3781 4000 4011 87e7 2e20 e01d
        0x0010:  c2c1 aa46 74a8 0035 002b 7b82 e1d7 0000
        0x0020:  0001 0000 0000 0000 0461 7070 7308 6a6f
        0x0030:  6273 6572 7665 0363 6f6d 0000 0f00 01
11:33:29.266659 IP (tos 0x0, ttl 121, id 23140, offset 0, flags [DF], proto UDP (17), length 95)
    194.193.170.70.domain > pdns_recursor.29864: [udp sum ok] 57815*- q: MX? apps.jobserve.com. 1/0/1 apps.jobserve.com. MX apps.jobserve.com. 10 ar: apps.jobserve.com. A 193.119.59.220 (67)
        0x0000:  4500 005f 5a64 4000 7911 2be4 c2c1 aa46
        0x0010:  2e20 e01d 0035 74a8 004b f02f e1d7 8400
        0x0020:  0001 0001 0000 0001 0461 7070 7308 6a6f
        0x0030:  6273 6572 7665 0363 6f6d 0000 0f00 01c0
        0x0040:  0c00 0f00 0100 0143 7000 0400 0ac0 0cc0
        0x0050:  3100 0100 0100 0143 7000 04c1 773b dc
```

trace excerpts:
  
```
Apr 29 09:29:13 nsa pdns_recursor[17178]: PowerDNS Recursor 3.7.1 (jenkins@autotest.powerdns.com) (C) 2001-2015 PowerDNS.COM BV
[...]
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Nameservers: res3.amgsharedservices.com.(2.71ms), res4.amgsharedservices.net.(2.71ms), res1.amgsharedse
rvices.com.(2.89ms), 
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.:              res2.amgsharedservices.net.(3.08ms)
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Trying to resolve NS 'res3.amgsharedservices.com.' (1/4)
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Resolved 'jobserve.com.' NS res3.amgsharedservices.com. to: 194.193.170.69
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Trying IP 194.193.170.69:53, asking 'apps.jobserve.com.|MX'
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Got 0 answers from res3.amgsharedservices.com. (194.193.170.69), rcode=1 (Form Error), aa=0, in 10ms
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: determining status after receiving this packet
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: status=NS res3.amgsharedservices.com. (194.193.170.69) is lame for 'jobserve.com.', trying sibling IP o
r NS
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Trying to resolve NS 'res4.amgsharedservices.net.' (2/4)
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Resolved 'jobserve.com.' NS res4.amgsharedservices.net. to: 194.193.170.70
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Trying IP 194.193.170.70:53, asking 'apps.jobserve.com.|MX'
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Got 0 answers from res4.amgsharedservices.net. (194.193.170.70), rcode=1 (Form Error), aa=0, in 9ms
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: determining status after receiving this packet
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: status=NS res4.amgsharedservices.net. (194.193.170.70) is lame for 'jobserve.com.', trying sibling IP o
r NS
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Trying to resolve NS 'res1.amgsharedservices.com.' (3/4)
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Resolved 'jobserve.com.' NS res1.amgsharedservices.com. to: 193.119.59.51
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Trying IP 193.119.59.51:53, asking 'apps.jobserve.com.|MX'
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Got 0 answers from res1.amgsharedservices.com. (193.119.59.51), rcode=1 (Form Error), aa=0, in 11ms
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: determining status after receiving this packet
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: status=NS res1.amgsharedservices.com. (193.119.59.51) is lame for 'jobserve.com.', trying sibling IP or
 NS
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Trying to resolve NS 'res2.amgsharedservices.net.' (4/4)
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Resolved 'jobserve.com.' NS res2.amgsharedservices.net. to: 193.119.59.52
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Trying IP 193.119.59.52:53, asking 'apps.jobserve.com.|MX'
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Got 0 answers from res2.amgsharedservices.net. (193.119.59.52), rcode=1 (Form Error), aa=0, in 11ms
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: determining status after receiving this packet
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: status=NS res2.amgsharedservices.net. (193.119.59.52) is lame for 'jobserve.com.', trying sibling IP or NS
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: Failed to resolve via any of the 4 offered NS at level 'jobserve.com.'
Apr 29 10:07:16 nsa pdns_recursor[17201]: [797013] apps.jobserve.com.: failed (res=-1)
```

**Comment by Habbie** [comment] 2015-04-29 11:01
We cannot reproduce this; can you provide your recursor.conf?

**Comment by Habbie** [comment] 2015-04-29 11:09
And can you try enabling `log-common-errors` to see if that sheds any more light?

**Comment by jm-hi-heg** [comment] 2015-04-29 11:19
egrep -v '^(#|$)' /etc/powerdns/recursor.conf
allow-from-file=/etc/powerdns/allowed
forward-zones-file=/etc/powerdns/forward-zones
local-address=10.3.224.29,10.3.224.30,10.3.224.31
max-mthreads=4096
packetcache-servfail-ttl=10
packetcache-ttl=10
setgid=pdns
setuid=pdns

**Comment by Habbie** [comment] 2015-04-29 11:22
What exact package is this and where did you get it?

**Comment by jm-hi-heg** [comment] 2015-04-29 11:50
http://downloads.powerdns.com/releases/pdns-recursor-3.7.1.tar.bz2

with the following changes
https://github.com/PowerDNS/pdns/commit/464de3b03c50e9780164e5c29289ef4d644b79bc#diff-68a3ee15b9998709b71d87ec594539ac
https://github.com/PowerDNS/pdns/commit/dc544e80f94481619719137063b460c50116dee5#diff-68a3ee15b9998709b71d87ec594539ac

Sorry, had I know we had patched the parser, I might have looked a little harder before raising the issue

**Comment by Habbie** [comment] 2015-04-29 11:55
In that case you also need dc02ebf65ab41ba3c84b05d8d7f1505695adcaf7 - making your total patch equal to the one we actually released with the CVE.

Closing ticket!

**Closed by Habbie** 2015-04-29 11:55 UTC
