### ISSUE TITLE
pdns-recursor infrequently returns incorrect NXDOMAIN entries

### ISSUE THREAD

**Issue by steven-tan** [PowerDNS/pdns#6112] opened 2017-12-21 08:32 UTC
- Program: Recursor 
 - Issue type: Bug report 

### Short description

Infrequently (only a few times a day, sometimes not at all), we will get odd-looking NXDOMAIN responses from our pdns-recursor hosts. These are for entries that definitely exist that are forwarded to google public resolvers (8.8.8.8/8.8.4.4)

The authority section shows incorrect entries when this happens. Some sample output listed below.

### Environment

 - Operating system: centos7
 - Software version: various, including pdns-recursor-4.0.4-1 and pdns-recursor-4.1.0
 - Software source: rpms (pdns repo) 

### Steps to reproduce

1. "dig google-public-dns-a.google.com @internal.nameserver.example.com" repeatedly, eventually will get the incorrect NXDOMAIN responses (where internal.nameserver.example.com = pdns-recursor not publicly exposed to internet)
2. see below for relevant config (fairly minimal)

```
forward-zones=foo.onpremauth=10.0.0.21,bar.onpremauth=10.0.1.21
forward-zones-recurse=awszone=10.20.0.21,.=8.8.8.8;8.8.4.4
local-address=0.0.0.0
log-common-errors=yes
quiet=yes
setgid=pdns-recursor
setuid=pdns-recursor
```

### Expected behaviour

```
; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> google-public-dns-a.google.com @internal.nameserver.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26778
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google-public-dns-a.google.com.	IN	A

;; ANSWER SECTION:
google-public-dns-a.google.com.	20857 IN A	8.8.8.8

;; Query time: 2 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Dec 21 00:25:24 PST 2017
;; MSG SIZE  rcvd: 75
```

### Actual behaviour

Sample errors below - note the odd authority sections (apologies for the single-line formatting, these are infrequent so they are gathered from a script)

```
; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.4 <<>> google-public-dns-a.google.com @internal.nameserver.example.com 
;; global options: +cmd 
;; Got answer: 
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 47290 
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1 
;; OPT PSEUDOSECTION: ; EDNS: version: 0, flags:; udp: 4096 
;; QUESTION SECTION:
 ;google-public-dns-a.google.com. IN A 
;; AUTHORITY SECTION:
 . 83 IN SOA verify-contact-details.namecheap.com. support.namecheap.com. 2017090600 28800 7200 8640 120 
;; Query time: 1 msec 
;; SERVER: 10.7.53.26#53(10.7.53.26) 
;; WHEN: Tue Dec 19 00:57:01 PST 2017 
;; MSG SIZE rcvd: 135
```

```
; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.4 <<>> google-public-dns-a.google.com @internal.nameserver.example.com 
;; global options: +cmd 
;; Got answer: 
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 34517 
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1 
;; OPT PSEUDOSECTION: ; EDNS: version: 0, flags:; udp: 4096 
;; QUESTION SECTION:
 ;google-public-dns-a.google.com. IN A 
;; AUTHORITY SECTION:
 . 1795 IN SOA . root.west263.com. 4 604800 86400 2419200 604800 
;; Query time: 1 msec 
;; SERVER: 10.7.53.26#53(10.7.53.26) 
;; WHEN: Tue Dec 19 21:01:01 PST 2017 
;; MSG SIZE rcvd: 106
```

```
; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.4 <<>> google-public-dns-a.google.com @internal.nameserver.example.com 
;; global options: +cmd 
;; Got answer: 
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 11107 
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1 
;; OPT PSEUDOSECTION: ; EDNS: version: 0, flags:; udp: 4096 
;; QUESTION SECTION:
 ;google-public-dns-a.google.com. IN A 
;; AUTHORITY SECTION:
 . 1757 IN SOA a.root-servers.net. nstld.verisign-grs.com. 2017121902 1800 900 604800 86400 
;; Query time: 1 msec 
;; SERVER: 10.7.53.26#53(10.7.53.26) 
;; WHEN: Wed Dec 20 18:01:01 PST 2017 
;; MSG SIZE rcvd: 131
```

### Other information

We've already tried using the latest version of pdns-recursor, as well as a few other versions, and all exhibit the same problem. We've also seen the issue on mixed-mode pdns(auth)/pnds-recursor hosts as well as standalone pdns-recursor (we tried re-architecting already to recommended recursor-only host to see if problem still manifests, and it does.)

**Comment by rgacogne** [comment] 2017-12-26 10:07
This indeed looks like a bug, would you be able to get a trace [1] by any chance? 

[1]: https://doc.powerdns.com/recursor/running.html?#tracing-queries

**Comment by phonedph1** [comment] 2017-12-29 02:46
Looks like #5107

**Comment by loopodoopo** [comment] 2018-02-20 19:01
I think I'm experiencing the same problem as steven-tan on the following PDNS

```
Feb 20 19:55:27 PowerDNS Recursor 4.0.8 (C) 2001-2017 PowerDNS.COM BV
Feb 20 19:55:27 Using 64-bits mode. Built using gcc 4.8.5 20150623 (Red Hat 4.8.5-16) on Dec 11 2017 10:46:48 by buildbot@8d340649fa91.
```

### Expected
```
[root@dns05 ~]# dig outlook.office365.com

; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7_4.2 <<>> outlook.office365.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47956
;; flags: qr rd ra; QUERY: 1, ANSWER: 12, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;outlook.office365.com.		IN	A

;; ANSWER SECTION:
outlook.office365.com.	23	IN	CNAME	outlook.ha.office365.com.
outlook.ha.office365.com. 21	IN	CNAME	outlook.office365.com.g.office365.com.
outlook.office365.com.g.office365.com. 297 IN CNAME outlook-emeacenter6.office365.com.
outlook-emeacenter6.office365.com. 297 IN A	40.101.30.18
outlook-emeacenter6.office365.com. 297 IN A	40.101.12.50
outlook-emeacenter6.office365.com. 297 IN A	40.101.12.2
outlook-emeacenter6.office365.com. 297 IN A	40.101.55.162
outlook-emeacenter6.office365.com. 297 IN A	40.101.125.194
outlook-emeacenter6.office365.com. 297 IN A	40.101.80.194
outlook-emeacenter6.office365.com. 297 IN A	40.101.43.194
outlook-emeacenter6.office365.com. 297 IN A	40.101.6.242
outlook-emeacenter6.office365.com. 297 IN A	40.101.7.2

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Feb 20 19:54:30 CET 2018
;; MSG SIZE  rcvd: 291
```

### Actual
```
[root@dns05 pdns-recursor]# dig outlook.office365.com 

; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7_4.2 <<>> outlook.office365.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 22912
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;outlook.office365.com.         IN      A

;; AUTHORITY SECTION:
.                       2108    IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2018022000 1800 900 604800 86400

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Feb 20 11:18:09 CET 2018
;; MSG SIZE  rcvd: 122
```

### Extra info

- I run recursor-only with the folllowing forwarders: 

`forward-zones=.=8.8.8.8;208.67.222.222;8.8.4.4;208.67.220.220,local=my.local.server,loc=my.local.server`

It seems to be a problem with domains which have a low TTL. Observed this issue with the following domains: 

- pubs.vmware.com
- cloudsso.cisco.com
- outlook.office365.com

I will see if I can create a trace.

**Comment by Habbie** [comment] 2018-02-20 19:04
@loopodoopo can you try `root-nx-trust=no` ?

**Comment by loopodoopo** [comment] 2018-03-05 15:51
I was able to reproduce this problem with the following script after 36 hours with 10 running instances: 

```
def domain():
    f = open('domainlist', 'r')
    for line in f:
        #print line.strip()
        try:
            nxanswer = resolver.query(line.strip(), 'A')
        except:
            pass
 
        try:
            answer = resolver.query('outlook.office365.com', 'A')
        except:
            print resolver.query('outlook.office365.com', 'A')
            sys.exit()
    domain()
 
domain()
```

For domainlist i used: https://blog.majestic.com/development/majestic-million-csv-daily/

For me, this issue was resolved and validated after 170 hours of testing by setting PDNS to do full recursion and keep the root-nx-trust to the default value (yes)

**Comment by phonedph1** [comment] 2018-09-10 17:04
OK - I can still trigger this on master.

```
$ dig www.minecraft.org @8.8.8.8

; <<>> DiG 9.10.3-P4-Debian <<>> www.minecraft.org @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 15878
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.minecraft.org.             IN      A

;; AUTHORITY SECTION:
.                       1799    IN      SOA     ns1.msft.net. msnhst.microsoft.com. 2018080843 7200 900 2419200 3600

;; Query time: 53 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Sep 10 17:02:05 UTC 2018
;; MSG SIZE  rcvd: 113
```

```
Sep 10 17:00:32 Added root-nx-trust due to: www.minecraft.org
```

```
diff --git a/pdns/syncres.cc b/pdns/syncres.cc
index ac94aa7fb..68806dd86 100644
--- a/pdns/syncres.cc
+++ b/pdns/syncres.cc
@@ -2265,6 +2265,7 @@ bool SyncRes::processRecords(const std::string& prefix, const DNSName& qname, co
       if(!wasVariable() && newtarget.empty()) {
         t_sstorage.negcache.add(ne);
         if(s_rootNXTrust && ne.d_auth.isRoot() && auth.isRoot()) {
+          g_log<<Logger::Warning<<"Added root-nx-trust due to: "<<ne.d_name<<endl;
           ne.d_name = ne.d_name.getLastLabel();
           t_sstorage.negcache.add(ne);
         }
```


```
Sep 10 17:03:58 Ignoring response for security status update, this is a non-release version.
Sep 10 17:04:11 1 [1/1] question for 'www.minecraft.org|A' from 127.0.0.1:29209
Sep 10 17:04:11 Added root-nx-trust due to: www.minecraft.org
Sep 10 17:04:11 [1] www.minecraft.org: Wants NO DNSSEC processing, auth data in query for A
Sep 10 17:04:11 [1] www.minecraft.org: Looking for CNAME cache hit of 'www.minecraft.org|CNAME'
Sep 10 17:04:11 [1] www.minecraft.org: No CNAME cache hit of 'www.minecraft.org|CNAME' found
Sep 10 17:04:11 [1] www.minecraft.org: No cache hit for 'www.minecraft.org|A', trying to find an appropriate NS record
Sep 10 17:04:11 [1] : got TA for '.'
Sep 10 17:04:11 [1] : setting cut state for . to Secure
Sep 10 17:04:11 [1] www.minecraft.org: initial validation status for www.minecraft.org is Indeterminate
Sep 10 17:04:11 [1] www.minecraft.org: Cache consultations done, have 1 NS to contact
Sep 10 17:04:11 [1] www.minecraft.org: Domain has hardcoded nameserver
Sep 10 17:04:11 [1] www.minecraft.org.: Nameservers: +8.8.8.8:53(5.88ms)
Sep 10 17:04:11 [1] www.minecraft.org: Resolved '.' NS (empty) to: 8.8.8.8
Sep 10 17:04:11 [1] www.minecraft.org: Trying IP 8.8.8.8:53, asking 'www.minecraft.org|A'
Sep 10 17:04:11 [1] www.minecraft.org: Got 2 answers from (empty) (8.8.8.8), rcode=3 (Non-Existent domain), aa=0, in 7ms
Sep 10 17:04:11 [1] www.minecraft.org: accept answer '.|SOA|ns1.msft.net. msnhst.microsoft.com. 2018080843 7200 900 2419200 3600' from '.' nameservers? ttl=1673, place=2 YES! - This answer was received from a server we forward to.
Sep 10 17:04:11 [1] www.minecraft.org: OPT answer '.' from '.' nameservers
Sep 10 17:04:11 [1] : got initial zone status Indeterminate for record .|SOA
Sep 10 17:04:11 [1] www.minecraft.org: determining status after receiving this packet
Sep 10 17:04:11 [1] www.minecraft.org: got negative caching indication for name 'www.minecraft.org' (accept=1), newtarget='(empty)'
Sep 10 17:04:11 [1] www.minecraft.org: status=NXDOMAIN, we are done (have negative SOA)
Sep 10 17:04:11 [1] www.minecraft.org: failed (res=3)
Sep 10 17:04:14 1 [2/1] question for 'powerdns.org|A' from 127.0.0.1:14580
Sep 10 17:04:14 [2] powerdns.org: Wants NO DNSSEC processing, auth data in query for A
Sep 10 17:04:14 [2] powerdns.org: Looking for CNAME cache hit of 'powerdns.org|CNAME'
Sep 10 17:04:14 [2] powerdns.org: No CNAME cache hit of 'powerdns.org|CNAME' found
Sep 10 17:04:14 [2] powerdns.org: Entire name 'powerdns.org', is negatively cached via '.' & 'org' for another 1670 seconds
Sep 10 17:04:14 [2] powerdns.org: updating validation state with negative cache content for powerdns.org to Indeterminate
```

**Comment by omoerbeek** [comment] 2021-08-23 13:42
We have have no reports of this happening since quite some time, so closing this. If it happens again, re-open with full details.

**Closed by omoerbeek** 2021-08-23 13:42 UTC
Labels: rec, defect
