### ISSUE TITLE
Error when upgrade recursor 4.3.0 chroot operation not permitted

### ISSUE THREAD

**Issue by pprietosanchez** [PowerDNS/pdns#8978] opened 2020-03-27 14:33 UTC
- Program: Recursor 
 - Issue type: Bug report

### Short description

When upgrade to 4.3.0 version and chroot is set, the service cannot start because it cannot do a chroot as a result the systemd service-file that is installed no longer uses the root user to start.

### Environment

 - Operating system: Centos 7
 - Software version: Centos 7 pdns-rec 4.3.0
 - Software source: PowerDNS repository 

### Steps to reproduce

Configure by defaults and include these lines in config:
chroot=/var/chroot/pdns-recursor/

### Expected behaviour

The service start properly

### Actual behaviour

The service is not started, trhowing the error:
Unable to chroot to '/var/chroot/pdns-recursor/': Operation not permitted, exitin

**Comment by pieterlexis** [comment] 2020-03-27 14:41
On systemd-systems (like CentOS 7). PowerDNS uses the sandboxing options provided by systemd. Along with this, in 4.3, PowerDNS recursor is started by default as the pdns-recursor user (as mentioned [in the upgrade guide](https://docs.powerdns.com/recursor/upgrade.html#systemd-service-and-permissions)).

If you _insist_ on using chroot, add a systemd drop-in starting the service as root and add the `CAP_CHROOT` to the `CapabilityBoundingSet`.

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Closed by pieterlexis** 2020-03-27 14:41 UTC
