### ISSUE TITLE
Unable to load module '/usr/lib/x86_64-linux-gnu/pdns/libgeoipbackend.so': /usr/lib/x86_64-linux-gnu/pdns/libgeoipbackend.so: undefined symbol: _ZNKSt10filesystem7__cxx1118directory_iteratordeE

### ISSUE THREAD

**Issue by plachetka** [PowerDNS/pdns#14276] opened 2024-06-03 17:33 UTC
- [X] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [X] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report

### Short description
geoip module could not be loaded after 4.8 to 4.9 upgrade on debian buster

### Environment

 - Operating system: Debian Buster (10.13)
 - Software version: 4.9
 - Software source: PowerDNS repository

### Steps to reproduce
syslog: Unable to load module '/usr/lib/x86_64-linux-gnu/pdns/libgeoipbackend.so': /usr/lib/x86_64-linux-gnu/pdns/libgeoipbackend.so: undefined symbol: _ZNKSt10filesystem7__cxx1118directory_iteratordeE

### Expected behaviour
no errors

### Actual behaviour
loading module crashes

**Comment by plachetka** [comment] 2024-06-03 18:04
ii  pdns-backend-bind        4.9.1-1pdns.buster amd64        BIND backend for PowerDNS
ii  pdns-backend-geoip       4.9.1-1pdns.buster amd64        GeoIP backend for PowerDNS
ii  pdns-backend-lua2        4.9.1-1pdns.buster amd64        Lua2 backend for PowerDNS
ii  pdns-backend-lua2-dbgsym 4.9.1-1pdns.buster amd64        debug symbols for pdns-backend-lua2
ii  pdns-backend-mysql       4.9.1-1pdns.buster amd64        MySQL backend for PowerDNS
ii  pdns-recursor            4.9.6-1pdns.buster amd64        PowerDNS Recursor
ii  pdns-server              4.9.1-1pdns.buster amd64        extremely powerful and versatile nameserver
ii  pdns-tools               4.9.1-1pdns.buster amd64        Tools for DNS debugging by PowerDNS

**Comment by Habbie** [comment] 2024-06-03 18:05
does `apt-get install -f` complain about anything, or offer to fix anything?

**Comment by plachetka** [comment] 2024-06-03 18:10
To solve the problem I updated the operating system to debian 11 bullseye and changed the repos
deb [arch=amd64] http://repo.powerdns.com/debian bullseye-rec-49 main
deb [arch=amd64] http://repo.powerdns.com/debian bullseye-dnsdist-17 main
deb [arch=amd64] http://repo.powerdns.com/debian bullseye-auth-49 main
deb [arch=amd64] http://repo.powerdns.com/debian bullseye-metronome-master main

After that, the module was loadable, but the packages where still debian buster (as written before). Strange. It looks like an repos problem - wrong packages in the dirs.

**Comment by plachetka** [comment] 2024-06-03 18:11
> does `apt-get install -f` complain about anything, or offer to fix anything?

No errors, all updates did run without errors.

**Comment by Habbie** [comment] 2024-06-03 18:12
> It looks like an repos problem - wrong packages in the dirs.

the packages in the dirs are fine. The problem with upgrading is that due to the way we generate version numbers (which we fixed last week, but not for 4.9), the buster packages look newer to apt than the bullseye packages. You'll have to force a downgrade, or remove+reinstall our packages.

**Comment by plachetka** [comment] 2024-06-03 18:15
> > It looks like an repos problem - wrong packages in the dirs.
> 
> the packages in the dirs are fine. The problem with upgrading is that due to the way we generate version numbers (which we fixed last week, but not for 4.9), our buster packages look newer to apt than the bullseye packages. You'll have to force a downgrade, or remove+reinstall our packages.

OK, fixed it for my case. But the geoip module of the buster package runs on Debian 11 - not on Debian 10.

**Comment by Habbie** [comment] 2024-06-04 09:20
> syslog: Unable to load module '/usr/lib/x86_64-linux-gnu/pdns/libgeoipbackend.so': /usr/lib/x86_64-linux-gnu/pdns/libgeoipbackend.so: undefined symbol: _ZNKSt10filesystem7__cxx1118directory_iteratordeE

i reproduced this with 4.9.1 buster packages on buster.

**Comment by Habbie** [comment] 2024-06-04 11:03
fixed in #14277. Thank you for the report!

**Closed** 2024-06-07 12:24 UTC
Labels: auth
