### ISSUE TITLE
API  returns empty rrset

### ISSUE THREAD

**Issue by ochansen** [PowerDNS/pdns#7711] opened 2019-04-11 12:45 UTC
- Program: Authoritative
 - Issue type: Bug report

### Short description

Used this as source:
https://doc.powerdns.com/authoritative/guides/basic-database.html#example-configuring-mysql
Installed pdns-server by apt. 
Created database and tables and test data 'manually'.
It seemed to work fine until i tried to list a specific zone (as shown below).
The rrset is empty even if the records table holds 7 records with the doman_id to my zone.
Table output show further down.

```
$ curl -s -H 'X-API-Key: xxxxxx' http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.com | jq .
{
  "account": "",
  "api_rectify": false,
  "dnssec": false,
  "id": "example.com.",
  "kind": "Native",
  "last_check": 0,
  "masters": [],
  "name": "example.com.",
  "notified_serial": 0,
  "nsec3narrow": false,
  "nsec3param": "",
  "rrsets": [],
  "serial": 1,
  "soa_edit": "",
  "soa_edit_api": "",
  "url": "/api/v1/servers/localhost/zones/example.com."
}
```

Tried with both FQDN and non-canonical values

### Environment

 - Operating system:  Ubuntu 18.04
 - Software version: mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper
 - Software source: Operating system repository

### Steps to reproduce

1. <Follow the installation formula
2. pdns.conf
```
api-key=xxxxxxxx
config-dir=/etc/powerdns
include-dir=/etc/powerdns/pdns.d
local-address=127.0.0.1
local-ipv6=::1
local-port=5300
module-dir=/usr/lib/x86_64-linux-gnu/pdns
security-poll-suffix=
setgid=pdns
setuid=pdns
webserver=yes
webserver-allow-from=0.0.0.0/0,::/0
webserver-port=8081
launch=bind
launch=gmysql
```

### Expected behaviour

Output as the example

### Actual behaviour

dig works for getting the examples given

```
$ sudo /usr/sbin/pdns_server --daemon=no --guardian=no --loglevel=9
Apr 11 14:11:11 Reading random entropy from '/dev/urandom'
Apr 11 14:11:11 Loading '/usr/lib/x86_64-linux-gnu/pdns/libgmysqlbackend.so'
Apr 11 14:11:11 [gmysqlbackend] This is the gmysql backend version 4.1.1 reporting
Apr 11 14:11:11 This is a standalone pdns
Apr 11 14:11:11 Listening on controlsocket in '/var/run/pdns.controlsocket'
Apr 11 14:11:11 UDP server bound to 127.0.0.1:5300
Apr 11 14:11:11 UDPv6 server bound to [::1]:5300
Apr 11 14:11:11 TCP server bound to 127.0.0.1:5300
Apr 11 14:11:11 TCPv6 server bound to [::1]:5300
Apr 11 14:11:11 PowerDNS Authoritative Server 4.1.1 (C) 2001-2017 PowerDNS.COM BV
Apr 11 14:11:11 Using 64-bits mode. Built using gcc 7.3.0.
Apr 11 14:11:11 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Apr 11 14:11:11 Set effective group id to 142
Apr 11 14:11:11 Listening for HTTP requests on 127.0.0.1:8081
Apr 11 14:11:11 Set effective user id to 128
Apr 11 14:11:11 Creating backend connection for TCP
Apr 11 14:11:11 gmysql Connection successful. Connected to database 'pdns' on 'localhost'.
Apr 11 14:11:11 About to create 3 backend threads for UDP
Apr 11 14:11:11 gmysql Connection successful. Connected to database 'pdns' on 'localhost'.
Apr 11 14:11:11 gmysql Connection successful. Connected to database 'pdns' on 'localhost'.
Apr 11 14:11:11 gmysql Connection successful. Connected to database 'pdns' on 'localhost'.
Apr 11 14:11:11 Done launching threads, ready to distribute questions
Apr 11 14:11:31 HTTP: Handling request "/api/v1/servers/localhost/zones/example.com"
Apr 11 14:11:31 gmysql Connection successful. Connected to database 'pdns' on 'localhost'.
Apr 11 14:11:31 HTTP: Result for "/api/v1/servers/localhost/zones/example.com": 200, body length: 330
```

from the db:
```
mysql> select domain_id,name,type,content,ttl,prio,disabled,ordername,auth from records;
+-----------+-----------------------+------+------------------------------------------------------+-------+------+----------+-----------+------+
| domain_id | name                  | type | content                                              | ttl   | prio | disabled | ordername | auth |
+-----------+-----------------------+------+------------------------------------------------------+-------+------+----------+-----------+------+
|         1 | example.com           | SOA  | localhost admin.example.com 1 10380 3600 604800 3600 | 86400 | NULL |        0 | NULL      |    1 |
|         1 | example.com           | NS   | dns-us1.powerdns.net                                 | 86400 | NULL |        0 | NULL      |    1 |
|         1 | example.com           | NS   | dns-eu1.powerdns.net                                 | 86400 | NULL |        0 | NULL      |    1 |
|         1 | www.example.com       | A    | 192.0.2.10                                           |   120 | NULL |        0 | NULL      |    1 |
|         1 | mail.example.com      | A    | 192.0.2.12                                           |   120 | NULL |        0 | NULL      |    1 |
|         1 | localhost.example.com | A    | 127.0.0.1                                            |   120 | NULL |        0 | NULL      |    1 |
|         1 | example.com           | MX   | mail.example.com                                     |   120 |   25 |        0 | NULL      |    1 |
+-----------+-----------------------+------+------------------------------------------------------+-------+------+----------+-----------+------+
7 rows in set (0.00 sec)
```

### Usecase

Try to get the API working like the example

### Description

Try to get the API working like the example

Cheers
Ole

**Comment by pieterlexis** [comment] 2019-04-11 13:33
This is probably not the solution, but your API call is not good:

> $ curl -s -H 'X-API-Key: xxxxxx' http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.com | jq .

should be

$ curl -s -H 'X-API-Key: xxxxxx' http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.com. | jq .

(note the dot at the end)

Could you show us the output of `pdnsutil list-zone example.com`, `pdnsutil show-zone example.com` and `pdnsutil --version`?

**Comment by ochansen** [comment] 2019-04-12 05:09
Hi, thanks for quick reply. Unfortunately I can only reply during working
hours

>This is probably not the solution, but your API call is not good:
> $ curl -s -H 'X-API-Key: xxxxxx'
http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.com | jq .
> should be
 > $ curl -s -H 'X-API-Key: xxxxxx'
http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.com. | jq .
 >(note the dot at the end)

Yes, I tried both with(FQDN) or without, with the same result.

Could you show us the output of
>


> pdnsutil list-zone example.com,
>
$ORIGIN .


> pdnsutil show-zone example.com
>
This is a Native zone
Zone is not actively secured
Metadata items: None
No keys for zone 'example.com'.


> pdnsutil --version
>
pdnsutil 4.1.1


Don't think I mentioned this test setup is just to play with the API.

Best regards
Ole Christian

**Comment by Habbie** [comment] 2019-04-12 07:06
Hello Ole,

I've tried reproducing your steps, using the pdns 4.1.1 in ubuntu 18.04, and my list-zone looks like this:
```
 pdnsutil list-zone example.com
$ORIGIN .
example.com	120	IN	MX	25 mail.example.com.
example.com	86400	IN	NS	dns-us1.powerdns.net.
example.com	86400	IN	NS	dns-eu1.powerdns.net.
example.com	86400	IN	SOA	localhost admin.example.com 1 10380 3600 604800 3600
localhost.example.com	120	IN	A	127.0.0.1
mail.example.com	120	IN	A	192.0.2.12
www.example.com	120	IN	A	192.0.2.10
```

So I'm pretty sure this is not a bug, but some practical issue - like mixing up two databases. I'm closing this ticket. Please find us on IRC or our mailing lists, via https://www.powerdns.com/opensource.html, so that we can figure this out together.

**Closed by Habbie** 2019-04-12 07:06 UTC
Labels: auth
