### ISSUE TITLE
no response rule with spoof action 

### ISSUE THREAD

**Issue by tobiasneumann42** [PowerDNS/pdns#7774] opened 2019-05-03 12:52 UTC
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report/Feature request 

### Short description

trying to setup dnsdist in an env. where all queries should be sent to internal DNS servers.
if query is refering to any internal domain answer from internal DNS server is returned to client via dnsdist. 
for all other domains/queries spoofing is required, so *.google.com would always get a response of 192.168.1.1 
Documentation doesn't mention that spoofing action not being supported.

tried to setup: 
addResponseAction(RCodeRule(dnsdist.SERVFAIL), SpoofAction("192.168.1.1"))
Caught exception: addResponseAction() can only be called with response-related actions, not query-related ones. Are you looking for addAction()?
 
contrary to the above this works:
addResponseAction(RCodeRule(dnsdist.SERVFAIL), DelayResponseAction(1000))

### Environment

 - Operating system: CentOS 7
 - Software version: 
 - Software source: 
latest install of dnsdist via yum install dnsdist

### Steps to reproduce

just enter above command into console 

### Expected behaviour

Response records with SERVFAIL should return A record with spoofed IP

### Actual behaviour

Not possible to configure

**Comment by rgacogne** [comment] 2019-05-06 14:42
I am closing this issue at it appears a support question  and not a bug or issue. If you require further support, please post your  issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on IRC.

**Closed by rgacogne** 2019-05-06 14:42 UTC
