### ISSUE TITLE
Can't run pdnsutil command

### ISSUE THREAD

**Issue by MyIcecream** [PowerDNS/pdns#9164] opened 2020-05-28 03:05 UTC
I install pdns by yum on Amazon Linux 2 AMI, When I run pdnsutil command, I got this error:

`pdnsutil: symbol lookup error: pdnsutil: undefined symbol: _ZNK5boost15program_options22error_with_option_name23substitute_placeholdersERKSs`

Does someone know how to deal with it, please?

**Comment by phonedph1** [comment] 2020-05-28 03:08
You need to fill out the proper issue template as likely you installed from CentOS repo which is not fully supported by Amazon Linux 2, but the tmeplate which would ask for these has not been filled out.

**Comment by MyIcecream** [comment] 2020-05-28 03:11
Unless I use Centos to instead of Amazon Linux 2 AMI, I won't resolve it, right?

**Comment by phonedph1** [comment] 2020-05-28 03:14
Maybe? You haven't made it clear what you did. You may or may not be able to build what you need for AL2 based on https://github.com/PowerDNS/pdns/issues/9089

**Comment by pieterlexis** [comment] 2020-05-28 06:19
> Unless I use Centos to instead of Amazon Linux 2 AMI, I won't resolve it, right?

Indeed, AL2 is a weird amalgamation of incompatible boost and compiler versions. We can't properly build on it as shown in #9089.

I'm closing this issue as it is a duplicate of the above-mentioned one.

**Closed by pieterlexis** 2020-05-28 06:19 UTC
