### ISSUE TITLE
ifurlup change

### ISSUE THREAD

**Issue by ZTzha** [PowerDNS/pdns#8119] opened 2019-07-24 03:44 UTC
### Short description
how can I change  ifurlup check time,
like check once time per minutes

### Environment

 - Operating system:  ubuntu18.04
 - Software version:  pdns 4.2.0rc2

**Comment by pieterlexis** [comment] 2019-07-24 07:29
This is not configurable. This is planned for the future.

**Comment by Habbie** [comment] 2019-07-24 07:46
Duplicate of #7469. Please read the proposal there and comment on it!

**Closed by Habbie** 2019-07-24 07:46 UTC
